# 02 Data Cleaning

In [1]:
import os
import re
import pandas as pd
from bs4 import BeautifulSoup
import trafilatura
import matplotlib.pyplot as plt
import seaborn as sns
import html
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import sys
import json

In [2]:
df = pd.read_parquet("../data/processed/articles_clean_notebook.parquet")

## 1. Field Quality: `full_text` vs `summary`

We have two text fields. Understanding their relationship helps decide which one to use downstream.

In [47]:
# Compare lengths
df["full_text_len"] = df["full_text"].replace("", pd.NA).str.len()
df["summary_len"] = df["summary"].replace("", pd.NA).str.len()

stats = pd.concat(
    [
        df["full_text_len"].describe().round(0).rename("full_text"),
        df["summary_len"].describe().round(0).rename("summary"),
    ],
    axis=1,
)
print(stats.to_string())

       full_text  summary
count    51801.0  51622.0
mean      2565.0    818.0
std       3219.0   1317.0
min         95.0      4.0
25%       1170.0    123.0
50%       1849.0    507.0
75%       2932.0   1003.0
max      83416.0  31422.0

In [48]:
# How often is full_text shorter than or equal to summary?
full_shorter = df[df["full_text_len"] <= df["summary_len"]]
print(
    f"Articles where full_text <= summary in length: {len(full_shorter)} ({len(full_shorter)/len(df)*100:.1f}%)"
)
print()
print(full_shorter[["source", "full_text_len", "summary_len"]].value_counts("source"))

Articles where full_text <= summary in length: 4646 (9.0%)

source
fakti      3140
24chasa    1019
banker      216
dnevnik     162
bta         109
Name: count, dtype: int64

In [49]:
for field in ["full_text", "summary"]:
    html_mask = df[field].fillna("").str.contains(r"<[a-zA-Z]", regex=True)
    print(f"=== {field.upper()} ===")
    print(f"Articles with HTML: {html_mask.sum()} ({html_mask.sum()/len(df)*100:.1f}%)")
    print("By source:")
    print(df[html_mask]["source"].value_counts().to_string())
    print()
    for source in df[html_mask]["source"].unique():
        sample = df[html_mask & (df["source"] == source)][field].iloc[0]
        print(f"--- {source} ---")
        print(sample[:400])
        print()
    print("=" * 60)
    print()

=== FULL_TEXT ===
Articles with HTML: 3 (0.0%)
By source:
source
monitor     2
actualno    1

--- monitor ---
Е дин човек е загинал, а най-малко четирима са ранени при мощното земетресение на филипинския остров Минданао, предаде Франс прес. Срутили са се и няколко сгради на различни места в архипелага, уточни полицията.
Earthquake in General Santos City, The Philippines on June 8, 2026 pic.twitter.com/ye8LHYwVzB
— Noypi (@noypistuff) June 8, 2026
"Няколко сгради са рухнали. Няколко къщи също са се срутили

--- actualno ---
Ориентираме се към край на сериозните новини за днес! Време е за вечерната ни доза допамин – няколко секунди, които да ни напомнят, че светът е пълен с причини за усмивка:
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">カワウソの寝る前のルーティン<a href="https://t.co/LWQr1lUDka">pic.twitter.com/LWQr1lUDka</a></p>— 癒される動物 (@cutest_animal1) <a href="https://x.com/cutest_animal1/status/20628451592940830

============================================================

=== SUMMARY ===
Articles with HTML: 21963 (42.4%)
By source:
source
24chasa    13128
fakti       7583
banker       997
dnevnik      255

--- banker ---
<img alt="Разкриха още една база за разпространение на наркотици през &quot;Телеграм&quot; в София, Любомир Николов ще изпълнява функциите на главен секретар на МВР" class="webfeedsFeaturedVisual wp-post-image" height="150" src="https://banker.bg/wp-content/uploads/a35948d3-48c1-42ce-99a0-f5608adad172-150x150.webp" style="float: left; margin-right: 5px;" title="Любомир Николов ще изпълнява функции

--- 24chasa ---
<img alt="Разработват нови терапии срещу рак на белия дроб" height="600" src="https://cache1.24chasa.bg/Images/Cache/991/IMAGE_23005991_2_0.jpg" width="800" /> Фармацевтичният гигант Джи Ес Кей (GSK plc) се споразумя да придобие американската компания за разработване на онкологични лекарства „Нювалент“ (Nuvalent Inc.) за 10,6 млрд. долара в брой, с цел разширяване на портфолиото си в областта на л

--- fakti ---
<img src="https://cdn4.focus.bg/fakti/photos/big/c9e/bobi-manekena-se-pohvali-che-gleda-formula-1-s-mika-hakinen-snimkavideo-1.webp" /><p><strong>Боби Манекена - едната половинка от Пиленцата от Монако, се похвали, че е имал привилегията да седи до легендата от Формула 1 Мика Хакинен по време на Гран При на Монако.</strong></p>


















Вижте тази публикация в Instagram.












--- dnevnik ---
<img src="https://img.dnevnik.bg/shimg/zx350c_4907083.jpg" /><br />
Иранската делегация на преговорите със САЩ за спиране на конфликта е отпътувала от Пакистан, съобщиха източници от страната за "Ройтерс". Според Times of Israel това е станало преди американските представители да са отпътували от Флорида за...

============================================================

- full_text is on average 3.4× longer than summary, confirming it as the primary field for embedding and retrieval.
- ~50% of summaries contain raw HTML tags — stripping is required before any use.
- ~10% of articles have full_text ≤ summary length, concentrated in fakti (likely HTML inflation) and 24chasa/dnevnik (possibly truncated full text).

### 1a. HTML striping from `summary`

In [50]:
def strip_html(text):
    if not isinstance(text, str):
        return ""
    return BeautifulSoup(text, "html.parser").get_text(separator=" ", strip=True)

In [51]:
def print_by_words(text, chunk=20):
    words = text.split()
    for i in range(0, len(words), chunk):
        print(" ".join(words[i : i + chunk]))

In [52]:
for _, row in df[df["summary"].str.len() > 0].sample(3, random_state=42).iterrows():
    print(f"source: {row['source']}")
    print_by_words(row["summary"])
    print()

source: 24chasa
<img alt="Осъдиха на 6 години затвор и 15 000 евро глоба 44-годишен софиянец, продавал фентанил" height="600" src="https://cache2.24chasa.bg/Images/Cache/010/IMAGE_22705010_2_0.jpg" width="800" /> Шест
години лишаване от свобода и глоба от 15 хил. евро постанови Окръжният съд в Търговище за 44-годишен мъж от София
за държане с цел разпространение на фентанил, съобщиха от съда. С. В. от София (44-годишен, осъждан) бе признат за виновен
в това, че на 24.06.2025 г. е държал с цел разпространение високорискови наркотични вещества

source: standartnews
На 95 години почина Сони Ролинс, смятан за един от последните велики имена на златната ера на джаза и известен
като „Саксофонният колос&quot;.„С дълбока скръб и огромна любов съобщаваме за кончината на Сони Ролинс&quot;, гласи публикацията в официалната му страница
в социалните мрежи.Ролинс е роден в Ню Йорк. Първият си саксофон получава, когато е на 13. Ролинс отначало е пианист,
после преминава към алто саксофона, и в крайна сметка превключва към тенора през 1946 г. До 1954 г. той свири
с изпълнители като Майлс Дейвис, Чарли Паркър и Телониъс Монк.

source: fakti
<img src="https://cdn4.focus.bg/fakti/photos/big/c60/morgan-friiman-na-89-g-istoriata-na-glasa-koito-se-prevarna-v-legenda-1.webp" /><p><strong>На 1 юни светът отбелязва рождения ден на един от най-обичаните актьори в историята на киното &ndash; Морган
Фрийман. Носителят на &bdquo;Оскар&ldquo;, чиито глас и присъствие са се превърнали в запазена марка на Холивуд, навършва 89 години, а
кариерата му продължава да впечатлява с активност и нови проекти.</strong></p> <p><strong>От Мемфис до върха на Холивуд</strong></p> <p>Морган Портърфийлд Фрийман-младши е
роден на 1 юни 1937 г. в Мемфис, щата Тенеси. Любопитното е, че още като дете проявява интерес към актьорството
и на деветгодишна възраст печели училищен конкурс за драматично изпълнение.</p> <p>Преди да стане актьор обаче, животът му поема в друга
посока. След завършване на училище отказва стипендия за университет и постъпва във Военновъздушните сили на САЩ, където служи като механик.
По-късно признава, че именно там осъзнава, че истинската му страст е сцената, а не авиацията.</p> <p><strong>Славата идва късно</strong></p> <p>За разлика
от много холивудски звезди, Морган Фрийман не става известен като млад. Десетилетия наред играе в театъра и телевизията, преди да
получи големия си шанс.</p> <p>Истинският пробив идва през 1987 г. с филма &bdquo;Уличният мошеник&ldquo; (Street Smart), който му носи първата
номинация за &bdquo;Оскар&ldquo;. По това време той вече е на 50 години.</p> <p><strong>Следват роли, превърнали се в класика:</strong></p> &bdquo;Да возиш
мис Дейзи&ldquo; &bdquo;Слава&ldquo; &bdquo;Робин Худ: Принцът на разбойниците&ldquo; &bdquo;Седем&ldquo; &bdquo;Сблъсък&ldquo; &bdquo;Момиче за милиони&ldquo; &bdquo;Шоушенкско бягство&ldquo; трилогията &bdquo;Черният рицар&ldquo; <p>През 2005
г. печели &bdquo;Оскар&ldquo; за поддържаща мъжка роля във &bdquo;Момиче за милиони&ldquo;.</p> <strong>Любопитни факти за легендарния актьор</strong> <p><strong>Гласът, който всички разпознават</strong></p>
<p>Мнозина смятат гласа на Морган Фрийман за най-разпознаваемия в света. Именно затова той е сред най-търсените разказвачи на документални филми
и телевизионни продукции.</p> <p><strong>Играл е Бог</strong></p> <p>Една от най-запомнящите се роли в кариерата му е тази на Бог във филмите
&bdquo;Всемогъщият Брус&ldquo; и &bdquo;Евън Всемогъщият&ldquo;.</p> <p><strong>Притежава лиценз за пилот</strong></p> <p>След като напуска армията, Фрийман не губи любовта си към авиацията.
Той става лицензиран пилот и притежава няколко самолета.</p> <p><strong>Спасява пчелите</strong></p> <p>В ранчото си в щата Мисисипи актьорът отглежда пчели и
участва активно в инициативи за опазване на популацията им.</p> <p><strong>Закъснял успех</strong></p> <p>Морган Фрийман често е посочван като доказателство, че успехът
няма възраст. Световната слава идва при него едва след навършването на 50 години.</p> <strong>Актуалните новини около Морган Фрийман</strong> <p>Въпреки напредналата
си възраст актьорът остава изключително активен. През последните месеци той е сред изпълнителните продуценти на историческата минисерия &bdquo;The Gray House&ldquo;,
посветена на женска шпионска мрежа по време на Гражданската война в САЩ. Сериалът дебютира през 2026 г. и е реализиран
съвместно с Кевин Костнър.</p> <p>Фрийман продължава да работи и като разказвач на документални продукции. През 2026 г. неговият емблематичен глас
озвучава документалната поредица &bdquo;The Dinosaurs&ldquo; на Netflix, посветена на възхода и изчезването на динозаврите.</p> <p>Сред последните му екранни участия е
и третият филм от популярната поредица &bdquo;Now You See Me&ldquo;, в който отново влиза в ролята на Тадеус Брадли.</p> <p>Освен
това Фрийман продължава участието си в шпионския сериал &bdquo;Lioness&ldquo;, където играе държавния секретар Едуин Мълинс. Третият сезон вече е в
производство.</p> <p>Днес Морган Фрийман е не просто актьор, а институция в киното. С кариера, продължаваща повече от шест десетилетия, той
остава пример за талант, постоянство и професионализъм.</p>

In [53]:
df["summary"] = df["summary"].apply(strip_html)

In [54]:
for _, row in df[df["summary"].str.len() > 0].sample(3).iterrows():
    print(f"source: {row['source']}")
    print_by_words(row["summary"])
    print()

source: fakti
Приключи първата репетиция на България на сцената на „Евровизия 2026“ във Виена, а около участието на DARA вече се завихря
сериозен интерес и положителни коментари от медии, следящи отблизо конкурса. Още от първите минути на сцената българското представяне е успяло
да привлече внимание, а информацията, която излиза след техническата репетиция, само подсилва очакванията към втория полуфинал, пише darik.bg. DARA е
провела първата си техническа репетиция на огромната сцена във Виена и според присъстващи и наблюдатели се е раздала напълно –
както вокално, така и сценично. Изпълнението ѝ е описвано като енергично, уверено и добре структурирано, с ясно изразено сценично присъствие,
което не остава незабелязано дори сред силната конкуренция тази година. Още по-интересен обаче е фактът, който вече се коментира от
медии като Eurovisionfun и Eurovision Cloud, България е първата страна тази година, която прави промени по своята песен след началото
на репетициите. Според информацията, последната част на „Bangaranga“ е претърпяла известни промени и доработки, които ще бъдат представени официално по
време на втория полуфинал на 14 май, където DARA ще има честта да открие шоуто. <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/p/DX8xVYZgk85/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style="
background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% -
2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/DX8xVYZgk85/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex;
flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex;
flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div>
<div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto
12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41
553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114
551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606
564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803
520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894
C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938
564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575
C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438
511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965
532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50
C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div>
<div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px)
translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color:
#F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0;
height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px
solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent;
transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0;
border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;
margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4;
border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center;
text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/DX8xVYZgk85/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by Eurovision Song Contest (@eurovision)</a></p></div></blockquote> <script
async src="//www.instagram.com/embed.js"></script> Този ход се възприема като смел и стратегически знак, че екипът около изпълнителката не се страхува да надгражда
и да усъвършенства проекта дори в движение. В контекста на „Евровизия“, където всяка секунда и всеки детайл могат да бъдат
решаващи, подобна гъвкавост често се оказва ключова за силно представяне. Втората репетиция на България е насрочена за петък, 8 май,
и се очаква именно тогава да се види още по-ясна картина за финалния сценичен вариант на песента. Интересът към участието
на DARA расте с всяка нова информация, а очакванията се повишават не само заради музиката, но и заради цялостната визия,
хореография и концепция. Всичко това поставя българското участие в центъра на вниманието още преди официалното начало на полуфиналите. А DARA,
с увереното си сценично поведение и готовност да надгражда проекта си, показва, че не просто участва в конкурса, а влиза
в него с амбицията да остави следа. Предстои да видим дали направените промени ще се окажат решаващи, но едно вече
е ясно, България влиза във „Евровизия 2026“ със заявка за силно, модерно и запомнящо се представяне, а DARA е в
самия център на тази амбиция.

source: monitor
В петък във вестник "Мач Телеграф". Плакат на Кристъл Палас

source: fakti
Поп звездата Бритни Спиърс се призна за виновна по по-леко обвинение за „неразумно шофиране“, след като чрез своя адвокат постигна
споразумение с прокуратурата в окръг Вентура, Калифорния. Така изпълнителката избегна възможността за ефективна присъда , въпреки първоначалните обвинения, свързани с
управление на автомобил след употреба на алкохол и неуточнени вещества. Съгласно законодателството на щата Калифорния, при първо нарушение без причинени
щети или пострадали и при сравнително ниски нива на алкохол в кръвта, обвиняемите могат да се признаят за виновни по
редуцирано обвинение , известно като „wet reckless“. Тази практика позволява налагане на по-леки санкции, като в случая на Бритни Спиърс
се очаква присъда от една година пробация, задължително участие в програми за превенция на шофирането след употреба на алкохол и
наркотици, както и финансова санкция. Певицата не се яви лично в съда, като беше представлявана от адвоката си Майкъл А.
Голдстейн. Той заяви, че решението е взето с цел случаят да бъде приключен възможно най-бързо и да позволи на клиентката
му да се съсредоточи върху възстановяването си. По думите му Бритни е завършила курс на лечение в рехабилитационен център и
се е завърнала у дома, като опроверга твърденията, че е прекъснала терапията преждевременно. Окръжният прокурор Ерик Насаренко подчерта, че въпреки
по-лекото обвинение, случаят остава сериозен и изисква стриктно спазване на наложените условия. Те включват продължаващо лечение, редовни срещи с терапевт
и наблюдение от специалисти. „Важно е да се гарантира, че подобно поведение няма да се повтори“, посочи той. Инцидентът датира
от 4 март, когато певицата е била спряна от служители на пътната полиция заради рисково и неравномерно шофиране по магистрала
101 в близост до дома ѝ в окръг Вентура. По данни на властите тя е показвала признаци на нетрезво състояние,
а последвалите тестове са установили наличие на алкохол и други вещества, без да се уточняват конкретни стойности или видове. Случаят
привлече засилен медиен интерес, като се вписва в по-широкия контекст на личните и здравословни предизвикателства, през които Спиърс преминава през
последните години. След прекратяването на дългогодишното ѝ попечителство през 2021 г., певицата постепенно възстановява професионалната си активност и публичното си
присъствие, като през 2023 г. издаде мемоарите си „The Woman in Me“, които оглавиха класациите за нехудожествена литература и предизвикаха
широк обществен отзвук. Правни експерти коментират, че постигнатото споразумение е стандартна практика при подобни случаи, особено когато обвиняемият съдейства на
разследването и предприема конкретни стъпки за лечение. Очаква се делото да бъде окончателно приключено след изпълнение на наложените мерки.

In [55]:
for field in ["summary"]:
    html_mask = df[field].fillna("").str.contains(r"<[a-zA-Z]", regex=True)
    print(f"=== {field.upper()} ===")
    print(f"Articles with HTML: {html_mask.sum()} ({html_mask.sum()/len(df)*100:.1f}%)")
    print("By source:")
    print(df[html_mask]["source"].value_counts().to_string())
    print()
    for source in df[html_mask]["source"].unique():
        sample = df[html_mask & (df["source"] == source)][field].iloc[0]
        print(f"--- {source} ---")
        print_by_words(sample)
        print()
    print("=" * 60)
    print()

=== SUMMARY ===
Articles with HTML: 282 (0.5%)
By source:
source
fakti    282

--- fakti ---
Бразилският защитник на Левски Майкон официално се ожени за своята дългогодишна половинка Тайнара Гомес. Двойката отпразнува своя специален ден с
пищна церемония, а щастливите мигове не закъсняха да се появят в социалните мрежи, където приятели, фенове и съотборници се надпреварваха
да ги поздравят. <blockquote class="instagram-media" data-instgrm-captioned data-instgrm-permalink="https://www.instagram.com/p/DZSv9W8jix-/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0
rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/DZSv9W8jix-/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0
0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0;
height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius:
4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width:
60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g
stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41
M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113
C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521
548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50
C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479
553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631
C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834
521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625
514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965
C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal;
font-weight:550; line-height:18px;">Вижте тази публикация в Instagram.</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color:
#F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width:
12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left:
8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top:
2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width:
0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width:
16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div>
<div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height:
14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif;
font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/DZSv9W8jix-/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;"
target="_blank">Публикация, споделена от Tainara Gomes (@tainara_gomes_027)</a></p></div></blockquote> <script async src="//www.instagram.com/embed.js"></script> Снимки и видеоклипове от тържеството буквално заляха интернет пространството, а усмивките
на младоженците озариха профилите им. Тайнара Гомес не скри вълнението си и публикува трогателно послание: „Колко хубаво, че дойде“, с
което докосна сърцата на последователите си. Мигновено под публикацията заваляха поздравления и пожелания за дълъг и щастлив семеен живот. Новината
за сватбата на Майкон се разпространи със скоростта на светлината сред феновете на Левски и футболната общественост. Съотборници и приятели
не пропуснаха да изразят радостта си от щастливото събитие, изпращайки топли думи и благопожелания към новото семейство. <blockquote class="instagram-media" data-instgrm-captioned
data-instgrm-permalink="https://www.instagram.com/p/DZSDiYkFgBU/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0;
width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/p/DZSDiYkFgBU/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div
style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div>
<div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom:
6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block;
height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)"
fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342
541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886
M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244
524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338
C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846
562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035
C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377
512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167
525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369
C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">Вижте тази публикация в Instagram.</div></div><div
style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width:
12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left:
2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius:
50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid
#f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right:
8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width:
0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow:
1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div
style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px
0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/p/DZSDiYkFgBU/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">Публикация, споделена от Tainara Gomes (@tainara_gomes_027)</a></p></div></blockquote>
<script async src="//www.instagram.com/embed.js"></script>

============================================================

## Decision: Drop `summary`

The `summary` field is sourced directly from the RSS `<description>` tag and is inconsistent across sources — some articles have a meaningful short intro, others have a duplicate of `full_text`, and roughly 50% contain raw HTML markup. Several sources (`vesti`, `segabg`) provide no summary at all.

Since `full_text` is the authoritative text field used for all downstream tasks `summary` adds no value and is dropped.

In [56]:
df = df.drop(columns=["summary", "full_text_len", "summary_len"])

In [57]:
df.head(3)

,source,title,url,published_at,full_text,fetched_at,published_at_dt,word_count
0,vesti,<p>Ким Чен-ун и Си Дзинпин с ключова среща в П...,https://www.vesti.bg/sviat/kim-chen-un-i-si-dz...,2026-06-09T07:35:00+00:00,С евернокорейският лидер Ким Чен-ун и китайски...,2026-06-09T11:20:07.411349+00:00,2026-06-09 07:35:00+00:00,315
1,vesti,<p>Зеленски с &bdquo;желязна&ldquo; подкрепа о...,https://www.vesti.bg/sviat/zelenski-s-zheliazn...,2026-06-09T08:04:00+00:00,У краинският президент Володимир Зеленски се с...,2026-06-09T11:20:07.411341+00:00,2026-06-09 08:04:00+00:00,396
2,vesti,New York Times: Израел сипе бял фосфор над гра...,https://www.vesti.bg/sviat/new-york-times-izra...,2026-06-09T08:05:00+00:00,"В изуални доказателства, събрани и проверени о...",2026-06-09T11:20:07.411332+00:00,2026-06-09 08:05:00+00:00,1103

## 2. Cyrillic & Encoding Quality Check

Bulgarian uses the Cyrillic alphabet. Encoding issues (e.g. Windows-1251 misread as UTF-8) produce garbled text.
We check how much of the text is valid Cyrillic and flag suspicious articles.

In [58]:
def is_mojibake(text: str) -> bool:
    if not isinstance(text, str) or not text.strip():
        return False
    dash_ratio = (text.count("–") + text.count("—")) / max(len(text), 1)
    return dash_ratio > 0.05

In [59]:
mojibake_mask = df["full_text"].apply(is_mojibake)
print(
    f"Unreadable (mojibake): {mojibake_mask.sum()} ({mojibake_mask.sum()/len(df)*100:.1f}%)"
)
print(df[mojibake_mask]["source"].value_counts().to_string())
print()

Unreadable (mojibake): 62 (0.1%)
source
actualno    62

In [60]:
for _, row in df[mojibake_mask][["source", "title", "full_text"]].head(3).iterrows():
    print(f"  Source : {row['source']}")
    print(f"  Title  : {row['title']}")
    print(f"  Preview: {row['full_text'][:200]}")
    print()

  Source : actualno
  Title  : Оръжията да говорят: Лавров призова, Украйна изпълни серия унищожителни удари (ОБЗОР - ВИДЕО)
  Preview: "–Ь–љ–Њ–≥–Њ –њ–Њ–Ј–Є—В–Є–≤–µ–љ" - —В–∞–Ї—К–≤ –µ –±–Є–ї —А–∞–Ј–≥–Њ–≤–Њ—А—К—В –Љ–µ–ґ–і—Г —Г–Ї—А–∞–Є–љ—Б–Ї–Є—П –њ—А–µ–Ј–Є–і–µ–љ—В –Т–Њ–ї–Њ–і–Є–Љ–Є—А –Ч–µ–ї–µ–љ—Б–Ї–Є, —Б–њ–µ—Ж–Є–∞–ї–љ–Є—П –њ—А–∞—В–µ–љ–Є–

  Source : actualno
  Title  : Проектът на зетя на Тръмп в Албания е "благословия": Албанците не са съгласни с Еди Рама и са по улиците (ВИДЕО)
  Preview: –Ю—Б—В–∞–≤–Ї–∞ –љ–∞ –њ—А–µ–Љ–Є–µ—А–∞ –Х–і–Є –†–∞–Љ–∞ - –≤ —В–Њ–≤–∞ –≤–µ—З–µ —Б–µ –њ—А–µ–≤—К—А–љ–∞—Е–∞ –њ—А–Њ—В–µ—Б—В–Є—В–µ —Б—А–µ—Й—Г –Љ–∞—Й–∞–±–љ–Є—П –Є–љ–≤–µ—Б—В–Є—Ж–Є–Њ–љ–µ–љ –њ—А–Њ–µ–Ї—В –≤ –Р–ї–±

  Source : actualno
  Title  : След като Армения избра Европа, Русия я обвини в "груби нарушения на демокрацията" (ВИДЕО)
  Preview: –†―É―¹–Η―è –¥–Α ―²–Η –Η–Ζ–Ϋ–Α―¹―è ―É―Ä–Ψ–Κ –Ω–Ψ –¥–Β–Φ–Ψ–Κ―Ä–Α―Ü–Η―è –Η –¥–Β–Φ–Ψ–Κ―Ä–Α―²–Η―΅–Ϋ–Η ―Ü–Β–Ϋ–Ϋ–Ψ―¹―²–Η - –Η –¥–Ψ ―²–Ψ–≤–Α ―¹―²–Η–≥–Ϋ–Α―Ö–Φ–Β –Ω―Ä–Β–Ζ 2026 –≥., ―¹–Μ–Β–¥ –Κ–Α―²–Ψ –Η–Ζ–±–Η―Ä–

In [61]:
df = df[~mojibake_mask].reset_index(drop=True)
print(f"Dropped {mojibake_mask.sum()} unreadable articles. Remaining: {len(df)}")

Dropped 62 unreadable articles. Remaining: 51739

**Finding:** A small number of articles from `actualno` contained fully unreadable text — classic mojibake produced by Windows-1251 content misread as UTF-8, recognisable by an abnormally high density of `–`/`—` characters.

**Decision:** Dropped all articles where more than 5% of characters are em/en dashes. All remaining articles contain readable Bulgarian text.

## 3. Source-Specific Investigations

### 3a. Dnevnik — JavaScript-Rendered Content

In [62]:
if "dnevnik" in df["source"].values:
    dnevnik_sample = df[df["source"] == "dnevnik"][
        ["title", "url", "word_count", "full_text"]
    ].sort_values("word_count")
    print(f"Total dnevnik articles : {len(dnevnik_sample)}")
    print(f"Median word count      : {dnevnik_sample['word_count'].median()}")
    print()
    for _, row in dnevnik_sample.head(3).iterrows():
        print(f"Title   : {row['title']}")
        print(f"Words   : {row['word_count']}")
        print(f"Full text : {row['full_text'][:300]}")
        print("-" * 60)

Total dnevnik articles : 255
Median word count      : 23.0

Title   : Слънчево и топло време в събота
Words   : 13
Full text : 06:20Слънчево и топло време в съботаДневник0СподелиЛинкът е копиранКопирай линкИзпрати по имейлFacebookХLinkedInViber25 април 2026
------------------------------------------------------------
Title   : САЩ разхлабват правилата за канабиса
Words   : 14
Full text : 21:30САЩ разхлабват правилата за канабисаДневник5СподелиЛинкът е копиранКопирай линкИзпрати по имейлFacebookХLinkedInViber23 април 2026ВСИЧКИ БЪРЗИ НОВИНИ
------------------------------------------------------------
Title   : "Левски" има нов собственик
Words   : 14
Full text : HomeСпорт"Левски" има нов собственикЦВЕТЕЛИНА БЕЛУТОВААтанас БостанджиевАндриян Георгиев37СподелиЛинкът е копиранКопирай линкИзпрати по имейлFacebookХLinkedInViber24 април 2026
------------------------------------------------------------

In [63]:
# Verify with trafilatura directly
if "dnevnik" in df["source"].values:
    test_url = df[df["source"] == "dnevnik"]["url"].iloc[0]
    downloaded = trafilatura.fetch_url(test_url)
    result = trafilatura.extract(downloaded) if downloaded else None
    print(
        f"Trafilatura extraction result: {repr(result[:200]) if result else 'None — extraction failed'}"
    )

Trafilatura extraction result: 'HomeСвятПреговорите САЩ-Иран в Пакистан приключиха преди да започнат, Тръмп ги прекъснаReutersПетър Карабоев97СподелиЛинкът е копиранКопирай линкИзпрати по имейлFacebookХLinkedInViber25 април 2026Удар'

**Finding:** Dnevnik runs on Next.js. Trafilatura receives the bare HTML shell before JavaScript renders the content.
All 253 articles contain only 13–14 words of boilerplate (timestamps, share buttons).

**Decision:** Remove Dnevnik from the dataset.

In [64]:
mask = df["source"] == "dnevnik"

print(f"Dropping {mask.sum()} articles from: dnevnik")
df = df[~mask].reset_index(drop=True)
print(f"Remaining articles: {len(df)}")

Dropping 255 articles from: dnevnik
Remaining articles: 51484

### 3b. 24chasa — Very Long Outliers

In [65]:
chasa_outliers = df[(df["source"] == "24chasa") & (df["word_count"] > 3000)][
    ["title", "url", "word_count", "full_text"]
].sort_values("word_count", ascending=False)

print(f"24chasa articles over 3000 words: {len(chasa_outliers)}")
print()
for _, row in chasa_outliers.head(5).iterrows():
    print(f"Title   : {row['title']}")
    print(f"Words   : {row['word_count']}")
    print(f"Preview : {row['full_text'][:300]}")
    print("-" * 60)

24chasa articles over 3000 words: 55

Title   : Вижте какво е състоянието на пътищата тази вечер
Words   : 13773
Preview : Агенция "Пътна инфраструктура" информира за състоянието на пътищата, въведените ограничения и метеорологичната обстановка у нас към 17:30 часа.
I. МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
През следващото денонощие синоптичната обстановка в страната ще бъде усложнена. Ще бъде облачно и с повсеместни валежи от дъжд
------------------------------------------------------------
Title   : Вижте какво е състоянието на пътищата тази вечер
Words   : 13621
Preview : Информация за състоянието на републиканските пътища към 17:30 часа на 08.06.2026 г.
МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
През нощта валежите ще спрат и облачността ще се разкъса и ще намалее до предимно ясно. Ще бъде почти тихо и след полунощ на отделни места в равнинните райони ще се образува мъгла или ниска
------------------------------------------------------------
Title   : Вижте какво е състоянието на пътищата тази вечер
Words   : 13408
Preview : Информация за състоянието на републиканските пътища към 17:30 часа на 23.05.2026 г.
МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
И през следващото денонощие въздушната маса над страната ще остане силно неустойчива. През по-голямата част на нощта валежи ще има в западните и централните райони на Северна България, Горн
------------------------------------------------------------
Title   : Вижте какво е състоянието на пътищата тази вечер
Words   : 13350
Preview : Информация за състоянието на републиканските пътища към 17:30 часа на 21.05.2026 г.
МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
През нощта и утре над страната ще има значителна купеста и купесто-дъждовна облачност с краткотрайни, временно интензивни валежи с гръмотевици. Ще има и градушки. Ще духа до умерен север-се
------------------------------------------------------------
Title   : Вижте какво е състоянието на пътищата тази вечер
Words   : 13335
Preview : Агенция "Пътна инфраструктура" информира за състоянието на пътищата, въведените ограничения и метеорологичната обстановка у нас към 17:30 часа.
I. МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
През нощта облачността ще е по-често значителна и на отделни места, главно в източната половина от страната, ще има валежи от
------------------------------------------------------------

In [66]:
short_24chasa = df[(df["source"] == "24chasa") & (df["word_count"] < 50)]
print(f"24chasa articles under 50 words: {len(short_24chasa)}")
print(short_24chasa[["title", "word_count", "full_text"]].to_string())

24chasa articles under 50 words: 193
                                                                                                                title  word_count                                                                                                                                                                                                                                                                                                                                                              full_text
251                                                                     Малкият Иванчо се учи как започва глаголицата          16                                                                                                                                                                                                            https://www.24chasa.bg/mneniya/article/23002668\nwww.24chasa.bg\nМалкият Иванчо се учи как започва глаголицата\n1856\nПоследвайте ни в Google News Showcase
596                                                                                      Трус 5 по Рихтер в южен Иран          45                                                                Земетресение с магнитуд 5 разтърси град Саргаз в южната иранска провинция Хормозган рано тази сутрин, съобщиха иранските държавни медии, цитирани от Ройтерс, информира БТА.\nЕпицентърът на земния трус е бил на дълбочина 22 км, се казва още в съобщението.\nНяма информация за пострадали или щети.
648                                                     „Кандидатстудентски наръчник"- изтегли безплатно приложението          14                                                                                                                                                                                           https://www.24chasa.bg/bulgaria/article/23004137\nwww.24chasa.bg\n„Кандидатстудентски наръчник"- изтегли безплатно приложението\n1548\nПоследвайте ни в Google News Showcase
775                                                                Почина биатлонист от олимпийския дебют на България          43                                                             Напуснал ни е Илия Тодоров (Ишо).\nЕдин от първите двама български биатлонисти, участници на олимпиада през 1976 г. в Инсбрук, заедно с Христо Маджаров.\nТъжната вест обяви генералният секретар на федерацията на най-успешния зимен спорт на България Борислав Панков.\nСъболезнования към близките му.
859                                                                           Нидерландски защитник аут за световното          49     Защитникът на Нидерландия и английския първенец "Арсенал" Юриен Тимбер ще пропусне световното първенство, тъй като не успя да се възстанови от травма в слабините.\n24-годишният футболист напуска лагера на „оранжевите".\nСелекционерът Роналд Куман повика Лутсхарел Гертройда ("Съндърланд") на негово място.\nНидерландия е в група с Япония, Швеция и Тунис.
1249                                                                     КМГ: Каналът „Пинлу“: Проект на века (Видео)          48                                                            Провинция Гуанси е място, където водата не просто оформя природата — тя е двигател на икономически растеж. Един от най-важните инфраструктурни проекти тук е каналът „Пинлу". Той е с дължина над 130 километра и отваря нови възможности за воден транспорт, като свързва много от местните реки с морето.
1325                                                                             Ренета Колева става зам.-екоминистър          36                                                                                           Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на околната среда и водите е назначена Ренета Георгиева Колева.\nТова съобщиха от правителствената пресслужба. Другият зам.-екоминистър е Костадин Гешев, който бе назначен в края на май.
1662                                      Мъж подаде фалшив сигнал, че специализиран автомобил е опитал да го прегази          45                                                                        39-годишен мъж подаде фалшив сигнал, че специализиран автомобил се е опитал да го прегази, съобщиха от полицията.\nМъжът е община Кирково. Установено е, че сигналът не отговаря на истината и не е имало такъв инцидент.\nПодателят на съобщението е задържан.\nПо случая се води разследване.
1674                                        Израел обяви мащабен удар по иранските стратегически отбранителни системи          46                  Израел обяви, че е нанесъл днес мащабен удар по иранските стратегически отбранителни системи, предаде Ройтерс.\nЦелта е била да бъдат унищожени противовъздушни отбранителни способности, които Иран е разполагал, каза в изявление израелската армия.\nИзраел удари и нефтохимически завод в югозападната част на Ислямската република, посочва БТА.
2101                                                                 Как малкият Иванчо сравнява любовта с политиката          16                                                                                                                                                                                                         https://www.24chasa.bg/mneniya/article/22994735\nwww.24chasa.bg\nКак малкият Иванчо сравнява любовта с политиката\n1900\nПоследвайте ни в Google News Showcase
2175                                                       Кола се качи на трамвайните релси до гара Подуяне (Снимки)          41                                                                                                 Кола се качи на трамвайните релси на бул. "Ботевградско шосе" до гара Подуяне. Заради инцидента е възможно забавяне на графика на трамваите. Въпреки това движението по булеварда не е затруднено. Други шофьори се опитват да помогнат на закъсалата на релсите кола.
2284                                                                   Ясни са съперничките на Серена Уилямс в Лондон          46                                                                                                  Серена Уилямс официално се завръща на корта и първите й съпернички са известни.\nНа турнира в Куинс (Лондон) бившата №1 в света участва на двойки с Виктория Мбоко (Кан) и в първия кръг ще играят срещу Никол Меличар Мартинес (САЩ) и Ерин Рутлиф от Нова Зеландия.
2405                                                        Верижна катастрофа затвори пътя София-Варна край Лясковец          38                                                                                                         Временно е затворен главен път София -Варна, в района на разклона за Лясковец, заради катастрофа. Автомобилите се пренасочват през с. Козаревец. Това съобщи ОДМВР - Велико Търново.\nПо първоначални данни са се ударили три леки автомобила, има пострадали.
2618                                                         Южна Корея номинира жена за премиер за пръв път от 20 г.          38                                                                     Южнокорейският президент И Дже-мьон избра Хан Сонгсук, министър на малките и средните предприятия и стартиращите фирми, за министър-председател, съобщи президентската канцелария, предаде Ройтерс.\nХан ще бъде първата жена министър-председател на Южна Корея от 20 години насам, припомня БТА.
2790                                                           488 са потвърдените случаи на зараза с ебола в ДРКонго          40                                                                                                        Властите на Демократична република Конго заявиха, че броят на потвърдените случаи на зараза с ебола се е увеличил на 488 души, предаде Ройтерс, съобщи БТА.\nСред тези потвърдени случаи има и 86 с летален изход, заяви правителството на африканската страна.
3206                                        Русия: Превзехме населеното място Шевченко в украинската Харковска област          43                                                        Руското министерство на отбраната заяви днес, че руските сили са превзели населеното място Шевченко в украинската Харковска област, предаде Ройтерс, като се позова на руската новинарска агенция РИА Новости.\nРойтерс отбелязва, че засега не може да потвърди достоверността на тази информация, съобщи БТА.
3209   Вижте отговора на фотозагадката: Кой е актьорът, рисуван от от големия художник Кольо Карамфилов през 2005 г.?          43                                                                                              Отговорът на фотозагадката от 5 юни е: Христо Пъдев!\nВъпросът беше: Кой е актьорът, рисуван от от големия художник Кольо Карамфилов през 2005 г.⁉️\nЖокерът беше: 17 години танцува в ансамбъл, но при кандидатстването му в НАТФИЗ го късат именно в категория "танци".
3211                                           Кола се блъсна в крайпътно съоръжение до пловдивското село Чешнегирово          49                                                                     Кола се е блъснала в крайпътно съоръжение в близост до пловдивското село Чешнегирово. Има ранен в катастрофата, която е станала в 13,10 часа днес.\nОт началото на денонощието пътните инциденти в страната са общо 48. Има един загинал - след удар в дърво в Силистренска област, ранените са 9.
3563                                                                                  Катастрофа в Белозем, има ранен          44                                                                                                        Коли са се сблъскали снощи в пловдивското село Белозем и един от участниците в катастрофата е ранен. Инцидентът е станал в 19,32 часа на 5 юни, ударът е бил страничен.\nОт началото на днешното денонощие в страната са станали общо 9 катастрофи, няма тежки.
3566                                                                              Автобус се запали на Аспарухов мост          43                                                                                         Автобус се запали на Аспаруховия мост във Варна. Сигналът е получен в 8 сутринта на тел. 112.\nКасае се за техническа повреда, няма пострадали. Автобусът е бил празен, пожарът е изгасен и се чака пътна помощ.\nИнцидентът предизвика километрична опашка, съобщава Нова тв.
4061                       Фотозагадка: Кой е този актьор, рисуван от големия художник Кольо Карамфилов през 2005 г.?          40                                                                                                       Фотозагадката от днес е: Кой е този актьор, рисуван от големия художник Кольо Карамфилов през 2005 г.?\nЖокер: 17 години танцува в ансамбъл, но при кандидатстването му в НАТФИЗ го късат именно в категория "танци".\nОчаквайте утре отговора на фотозагадката!
4078                                                                 "Казанлък рестарт" - изтегли приложението от тук          31                                                                                                                                   "Казанлък рестарт" - изтегли приложението от тук\nСпециален проект\n2248\nЧетете още\n"Горна Оряховица Рестарт" - изтегли приложението от тук\n29.05.2026,\n08:43\n"Пирин Рестарт" - изтегли приложението от тук\n22.05.2026,\n08:35
4356                                                     Южнокорейският президент отива във Франция за срещата на Г-7          43                                                                              Южнокорейският президент И Дже-мьон ще пътува до Европа от 9 до 18 юни, за да посети Белгия, Италия и Ватикана, предаде Ройтерс, цитирана от БТА.\nЮжнокорейският лидер също така ще присъства на срещата на Г-7 във Франция, съобщиха днес от южнокорейската президентска администрация.
4418                                           Временно движението при км 20 по пътя Арчар – Добри дол е в една лента          48                                                      Временно движението при км 20 по път II-11 Арчар – Добри дол се осъществява двупосочно в една лента поради ПТП, съобщават от АПИ.\nШофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция".\nДвижението в участъка вече се осъществява нормално без ограничения.
4428                                                       Катастрофа при км 55 на магистрала "Тракия" в посока София          46                                                                            Временно движението при км 55 на АМ "Тракия" в посока София се осъществява в активната лента поради ПТП, съобщават от АПИ. Ограничена е изпреварващата лента. Трафикът се регулира от "Пътна полиция".\nВъзстановено е движението при км 55 на АМ "Тракия" в посока София, съобщиха от АПИ.
4742                                               "Цървена звезда" е близо до трансфер на Кристиян Балов от "Славия"          44                                                  "Цървена звезда" преговаря със "Славия" за младия български нападател Кристиян Балов, пише Sportal.rs.\nСръбското издание описва крилото на "белите" като един от големите български таланти.\nБалов ще подпише четиригодишен договор със "звездашите", а трансферът му ще струва на сръбския шампион 2 500 000 евро.
4756               Заради ремонт на "Тракия" - движението от 2 до 3 км към София е във втората и изпреварващата лента          48                                                                                      Заради ремонт на "Тракия" - движението от 2 до 3 км към София е във втората и изпреварващата лента, съобщиха от АПИ. Така ще бъде до 14 ч днес, докогато се очаква да продължи ремонтът на асфалтовата настилка. Шофьорите да се движат с повишено внимание и съобразена скорост.
4888                                                                        Честит рожден ден на Камелия Александрова          41                                                                                                   Днес рожден ден празнува Камелия Александрова, кореспондентката на “24 часа” в Монтана.\nУпорита и добронамерена, тя пише за града и жителите му с огромна надежда за развитие на Северозапада.\nОт редакцията на в. “24 часа” пожелание за здраве и честит празник.
5593                                               Катастрофа на пътя Велинград –  Варвара, движението е в една лента          49                                                                Временно при км 25 на път II-84 Велинград – с. Варвара, в участъка Гара Костандово – с. Варвара, движението се осъществява двупосочно в една лента поради ПТП, съобщиха от АПИ.\nВодачите да се движат с повишено внимание и съобразена скорост, като трафикът в района се регулира от „Пътна полиция".
5608                                                                   Рожденичката Мария Бакалова пие кафе във Виена          49                                                    30-ия си рожден ден единствената българска актриса с номинация за "Оскар" Мария Бакалова пие кафе в австрийската столица Виена. Това сподели самата тя в публикация във фейсбук.\n"Преди тридесет години в 09:40 едно малко момиченце пристигна в Бургас.\nДнес сутринта в 09:40 тя пиеше кафе във Виена", пише тя.
5973                                     Малкият Иванчо  казва кое за политиците е най-спешното след детската болница          26                                                                                                                                              https://www.24chasa.bg/mneniya/article/22973688\nwww.24chasa.bg\nМалкият Иванчо казва кое за политиците е най-спешното след детската болница\n2480\nПоследвайте ни в Google News Showcase\nОще от Малкият Иванчо\nНА ЖИВО
6192                                                                                         На 4 юни рожден ден имат          40                                                                   Мария Бакалова, актриса\nСпас Русев, бизнесмен\nЧл.-кор. проф. д-р Николай Милошев, директор на Националния институт по геофизика, геодезия и география към БАН\nМилица Божинова, певица от “Фамилия Тоника”\nД-р Миряна Сечанова, хирург мамолог, ръководител на Центъра за млечни жлези “Софиямед”
6194                                                                                Честит рожден ден на Петър Попов!          47                                               Днес рожден ден празнува колегата ни от отдел “Реклама” Петър Попов. Със своята отдаденост, професионален подход и усет към добрите решения той е важна част от екипа, който всекидневно работи за доброто представяне и развитието на медията.\nПожелаваме му здраве, много лични и професионални успехи и вдъхновение!
6694                                                        Земетресение с магнитуд 5,5 удари американския щат Орегон          46                                               Земетресение с магнитуд 5,5 по скалата на Рихтер бе регистрирано край бреговете на американския щат Орегон, съобщи Германският изследователски център за геонауки, предаде Ройтерс.\nТо е станало на дълбочина от 10 километра, посочи центърът, цитиран от БТА. Засега няма данни за жертви и сериозни материални щети.
7098                                 Ограничават движението в тунел "Топли дол" на АМ "Хемус" към София заради ремонт          43                                                                             Движението в тунел "Топли дол" на АМ "Хемус" в посока София се осъществява в изпреварващата лента поради ремонт на асфалтовата настилка, съобщиха от АПИ.\nОт агенциятта съветват шофьорите да се движат с повишено внимание и съобразена скорост. Участъкът е сигнализиран с пътни знаци.
7110                          Прокурорската колегия на ВСС отложи избора на нов шеф на Националната следствена служба          41                                                                    Прокурорската колегия на ВСС отложи избора на нов директор на Националната следствена служба, тъй като няма постъпили кандидатури.\nДвамата заместник-директори на НСлС не са дали съгласие да бъдат кандидатирани. И даде тридневен срок на главния прокурор да направи предложения, съобщава БНТ.
7121                                        Пожар гори в заведение в Слънчев бряг, евакуират туристи от хотел (Видео)          38                                                                                                           Пожар гори в заведение в курорта Слънчев бряг, съобщи БТА. Евакуирани са всички туристи и персонал от намиращия се в непосредствена близост хотел „Тиара бийч“, казаха от полицията на място.\nРайонът е отцепен. Огъня гасят два противопожарни автомобила.
7151                                                                        Григор и Ейса заедно на парти край морето          42                                                                                   Григор Димитров и Ейса Гонсалес пак се събраха и бяха сред гостите на специално парти.\nНай-добрият български тенисист в историята и мексиканската му приятелка присъстваха на вечерята на модна марка във френския курортен град Антиб.\nНа Григор му предстоят турнирите на трева.
7500                                                                      Изпращането на Любен Дилов-син ще е в петък          45                                                                                                  Изпращането на Любен Дилов-син, който почина на 61-годишна възраст, ще е на 5 юни, петък.\nТова съобщиха от семейството в профила във фейсбук на Дилов. Изпращането на тленните останки на писателя ще е от 15 часа с църковен ритуал в храм "Св. София" в столицата.

**Finding:** 24chasa — Two edge cases

Very short articles (< 50 words): 

Inspection shows two patterns:

- Pure boilerplate stubs — newsletter prompts, social links, no real content (e.g. "24 часа в мейла ти...")
- Legitimate short-form content — breaking news flashes, traffic updates, photo captions (37–49 words)

Very long articles (> 3 000 words):
All are structured road condition reports published daily by the Road Infrastructure Agency under the same title ("Вижте какво е състоянието на пътищата тази вечер"), reaching up to 13 773 words. These are not news articles and would pollute RAG retrieval.

### 3c. Per-Source Shortest & Longest Articles

In [67]:
for source in df["source"].unique():
    source_df = df[df["source"] == source].sort_values("word_count")
    print(f"=== {source.upper()} ===")
    print(
        f"Total: {len(source_df)} | Median words: {source_df['word_count'].median():.0f}"
    )
    print()
    print("-- 2 SHORTEST --")
    for _, row in source_df.head(2).iterrows():
        print(f"  [{row['word_count']} words] {row['title']}")
        print(f"  Preview: {row['full_text'][:150]}")
        print()
    print("-- 2 LONGEST --")
    for _, row in source_df.tail(2).iterrows():
        print(f"  [{row['word_count']} words] {row['title']}")
        print(f"  Preview: {row['full_text'][:150]}")
        print()
    print("=" * 60)
    print()

=== VESTI ===
Total: 3147 | Median words: 340

-- 2 SHORTEST --
  [42 words] Коулрофобия, чиклефобия и атаксофобия: От какво се ужасяват Меган Фокс, Джони Деп и Опра Уинфри?
  Preview: С трахът е нормална човешка емоция, която всички изпитваме, и известните и влиятелните личности не правят изключение. Докато някои звезди страдат от п

  [47 words] Арестуваха кмета на Кърджали
  Preview: К метът на Кърджали Ерол Мюмюн е бил арестуван в четвъртък, научи NOVA от свои източници.
По информация от пресцентъра на Община Кърджали градоначални

-- 2 LONGEST --
  [4081 words] <p>Кабинетът &quot;Радев&quot; е готов: Кои са големите изненади</p>
  Preview: К андидатът за министър-председател Румен Радев, излъчен от парламентарната група на „Прогресивна България“, получи днес от президента Илияна Йотова м

  [4945 words] Мистерията на златния ковчег: Голямата измама в международната търговия с антики
  Preview: П рез ноември 2017 г. френският президент Еманюел Макрон пътува до Обединените арабски емирства, за да открие нов музей - и нови отношения между Изток

============================================================

=== MONITOR ===
Total: 3404 | Median words: 220

-- 2 SHORTEST --
  [35 words] Румънското правителство падна!
  Preview: Р умънският парламент подкрепи вота на недоверие срещу Илие Боложан.
Той беше внесен от социалдемократите и крайната десница.
Решението задълбочава по

  [39 words] ЦСКА със специален поздрав към феновете
  Preview: Ф утболистите, треньорите и част от ръководството поздравиха феновете на тима по случай 78-годишнина, която клубът празнува днес.
Христо Янев и компан

-- 2 LONGEST --
  [3145 words] Топ 20 на младите звезди на Мондиала
  Preview: Н яколко дни преди старта на Мондиал 2026 вече са ясни имената на всички повикани футболисти. Ето кои 20 младока заслужават внимание според известния

  [3173 words] Доц. Людмила Беленска: Невежеството е най-опасно за здравето
  Preview: - Развитието на технологиите и конкретно AI с какво промениха генетиката и кое може да определим като най-модерното в тази област?
- Нека първо да съп

============================================================

=== STANDARTNEWS ===
Total: 3930 | Median words: 323

-- 2 SHORTEST --
  [34 words] Рожден ден днес има култов актьор
  Preview: Рожден ден днес празнуат:
Николай Сотиров, актьор
Веселин Тодоров, изпълнителен директор на „Сиела“
Лияна Панделиева, журналистка
Васил Сотиров, писат

  [37 words] Рожден ден днес има култова актриса
  Preview: Рожден ден днес празнуват:
Пламена Гетова, актриса
Калин Георгиев, бивш главен секретар на МВР
Георги Станчев, композитор и певец
Надя Попова, поетеса

-- 2 LONGEST --
  [3640 words] Ето ги шефовете на парламентарни комисии. Големи изненади
  Preview: Народното събрание определи съставите и ръководствата на парламентарните комисии, които ще функционират като постоянно действащи органи, след като дос

  [3687 words] Кой кой е в кабинета "Радев" (БИОГРАФИИ)
  Preview: Министър - председател – Румен Георгиев Радев:
От 2017 до 2026 г. Румен Радев е президент на Република България. На 19 януари 2026 г. в обръщение към

============================================================

=== SEGABG ===
Total: 1567 | Median words: 351

-- 2 SHORTEST --
  [57 words] Арестуван е кметът на Кърджали
  Preview: Кметът на Кърджали Ерол Мюмюн е бил арестуван, съобщи "Нова тв", като се позова на свои източници.
По информация от пресцентъра на Община Кърджали Мюм

  [60 words] Два трамвая се сблъскаха в София
  Preview: Два трамвая — линии 3 и 13 — се сблъскаха в района на Централна гара в София, в посока бул. „Христо Ботев“.
Няма данни за тежко пострадали към този мо

-- 2 LONGEST --
  [2555 words] Изненадите в кабинета на Радев - някои невзрачни, други - комични
  Preview: Правителството на Румен Радев се състои главно от познати кадри от неговите служебни кабинети, приютили се като негови съветници след напускането на и

  [2696 words] Трансферите в Първа лига - сезон 2025/26
  Preview: "БОТЕВ" (ПД)
Пловдивският клуб подписа дългосрочен договор с датския нападател Ифена Доргу (19 г.) с перспектива за следащите сезони. Той идва от датс

============================================================

=== BTA ===
Total: 4633 | Median words: 261

-- 2 SHORTEST --
  [36 words] Петер Мадяр положи клетва като министър-председател на Унгария
  Preview: Петер Мадяр пристигна в парламента, за да положи клетва като министър-председател на Унгария
Бъдещият министър-председател на Унгария Петер Мадяр прис

  [38 words] Иранската държавна телевизия предаде, че американски самолет е бил унищожен близо до град Бушер, няма потвърждение от страна на САЩ
  Preview: Иранските въоръжени сили са изстреляли ракети от южната част на страната, съобщи агенция Фарс
Въоръжените сили на Иран са изстреляли ракети от южната

-- 2 LONGEST --
  [3582 words] Пазарите навлизат в седмица на инфлационни данни, заседание на ЕЦБ и очакван борсов дебют на „СпейсЕкс“
  Preview: site.btaПазарите навлизат в седмица на инфлационни данни, заседание на ЕЦБ и очакван борсов дебют на „СпейсЕкс“
Световните пазари навлизат в седмица,

  [4016 words] Поредна дама напуска администрацията на Тръмп - случайно съвпадение или закономерна тенденция
  Preview: site.btaПоредна дама напуска администрацията на Тръмп - случайно съвпадение или закономерна тенденция
В петък в администрацията на президента на САЩ Д

============================================================

=== BANKER ===
Total: 997 | Median words: 259

-- 2 SHORTEST --
  [31 words] Лилия Стоянович е назначена за зам.-министър на труда и социалната политика
  Preview: Социалното министерство ще има нов заместник-министър.
Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на труда и со

  [43 words] Назначиха Ива Кечева за заместник-министър на правосъдието
  Preview: Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на правосъдието е назначена Ива Димчева Кечева, съобщават от пресслу

-- 2 LONGEST --
  [1870 words] Със 122 гласа „За“ парламентът гласува кабинета с министър-председател Румен Радев
  Preview: Със 122 гласа „За“ (на депутатите от „Прогресивна България“) 52-рото Народно събрание подкрепи състава на кабинета, предложен от Румен Радев – с четир

  [3714 words] Кой кой е в кабинета на Румен Радев
  Preview: Кандидатът за министър-председател Румен Радев, излъчен от парламентарната група на „Прогресивна България“, получи днес от президента Илияна Йотова ма

============================================================

=== ECONOMIC ===
Total: 466 | Median words: 521

-- 2 SHORTEST --
  [122 words] Вятърът генерира 11% от електроенергията в Европа
  Preview: Вятърът генерира 11% от електроенергията в Европа
Делът на електроенергията от вятърни централи в Европа през изминалите 24 часа е 10.6 на сто, сочат

  [130 words] Nintendo вдига цената на конзолата Switch 2
  Preview: Nintendo вдига цената на конзолата Switch 2
Японската компания се сблъсква с недостиг на чипове и спад на продажбите
Nintendo ще повиши цената на флаг

-- 2 LONGEST --
  [2668 words] CBAM в действие: Между климатичните амбиции и съпротивата на бизнеса
  Preview: CBAM в действие: Между климатичните амбиции и съпротивата на бизнеса
Индустрията предупреждава за риск от деиндустриализация, ЕК обещава гъвкавост в п

  [4092 words] Как да стане безрискова фискална децентрализация в България?
  Preview: Как да стане безрискова фискална децентрализация в България?
Незначителни, лесни за разбиране и прилагане изменения и допълнения на Закона за публични

============================================================

=== ACTUALNO ===
Total: 7489 | Median words: 306

-- 2 SHORTEST --
  [39 words] Евро - лев. Калкулатор от евро в стария лев, 30 април /валутен калкулатор/
  Preview: Колко би струвала определена стока в евро спрямо старите левове? Използвайте този валутен калкулатор, за да сметнете в левове определена цена в евро,

  [39 words] Евро - лев. Калкулатор от евро в стария лев, 27 април /валутен калкулатор/
  Preview: Колко би струвала определена стока в евро спрямо старите левове? Използвайте този валутен калкулатор, за да сметнете в левове определена цена в евро,

-- 2 LONGEST --
  [3203 words] 9 май: От парад на победата до тържество на презрението (СНИМКИ И ВИДЕО)
  Preview: Парадът за Деня на победата, който традиционно се отбелязва на 9 май всяка година е събитието в Русия, което концентрира най-много военна техника, при

  [3469 words] Как Путин живее в паралелна реалност и там мир няма: Колекция с примери от Санкт Петербург (ОБЗОР - ВИДЕО)
  Preview: Руският диктатор Владимир Путин отхвърли предложението на украинския президент Володимир Зеленски за преговори за прекратяване на войната на ниво лиде

============================================================

=== NOVA ===
Total: 5140 | Median words: 288

-- 2 SHORTEST --
  [15 words] „DARA: Роди се звезда”: Специално студио на NOVA (19.05.2026)
  Preview: Гледайте цялото тържество по официалното посрещане на победителката в „Евровизия”
Редактор: Маргарита Стоянчева
Последвайте ни

  [33 words] Янез Янша е новият премиер на Словения
  Preview: Снимка: БТА
51 депутати подкрепиха лидера на десницата
Парламентът на Словения избра Янез Янша за министър-председател.
51 депутати подкрепиха лидера

-- 2 LONGEST --
  [3761 words] Кой кой е в проектокабинета „Радев”
  Preview: Снимка: БГНЕС
Вижте кои са хората, насочили се към министерските кресла в новия състав на МС
Кандидатът за министър-председател - Румен Радев, предста

  [4502 words] Служебните министри предадоха властта на членовете на редовния кабинет
  Preview: Структурата на МС се променя след сливането на две ведомства
След малко над два месеца на управление в рамките на служебен кабинет, начело с премиера

============================================================

=== 24CHASA ===
Total: 13128 | Median words: 213

-- 2 SHORTEST --
  [13 words] Малкият Иванчо иска череши
  Preview: https://www.24chasa.bg/mneniya/article/22821913
www.24chasa.bg
Малкият Иванчо иска череши
1552
Последвайте ни в Google News Showcase

  [14 words] Бащата на Иванчо за живота
  Preview: https://www.24chasa.bg/mneniya/article/22819080
www.24chasa.bg
Бащата на Иванчо за живота
152
Последвайте ни в Google News Showcase

-- 2 LONGEST --
  [13621 words] Вижте какво е състоянието на пътищата тази вечер
  Preview: Информация за състоянието на републиканските пътища към 17:30 часа на 08.06.2026 г.
МЕТЕОРОЛОГИЧНА ОБСТАНОВКА:
През нощта валежите ще спрат и облачнос

  [13773 words] Вижте какво е състоянието на пътищата тази вечер
  Preview: Агенция "Пътна инфраструктура" информира за състоянието на пътищата, въведените ограничения и метеорологичната обстановка у нас към 17:30 часа.
I. МЕТ

============================================================

=== FAKTI ===
Total: 7583 | Median words: 390

-- 2 SHORTEST --
  [44 words] Арестуваха кмета на Кърджали
  Preview: Арестуваха кмета на Кърджали Ерол Мюмюн, съобщи NOVA.
Местните медии съобщават, че той е бил отведен от четирима полицаи тази сутрин.
В момента се изв

  [47 words] Резултати от мачовете в НБА
  Preview: Резултати от първи кръг на плейофите в Националната баскетболна асоциация на САЩ и Канада - НБА:
Минесота Тимбърлувс - Денвър Нъгетс 110:98
Филаделфия

-- 2 LONGEST --
  [8549 words] 3 май 1481 г. Умира Мехмед II Завоевателят
  Preview: На 3 май 1481 г. умира Мехмед II Завоевателят. Той издъхва по време на поход срещу Египет.
Мехмед II е 7-ият султан на Османската империя, управлявал

  [10868 words] В Москва! Парадът на победата на Червения площад (ВИДЕО)
  Preview: Парадът в чест на 81-вата годишнина от победата във Великата отечествена война започна на Червения площад, съобщи ТАСС, цитирана от БТА.
Началото му б

============================================================

### 3d. Calculator Articles

In [68]:
calculator_articles = df[
    (df["source"] == "actualno")
    & (df["title"].str.contains("валутен калкулатор", na=False))
]

print(f"Calculator articles: {len(calculator_articles)}")
print(calculator_articles[["title", "word_count", "url"]].to_string())

Calculator articles: 151
                                                                                                     title  word_count                                                                                                                                               url
13819    Турска лира - евро. Колко струва една турска лира към едно евро днес, 28 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-28-maj-valuten-kalkulator-news_2599651.html
13822         Долар - евро. Колко струва един щатски долар към едно евро днес, 28 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-28-maj-valuten-kalkulator-news_2599652.html
13823      Паунд - евро. Колко струва един британски паунд към едно евро днес, 28 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-28-maj-valuten-kalkulator-news_2599653.html
15039                             Евро - лев. Калкулатор от евро в стария лев, 27 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-27-maj-valuten-kalkulator-news_2599205.html
15041    Турска лира - евро. Колко струва една турска лира към едно евро днес, 27 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-27-maj-valuten-kalkulator-news_2599202.html
15043         Долар - евро. Колко струва един щатски долар към едно евро днес, 27 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-27-maj-valuten-kalkulator-news_2599203.html
15044      Паунд - евро. Колко струва един британски паунд към едно евро днес, 27 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-27-maj-valuten-kalkulator-news_2599204.html
16058    Турска лира - евро. Колко струва една турска лира към едно евро днес, 26 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-26-maj-valuten-kalkulator-news_2598750.html
16060         Долар - евро. Колко струва един щатски долар към едно евро днес, 26 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-26-maj-valuten-kalkulator-news_2598751.html
16062      Паунд - евро. Колко струва един британски паунд към едно евро днес, 26 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-26-maj-valuten-kalkulator-news_2598752.html
16095                             Евро - лев. Калкулатор от евро в стария лев, 26 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-26-maj-valuten-kalkulator-news_2598753.html
17008                             Евро - лев. Калкулатор от евро в стария лев, 25 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-25-maj-valuten-kalkulator-news_2598468.html
17010    Турска лира - евро. Колко струва една турска лира към едно евро днес, 25 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-25-maj-valuten-kalkulator-news_2598465.html
17012         Долар - евро. Колко струва един щатски долар към едно евро днес, 25 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-25-maj-valuten-kalkulator-news_2598466.html
17013      Паунд - евро. Колко струва един британски паунд към едно евро днес, 25 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-25-maj-valuten-kalkulator-news_2598467.html
18041                             Евро - лев. Калкулатор от евро в стария лев, 24 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-24-maj-valuten-kalkulator-news_2598197.html
18043    Турска лира - евро. Колко струва една турска лира към едно евро днес, 24 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-24-maj-valuten-kalkulator-news_2598194.html
18044         Долар - евро. Колко струва един щатски долар към едно евро днес, 24 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-24-maj-valuten-kalkulator-news_2598195.html
18045      Паунд - евро. Колко струва един британски паунд към едно евро днес, 24 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-24-maj-valuten-kalkulator-news_2598196.html
19109    Турска лира - евро. Колко струва една турска лира към едно евро днес, 23 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-23-maj-valuten-kalkulator-news_2597925.html
19111         Долар - евро. Колко струва един щатски долар към едно евро днес, 23 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-23-maj-valuten-kalkulator-news_2597926.html
19113      Паунд - евро. Колко струва един британски паунд към едно евро днес, 23 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-23-maj-valuten-kalkulator-news_2597927.html
19152                             Евро - лев. Калкулатор от евро в стария лев, 23 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-23-maj-valuten-kalkulator-news_2597928.html
20444      Паунд - евро. Колко струва един британски паунд към едно евро днес, 22 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-22-maj-valuten-kalkulator-news_2597415.html
20511                             Евро - лев. Калкулатор от евро в стария лев, 22 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-22-maj-valuten-kalkulator-news_2597416.html
20512    Турска лира - евро. Колко струва една турска лира към едно евро днес, 22 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-22-maj-valuten-kalkulator-news_2597413.html
20513         Долар - евро. Колко струва един щатски долар към едно евро днес, 22 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-22-maj-valuten-kalkulator-news_2597414.html
21828                             Евро - лев. Калкулатор от евро в стария лев, 21 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-21-maj-valuten-kalkulator-news_2596896.html
21831    Турска лира - евро. Колко струва една турска лира към едно евро днес, 21 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-21-maj-valuten-kalkulator-news_2596893.html
21833         Долар - евро. Колко струва един щатски долар към едно евро днес, 21 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-21-maj-valuten-kalkulator-news_2596894.html
21834      Паунд - евро. Колко струва един британски паунд към едно евро днес, 21 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-21-maj-valuten-kalkulator-news_2596895.html
23017         Долар - евро. Колко струва един щатски долар към едно евро днес, 20 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-20-maj-valuten-kalkulator-news_2596392.html
23019      Паунд - евро. Колко струва един британски паунд към едно евро днес, 20 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-20-maj-valuten-kalkulator-news_2596393.html
23092                             Евро - лев. Калкулатор от евро в стария лев, 20 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-20-maj-valuten-kalkulator-news_2596394.html
23094    Турска лира - евро. Колко струва една турска лира към едно евро днес, 20 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-20-maj-valuten-kalkulator-news_2596391.html
24323    Турска лира - евро. Колко струва една турска лира към едно евро днес, 19 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-19-maj-valuten-kalkulator-news_2595878.html
24324         Долар - евро. Колко струва един щатски долар към едно евро днес, 19 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-19-maj-valuten-kalkulator-news_2595879.html
24326      Паунд - евро. Колко струва един британски паунд към едно евро днес, 19 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-19-maj-valuten-kalkulator-news_2595880.html
24375                             Евро - лев. Калкулатор от евро в стария лев, 19 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-19-maj-valuten-kalkulator-news_2595881.html
25550                             Евро - лев. Калкулатор от евро в стария лев, 18 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-18-maj-valuten-kalkulator-news_2595379.html
25552    Турска лира - евро. Колко струва една турска лира към едно евро днес, 18 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-18-maj-valuten-kalkulator-news_2595376.html
25554         Долар - евро. Колко струва един щатски долар към едно евро днес, 18 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-18-maj-valuten-kalkulator-news_2595377.html
25556      Паунд - евро. Колко струва един британски паунд към едно евро днес, 18 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-18-maj-valuten-kalkulator-news_2595378.html
26484                             Евро - лев. Калкулатор от евро в стария лев, 17 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-17-maj-valuten-kalkulator-news_2595143.html
26485    Турска лира - евро. Колко струва една турска лира към едно евро днес, 17 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-17-maj-valuten-kalkulator-news_2595140.html
26486         Долар - евро. Колко струва един щатски долар към едно евро днес, 17 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-17-maj-valuten-kalkulator-news_2595141.html
26487      Паунд - евро. Колко струва един британски паунд към едно евро днес, 17 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-17-maj-valuten-kalkulator-news_2595142.html
27375                             Евро - лев. Калкулатор от евро в стария лев, 16 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-16-maj-valuten-kalkulator-news_2594882.html
27376    Турска лира - евро. Колко струва една турска лира към едно евро днес, 16 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-16-maj-valuten-kalkulator-news_2594879.html
27377         Долар - евро. Колко струва един щатски долар към едно евро днес, 16 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-16-maj-valuten-kalkulator-news_2594880.html
27378      Паунд - евро. Колко струва един британски паунд към едно евро днес, 16 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-16-maj-valuten-kalkulator-news_2594881.html
28664    Турска лира - евро. Колко струва една турска лира към едно евро днес, 15 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-15-maj-valuten-kalkulator-news_2594402.html
28666         Долар - евро. Колко струва един щатски долар към едно евро днес, 15 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-15-maj-valuten-kalkulator-news_2594403.html
28668      Паунд - евро. Колко струва един британски паунд към едно евро днес, 15 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-15-maj-valuten-kalkulator-news_2594404.html
28714                             Евро - лев. Калкулатор от евро в стария лев, 15 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-15-maj-valuten-kalkulator-news_2594405.html
30013      Паунд - евро. Колко струва един британски паунд към едно евро днес, 14 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-14-maj-valuten-kalkulator-news_2593879.html
30103                             Евро - лев. Калкулатор от евро в стария лев, 14 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-14-maj-valuten-kalkulator-news_2593880.html
30105    Турска лира - евро. Колко струва една турска лира към едно евро днес, 14 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-14-maj-valuten-kalkulator-news_2593877.html
30108         Долар - евро. Колко струва един щатски долар към едно евро днес, 14 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-14-maj-valuten-kalkulator-news_2593878.html
31349         Долар - евро. Колко струва един щатски долар към едно евро днес, 13 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-13-maj-valuten-kalkulator-news_2593332.html
31351      Паунд - евро. Колко струва един британски паунд към едно евро днес, 13 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-13-maj-valuten-kalkulator-news_2593333.html
31425                             Евро - лев. Калкулатор от евро в стария лев, 13 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-13-maj-valuten-kalkulator-news_2593334.html
31426    Турска лира - евро. Колко струва една турска лира към едно евро днес, 13 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-13-maj-valuten-kalkulator-news_2593331.html
32708         Долар - евро. Колко струва един щатски долар към едно евро днес, 12 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-12-maj-valuten-kalkulator-news_2592785.html
32710      Паунд - евро. Колко струва един британски паунд към едно евро днес, 12 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-12-maj-valuten-kalkulator-news_2592786.html
32750                             Евро - лев. Калкулатор от евро в стария лев, 12 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-12-maj-valuten-kalkulator-news_2592787.html
32751    Турска лира - евро. Колко струва една турска лира към едно евро днес, 12 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-12-maj-valuten-kalkulator-news_2592784.html
34037                             Евро - лев. Калкулатор от евро в стария лев, 11 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-11-maj-valuten-kalkulator-news_2592275.html
34039    Турска лира - евро. Колко струва една турска лира към едно евро днес, 11 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-11-maj-valuten-kalkulator-news_2592272.html
34040         Долар - евро. Колко струва един щатски долар към едно евро днес, 11 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-11-maj-valuten-kalkulator-news_2592273.html
34043      Паунд - евро. Колко струва един британски паунд към едно евро днес, 11 май /валутен калкулатор/          40      https://www.actualno.com/finance/paund-evro-kolko-struva-edin-britanski-paund-kym-edno-evro-dnes-11-maj-valuten-kalkulator-news_2592274.html
35001                             Евро - лев. Калкулатор от евро в стария лев, 10 май /валутен калкулатор/          66                            https://www.actualno.com/finance/evro-lev-kalkulator-ot-evro-v-starija-lev-10-maj-valuten-kalkulator-news_2592046.html
35002    Турска лира - евро. Колко струва една турска лира към едно евро днес, 10 май /валутен калкулатор/         226    https://www.actualno.com/finance/turska-lira-evro-kolko-struva-edna-turska-lira-kym-edno-evro-dnes-10-maj-valuten-kalkulator-news_2592043.html
35003         Долар - евро. Колко струва един щатски долар към едно евро днес, 10 май /валутен калкулатор/          66       https://www.actualno.com/finance/dolar-evro-kolko-struva-edin-shtatski-dolar-kym-edno-evro-dnes-10-maj-valuten-kalkulator-news_2592044.html

In [69]:
road_mask = (df["source"] == "24chasa") & (
    df["title"].str.contains("състоянието на пътищата", na=False)
)
print(f"Road condition reports: {road_mask.sum()}")

calc_mask = (df["source"] == "actualno") & (
    df["title"].str.contains("валутен калкулатор", na=False)
)
print(f"Calculator articles: {calc_mask.sum()}")

short_mask = df["word_count"] < 30
print(f"Articles under 30 words: {short_mask.sum()}")

Road condition reports: 37
Calculator articles: 151
Articles under 30 words: 40

**Decision:** drop records with following content:
- Boilerplate stubs (< 30 words, 24chasa) — newsletter prompts and social share links with no real content.
- Daily currency calculators (actualno) — four currency pairs published as articles every day, identified by "калкулатор" in the title.
- Road condition reports (24chasa) — daily government bulletins up to 13 773 words, identified by "състоянието на пътищата" in the title.

In [70]:
print(f"Dropping {short_mask.sum()} articles under 30 words")
df = df[~short_mask].reset_index(drop=True)
print(f"Remaining articles: {len(df)}")

Dropping 40 articles under 30 words
Remaining articles: 51444

In [71]:
mask = (df["source"] == "24chasa") & (
    df["title"].str.contains("състоянието на пътищата", na=False)
)
print(f"Dropping {mask.sum()} road condition reports")
df = df[~mask].reset_index(drop=True)

mask = (df["source"] == "actualno") & (
    df["title"].str.contains("валутен калкулатор", na=False)
)
print(f"Dropping {mask.sum()} calculator articles")
df = df[~mask].reset_index(drop=True)

print(f"Remaining: {len(df)}")

Dropping 37 road condition reports
Dropping 151 calculator articles
Remaining: 51256

### 3e. Fakti outliers

In [72]:
fakti_outliers = df[(df["source"] == "fakti") & (df["word_count"] > 2000)].sort_values(
    "word_count", ascending=False
)

print(f"Fakti articles over 2000 words: {len(fakti_outliers)}")
print()
for _, row in fakti_outliers.head(5).iterrows():
    print(f"Title   : {row['title']}")
    print(f"Words   : {row['word_count']}")
    print(f"Preview : {row['full_text'][:400]}")
    print(f"End     : {row['full_text'][-400:]}")
    print("-" * 60)

Fakti articles over 2000 words: 269

Title   : В Москва! Парадът на победата на Червения площад (ВИДЕО)
Words   : 10868
Preview : Парадът в чест на 81-вата годишнина от победата във Великата отечествена война започна на Червения площад, съобщи ТАСС, цитирана от БТА.
Началото му бе отбелязано с ударите на курантите на Спаската кула. Под оркестровото изпълнение на легендарната композиция "Свещената война" на паветата на Червения площад бяха изнесени държавният флаг на Руската федерация и флагът на Съветския съюз, страната побе
End     : оленето и истината винаги се разминават. Не, че това има значение за безроден глупак!
13:57 09.05.2026
390 Северно Корейския ХОБИТ
До коментар #119 от "Мунчо":
Пратил малко РобиДа ги нагостят със
КУЧЕШКО ВАРЕНО
В Северна Корея
Сабаки нетъ.
13:57 09.05.2026
391 Така е
До коментар #386 от "Себе си описа,":
Безродника няма родина и затова клоака като запада го ползва за евтин отпадък!13:58 09.05.2026
------------------------------------------------------------
Title   : 3 май 1481 г. Умира Мехмед II Завоевателят
Words   : 8549
Preview : На 3 май 1481 г. умира Мехмед II Завоевателят. Той издъхва по време на поход срещу Египет.
Мехмед II е 7-ият султан на Османската империя, управлявал през периодите август 1444 – септември 1446 и 3 февруари 1451 – 3 май 1481 година. Той е наричан Завоевателя, заради успешната обсада на Константинопол през 1453 година.
Той управлява от август 1444 г. до септември 1446 г., а след това по-късно от фе
End     : о коментар #4 от "Какъв":
За твое сведение и Египет е бил техен. Но няма кой да се позаинтересува преди да вземе да пише тук.16:24 06.05.2025
227 Насилственото смяна имене
До коментар #2 от "Анонимен":
Не е турски възродителен процесА тоя е с много противна физиономия, чак плашеща!
05:24 03.05.2026
228 Какви са тия коменштари
Ега ти бокУууулуците
05:26 03.05.2026
229 Засрами се бе
05:28 03.05.2026
------------------------------------------------------------
Title   : 5 май 1876 г. Баташкото клане
Words   : 7789
Preview : 1876 г. при потушаването на Априлското въстание е извършено Баташкото клане. То е извършено от османски башибозук от съседните села под прякото командване на Ахмед ага Барутанлията. След клането той получава отличия и повишение от султана.
След началото на Априлското въстание на 20 април 1876 г. част от въоръжените боеспособни мъже от населението на село Батак, водени от войводата Петър Горанов, В
End     : и!":
Въри да прайш деца че сте -65000 на година:)17:24 28.04.2026
280 Горски
03:22 05.05.2026
281 АЛТЕРНАТИВА ЗА БЪЛГАРИЯ
......
А МАЙКАТА Е БЛУДНИЦАТА САЛОМЕ ;)
03:56 05.05.2026
282 Софийски
04:18 05.05.2026
283 Този коментар е премахнат от модератор.
284 Арена Арменец
До коментар #18 от "Ачо":
A Румен Радев ПЛАЩА ОДМАНДКИ кръвен данък "БОТАШ" ма сегашния Султан Чеекезин Ердоган I05:09 05.05.2026
------------------------------------------------------------
Title   : Путин: Готов съм на компромиси по отношение на Киев! Зеленски: Ако не се съгласи на мир, Путин ще трябва да се бори за своето съществуване
Words   : 7211
Preview : Руският президент Владимир Путин каза на среща с ръководителите на водещи световни новинарски агенции, че американският му колега Доналд Тръмп е поискал от Москва да направи известни компромиси по отношение на Украйна, и добави, че Русия има такава готовност, ако Киев направи същото, предаде Ройтерс, цитирана от БТА.
Путин посочи на срещата, която се състоя в Константиновския дворец в Санкт Петерб
End     : .
До коментар #172 от "Хм Хм":
А БВП на САЩ колко пъти е повече от на Иран?01:33 05.06.2026
251 ГОТОВНОСТТА
Коментиран от #252
01:37 05.06.2026
252 Язък
До коментар #251 от "ГОТОВНОСТТА":
Много си талантлив, пробвай и по-малоумно да пишеш тука. Явно в учище си бил отличника на класа😆01:48 05.06.2026
253 Смотльо,
До коментар #2 от "🇺🇦УКРАÏНА🇺🇦":
Какъв е този парцал който си сложил ?01:51 05.06.2026
------------------------------------------------------------
Title   : ВСУ подложиха Санкт Петербург на една от най-мащабните атаки от началото на войната
Words   : 7204
Preview : В ранните съботни Ленинградска област и Санкт Петербург бяха подложени на една от най-мащабните вълни от атаки с украински дронове от началото на конфликта.
Губернаторът на Ленинградска област Александър Дрозденко съобщи официално, че в небето над региона вече са свалени 86 безпилотни летателни апарата (БПЛА).
Опасността от въздушно нападение е обявена в 03:59 ч. московско време и остава активна.
End     : м - другар ти по умен от московските чикисти бре - с какво да го сринат Киев с ирански шахеди или с корейски снаряди и ракети - то руските свършиха и каквито ракети произведат ги хвърлят в Украйна - явно искаш с атома ама ще има ответка и москвабад ще изгори09:51 06.06.2026
267 Така е
До коментар #90 от "Хаха":
Русия сваля дроновете ,но дроновете не са страшни ,страшни са отломките09:52 06.06.2026
------------------------------------------------------------

**Finding:** The long outliers in `fakti` are likely caused by reader comments being included in the extracted `full_text`. This will be addressed in the source-specific cleaning step, after which the word count distribution will be re-checked.

## 4. `full_text` investigation

In [73]:
sources = df["source"].unique().tolist()
sources

['vesti',
 'monitor',
 'standartnews',
 'segabg',
 'bta',
 'banker',
 'economic',
 'actualno',
 'nova',
 '24chasa',
 'fakti']

In [4]:
def print_source_samples(df, source, n=3, random_state=None):
    source_df = df[df["source"] == source]
    print(f"=== {source.upper()} ({len(source_df)} articles) ===\n")
    for _, row in source_df.sample(
        min(n, len(source_df)), random_state=random_state
    ).iterrows():
        print(f"--- {row['title']} ---")
        print(f"URL: {row['url']}")
        print(row["full_text"])
        print()

In [75]:
def drop_lines(text, predicate):
    if not isinstance(text, str):
        return text
    return "\n".join(line for line in text.split("\n") if not predicate(line))

In [76]:
def truncate_at_sentinel(text: str, sentinels: list[str]) -> str:
    if not isinstance(text, str):
        return text
    text_lower = text.lower()
    for sentinel in sentinels:
        idx = text_lower.find(sentinel.lower())
        if idx != -1:
            text = text[:idx].strip()
    return text

In [77]:
def apply_to_source(df, fn, source=None):
    if source:
        mask = df["source"] == source
        df.loc[mask, "full_text"] = df.loc[mask, "full_text"].apply(fn)
    else:
        df["full_text"] = df["full_text"].apply(fn)
    return df

In [78]:
def fix_split_first_letter(text: str, word_set: set) -> str:
    if not isinstance(text, str):
        return text
    match = re.match(r"^([А-Я]) ([а-я])", text)
    if not match:
        return text
    letter, next_char = match.group(1), match.group(2)
    merged = letter + text[2:].split()[0] if text[2:].split() else ""
    if letter not in "ВС" or merged in word_set:
        return letter + next_char + text[3:]
    return text

In [79]:
EMOJI_RE = re.compile(r"[\U0001F000-\U0001FFFF\U00002600-\U000027BF]")
SOCIAL_ATTR = re.compile(r"\(@\w+\).*\b\d{4}\b")


def is_noise_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False

    # remove leading dash/dash+space for content checks
    content = re.sub(r"^[—–-]+\s*", "", stripped)

    # social media attribution: — Handle (@handle) date
    if SOCIAL_ATTR.search(stripped):
        return True

    # lines starting with @handle
    if content.startswith("@"):
        return True

    # emoji heavy lines
    words = content.split()
    if words and sum(1 for w in words if EMOJI_RE.search(w)) / len(words) > 0.3:
        return True

    # entirely Latin (no Cyrillic) — covers plain Latin and — Latin text
    if content and not any("\u0400" <= c <= "\u04ff" for c in content):
        return True

    return False

## 4.a. Vesti

In [80]:
print_source_samples(df, "vesti", n=3, random_state=42)

=== VESTI (3147 articles) ===

--- Рапърът Йонислав Йотов-Тото приключи участието си в Hell’s Kitchen ---
URL: https://www.vesti.bg/lyubopitno/rapyryt-ionislav-iotov-toto-prikliuchi-uchastieto-si-v-hells-kitchen-6258870
О ще един участник се сбогува с възможността да грабне звездната победа в Hell’s Kitchen. Рапърът Йонислав Йотов-Тото не се справи с напрежението на станция “Гарнитури” по време на вечерната резервация и шеф Ангелов сложи край на участието му в надпреварата.
Черните куртки и техните опоненти се впуснаха в забавно и изпълнено с екшън предизвикателство с италиански пици на открито. След спечеленото ценно предимство, претендентите за голямата награда от €50 000 се поздравиха с победата, а фотомоделът Нора Недкова получи оранжева престилка.
Вечерната резервация донесе нов обрат, приготвен от шеф Ангелов. Той обедини звездните готвачи и Черните куртки в един общ отбор, предвождан от номинираната Нора Недкова. Въпреки множеството проблеми с комуникацията, играчите съумяха да издадат почти всички поръчки успешно. Липсата на отборна игра и поредицата от грешки на темпераментния Тото обаче не останаха незабелязани.
Музикантът е гост в поредицата “Кухнята след Ада”, където разказва за силната си връзка с кулинарията, отношенията с Нора, динамиката при Платинените и Златните и своите фаворити за звездната и голямата победа. Епизодът е наличен в NOVA PLAY, Vbox7 и YouTube.
Утре от 20:00 ч. по NOVA участниците в Hell’s Kitchen ще влязат в битка със съдбата, а един от тях ще бъде елиминиран на крачка от финалния етап на най-горещото кулинарно състезания в телевизионния ефир.
Всичко за Hell’s Kitchen може да откриете в сайта и официалните профили на предаването във Facebook, Instagram и TikTok. Гледайте подкаста “Кухнята след Ада” в NOVA PLAY, Vbox7 и YouTube.

--- САЩ заплашиха Оман със санкции ---
URL: https://www.vesti.bg/sviat/sasht-zaplashiha-oman-sys-sankcii-6260917
С АЩ предупредиха Оман да не участва пряко или косвено в опити за въвеждане на такси за преминаване през Ормузкия проток, като заявиха, че ще наложат санкции на всяка страна или партньор, включен в подобна схема, съобщи "Ройтерс".
Иран въвежда такси за Ормузкия проток, забранява американски и израелски кораби
"Правителството на САЩ няма да толерира никакви опити за въвеждане на система за таксуване в Ормузкия проток", заяви американският министър на финансите Скот Бесънт в публикация в X.
Той подчерта, че американското финансово министерство ще действа "решително" срещу всеки, който участва във въвеждането на подобни такси.
Тръмп обяви, че нито една държава няма да контролира Ормузкия проток
"Оман, в частност, трябва да знае, че Министерството на финансите на САЩ ще се бори решително срещу всеки, който участва пряко или непряко в улесняването на таксите за протока, и всеки партньор, който е готов да съдейства, ще бъде санкциониран", добави Бесънт.
The United States Government will not tolerate any effort to impose a tolling system in the Strait of Hormuz. Oman, in particular, should know that the U.S. Treasury will aggressively target any actors involved - directly or indirectly - in facilitating tolls for the Strait and…
— Treasury Secretary Scott Bessent (@SecScottBessent) May 28, 2026

--- Катастрофа край Казанлък, петима пострадали, сред които и новородено ---
URL: https://www.vesti.bg/bulgaria/katastrofa-kraj-kazanlyk-petima-postradali-sred-koito-i-novorodeno-6260429
П етима души пострадаха при катастрофа, сред тях е и новородено. Всички са пътували в един автомобил, предаде NOVA.
Водачът на колата загубил контрол на един от завоите към казанлъшкото село Горно Черковище и автомобилът се преобърнал.
Пострадалите са откарани от екипи на Спешната помощ в болницата в Казанлък.
При друга катастрофа в неделя сутрин е загинал 25-годишен мъж, шофьор на лек автомобил, който се е блъснал в товарен камион с полска регистрация, съобщиха от МВР.
Инцидентът е станал около 07:30 часа в района на Ботевград. Пострадала е и 23-годишната спътничка на загиналия, тя е откарана в болница.
По данни на Агенция "Пътна инфраструктура" пътното произшествието се е случило в района на км 4 по път II-17 при пътен възел "Малините" в посока АМ "Хемус".
По-рано от Министерството на вътрешните работи съобщиха на сайта си, че един човек е загинал, а 16 са ранени при 15 катастрофи през изминалото денонощие.
От началото на месеца 33 души са загинали, а 525 са ранени при 439 катастрофи.
От началото на годината при 2152 катастрофи 160 души са загинали, а 2663 - ранени.
При сравнение с реалните данни за загиналите (137) през същия период на 2025 г. се отчитат 23 повече загинали участници в движението по пътищата през 2026 г.

In [81]:
df = apply_to_source(df, lambda t: drop_lines(t, is_noise_line), source="vesti")

In [82]:
print_source_samples(df, "vesti", n=3)

=== VESTI (3147 articles) ===

--- Осъдиха шофьора, блъснал човек на АТВ в София ---
URL: https://www.vesti.bg/bulgaria/osydiha-shofiora-blysnal-chovek-na-atv-v-sofiia-6261280
С офийският градски съд (СГС) осъди на осем години лишаване от свобода Валентин Асенов, обвинен за катастрофата в столичния квартал „Христо Ботев“, при която на 14 юли 2025 г. един човек загина, каращ АТВ, а друг беше ранен, съобщиха от пресцентъра на съда.
Според съдебния състав подсъдимият е нарушил разпоредбите на Закона за движението по пътищата, като деянието е извършено по непредпазливост. Съдът постанови Валентин Асенов да изтърпи наложеното наказание при първоначален общ режим.
Оставиха в ареста Валентин Асенов, обвинен за катастрофата с АТВ в София
Съдът отне в полза на държавата лекия автомобил Бе Ем Ве, използван при извършването на престъплението.
Присъдата подлежи на обжалване и протест в 15-дневен срок от днес пред Софийския апелативен съд.
Припомняме, че през октомври 2025 г. Софийският апелативен съд остави в ареста 18-годишния Валентин Асенов, обвинен за катастрофата с АТВ в столичния квартал „Христо Ботев“.
Протест в София: Близки на жертва от катастрофа с АТВ искат арест за 19-годишния извършител
Председателят на съдебния състав тогава посочи, че има опасност Асенов да извърши друго престъпление, тъй като катастрофата се е случила, докато обвиняемият е бил в изпитателен срок. Асенов е шофирал и под въздействие на наркотици.

--- Революция в Космоса: Откриха атмосфера там, където науката смяташе за невъзможно ---
URL: https://www.vesti.bg/lyubopitno/revoliuciia-v-kosmosa-otkriha-atmosfera-tam-kydeto-naukata-smiatashe-za-nevyzmozhno-6258772
З а първи път учени успяха да регистрират тънка атмосфера около миниатюрно небесно тяло в далечния край на нашата система — обект, който досега се смяташе за твърде малък, за да задържи какъвто и да е газ около себе си. Става въпрос за т.нар. транснептунови обекти (ТНО), разположени в Пояса на Кайпер. Те са замръзнали останки от зараждането на Слънчевата система преди 4,5 милиарда години, съобщи CNN.
Досега се знаеше, че единствено Плутон (най-големият сред тях) притежава атмосфера. Ниските температури и слабата гравитация на по-малките тела караха астрономите да вярват, че те са „голи“ скали. Новите данни за обекта (612533) 2002 XV93, публикувани в списание Nature Astronomy, опровергават това схващане.
Удар в десетката: Как бе направено откритието?
Екипът на д-р Ко Аримацу от Националната астрономическа обсерватория на Япония се възползва от рядък феномен — звездна окултация. Това се случва, когато далечен обект премине точно пред ярка звезда, гледано от Земята.
- Размерите: Докато Плутон е с диаметър от 2377 км, 2002 XV93 е едва около 500 км.
- Доказателството: При преминаването пред звездата нейната светлина не изчезнала рязко (както при безвъздушно тяло), а е заглъхнала постепенно за около 1,5 секунди. Това е сигурен знак, че около обекта има газов слой, който пречупва светлината.
Изчисленията показват, че тази атмосфера е между 5 и 10 милиона пъти по-тънка от земната.
Криовулкани или космически сблъсък?
Учените имат две основни теории за произхода на тази неочаквана обвивка:
- Криовулканизъм: Ледени вулкани на повърхността на малкото тяло изхвърлят метан, азот или въглероден окис от вътрешността му.
- Сблъсък: Комета или друг обект от Пояса на Кайпер се е ударил в 2002 XV93, освобождавайки газове под налягане.
Ако атмосферата е резултат от удар, тя ще изчезне след няколкостотин години. Но ако е плод на активни ледени вулкани, тя може да съществува в продължение на еони.
Какво следва?
Предстоящи наблюдения с мощния телескоп „Джеймс Уеб“ (James Webb) ще се опитат да определят точния химичен състав на газовете. „Това откритие показва, че Поясът на Кайпер не е студено и мъртво място, а кипи от активност и съдържа много от градивните елементи на живота“, коментира д-р Скот Шепърд от Института „Карнеги“.
Сега голямата задача пред екипа на д-р Аримацу е да разбере дали 2002 XV93 е рядко изключение, или Космосът е пълен с малки „дишащи“ светове, които просто не сме забелязали досега.

--- Тайните на малката държава, която живее на високи обороти ---
URL: https://www.vesti.bg/lyubopitno/tajnite-na-malkata-dyrzhava-koiato-zhivee-na-visoki-oboroti-6259050
Всички са чували за Монако - перлата на Френската Ривиера. В това слънчево кътче на Европа се провеждат едни от най-вълнуващите световни събития и се създават спомени, които остават за цял живот. Но зад блясъка, яхтите и легендарните гледки се крият и някои любопитни факти за княжеството, които със сигурност ще ви впечатлят.
Малка площ с голямо очарование
Цялата територия на Монако се простира на едва 2,1 кв. км. Да, точно така - това го превръща във втората най-малка държава в света след Ватикана. Въпреки миниатюрните си размери обаче княжеството заслужено се нарежда сред най-популярните туристически дестинации, пленявайки посетителите с лазурните си брегове, златните залези и невероятната си атмосфера.
Най-гъсто населената страна в света
Монако често е посочвано като най-гъсто населената държава в света - факт, който впечатлява почти толкова, колкото и блясъкът й. С население от около 38 000 души и изключително малка територия, княжеството е истински пример за това как едно компактно пространство може да побере динамичен градски живот, луксозни хотели, впечатляващи сгради и постоянен поток от туристи.
Запазена марка: Хеликоптерите
Монако няма собствено летище, но това никога не е било пречка. Само на около 30 км се намира летището в Ница, което предлага богата селекция от международни полети. А за още по-голямо удобство княжеството разполага с хеликоптерна площадка, откъдето се изпълняват полети до различни точки на Френската Ривиера и обратно. А пътуването? То отнема едва няколко минути...
Държавата на милионерите
Ето и един наистина впечатляващ факт: според международни доклади над 40% от жителите на Монако са милионери, а процентът на бедност в страната е практически нулев. Високият стандарт на живот, благоприятната данъчна политика, сигурността и престижът на княжеството го превръщат в едно от най-богатите и желани места за живеене в света.
XIX век, който носи промяната
Преди няколко века населението на Монако не е живяло сред луксозни вили, яхти и разкош. Княжеството било дом предимно на обикновени хора, които изкарвали прехраната си с риболов. Всичко започва да се променя през XIX век, когато прочутото казино „Монте Карло“ отваря врати и постепенно превръща Монако в символ на елегантност, европейски блясък и изискано забавление.
Монети с колекционерска стойност
Въпреки че Монако не е член на Европейския съюз, официалната валута в княжеството е еврото, а местните евромонети се секат в ограничени количества. Именно затова те често са търсени от нумизматите. Монетите носят символи, свързани с историята и наследството на княжеството, и са валидни и ценени в еврозоната.
Когато улиците се превръщат в писта
Освен с казиното, лукса и неповторимата си атмосфера, Монако най-често блести в съзнанието на хората по света и с адреналина на Формула 1. По време на Гран При на Монако улиците на княжеството буквално оживяват, защото самите те се превръщат в легендарната писта.
Милиони фенове мечтаят да усетят на живо тръпката от това престижно автомобилно събитие, а през 2026 г. Гран При на Монако ще се проведе от 4 до 7 юни. За истинските почитатели на автомобилния спорт това е шанс да се докоснат до една от най-емблематичните надпревари в света.
Монако е повече от дестинация
Монако не е просто място на картата - то е изживяване. Княжеството съчетава история, разкош, гледки и неподправен адреналин по начин, който трудно може да бъде сравнен с което и да е друго място в Европа.
Всеки заслужава да се докосне до тази атмосфера поне веднъж. А най-големите късметлии могат съвсем скоро да се озоват в сърцето на най-емблематичното автомобилно събитие в света и да усетят отблизо пулса на Гран При на Монако - там, където луксът и скоростта се срещат на самия бряг на Ривиерата.

In [83]:
mask = (df["source"] == "vesti") & df["full_text"].str.contains(
    "Още от автора", na=False
)
print(f"Vesti articles containing 'Още от автора': {mask.sum()}\n")

for _, row in df[mask].iterrows():
    print(f"--- {row['title']} ---")
    print(row["full_text"])
    print()

Vesti articles containing 'Още от автора': 13

--- <p>Зад кулисите на Мондиал 2026: Опасният съюз между Тръмп и шефа на ФИФА</p> ---
Б роени дни остават до началото на Световното първенство по футбол. Домакини на дългоочакваното събитие ще бъдат три страни – САЩ, Канада и Мексико. В надпреварата ще участват цели 48 отбора, което се случва за пръв път в историята. Турнирът ще започне на 12 юни в мексиканската столица Мексико Сити. Отвъд всички емоции и това, което предстои да се случи по терените, огромен интерес предизвикват някои политически въпроси, свързани с Мондиала. Сред тях са отношенията между две личности, които имат водещa роля в провеждането на първенството – държавния глава на САЩ Доналд Тръмп и президента на Международната футболна федерация ФИФА Джани Инфантино.
- Корупция, скандали и награда за мир
Още преди началото на Световното първенство, едно събитие от края на 2025 г. продължава да е обект на разпалени дебати и символизира необичайно близките отношения между Тръмп и Инфантино. През декември ръководителят на футболната федерация връчи на американския президент новоучредената Награда за мир на ФИФА – жест, който мнозина възприеха като политически ход, а не като признание за конкретни постижения. След като така и не получи силно желаната от него Нобелова награда за мир, Тръмп намери своеобразна алтернатива в лицето на ФИФА и Инфантино. По този начин двамата демонстрираха по красноречив начин, че са близки съюзници.
За никого не е тайна, че Тръмп е фигура, която предизвиква силни противоречия. Извън твърдото ядро на неговите най-верни поддръжници, още по време на първия му мандат редица социологически проучвания го определяха като един от американските политици с най-ниски нива на одобрение в световен мащаб. Неговите критици често акцентират върху агресивната му реторика, склонността към конфронтации и симпатиите, които изпитва към авторитарните методи на управление. Инфантино на свой ред е юрист, който говори седем езика. Роден е в Швейцария, в семейството на италиански имигранти. Той наследи ръководния пост в ФИФА от своя сънародник Йозеф Блатер, който беше принуден да подаде оставка след грандиозния корупционен скандал, разтърсил световния футбол през 2015 г. Тогава, по време на конгрес на ФИФА в Цюрих, агенти на ФБР извършиха зрелищна акция, довела до арестите на седем високопоставени служители на организацията, както и до повдигането на обвинения срещу редица други нейни представители.
Скандалът разкри, че ФИФА е пряко замесена в мащабни корупционни схеми. Подобно на обещанията на Тръмп да „пресуши блатото“ във Вашингтон и да разкрие колко порочен е политическият елит в САЩ, при встъпването си в длъжност Инфантино се представи като реформатор, готов да се справи с всички вътрешни проблеми, пред които е изправена организацията. В интерес на истината, това далеч не е единствената прилика между двамата. Те често вземат важни решения без да се консултират със съветниците си и „награждават“ лоялността на онези, които не поставят под съмнение водената от тях политика. През последните години Инфантино възприе подход, който доскоро беше характерен за някои световни лидери – ласкателства и приспособяване към стила на Тръмп. Президентът на ФИФА посети Белия дом няколко пъти, а през февруари 2026 г. обяви началото на стратегическо партньорство между футболната федерация и създадения от американския държавен глава Съвет за мир – организация, описвана от повечето анализатори като алтернатива на ООН. Показателно е и случилото се на финала на Световното клубно първенство през миналата година, когато Тръмп неочаквано се включи в празненствата на терена след триумфа на „Челси“.
- Ескалиращо напрежение
От гледна точка на Инфантино, успешното провеждане на започващото след дни Световно първенство изисква максимално добро сътрудничество с домакина, независимо от всички противоречия около него. А такива не липсват. Доналд Тръмп нееднократно заяви, че Канада трябва да стане 51-ия американски щат – думи, които предизвикаха остри реакции в Отава. В същото време, президентът отправя обидни квалификации към другия съорганизатор на Мондиала – Мексико, описвайки страната като източник на организирана престъпност и нелегална миграция. Вашингтон също така наложи забрани или визови ограничения за граждани на няколко държави, част от които ще участват в турнира. Това повдига много въпроси относно достъпността и универсалния характер на спортното събитие.
Допълнително безпокойство предизвикаха изказвания на Тръмп, в които той намекна, че някои градове, управлявани от представители на Демократическата партия, не са безопасни и затова е възможно планираните там мачове да се проведат другаде. Изключително скъпите билети, както и опасенията, че в някои населени места могат да избухнат безредици, усложняват ситуацията. На всичкото отгоре, само три месеца преди началото на първенството, САЩ и Израел атакуваха Иран, поради което се повиха твърдения, че националният отбор на Ислямската република може да се оттегли от турнира (това така и не се случи). Освен че повиши рисковете, свързани със сигурността, кризата направи пътуванията до САЩ още по-сложни и скъпи.
- Приятел на авторитарни лидери
Поддържането на добри взаимоотношения с лидери, обвинявани в авторитаризъм, не е нещо ново за Инфантино. Откакто застана начело на ФИФА през 2016 г., той се превърна в основно действащо лице в провеждането на световни първенства в държави, критикувани за потъпкване на демокрацията и неспазване на човешките права. След Мондиал 2018, който се състоя в Русия, Владимир Путин удостои ръководителя на ФИФА с Орден на приятелството. Самият Инфантино определи въпросния турнир като „най-добрия в историята“. В навечерието на футболната надпревара в Катар през 2022 г. той посети държавата няколко пъти, изграждайки близки отношения с емира Тамим бин Хамад ал-Тани. Междувременно, Инфантино отхвърляше всички критики, свързани с условията на труд и смъртните случаи сред мигрантите, участвали в изграждането на стадионите.
Един от най-противоречивите моменти е свързан с неговата реч преди началото на първенството, когато сравни собствените си преживявания с дискриминацията, на която са подложени катарци, араби, африканци, представители на ЛГБТ общността, хора с увреждания и мигранти. Впоследствие Инфантино подкрепи решение, което позволи Мондиалът през 2030 г. да се проведе на територията на цели шест държави – Мароко, Испания, Португалия, Уругвай, Аржентина и Парагвай. През 2034 г., обаче, престижното събитие ще се завърне в Близкия изток, като този път домакин ще бъде Саудитска Арабия – друга страна, с която той се стреми да поддържа добри отношения, включително с престолонаследника Мохамед бин Салман.
На фона на всичко това, „приятелството“ между Тръмп и Инфантино изобщо не е изненадващо. Президентът на ФИФА възприема американския държавен глава като поредния влиятелен лидер, способен да осигури успешното провеждане на най-печелившия турнир в календара на световния футбол. Макар критиците му често да определят подобни партньорства като скандални и недостойни, ролята на икономическите интереси няма как да бъде подценена. Зад всички символични жестове и противоречиви прояви, ядосващи голяма част от почитателите на футбола по цял свят, стоят рекордните печалби, които този спорт носи. Не бива да се забравя, че както Тръмп, така и Инфантино дойдоха на власт с обещания за значими успехи и просперитет. Световното първенство през 2026 г., обаче, може да разкрие и нещо много тревожно – това, че световният футбол е изпаднал в тежка етична криза, която се задълбочава с всеки изминал ден.
Още от автора:
Избори в разгара на политическа криза – накъде ще поеме Косово
Какво ще се случи с НАТО, ако САЩ напуснат организацията
Наближава ли краят на партньорството между ЕС и САЩ
Много шум за нищо – какво постигна Тръмп в Китай
Колко строга е цензурата в Китай
Държавите, в които водата е по-ценна от златото
Шест години по-късно: Между фактите и лъжите за пандемията от COVID-19
В сянката на Иран – нестихващият конфликт между Пакистан и Афганистан
Ще се превърне ли конфликтът в Близкия изток във война на изтощение
Време за промяна или запазване на статуквото – в каква посока ще поеме Унгария
Между фактите и митовете – какво знаем за едни от най-известните легендарни създания
Кой е Рупърт Лоу - новата звезда на крайната десница във Великобритания
Постижима цел ли е възстановяването на Газа
Ключови парламентарни избори в Япония – накъде ще поеме Страната на изгряващото слънце
Как светът се изправи пред воден банкрут
Лъжите, които промениха хода на историята
Най-голямата заплаха за бъдещето на НАТО
Пясъчните бури и растящото напрежение между Китай и Монголия
Ще приключи ли войната в Украйна през настоящата година
Странно, но факт – какво всъщност знаем за снега
Научните открития, които ще променят света
Мистериите, които озадачиха света през 2025 г.
Скандалите, които шокираха света през 2025 г.
Надежда за мир или нови кръвопролития – Близкият изток през 2026 г.
Забравените жени воини, шокирали античния свят
Сблъсък за милиони – Мъск срещу ЕС
Между дипломацията и хаоса – плановете за прекратяването на войната в Украйна
Когато историята се превърне в пропаганда – Кремъл и англосаксонците
Разделяй и владей – социалните мрежи и стратегията на Тръмп
Абсурдните изказвания на американските политици
Напрежението в Карибско море и новата дипломация на канонерките
Парламентарните избори в Нидерландия – как популизмът се превръща в заплаха за демокрацията
Надежда за мир или пореден провал – ще се срещнат ли Тръмп и Путин

--- <p>Как едно златно съкровище по нашите земи пренаписа световната история</p> ---
Б ългария е страна с много богата култура, история и древни традиции и обичаи. На нейната територия са откриване значителни количества ценни съкровища, предмети и артефакти, които са се оказвали изключително важни не само за историята на Балканите, но и за цяла Европа, че дори за света.
Една от най-значителните находки, когато говорим за златни древни съкровища е намерена във Варненския некропол – т.нар. Варненско златно съкровище. То не е само най-старото златно съкровище в света, но и най-уникалното такова.
Откритие от световна величина
През 1972 г., по време на изкопни работи в района на Варненското езеро е открит некропол, датиран от 4200 – 4000 година преди Христа. Уникалните предмети и накити, които са открити в него са предадени на уредника на музея в Дългопол – Димитър Златарски. Именно благодарение на него съкровището е било описано, оценено и запазено. Намереното злато се оказва истинска световна сензация – това е най-голямото количество обработено злато в света от този период, находка която ни поставя на челно място в световната карта на съкровищата.
Варненското златно съкровище тежи над 6.5 килограма като в самия некропол са били открити 294 гроба и над 3 000 украшения в тях. Самото съкровище е от каменно-медната епоха и доказва, че златото се е използвало и обработвало наравно с медта.
Значение на Варненското златно съкровище
Освен като изключителен археологически артефакт, съкровището дава ценна информация за обществената структура на праисторическите общества по нашите земи. Разнообразието и богатството на гробните дарове показва ясно наличие на социална йерархия и изявени личности с висок статус. Златните предмети не са били просто украшения, а символ на власт, престиж и духовна значимост. Те свидетелстват за развито занаятчийство и високо ниво на технологични умения за времето си. Също така находките подсказват за съществуването на търговски връзки и обмен между различни племена и региони.
Варненският некропол променя представите ни за развитието на цивилизацията в Югоизточна Европа, доказвайки, че тук е съществувала една от най-ранните сложни общества в света. Особен интерес представляват няколко изключително богати погребения, сред които най-известен е гроб №43. В него е открит скелет на зрял мъж, погребан с близо хиляда златни предмета, жезъл и множество престижни вещи. Богатството на инвентара подсказва, че той е заемал високо обществено положение – вероятно владетел, жрец или водач на общността. Наличието на такива разлики между отделните погребения е сред най-ранните доказателства за социална стратификация и формиране на обществен елит в праисторическа Европа.
Археолозите разграничават различни типове погребения – реални гробове с човешки останки и символични (кенотафи), в които липсва тяло, но са положени богати дарове. Това свидетелства за сложни религиозни вярвания и развит погребален ритуал. Откритите предмети разкриват и широки контакти с други региони, което предполага участие в далечни търговски мрежи.
Значението на Варненския халколитен некропол далеч надхвърля границите на България. Той променя представите за развитието на древните общества на Балканите, доказвайки, че още преди появата на първите цивилизации в Египет и Месопотамия в района на днешна България е съществувала високоорганизирана култура с развита металургия, социална йерархия и богата духовна традиция. Поради това некрополът се смята за един от най-ценните праисторически паметници в света и ключов източник за изучаването на ранната европейска цивилизация.
Какво крият част от гробовете?Top of Form
- Гроб № 36 – символично погребение
Гробът е разположен в югоизточната част на некропола и съдържа изключително богат инвентар. Даровете са разпределени в различни зони на ямата и включват златни, медни, костни и керамични предмети. В северната част са открити черупки денталиум и медна брадва, в центъра – златен жезъл и гривни, а около тях – зооморфни апликации. В южната част са намерени мраморен съд, костен идол, кремъчна пластина и други предмети. Общият брой находки е 857, като златните предмети тежат 789 г. Погребението е датирано в халколита (V хил. пр. Хр.) и вероятно има ритуален характер.
- Гроб № 2 – символично погребение на идол
Ямата е правоъгълна, с ориентация североизток–югозапад. В нея са открити слоеве от органична материя и червена охра, между които са положени предмети от злато, мед, кост, глина и кремък. В североизточната част има глинено релефно лице с богата златна украса – диадема, обеци, златни пластини за очи и уста, както и амулети на шията. Около него са открити керамични съдове, златни халки, костен идол, игла, кремъчна пластина и други предмети. Погребението се тълкува като ритуално и датира от V хил. пр. Хр.
- Гроб № 3 – символично погребение на идол
Този гроб също е с правоъгълна форма и ориентация североизток–югозапад. В него са открити слоеве от охра и органична материя, както и богати дарове. В североизточната част е разположено глинено лице, украсено със златни елементи – диадема, обеци, пластини за черти на лицето и нанизи от мъниста с амулети. В ямата са намерени още керамични съдове, мраморен идол, златни апликации, кремъчна пластина, графит и множество черупки денталиум. Открити са и костни елементи, вероятно част от колан. Погребението е символично и датира от халколита (V хил. пр. Хр.).
Още от автора:
Неразказаната история на двореца „Врана“: От чифлика до перлата в царската корона
Българската следа на Антарктида: История и наука на Ледения континент
Тайните на Вавелския замък: Вековна история, кралски тайни и легендата за свирепия дракон
Солна мина "Величка": Как "бялото злато" създаде подземен свят на изкуство и легенди
Самуиловата крепост - тихият свидетел на една невиждана жестокост
Бурната история на храм-паметника "Александър Невски"
Стобските пирамиди – място, където природата и въображението се срещат
Мистериите на „Баба Вида“ – единствената изцяло запазена крепост в България
Опознай България за един ден: Културно-историческа разходка в дома на компютъра – град Правец
От езическо светилище до християнски храм: Историята на Цари Мали град
50 интересни факта за българските планини
Магичната красота на Царска Бистрица
Шумерите: Цивилизацията, която даде старт на човешката история
Между невинност и съблазън: Жената в света на Ботичели
Махала Баба Стана - историята на една чудна местност, която остава скрита за мнозина
Тайните на Античната куполна гробница край Поморие, в която времето е спряло
30 интересни факта за Райна Княгиня
Рилската света обител в 30 уникални факта
Какво трябва да знаем за една от най-страшните природни стихии – земетресенията
Земята отвътре – какво се крие под земната повърхност – интересни факти и теории
Тъмната страна на Луната – факти и спекулации около земния спътник
Образователни постижения през Възраждането – кое е най-значимото и защо?
Назад към корените ни: Кои са най-чудатите факти за българските владетели
Уникалната и странна съдба на църквата "Света София" в столицата
Тайните на ароматерапията и как да я използваме ефективно в нашето ежедневие
Мистериите по българските земи – какво знаем за древния град Хераклея Синтика
Днес знаем цената на всичко, но не и истинската стойност на важните неща
30 невероятни факта за ацтеките
Какво се крие зад фамилията Рокфелер?
Проверете знанията си: 50 географски факта за България
„Аз съм държавата“: Лудостта на Краля Слънце и „позлатената клетка“ Версай

--- <p>Институционална агония в Косово: Трети избори за година и половина след тежък провал за избор на президент</p> ---
С лед броени дни в Косово ще се състоят извънредни парламентарни избори. Вотът, който е насрочен за 7 юни, ще бъде трети за по-малко от година и половина. Анализаторите отбелязват, че страната е изправена пред тежка политическа криза, намирането на изход от която ще бъде сложна задача. Парламентът беше разпуснат, след като депутатите не успяха да изберат нов президент в рамките на предвидения в конституцията срок. В самото гласуване участваха единствено членовете на управляващата формация „Самоопределение“ на премиера Албин Курти и представителите на несръбските малцинства. Как се стигна до настоящата ситуация? И какво предстои да се случи в Косово?
- Възходът на Курти
На предишния вот, който се проведе през декември миналата година, „Самоопределение“ получи над половината от гласовете на избирателите. Поддръжниците на формацията приветстваха това като убедителен триумф, който ще сложи край на кризата, започнала след предходните избори, състояли се през февруари. Подкрепата за Курти се увеличи по впечатляващ начин – от 42 на сто тя нарасна с близо десет процента. В речта си след обявяването на резултатите, премиерът не скри своето задоволство и благодари на жителите на Косово за „свободните, демократични и честни избори“. Изненадващо или не, надеждите за сформиране на стабилно правителство бяха попарени сравнително бързо. Курти така и не получи възможността да управлява самостоятелно, тъй като в Косово партията, получила 50 процента подкрепа, не може да разчита на половината от местата в парламента. Причината е, че 20 от 120-те депутатски кресла са запазени за малцинствата (10 са за косовските сърби, а другите 10 – за бошняците, турците и ромите).
Повечето анализатори отбелязват, че настоящата ситуация не е класическа парламентарна криза. Причината е, че Курти успя да състави кабинет с подкрепата на несръбските малцинствени групи и през февруари тази година депутатите одобриха новото правителство. Това, обаче, не сложи край на безизходицата. Само няколко седмици по-късно тя се прехвърли към президентската институция. Конституцията на Косово изисква изборът на държавен глава да бъде подкрепен от квалифицирано мнозинство от две трети в парламента, което предполага участие и на опозиционните партии. Управляващите не разполагат с необходимите гласове, а опонентите им категорично отказват да подкрепят предложения от Курти кандидат за наследник на досегашния президент Вьоса Османи.

In [84]:
df = apply_to_source(
    df, lambda t: truncate_at_sentinel(t, ["Още от автора"]), source="vesti"
)

In [85]:
word_set = set(word for text in df["full_text"].dropna() for word in text.split())

# add manually some words that are not present in the corpus
word_set.update(
    ["Стегнатата", "Стрелбата", "Взискателният", "Синьо-зелен"]
)

In [86]:
vesti_df = df[df["source"] == "vesti"]
ambiguous_mask = vesti_df["full_text"].str.match(r"^[ВС] [а-я]", na=False)

for text in vesti_df[ambiguous_mask]["full_text"].head(10):
    parts = text.split()
    merged = parts[0] + parts[1]
    valid = merged in word_set
    print(f"'{parts[0]} {parts[1]}' → '{merged}' — {'✓' if valid else '✗'}")

'С евернокорейският' → 'Севернокорейският' — ✓
'В изуални' → 'Визуални' — ✓
'С и' → 'Си' — ✓
'В ицепрезидентът' → 'Вицепрезидентът' — ✓
'С инът' → 'Синът' — ✓
'С ветовното' → 'Световното' — ✓
'В ъзможно' → 'Възможно' — ✓
'С офийският' → 'Софийският' — ✓
'В столицата' → 'Встолицата' — ✗
'С пасители' → 'Спасители' — ✓

In [87]:
df = apply_to_source(df, lambda t: fix_split_first_letter(t, word_set), source="vesti")

In [88]:
mask = df[df["source"] == "vesti"]["full_text"].str.match(r"^[А-Я] [а-я]", na=False)
print(f"Remaining split first letters: {mask.sum()}\n")

for text in df[df["source"] == "vesti"][mask]["full_text"]:
    print(text[:80])

Remaining split first letters: 89

В столицата на Нова Зеландия Уелингтън бяха евакуирани стотици жители на крайбре
В рамките на тазгодишното издание на кампанията #PlantHealth4Life Българската аг
С настъпването на пролетта и началото на лятото Спасителният център за диви живо
В следващите дни Европейският съюз може да въведе нови санкции срещу израелски з
В събота прокурорите започнаха разследване срещу 95-годишен милиардер и почетен
С мразяващо обаждане на спешния телефон 911 вдигна на крак полицейското управлен
В сряда ще бъде предимно слънчево, но в следобедните часове, главно над Източна
В аналите на историята има малко гримоари (книги с магии), които да вдъхват толк
С документ под надслов "От фрагментация към мащаб - ускоряване на конкурентоспос
С документ под надслов "От фрагментация към мащаб - ускоряване на конкурентоспос
В най-късметлийския ден за вашата зодия през следващата седмица (от 8 до 14 юни
В свят, в който животът ни преминава пред екрана, а дигиталната зависимост ни дъ
С нарастващото използване на изкуствен интелект в подбора на кадри все повече ка
В писмо, написано през ноември 1995 г., покойната принцеса Даяна изразява желани
В свят, в който храната все по-често е компромис между бързина и качество, има м
В новия епизод на Nova Lab ГРИЖА, топ гримьорът Цецо Андреев се впусна в открове
В сряда /3 юни/ ще се проведе ново заседание на съда по делото срещу бившия прем
С настъпването на лятото небесната конфигурация се подрежда по уникален начин, о
В нормативно установените срокове Комисията за енергийно и водно регулиране публ
В света на Холивуд луксът е абсолютна норма. Понякога обаче известните личности
В българската национална памет датата 2 юни традиционно е свързана със смирение,
В ирусно видео, показващо метеорит, преминаващ пред изригващ филипински вулкан,
В историята на всяка нация има дати, които остават запечатани с кървави букви за
С настъпването на летните горещини, поддържането на комфортна температура в дома
В една бурна мартенска вечер през 1827 г. германският композитор Лудвиг ван Бето
В петък федерален съдия забрани на Центъра „Кенеди“ временно да затвори врати за
В началото на юли в турската столица Анкара ще се състои среща на върха на НАТО.
В приглушена светлина и сплетени паяжини, висящи от тавана на хранилище в грузин
С ветовният, европейски и олимпийски шампион по вдигане на тежести Карлос Насар
В дълбините на океана живее едно миниатюрно създание, което притежава суперсила,
С наближаването на юни 2026 година астрологичната картина претърпява мащабна про
С тряскащият инцидент се случил с Пенелопе Крус по време на снимките за най-нови
В първия си голям официален документ Светият отец направи шокиращ паралел между
В понеделник преди обяд ще бъде предимно слънчево. Около и след обяд ще се разви
В епизод на „Семейство Симпсън“ от 1991 г. Хоумър отива в японски ресторант и яд
С тържествено шествие, концерти, литературни инициативи и изложби София отбелязв
В началото на 2000-те години, излизането от вкъщи не ставаше без изпълнението на
В следващите дни Европа ще бъде обхваната от първата мощна вълна на лятна жега.
В петък, 22 май, лошото и опасно време ще обхване по-голямата част от страната,
В планината Витоша се въвеждат допълнителни мерки за безопасност след смъртоносн
В демонстрация на геополитическо единство, която има за цел да преначертае глоба
В последния странен обрат на събитията в живота на Кейти Прайс, телевизионната з
В прашните страници на българското минало има събития, които времето несправедли
В разгара на музикалната еуфория сградата на NOVA се превърна в сцена на мащабно
С пукването на зората стотици мъже се събират на прашен площад в Чагчаран, столи
В ъздушно-капкови инфекции като морбили, грип и COVID-19 могат да се разпростран
С бурни аплодисменти, емоционални моменти и усещане за истински телевизионен пра
В рамките на специализиран панел, посветен на внедряването на изкуствен интелект
В град Анкира в малоазийската област Галатия (днес Анкара, Турция) в началото на
В понеделник облачността ще бъде променлива, след обяд - често значителна, но са
В рамките на третия фестивален уикенд на Международния фестивал за съвременен та
В кусен десерт може да бъде не само удоволствие, но и помощно средство за хранос
В много домове мухълът се развива незабелязано. Влагата и лошата вентилация създ
В началото на месец май се отбелязва неофициалния, но признат ден за честване на
В събота над по-голямата част от страната ще преобладава слънчево време. Облачно
В две отделни производства Комисията за защита на конкуренцията обвини в картели
В разгара на корупционния скандал, който предизвика политическо земетресение в У
В петък мотористи от цялата страна излизат на протест срещу драстичния скок на ц
В петък преди обяд ще е предимно слънчево. След обяд ще се развива купеста, над
В един обикновен ден около 1150 г. жителите на английското село Улпит се сблъскв
С най-тежката мярка за неотклонение, „задържане под стража“, Oкръжният съд в Доб
В седмия епизод на подкаста NOVA LAB Баланс с водещата Лора Инджова гостува псих
В цяла Украйна бяха обявени въздушни тревоги, след като масирана вълна от атакув
В редица медийни публикации се появиха твърдения, свързващи смъртта на канадския
В историята на Втората световна война има дати, които променят всичко само за ня
В края на април светът стана свидетел на аномалия, която климатолозите определят
В сърцето на Западна Европа се намира една от най-малките, но и най-богатите дър
В дипломацията прецизността не е формалност, тя е отражение на уважението, напис
В петата година от войната Украйна определено е изтощена от руските нападения. Н
В резултат на проверка на "Инспекторат за противодействие на корупцията" към Сто
В понеделник ще преобладава слънчево време с развитие на купеста и купесто-дъждо
В южния индийски щат Тамил Наду терминът „култ към личността“ се приема буквално
В южния индийски щат Тамил Наду терминът „култ към личността“ се приема буквално
В столичния квартал „Дружба“ беше установен за държане и разпространение на дрог
С мразяваща новоразсекретена бележка на ФБР разкрива как млада жена, информатор
В събота облачността ще е предимно значителна, купеста и купесто-дъждовна. На мн
В деня, в който Народното събрание избра 107-ото правителство на България, прото
В бързо развиващия се пейзаж на мобилните технологии, границата между „флагман“
С трелбата, която прекъсна тазгодишната вечеря на кореспондентите в Белия дом, о
В забранената зона около АЕЦ "Чернобил“ пожарникарите се борят с мащабен горски
В петък облачността ще се увеличава. Около и след обяд главно в Западна и Центра
С решение на правителството парк „Врана“ в София и съседен поземлен имот премина
В ключвате климатика и веднага усещате неприятна миризма. Случвало ли ви се е? И
В преследване на красота и младост, мнозина са готови да експериментират с външн
С кворум от 210 народни представители 52-рият парламент официално даде старт на
В сряда ще бъде предимно слънчево с разкъсана висока облачност. В следобедните ч
В периода от 11 май до 20 юни 2026г. движението по Линия 3 на метрото ще се осъщ
В стремежа си към здравословен начин на живот много хора достигат до крайности в
В резултат на последователните и координирани действия на Прокуратурата на Репуб

### Vesti — Cleaning Summary

- Dropped social media attribution lines (e.g. `— Reuters (@Reuters) May 8, 2026`)
- Dropped lines containing only Latin characters (English sentences, social handles)
- Truncated text at `Още от автора`
- Merged split drop-cap first letters (e.g. `В ластите` → `Властите`), using corpus word lookup to avoid incorrectly joining valid single-letter prepositions

## 4.b. Monitor

In [89]:
print_source_samples(df, "monitor", n=3, random_state=42)

=== MONITOR (3404 articles) ===

--- Путин отряза Зеленски! ---
URL: https://telegraph.bg/svetat/novini/putin-otriaza-zelenski-otkaza-sreshta-moskva-shte-goni-voennite-si-celi-493633
Руският президент Владимир Путин отряза украинския си колега Володимир Зеленски.
Той заяви, че не вижда възможност за среща в близко бъдеще и подчерта, че конфликтът ще продължи, докато Москва не постигне поставените си военни цели.
Зеленски по-рано отправи публичен призив за директна среща между двамата лидери с цел ускоряване на дипломатическо решение и прекратяване на войната. Путин отхвърли предложението, като посочи, че подобна среща би имала смисъл единствено след изготвяне на конкретни договорености между експертни екипи и постигане на предварителни споразумения.
По думите му военните действия ще приключат единствено когато Русия реализира целите на своята операция. Той подчерта, че засега няма основания за политически диалог на най-високо ниво.
От своя страна Зеленски определи отказа като доказателство, че Москва не търси край на войната и продължава да избира военен път.
Москва продължава да поставя като условия за евентуално споразумение контрол върху Донбас и въвеждане на сериозни ограничения върху украинските военни способности. Киев и западните му съюзници определят тези искания като неприемливи и равносилни на капитулация.
Източник: БГНЕС

--- Черноморец Бургас се довери на Иван Колев ---
URL: https://telegraph.bg/sport/futbol-bulgaria/chernomorec-burgas-se-doveri-na-ivan-kolev.-specialistyt-udylzhi-dogovora-si-s-kluba-493187
Р ъководството на Черноморец 1919 обявява, че подновява договора на старши треньора на клуба Иван Колев. Опитният специалист пое отбора в труден момент и го изкачи в първата шестица. Положителна оценка и за работата на целия треньорски и спортно-технически екип, се казва в съобщението на "акулите" до медиите. В момента тече процес на селекция в клуба, като основата на отбора ще бъде запазена.
Бургазлии завършиха с актив от 46 точки, които бяха спечелени от 11 победи и 13 равенства, а тимът има и 8 поражения. В турнира за Купата на България Черноморец достигна до 1/16-финалите, където имаше много тежка задача – да мери сили с 14-кратните шампиони от Лудогорец, където дадоха здрава битка и отстъпиха с 2:3 в заключителните секунди. Личният баланс на наставника на тима Иван Колев в Черноморец е 9 победи, 7 равенства и 4 поражения в 20 мача, като той беше назначен на 23-и октомври 2025-а година.

--- Даряват на DARA общински имот край морето ---
URL: https://telegraph.bg/bulgaria/novini/dariavat-na-dara-obshtinski-imot-kraj-moreto.-predlagat-pevicata-i-za-pocheten-zhitel-na-s.-avren-491806
Щ е направя и предложение на певицата Дарина Йотова (DARA) да бъде дарен общински парцел в село Близнаци, където, надявам се, ще бъде построен дом, в който ще се родят още много красиви песни, радващи всички нас. Това съобщи кметът на варненската община Аврен Емануил Йорданов. Той обяснява, че победителката на "Евровизия" има корени от село Тръстиково, където живее и нейната баба.
Коцев прави DARA „Почетен гражданин на Варна“
"На следващото заседание на Общински съвет – Аврен ще предложа DARA да бъде удостоена със званието „Почетен жител на община Аврен“ заради грандиозния ѝ успех на "Евровизия" и славата, която донесе на България нашето прекрасно момиче", добавя Манолов. "Благодаря ти, DARA! Направи ни безкрайно щастливи!", завършва кметът.
СЛЕД ТРИУМФА: DARA се завърна в България! (ВИДЕО)
"Телеграф" припомня, че Дарина Йотова е вече кандидат за "почетен гражданин" на София, след предложение на лидера на групата на ГЕРБ-СДС в СОС Антон Хекимян и заявката от кмета на Варна Благомир Коцев, да я удостои с престижното звание за Празника на града на 15 август.
АБОНИРАЙТЕ СЕ ЗА КАНАЛА НИ В YOUTUBE
Любомир Славов

In [90]:
df = apply_to_source(df, lambda t: fix_split_first_letter(t, word_set), source="monitor")

In [91]:
mask = df[df["source"] == "monitor"]["full_text"].str.match(r"^[А-Я] [а-я]", na=False)
print(f"Remaining split first letters: {mask.sum()}\n")

for text in df[df["source"] == "monitor"][mask]["full_text"]:
    print(text[:80])

Remaining split first letters: 85

В историческия дворец Уестминстър, лорд Евгени Минчев стана първият българин удо
В японския град Уцуномия мечка, която броди по улиците от три дни, наложи затвар
В понеделник във вестник „Мач Телеграф“
* Последна част от поредицата ни за Монд
С началото на активния летен туристически сезон във Варна се активираха джебчиит
В неделя на пазара има само един спортен вестник - "Мач Телеграф"
* Най-важното
В лична година 4-ка ще се захванете с доста работа или личната ви отговорност ще
В събота във вестник "Мач Телеграф"
* Приложение за Мондиал 2026 - група К - отб
В петък във вестник "Мач Телеграф"
* Приложение за Мондиал 2026 - група J - отбо
В нощта между четвъртък и петък Земята ще бъде ударена от две мощни изригвания н
С най-голяма надценка от борсата до трапезата са родните зеленчуци. Това показа
С мразяващо предупреждение за бъдещето на човечеството направи професорът, нарич
В публикувано днес интервю президентът на САЩ Доналд Тръмп потвърди по-ранна инф
В четвъртък във вестник "Мач Телеграф"
* Приложение за Мондиал 2026 - група I -
В новия епизод на NOVA LAB Грижа Даниела Пехливанова ни среща с Цецо Андреев - г
В над 1700 училища в страната ще се проведе Националното външно оценяване за 4.
В сряда във вестник "Мач Телеграф"
* Най-важното за шампиона Левски
* Последното
С чествания и военни ритуали в цялата страна ще бъде почетена паметта на поета –
С уданският Ал-Хилал постигна немислимото – спечели шампионските титли на три ра
В ливанската версия на турския сериал „1001 нощ“ (Al Thaman) ролята на Надя Мата
С грандиозен концерт на Античния театър в Пловдив Локомотив Пловдив отбелязва 10
С пожелания за здраве, много усмивки и сбъдване и на най-смелите мечти политицит
В понеделник излиза уникален брой на вестник „Мач Телеграф“
* Специално приложен
В неделя на пазара има само един спортен вестник "Мач Телеграф"
* Всичко за фина
В лична година 9-ка разчиствате терена пред новото, което идва. Не започвайте ни
В събота във вестник "Мач Телеграф"
* Луксозен плакат на ЦСКА с Купата на Българ
С победата си на финала в Лигата на Конференциите над Райо Валекано Кристъл Пала
В петък преди обяд облачността над източната половина от страната все още ще е з
В петък във вестник "Мач Телеграф"
* Плакат на Кристъл Палас
* Анализа за случва
В четвъртък в "Мач Телеграф":
* Плакат на Байерн Мюнхен
* Група F на Мондиал 202
В началото на сезона мнозина вероятно са били тези, които са очаквали финал в Ев
В предварително обявения дневен ред на ВСС са включени кадрови решения, атестира
В северната част на Италия, в региона Ломбардия, е обявено здравно предупреждени
В лагера на Пари Сен Жермен има добра новина и след като футболистите почиваха д
В сряда във вестник "Мач Телеграф"
* Плакат на Арсенал с титлата
* Група Е на Мо
С пали сте цяла нощ, но се събуждате уморени. Звучи ли ви познато? Може би причи
В понеделник във вестник "Мач Телеграф"
* Последни новини от Левски
* Какво се с
В неделя на пазара има само един спортен вестник - "Мач Телеграф"
* Последни нов
В лична година 2-ка стремежът е да се издигнете до нивото на духовното число 11.
В събота във вестник "Мач Телеграф"
* Последни новини от Левски и каква награда
В петък във вестник "Мач Телеграф"
* Безплатно приложение "Букмейкър Мач"
* Всич
С пълно единодушие комисията по култура към Общински съвет - Варна подкрепи пред
В очакване на седмо дете е бившият треньор на руския национален отбор Валерий Ка
В деня на финала за Купата на България във вестник "Мач Телеграф"
* Какво се слу
С промени в удължителния закон за бюджета се гарантира, че от 1 юли минималната
В разгара на музикалната еуфория сградата на NOVA се превърна в сцена на мащабно
В новия епизод на подкаста “Храмът на историите” пред Мон Дьо застава световноиз
С шоколадова торта и портокалов сок посрещнаха Григор Димитров домакините на „Ро
В неделя на пазара има само един спортен вестник - „Мач Телеграф“
* Всичко след
В лична година 4-ка ще се наложи да поемете допълнителни функции в работата или
В началото на следващата седмица Регионалните здравни инспекции следва да старти
В новия епизод на „МачКаст“ Деси Джерманска говори откровено за дългоочакваната
В две отделни производства Комисията за защита на конкуренцията обвини в картел
В петък във вестник „Мач Телеграф“
* Безплатно приложение "Букмейкър Мач"
* Най-
В крайна сметка, ако Арсенал спечели Висшата лига, бележките на Микел Артета бих
В сряда във вестник „Мач Телеграф“
* Всичко за дербито между Лудогорец и Левски

В опита си да привлекат вниманието феновете на известните спортисти понякога пре
В сряда в по-голямата част от страната ще бъде много ветровито, с пориви до окол
В сряда във вестник „Мач Телеграф“
* Най-новото от Левски преди гостуването на Л
В резултат на проверка на „Инспекторат за противодействие на корупцията“ към Сто
В големите и значими язовири в момента има 5168,1 млн. куб. м вода, което предст
В предстоящия мач срещу ЦСКА 1948 в сряда, ЦСКА е изправен пред ситуация, в коят
В понеделник във вестник „Мач Телеграф“
* Отборно приложение "Балкани"
* Нови ст
В неделя облачността ще е променлива, с повече слънчеви разкъсвания в Западна и
В изключително неприятна ситуация се забърка Пиер-Емерик Обамеянг. 36-годишният
В неделя на пазара има само един спортен вестник - „Мач Телеграф“
* Снимки и реп
В лудия ритъм на съвременния живот, ако нещо ни липсва, това е времето за сън и
В лична година 6-ца е важно да намерите такова място и да влезете в такива отнош
В събота във вестник „Мач Телеграф“
* Нови страхотни материали за Левски преди н
С нукърът има своята нова суперзвезда. Още един китаец – У Ицзе, стана световен
В края на март 2026 г. беше обявено, че главният продуцент Фатих Аксой е започна
В сблъсъка в Будапеща на 30 май ще се изправят отбори от две европейски столици
В петък във вестник „Мач Телеграф“
* Безплатно приложение "Букмейкър Мач"
* Нови
С мразяваща вест за самоубийство на ключов експерт в Областно пътно управление –
С уперзвездите от BTS предизвикаха истинско земетресение в сърцето на Мексико си
В първите си гласувания на първото си редовно заседание 52-рото Народното събран
В условията на взривоопасна геополитическа обстановка българската армия преминав
В условията на екстремни условия, когато на везните са поставени животът и смърт
В българската Първа лига работят най-възрастните треньори. Това показва изследва
В четвъртък във вестник „Мач Телеграф“
* Нови страхотни материали за шампиона Ле
В празничната атмосфера на Деня на храбростта, след официалните слова и тържеств
В сряда във вестник „Мач Телеграф“
* Нови страхотни материали за Левски
* Какво
С гола си от дузпа и с постоянната си заплаха пред вратата на Давид Рая Хулиан А
С кандална брюнетка нахлу при играчите във финала на световното първенство по сн
В изминалия кръг Локомотив Сф разби Добруджа с 3:0 като гост и така новият трень
В началото на месец май кервани от поклонници и болни хора тръгват към светилища

In [92]:
word_set.update(
    [
        "Стегнатата",
        "Стрелбата",
        "Взискателният",
        "Синьо-зелен",
        "Суперзвездите",
        "Смразяваща",
        "Скандална",
    ]
)

In [93]:
mask = (df["source"] == "monitor") & df["full_text"].str.contains(
    "АБОНИРАЙТЕ СЕ", case=False, na=False
)
print(f"Monitor articles containing 'АБОНИРАЙТЕ СЕ': {mask.sum()}\n")

for _, row in df[mask].head(3).iterrows():
    print(f"--- {row['title']} ---")
    print(row["full_text"][20:])
    print()

Monitor articles containing 'АБОНИРАЙТЕ СЕ': 565

--- ИДВА ЛИ ЛЯТОТО? Чака ни жега с температури до 32 градуса! ---
ъде предимно слънчево. Около и след обяд главно над планините и Североизточна България ще се развива купеста и купесто-дъждовна облачност и на места там ще превали и прегърми. Ще духа слаб вятър от изток-североизток. Максималните температури ще бъдат предимно между 27° и 32°, по Черноморието – между 22° и 26°, а в София – около 28°.
В планините преди обяд ще бъде предимно слънчево. Около и след обяд ще се развива купеста и купесто-дъждовна облачност и на места, главно в Рило-Родопския масив и западните и централните дялове на Стара планина, ще има краткотрайни валежи и гръмотевици. Ще духа слаб до умерен вятър от изток-североизток, по най-високите върхове – от северозапад. Максималната температура на височина 1200 метра ще бъде около 22°, на 2000 метра – около 14°.
По Черноморието ще бъде предимно слънчево. В сутрешните часове на места видимостта ще е намалена. След обяд временни увеличения на облачността ще има главно над северното крайбрежие, където на отделни места не е изключено и да превали. Ще духа слаб до умерен вятър от изток-югоизток. Максималните температури ще бъдат между 22° и 26°. Температурата на морската вода е 20°-22°. Вълнението на морето ще бъде 1-2 бала.
На Балканите сутринта ще преобладава слънчево време, с купеста облачност в следобедните часове. Купесто-дъждовна облачност и краткотрайни валежи с гръмотевици ще има в източните райони на Румъния, в Гърция, Северна Македония и Албания.
АБОНИРАЙТЕ СЕ ЗА КАНАЛА НИ В YOUTUBE
Добавете „Телеграф“ сред предпочитаните си източници в Google

--- СГС разглежда искане за регистрация на политическа партия "Прогресивна България"! ---
ъд ще разгледа във вторник официалното искане за регистрация на политическа партия "Прогресивна България", внесено от премиера Румен Радев на 19 май 2026 г, предава БГНЕС.
На 9 юни 2026 г. съдът ще проведе открито заседание по делото, след което предстои произнасяне в законоустановения 14-дневен срок. Формацията се яви на изборите за народни представители на 19 април 2026 г. като коалиция (включваща ПП "Социалдемократи", "Социалдемократическа партия" и "Движение Нашият Народ").
АБОНИРАЙТЕ СЕ ЗА КАНАЛА НИ В YOUTUBE
Добавете „Телеграф“ сред предпочитаните си източници в Google

--- ИМА ЧОВЕК НАВСЯКЪДЕ: Тръмп номинира бившия си личен адвокат за генерален прокурор на САЩ! ---
ръмп номинира бившия си личен адвокат Тод Бланш за постоянен генерален прокурор на САЩ, което предвещава потенциална битка за одобрението му в Сената.
51-годишният Бланш заема поста на временно изпълняващ длъжността генерален прокурор, откакто Пам Бонди напусна поста през април. Оттогава той е повдигнал редица обвинения срещу политическите врагове на Тръмп.
Бившият втори човек в Министерството на правосъдието също така защити по спорен начин „черна каса“ в размер на 1,8 милиарда долара за компенсиране на политическите съюзници на Тръмп, която администрацията оттогава е отхвърлила, предаде АФП.
Белият дом съобщи, че официално е изпратил номинацията на Бланш до Сената в уведомление, публикувано на уебсайта му. Тръмп беше споделил пред гостите на вечеря в Розовата градина на Белия дом миналата седмица, че възнамерява да го номинира.
Но не е ясно дали Бланш ще получи достатъчна подкрепа в Сената на САЩ, който трябва да одобри номинациите на висши административни служители като генералния прокурор.
Републиканците в Конгреса нанесоха на Тръмп поредица от поражения през последните седмици, докато рейтингът му спада заради икономиката и войната с Иран, а до решаващите междинни избори остават само пет месеца.
Те бяха особено разгневени от т.нар. фонд срещу „оръжията“, за който настояваше Бланш и който щеше да даде компенсации на съюзниците на Тръмп, преследвани от правосъдието по времето на предшественика му Джо Байдън. Демократите също осъдиха фонда.
„Доналд Тръмп се занимава с най-корумпираното начинание в историята на президентството. Тод Бланш явно не е забелязал това“, заяви Дик Дърбин, високопоставен член на Демократическата партия в Сенатската съдебна комисия.
Бланш беше член на екипа за правна защита на Тръмп по време на съдебния процес в Ню Йорк за предполагаемите „пари за мълчание“, платени на порнозвездата Сторми Даниелс.
Той беше и в екипа за защита по две федерални дела, заведени от специалния прокурор Джак Смит – за предполагаемо неправилно боравене с класифицирани документи и опит да се отменят резултатите от президентските избори през 2020 г.
Тръмп уволни предшественичката на Бланш, Пам Бонди, след месеци на напрегнати отношения заради начина, по който тя се справи с публикуването на документи на Министерството на правосъдието за покойния осъден сексуален престъпник Джефри Епстийн, предава БГНЕС.
АБОНИРАЙТЕ СЕ ЗА КАНАЛА НИ В YOUTUBE
Добавете „Телеграф“ сред предпочитаните си източници в Google

In [94]:
df = apply_to_source(
    df,
    lambda t: drop_lines(t, lambda line: "абонирайте се" in line.lower()),
    source="monitor",
)

In [95]:
print_source_samples(df, "monitor", n=3)

=== MONITOR (3404 articles) ===

--- ВАТИКАНЪТ СРЕЩУ МАШИНИТЕ: Папа Лъв XIV призова за „разоръжаване“ на изкуствения интелект ---
URL: https://telegraph.bg/svetat/novini/vatikanyt-sreshtu-mashinite-papa-lyv-xiv-prizova-za-razoryzhavane-na-izkustveniia-intelekt.-svetiiat-otec-izdade-pyrvata-si-enciklika-v-koiato-obiavi-algoritmite-za-moralno-opasni-492492
Ватиканът обяви фронтална война на безконтролното развитие на технологиите. В публикуваната си днес първа енциклика папа Лъв XIV отправи драматичен апел за незабавно „разоръжаване“ на изкуствения интелект (ИИ), за да се предотврати надмощието на машините над човечеството. Главата на Римокатолическата църква предупреди, че дигиталната революция не е неутрална и вече копае дълбока бездна между приобщените и изолираните членове на обществото, предаде Франс прес.
Машините не са морално чисти
Папа Лъв XIV с предупреждение за изкуствения интелект!
Историческият документ от 130 страници, озаглавен „Magnifica Humanitas“ („Великолепното човечество“), има изключително тежък социален характер. В него папата американец посича илюзията, че ИИ е просто инструмент, и категорично заявява, че алгоритмите не могат да се смятат за морално неутрални. Светият отец призовава за спешно изработване на глобален етичен кодекс и настоява за фундаментални реформи в образованието, което да подготви хората за рисковете от дигиталното бъдеще.
Кървавата цена на чиповете: детско робство в мините
Ватиканът вижда „сянката на злото“ зад изкуствения интелект!
Лъв XIV шокира света с брутални разкрития за „новите форми на робство“, които захранват технологичната индустрия. Папата насочи прожектора към експлоатацията на най-невинните: „В някои региони на света тийнейджъри и деца работят в опасни условия при обработката на материали за извличане на редки земни елементи. Телата им са покрити с белези, те са осакатени и изтощени.“ Според Ватикана, блясъкът на високотехнологичните гиганти е изграден върху човешко страдание и тежка екологична щета, което налага търсенето на устойчиви решения за околната среда.
Хората като „данни“ и „пратки“
Светият отец отправи остри критики и към начина, по който престъпни синдикати използват ИИ за трафик на хора, предимно непълнолетни. Чрез онлайн платформи, системи за анонимни плащания и алгоритми за профилиране, трафикантите набират и контролират жертвите си с плашеща прецизност. В модерния дигитален свят, предупреждава папата, мъжете и жените безцеремонно са превърнати в „данни“, които се проследяват, и в „пратки“, които се преместват.

--- Тръмп: Постигнах фантастични търговски споразумения със Си Дзинпин ---
URL: https://telegraph.bg/svetat/novini/trymp-postignah-fantastichni-tyrgovski-sporazumeniia-sys-si-dzinpin.-kitaj-predlaga-sydejstvie-za-otvariane-na-ormuzkiia-protok-491503
Президентът на САЩ Доналд Тръмп заяви, че е постигнал „фантастични търговски споразумения“ със Си Дзинпин по време на заключителните разговори на срещата на върха между двете суперсили.
Според Тръмп има и предложение от китайска страна за съдействие за отваряне на Ормузкия проток.
Тръмп пристигна в Пекин с цел да сключи сделки в сектори като земеделие, авиация и изкуствен интелект, както и да намали различията между двете страни в редица напрегнати геостратегически области — не на последно място конфликта в Близкия изток.
Опитите на Тръмп да се сближи със Си, когото описа като „велик лидер“ и „приятел“, досега бяха посрещнати с по-умерен тон от китайския лидер. Въпреки това американският президент заяви, че „много добри неща“ са произлезли от посещението.
„Сключихме някои фантастични търговски споразумения, които са чудесни и за двете страни“, каза Тръмп, докато Си го придружаваше из градините на Джуннанхай – централен комплекс на лидерството до Забранения град в Пекин.
По темата за войната с Иран американският президент посочи, че Си е уверил колегата си, че Китай не се готви да окаже военна помощ на Техеран.
„Той каза, че няма да предостави военно оборудване... каза го категорично. Той би искал да види Ормузкия проток отворен и каза: „Ако мога да бъда от каквато и да е полза, бих искал да помогна“, обясни Тръмп.
На въпроса дали двамата лидери са обсъждали Иран, китайското външно министерство призова за „всеобхватно и трайно примирие“.
Източник: БГНЕС

--- ДО 26 ГРАДУСА ДНЕС: Редуват се слънце и бури! ---
URL: https://telegraph.bg/bulgaria/novini/do-26-gradusa-dnes-reduvat-se-slynce-i-buri-toplo-vreme-i-gradushki-ni-ochakvat-v-sledvashtite-dni-491606
Слънце, бури и градушки ще се редуват през следващите дни, показва прогнозата на Националния институт по хидрология и метеорология.
Днес над по-голямата част от страната ще преобладава слънчево време. На много места обаче ще има краткотрайни временно интензивни валежи с гръмотевици. Вятърът от юг-югоизток ще се усили и ще бъде умерен и силен. Максималните температури ще бъдат между 21° и 26°, в София - около 22°.
Утре ще нахлува относително студен въздух. Облачността ще е предимно значителна, ще има и валежи, на повече места в Източна България. В североизточните райони има условия да са временно интензивни и значителни по количество. Температурите ще се понижат и максималните ще са от 15°-16° на места в Западна България до 21°-22° в Горнотракийската низина.
В понеделник и вторник ще остане ветровито. Ще има променлива облачност. На отделни места в източните и планинските райони ще превали слаб дъжд. Максималните температури в по-голямата част от страната ще са около 20°. През следващите дни отново ще се развива купеста и купесто-дъждовна облачност, ще има краткотрайни валежи, придружени с гръмотевици. В сряда ще са главно в Източна България, а в четвъртък и петък на повече места в цялата страна. Повишава се вероятността за локални интензивни и значителни по количество валежи и градушки.

### Monitor — Cleaning Summary

- Merged split drop-cap first letters
- Dropped lines containing `АБОНИРАЙТЕ СЕ` (subscription prompt injected into article text)

## 4.c. STANDARTNEWS

In [5]:
print_source_samples(df, "standartnews", n=3, random_state=42)

=== STANDARTNEWS (3921 articles) ===

--- Важно за бъдещите първолаци! ---
URL: https://www.standartnews.com/balgariya-obrazovanie/vazhno-za-badeshtite-parvolaci-635622.html
Приемът на ученици в първи клас в София продължава по график, въпреки решението на Административния съд - София-град, с което бяха отменени част от последните промени в наредбата за прием в общинските училища.
Първото класиране на 2 юни остава без промяна, а от Столичната община уточняват, че съдебното решение няма да повлияе на текущата кампания.
За предстоящите класирания за учебната 2026/2027 година родителите трябва да посочат дали детето ще кандидатства с постоянен или с настоящ адрес, съобщава dariknews.bg.
Изборът се прави чрез платформата ИСОДЗ, ПГУ и първи клас, като в меню „Критерии“ е добавен специален жълт бутон за заявяване на адреса.
Промяната на избрания адрес може да бъде направена до заключването на системата в 18:00 часа на 1 юни 2026 г.
След участието в първото класиране избраният адрес се запазва за всички следващи класирания през учебната година и не може да бъде променян.
Какво се случва, ако не бъде избран адрес
В случай че родителите не посочат адрес до крайния срок, системата ще определи служебно начина на кандидатстване.
Ако в профила е въведен само един адрес или постоянният и настоящият адрес съвпадат, този адрес автоматично ще бъде използван.
Ако няма въведен адрес, детето ще бъде разпределено в четвърта група за всички училища.
При наличие на два различни адреса ще се извърши проверка спрямо училището по първо желание:
ако училището е прилежащо или гранично за един от адресите, той ще бъде избран автоматично;
във всички останали случаи детето ще бъде поставено в четвърта група за всички училища.
Дати за класиране и записване
Първото класиране за учебната 2026/2027 година ще бъде обявено на 2 юни 2026 г.
Записването на приетите ученици ще се извършва в периода от 3 до 9 юни включително.
Второто класиране е насрочено за 9 юни, а записването ще бъде от 10 до 16 юни.
Третото класиране ще се проведе на 16 юни, а записването ще бъде в периода 18 – 23 юни, с изключение на 17 и 19 юни заради провеждането на Националното външно оценяване.
Четвъртото класиране ще бъде на 23 юни, а записването – на 24 и 25 юни.
Допълнителни класирания са предвидени и през септември:
2 септември 2026 г. – класиране;
3 – 9 септември – записване;
9 септември – ново класиране;
10 – 11 септември – записване.
След всяко класиране резултатите ще бъдат публикувани в системата ИСОДЗ, ПГУ и първи клас.
От общината напомнят, че записването на класираните ученици трябва да бъде извършено до 16:00 часа на съответната дата. След този час незаписаните деца ще бъдат премахвани от системата, а тя ще се заключва в 17:00 часа.
След приключване на електронните класирания приемът ще продължи на място в училищата при наличие на свободни места.
Какви документи са необходими за записване
При записване в първи клас родителите трябва да представят:
удостоверение за завършена подготвителна група – оригинал;
оригинал и копие на акт за раждане;
заявление за записване, генерирано от системата ИСОДЗ;
лична карта на родителя;
документи, удостоверяващи допълнителни критерии, ако има такива.
След успешно записване родителите трябва да получат потвърждение по имейл, а статусът на детето в системата трябва да бъде променен на „записано“.
Как се прави отказ от записване
В определени случаи родителите могат да се откажат от вече получено място – например ако детето е прието по второ желание и семейството иска да участва в следващо класиране за по-предпочитано училище.
Отказът от записване се извършва единствено на място в училището и задължително в писмена форма. Това не може да стане по телефон.
Начало на учебната година
Учебната година за всички първокласници започва на 15 септември 2026 година.

--- Мъртвец си сипа една ракия за годишнината от "смъртта" ---
URL: https://www.standartnews.com/sport/martvec-si-sipa-edna-rakiya-za-godishninata-ot-smartta-635248.html
"За годишнината от моята смърт на 16 март първо си сипах една ракия за Бог да прости. А след това и една чаша вино, за да съм жив и здрав!"
Петко Ганчев, легендарният голмайстор на "Арда", беше обявен за мъртъв и дори почетен с минута мълчание на стадиона в Кърджали преди началото на мача между "Арда" и "Левски" през миналия сезон. Още на следващия ден "починалият" почерпи в заведението на село Коларово за кончината си. Година по-късно не е пропуснал и помена си.
"Бяха решили да ме погребват, ама аз възкръсвам и продължавам - с усмивка казва бай Петко. - Шегувам се с моята преждевременна умирачка. Ако няма хумор в този живот, наистина сме загинали!"
Историята за това как някогашният голаджия на "Арда" научава от телевизията, че е умрял, обиколи света преди малко повече от година.
Уникален цирк
На 16 март 2025 г. нищо неподозиращият бивш футболист се е настроил за приятна и спокойна неделна вечер, в която ще гледа мач на своя бивш отбор срещу "Левски". Надява се момчетата на треньора Сашо Тунчев да се опънат на столичния гранд.
По същото време на стадиона в Кърджали играчите на двата отбора са инструктирани, че срещата ще започне с минута мълчание, за да бъде почетена паметта на починалия... Петко Ганчев!
Тоест на самия него! Футболистите се нареждат в центъра на терена, прегърнати един за друг в тъгата си. Хората по трибуните почтително са се изправили на крака. Съдията подава сигнал и стадионът избухва в аплодисменти за славния голаджия, който има над 130 попадения за "Арда" в кариерата си.
За добро или лошо, Петко Ганчев изпуска началните минути на мача, а също и минутата за почит по повод собствената си смърт. Малко по-късно се настанява удобно пред екрана, а телефонът му започва неспирно да звъни.
Жив съм, защо да не съм жив?...
"Хората ми се обаждат и плачат - разказа тогава пред "България Днес" Петко Ганчев, който си е жив и здрав. - После чуват гласа ми и казват: "Ама ти си жив?!". Еми жив съм, отвръщам аз... Защо да не съм жив? "Защото по телевизията казаха, че си умрял - обясняват му близките. - Даже имаше минута мълчание в твоя чест преди мача "Арда" - "Левски"... И обажданията продължиха даже след полунощ. По едно време оставих телефона. Казах на жената да вдига тя и да казва, че не съм умрял."
В Кърджали се усещат за гафа и още по време на срещата със "сините" пускат официално съобщение: "Ръководството на "Арда" иска да изкаже огромно извинение на бившия футболист на клуба Петко Ганчев и неговите близки, след като при нас постъпи грешна информация относно неговата смърт. Пожелаваме на Петко Ганчев още много години здраве и да се радва на успехите на "Арда".
Оказва се, че недоразумението в Кърджали е станало заради объркване в имената. Веднага след като става ясно, че е станал гаф, следва и извинението. От клуба поканиха Петко Ганчев като официален гост на домакинство на "Арда". Бяха му поднесени лични извинения от ръководството и подарък - фланелка на отбора.
Ганчев е един от най-силните нападатели в "Б" група през 70-те години и има над 130 гола с фланелката на "Арда". Играе също така за отборите на Раднево и Гълъбово.
От години е пенсионер и живее в родното си село Коларово, където намира спокойствие и верни другари. Петко следи изкъсо българския и световния футбол. В Първа лига подкрепя, разбира се, "Арда".
Петко се подготвя на 17 юни да празнува 80-годишен юбилей и както винаги ще събере семейство и приятели около трапезата.

--- Дара няма да е по зърна ---
URL: https://www.standartnews.com/lifestyle-lyubopitno/dara-nyama-da-e-po-zarna-vav-viena-632640.html
Вече няма място за догадки – българското участие на „Евровизия 2026“ обещава да бъде едно от най-запомнящите се и визуално въздействащи представяния на конкурса. След първата официална репетиция на сцената във Виена, DARA даде ясна заявка за успех, залагайки на експлозивна комбинация от модерен поп шик и дълбоки фолклорни корени. Хубавицата показа и тоалета си и почитателите й отдъхнаха, че този път тя няма да е по зърна на сцената, както се показа на конкурса за "Евровизия" на сцената на БНТ.
Контрастът като оръжие
Сценичният аутфит, с който DARA ще открие втория полуфинал на 14 май, е внимателно калибриран баланс между класика и провокация. Изпълнителката се появи в силует, който излъчва едновременно стабилност и динамика.
Долната част на костюма – масивна черна пола, подчертана от тежък колан и високи ботуши до коляното – придава на певицата почти войнствено излъчване. Този „тъмен“ фундамент обаче е разчупен от дързък контраст: къс розов топ и дълги ръкавици в същия цвят. Изборът на розовото не е случаен – то внася модерна „поп“ енергия, която кореспондира с ритъма на песента „Бангаранга“ и кара DARA буквално да свети под прожекторите.
Кукерите на модерната сцена
Най-впечатляващият елемент в концепцията обаче не е в дрехите, а в духа на изпълнението. Българският екип е избрал да вплете кукерски мотиви в сценичното представяне. Това е амбициозен ход, който пренася древния ритуал за гонене на злите сили в контекста на съвременната поп култура.
Използването на кукерската символика е „скритият коз“ на България. В свят на глобализирана музика, ясно разпознаваемият културен код е това, което отличава победителите. Кукерските елементи не само придават мистичност, но и носят послание за пречистване и ново начало – енергия, която идеално пасва на темперамента на DARA.
Пътят към полуфинала
Репетицията във Виена показа, че нищо в представянето не е оставено на случайността. От аксесоарите до синхрона с осветлението, образът на DARA е завършен и готов за голямата сцена.
България ще се бори за място на финала на 14 май, а съдейки по първите отзиви, „Бангаранга“ има всички шансове да се превърне в един от визуалните пикове на вечерта. Комбинацията от международен звук и българска идентичност изглежда като печелившата формула, с която DARA ще се опита да покори сърцата на милионите зрители пред екраните.

In [97]:
df = apply_to_source(
    df,
    lambda t: truncate_at_sentinel(
        t, ["Последвайте ни в Google News Showcase за важните новини"]
    ),
    source="standartnews",
)

### Standartnews — Cleaning Summary

- Dropped lines starting with `Последвайте ни в Google News Showcase за важните новини` till end of the article

## 4.d. SEGABG

In [98]:
print_source_samples(df, "segabg", n=3, random_state=42)

=== SEGABG (1567 articles) ===

--- Новият унгарски премиер намали заплатата си наполовина ---
URL: https://www.segabg.com/hot/category-foreign-country/noviyat-ungarski-premier-namali-zaplatata-si-napolovina
Новият унгарски премиер намали собствената си заплата наполовина и съкрати възнагражденията на министрите си, за да си върне доверието на обществото, съобщава "Франкфуртер Рундшау", предаде БТА.
За да "даде пример" след години на предполагаема корупция в правителството. Петър Мадяр обяви, че ще намали годишното си възнаграждение до 45,6 милиона форинта (128 040 евро), което е по-малко от половината от 93,6 милиона (263 424 евро), колкото получаваше предшественикът му Виктор Орбан.
Мадяр обясни, че намаляването на заплатите ще важи и за ръководителите на държавни предприятия, както и за членовете на надзорни и консултативни органи на държавни фирми. Според неговите изчисления мерките биха могли да спестят около 139,91 млн. евро през текущия законодателен мандат. Освен това министрите му ще установят, че разходите им за гориво, настаняване и персонал ще бъдат ограничени до 7 милиона форинта (19 712 евро) на месец, заяви Мадяр.
Мадяр иска да ограничи броя на мандатите на правителствените ръководители
"Всеки ден от шкафовете излизат скелети – не само скелети, а понякога цели гробища – във всяко министерство", отбеляза Мадяр. "Имахме подозрения и все още ги имаме, но мисля, че ситуацията е по-лоша от всяко едно от нашите предположения".
Миналата седмица неговата партия ТИСА внесе първото си голямо предложение за конституционна промяна, за да ограничи броя на мандатите на ръководителите на правителството. Петер Мадяр подчерта пред парламента във вторник, че властта, било то местна или национална, не трябва да трае вечно. Неограничената власт, каза той, в крайна сметка губи сдържаността си във всяка демократична система и в даден момент вече няма разлика между държавата, партията и личните интереси на даден лидер. "Ето защо мандатът на министър-председателя трябва да бъде ограничен до осем години", аргументира се той, съобщи "Будапест Таймс".
Предложената конституционна промяна съдържа също така клауза, която забранява преизбирането на лица, които вече са били начело на правителството в продължение на осем години. Партията определи тази стъпка като "съществена" за възстановяването на върховенството на закона. Освен това действието се оценява като мярка, чрез която да се предотврати политическото завръщане на Орбан, който според депутатите от ТИСА е превърнал страната им в "Петриева паничка на нелиберализма".
Наследството на Орбан и борбата за средства от ЕС
Орбан беше на власт общо 20 години в два мандата. Мадяр ще пътува тази седмица до Брюксел, за да се срещне с Европейската комисия и да се опита да отблокира 10,48 млрд. евро от ЕС фондовете за възстановяване, които все още са замразени, преди изтичането на срока в края на август. "Трябва не само да променим законите и да постигнем споразумения, но и да преобразуваме институционалните системи", заяви той пред журналисти в Будапеща. Изглежда, че новият унгарски премиер се опитва да даде нов старт на сложните отношения на страната с ЕС, отбелязва "Франкфуртер рундшау".
Правителството няма да почива това лято
"Искаме Комисията да одобри програми, които наистина помагат на унгарските граждани", каза той, като посочи проекти в областта на транспорта и енергетиката, както и усилията за стартиране на мащабна програма за строителство на жилища под наем в страната му. Той добави, че трябва да бъдат създадени необходимите структури и правна рамка, което означава, че "никой в правителството или в министерствата няма да отиде на почивка това лято".
"На карта е заложена огромна сума пари; това са парите на унгарския народ. Нашата цел е да си осигурим всички 10,4 млрд. евро от фондовете за възстановяване, които в момента са замразени за Унгария", каза Мадяр.
В речта си в парламента във вторник премиерът подчерта: "Никой не бива да влиза в политиката или да остава в тази зала, ако иска да се обогати от това."

--- Димитров викна двама изненадващи дебютанти за мачовете с Черна гора и Молдова ---
URL: https://www.segabg.com/category-sport/dimitrov-vikna-dvama-iznenadvashti-debyutanti-za-machovete-cherna-gora-i-moldova
Селекционерът на националния отбор по футбол Александър Димитров обяви избраниците си за приятелски мачове с тимовете на Черна гора и Молдова. В състава заради контузии не са трима от основните играчи - Кирил Десподов (ПАОК, Гър), Илия Груев ("Лийдс") и Филип Кръстев ("Гьозтепе", Тур). По същата причина извън състава са още Станислав Шопов ("Осиек", Хър) и и Доминик Янков ("Локомотив 1929", Сф).
Изненадата е включването на двама пълни дебютанти - халфовете на ЦСКА Петко Панайотов (20 г.) и "Локомотив" (Пловдив) Ефе Али (23 г.). В състава се завръщат Борислав Цонев ("ЦСКА 1948") и Патрик-Габриел Галчев ("Железничар", Сараево).
На 1 юни българският отбор ще приеме Черна гора на ст.“Христо Ботев” в Пловдив от 19:00 ч., като билетите за този двубой вече са в онлайн продажба и може да бъдат закупени. От БФС обявиха, че по повод Международния ден на детето, подрастващи до 14-годишна възраст ще влизат безплатно. Проверката срещу Молдова пък ще е на 5 юни от 20:00 ч., на ст. "Зимбру" в Кишинев.
Ето и списъка на Димитров:
Вратари: Даниел Наумов ("Ботев", Пд), Мартин Величков ("Локомотив 1929", Сф), Димитър Шейтанов ("ЦСКА 1948");
Защитници: Кристиан Димитров ("Левски"), Андреа Христов ("Визела", Порт), Теодор Иванов (ЦСКА), Росен Божинов ("Пиза", Ин), Патрик-Габриел Галчев ("Железничар", БиХ), Иван Турицов (ЦСКА), Мартин Георгиев (АЕК, Гър), Християн Петров ("Хееренвеен", Нид), Димитър Велковски ("Арда");
Халфове: Емил Ценов ("Оренбург", Рус), Андриан Краев ("Апоел", Тел Авив, Изр), Берк Бейхан ("Черно море"), Петко Панайотов (ЦСКА), Ефе Али ("Локомотив", Пд), Никола Илиев ("Ботев", Пд), Борислав Цонев ("ЦСКА 1948");
Нападатели: Марин Петков ("Ал-Таавун", С.Арабия), Лукас Петков ("Елверсберг", Гер), Тонислав Йорданов ("Кишварда", Унг), Владимир Николов ("Корона", Пол), Мартин Минчев ("Краковия", Пола), Здравко Димитров ("Амедспор", Тур), Георги Русев ("ЦСКА 1948").

--- &quot;Берое&quot; изпадна от Първа лига в рулетката на последния кръг ---
URL: https://www.segabg.com/category-sport/beroe-izpadna-purva-liga-ruletkata-na-posledniya-krug
"Берое" стана последният отбор, който изпада директно от Първа лига. Старозагорци трябваше да спечелят задължително гостуването си срещу "Ботев" (Вр) в последния кръг от третата група на първенството, но загубиха с 0:3 и останаха на 14-ото място с 34 точки. Така тежката финансова криза при настоящия собственик на клуба Ернан Банато си каза думата и след 17 години в елитната дивизия старозагорци изпаднаха във Втора лига. За последно тимът игра там през сезон 2008/09.
Тепърва ще се изяснява дали клубът ще успее изобщо да получи лиценз за професионалния футбол за сезон 2026/27, след като Лицензионната комисия първоначално отказа такъв за Първа лига заради неизпълнени финансови критерии. В момента "Берое" обжалва и се надява поне лицензът да бъде спасен. Също така не е ясно дали Банато ще остане начело на клуба след изпадането. Ако аржентинският бизнесмен напусне, заедно с него ще си тръгнат всички чуждестранни футболисти.
Головете за "Ботев" (Враца) в днешния мач вкараха Мичи Нтело в 25-ата минута, Мартин Петков в 48-ата и Касим Аджи в 90-ата. Врачани отдавна си бяха осигурили оставане в елита и днес играха за честта си. "Ботев" спечели групата с 53 т.
Последният кръг в тази група бе драматичен не само за "Берое". Други два отбора трябваше задължително да спечелят - "Спартак 1918" и "Септември" (Сф). Успя само "Спартак 1918", който лесно се справи с 3:0 като домакин с настроения отпускарски "Локомотив 1929" (Сф). И трите гола вкара Георг Стояновски, внук на треньора Гьоко Хаджиевски. Това прати варненци на спасителното 12-то място с 37 т. "Железничарите" завършиха 10-ти с 47.
"Септември" пък бе само на 20-ина минути от директното спасение, след като водеше с 1:0 до 72-ата минута на "Добруджа" след гол на Мартин Христов в 33-ата минута. Гостите от Добрич, които вече бяха изпаднали, обаче не бяха отписали мача и Георги Трифонов изравни. Златният шанс за "Септември" бе в 83-ата минута, но голмайсторът на тима Бертран Фурие изпусна дузпа. Накрая нервите не издържаха и се стигна до масов бой. Изгонени бяха Галин Иванов и Божидар Томовски от "Септември" и Вашко Оливейра и Антон Иванов от "Добруджа".
Клубът от Добрич си остана на 15-ото, предпоследно място с 31 точки, а "Септември" завърши 13-ти с 36 т. и ще играе на 28 май бараж за оставане срещу втория от Втора лига, който ще стане ясен утре - "Янтра" или "Фратрия". Галин Иванов и Божидар Томовски ще пропуснат този мач заради червените си картони.
В по-ранен мач днес "Славия" победи с 2:0 "Монтана" в София, но това беше само за протокола. "Белите" си останаха на 11-то място, само увеличиха точките на 46. "Монтана" завърши последен с 23 т.
ОТЗИВИ
Съкрушеният треньор на "Берое" Хосу Урибе не скри недоволството си от колегата си от "Ботев" (Вр) Тодор Симов: "Не искам да говоря много. За съжаление ние изпаднахме. Опитахме да се спасим по всякакъв начин. В плейофите направихме силни мачове в трудна за клуба ситуация. Мисля, че стана много лошо в мача със "Септември", когато можехме да се спасим. Искам да кажа на всички фенове, че "Берое" трябва да вземе въздух, да направи добър проект, защото е отбор за Първа лига. Искам да поздравя феновете за подкрепата им. Аз дадох всичко от себе си, но не успяхме да се спасим. Имаше лошо поведение от треньора на "Ботев" (б.ред. - Тодор Симов), който нямаше направи 3 смени в 90-ата минута, когато играеш срещу изпаднал отбор. Това е лошо поведение от техния треньор, не трябва да се подиграваш със 100-годишен отбор като "Берое". Топката обаче е кръгла и един ден ще му се върне."
Наставникът на "Спартак 1918" (Вн) Гьоко Хаджиевски бе много щастлив след спасението: "Това е най-великото чувство в живота. Откакто стъпих на този стадион до днес, печелил съм много титли и отличия в Северна Македония, но никога няма да забравя това, което постигнахме. Взехме точки от най-големите - от "Левски", ЦСКА, "ЦСКА 1948", "Лудогорец". Бихме отбори като "Арда", "Ботев" (Пловдив), "Добруджа", с който имаме местно дерби. Тежко ни беше, трудно беше, но хората бяха тук и ни подкрепяха. Ние работихме без спонсор и Алекс Илиев (б.ред. - председателят на УС на клуба) е герой сега. Алекс Илиев е голям мъжкар, защото помогна много на "Спартак". Човекът сам се пребори, за да запази "Спартак". Имаше и хора около него, които успяха да направят така, че да покажем, че можем."
Пом.-треньорът на "Септември" Мариян Христов изрази увереност, че отборът ще спечели баража: "Не успяхме да отбележим още един гол. При 1:0 не трябваше да се връщаме назад, но явно не сме заслужили да се спасим по този начин и ще се опитаме по другия. Напрежение има във всеки мач и това е хубаво на футбола. Ако на някого му пречи напрежението, не е за тази игра. Напрежението е хубаво, защото те кара да даваш най-доброто от себе си. Момчетата си играха. Играят за емблемата. Ние искаме да се надиграваме с най-добрите и ако заслужаваме, да останем в групата. Берти (б.ред. - Бертран Фурие) толкова много мачове помогна, а днес нямаше късмет. В следващия мач сигурно ще отбележи два гола."

In [99]:
df = apply_to_source(df, lambda t: drop_lines(t, is_noise_line), source="segabg")

In [100]:
print_source_samples(df, "segabg", n=3)

=== SEGABG (1567 articles) ===

--- Бизнесът зове властта да се откаже от налагане на &quot;справедливи цени&quot; ---
URL: https://www.segabg.com/hot/category-economy/biznesut-zove-vlastta-da-se-otkazhe-nalagane-na-spravedlivi-ceni
Да отпадне понятието „справедлива цена“ като законова категория, а забраната на "икономически необосновано“ увеличение на цените да се преосмисли, така че да не бъде приложима към практически всяко ценово движение.
За това настояха работодателските организации на днешното заседание на съвета за тристранно сътрудничество, на което бяха обсъдени промените в Закона за защита на потребителите и Закона за защита на конкуренцията, с които новата власт иска да овладее ръста на цените. Обсъждането в тристранката се случва, след като промените вече са приети в НС на първо четене.
Междувременно премиерът Румен Радев реши да се срещне в късния следобед с представители на търговските вериги, за да обсъди същите промени.
Двата законопроекта се разглеждат заедно, защото въвеждат паралелни и частично покриващите се понятия и режими за контрол върху цените и търговското поведение и те вече предизвикаха силно безпокойство сред бизнеса.
В Закона за защита на потребителите се предлага забраната за „икономически необосновано“ увеличение на цените, въведена със закона за еврото, да продължи още една година - до август 2027 г. Освен това се въвежда понятието „справедлива цена“, която по обясненията на вносителите от "Прогресивна България" няма задължителен характер, а е само ориентир за потребителите. Предвиждат се и ежедневни докладвания на ценова информация от търговците към КЗП до август 2027 г., като в същото време двойно се завишават санкциите на комисията за неспазване на забраната за необосновано повишение на цените.
В Закона за защита на конкуренцията значително се разширява списъкът на забранените нелоялни търговски практики, а също се въвеждат и нови понятия и режими като защита от злоупотреба със „съвместно господстващо положение“, забрана за „прекомерно високи цени“, „разумна норма на печалба“, „обективни икономически причини", както и създаване на централен регистър за проследимост по веригата на доставки.
"В резултат от всичко това се създава сложна система от понятия без достатъчна яснота относно съдържанието им и границите между отделните режими", посочиха от Българска стопанска камара. Според камарата от подобна усложнена нормативна конструкция не става ясно за бизнеса какво конкретно поведение е разрешено и какво поведение ще бъде санкционирано.
Затова БСК и другите три работодателски организации настояват при второто четене на промените в Закона за защита на потребителите да отпадне понятието „справедлива цена“ като законова категория. "При необходимост държавата може да публикува статистически и информационни индекси, но не и административно определена „справедлива“ цена, която неизбежно ще влияе върху пазара", смятат представителите на бизнеса.
След тристранката от изказванията на участниците в нея стана ясно, че вероятно формулировката "справедлива цена" ще отпадне, като бъде заменена със "справедлива стойност" или "референтна стойност". Днес по-рано депутатът от "Прогресивна България" Константин Проданов също допусна, че може би е по-добре да се формулира като справедлива стойност. "Глобалните финансови пазари функционират изцяло на концепцията за справедлива цена. Когато пазарната цена на една компания се различава от нейната справедлива цена, това е сигнал за инвеститорите да купуват или да продават акции. Но потребителите не могат да се ориентират сами, затова ние даваме тези справедливи цени. И сега има приложения и сайтове, които показват такива цени в ЕС за различни сектори", обоснова се Проданов по bTV.
Работодателските организации се въздържаха да подкрепят законовите промени, свързани с цените, докато синдикатите дадоха пълната си подкрепа.
Бизнесът поиска също така между двете четения да се ограничат задълженията за ежедневно публикуване на ценова информация, както и да се направи оценка дали подобна публичност няма да доведе до антиконкурентни ефекти.
Според бизнеса трябва да се прецизира и понятието „съвместно господстващо положение“, за да се избегне възможността всяко сходно поведение на фирмите при сходни пазарни условия автоматично да поражда подозрение за нарушение.
При първото четене на законовите промени работодателските организации силно се противопоставиха и на разпоредбите, които предвиждат фирмите сами да доказват пред КЗК или КЗП, че не са нарушители, когато контролните органи идват на проверки. "Нарушението следва да се доказва от компетентния орган, а не от предприятията", настояват от БСК.

--- Бленджини даде почивка на волейболните асове ---
URL: https://www.segabg.com/category-sport/blendzhini-dade-pochivka-na-voleybolnite-asove
Още седмица почивка получиха тримата лидери на националния отбор по волейбол. Днес представителният ни тим замина за Полша за участие в елитния приятелски турнир "Силезия къп" (20-23 май) без капитана Алекс Грозданов и братята Александър и Симеон Николови.
Италианският селекционер на българския А отбор Джанлоренцо Бленджини определи група от 14 волейболисти. Сред тях преобладават състезатели от чужбина, а българското първенство има само четирима представители - трима от тях са от шампиона в Суперлигата "Левски София", а един е от вицешампиона "Нефтохимик" (вж. целия състав по-долу).
На турнира в Катовице и Сосновец "лъвовете" ще се изправят последователно срещу тимовете на Украйна (20 май), Сърбия (22 май) и домакина Полша (23 май). Всички двубои ще бъдат излъчвани по платените ТВ канали на "Макс спорт".
След "Силезия къп" отборът се прибира в България, а тренировъчният процес ще бъде подновен на 26 май в Самоков. Тогава към лагера ще се присъединят Грозданов и братя Николови.
СЪСТАВ НА БЪЛГАРИЯ ЗА "СИЛЕЗИЯ КЪП 2026"
Разпределители: Стоил Палев ("Левски София"), Любослав Телкийски ("Нефтохимик");
Диагонали: Венислав Антов ("Тюркоа", Франция), Димитър Димитров ("Бусан", Южна Корея);
Посрещачи: Аспарух Аспарухов ("Шлепск", Полша), Георги Татаров ("Галатасарай", Турция), Мартин Атанасов ("Веро Волей", Монца, Италия), Денислав Бърдаров (ИББ, Турция), Жасмин Величков ("Веро Волей", Монца, Италия);
Центрове: Борис Начев ("Сонепар", Падуа, Италия), Илия Петков ("Юаса Батъри", Гротадзолина, Италия), Преслав Петков ("Фолгоре", Маса, Италия);
Либеро: Дамян Колев ("Левски София"), Димитър Добрев ("Левски София").

--- Григор Димитров пропуска квалификациите за &quot;Уимбълдън&quot; ---
URL: https://www.segabg.com/category-sport/grigor-dimitrov-propuska-kvalifikaciite-za-uimbuldun
Григор Димитров няма да участва в квалификациите за Откритото първенство на Великобритания по тенис - "Уимбълдън" в Лондон (29 юни - 12 юли). Това стана ясно, след като организаторите на турнира от категория "АТР 250" в Майорка (21-27 юни) обявиха, че са предоставили "уайлд кард" на 35-годишния българин.
Надпреварата на трева в испанския град се провежда точно в седмицата, когато са пресявките в британската столица. А това означава, че първата ни ракета (№168 в света) най-вероятно има гарантирана покана и за основната схема в "Ол Ингланд Клъб". Защото в противен случай той ще пропусне третия за годината и най-престижен турнир от Големия шлем за първи път след 2010 г.
Именно от тревната класика в Лондон миналото лято започна злощастният срив в кариерата на най-добрия български тенисист в историята. На 7 юли 2025 г. Григор получи разкъсване в големия гръден мускул по време на 1/8-финала на "Уимбълдън" срещу Яник Синер, когато водеше с 2-0 сета срещу световния №1.
Димитров практически пропусна остатъка от миналия сезон, а от началото на настоящия е в неузнаваема форма. През 2026 г. ветеранът от Хасково има изиграни едва 13 мача, от които е спечелил само два. В момента бившият №3 в света се намира в серия от седем поредни загуби, последната от които дойде в I кръг на квалификациите за "Ролан Гарос" миналата седмица.
Засега не е известно дали той ще участва някъде другаде освен в Майорка преди "Уимбълдън". В последния месец българският топ тенисист направи две включвания в турнири от категория "Чалънджър" на клей във Франция, но дори там отпадна в I кръг - първо в Екс ан Прованс, а после и в Бордо.
Организаторите на испанския тревен "АТР 250" описаха привличането на българската звезда по следния начин:
"Участието на Григор Димитров в Майорка ще отбележи завръщането му на настилка, на която през годините е показвал изключително високо ниво. С елегантния си и разнообразен стил на игра, белязан от характерния бекхенд с една ръка, българинът се утвърди като един от най-завършените играчи в тура. В кариерата си той постигна сериозни успехи на трева, включително титли и силни представяния в турнири от най-високо ниво, доказвайки отличната си адаптация към тази настилка."
ТРЕНЬОРСКА РОКАДА
Джейми Делгадо се завръща като треньор на Григор Димитров, съобщи специализираният сайт TennisKafe.com, позовавайки се на мениджъра на българския тенисист Георги Стоименов. Британецът беше основен наставник на хасковлията до края на миналата година и беше с основна заслуга той да се завърне сред водещите имена в световен мащаб и да пробие обратно в Топ 10.
От началото на 2026 г. Делгадо работеше с Джак Дрейпър, но този период беше белязан от проблеми с контузии на англичанина. Наскоро Дрейпър реши да започне работа с Анди Мъри.
Според лондонския в. "Таймс" Делгадо е отказал работа с тенисист от настоящия Топ 10 на ранглистата, за да помогне на Димитров.
В треньорския екип на Григор ще остане и бившият №3 в света Давид Налбандиан, с когото работят заедно от средата на февруари. Напуска другият нов наставник на българина - белгиецът Ксавие Малис.

In [101]:
mask = (df["source"] == "segabg") & df["title"].str.startswith(
    "Спортът по телевизията", na=False
)
print(f"Segabg articles starting with 'Спортът по телевизията': {mask.sum()}")

Segabg articles starting with 'Спортът по телевизията': 37

In [102]:
def drop_by_field(df, pattern, field="full_text", source=None, match="startswith"):
    patterns = [pattern] if isinstance(pattern, str) else pattern
    combined = "|".join(patterns)

    if match == "startswith":
        mask = df[field].str.startswith(tuple(patterns), na=False)
    else:
        mask = df[field].str.contains(combined, case=False, na=False)

    if source:
        mask = mask & (df["source"] == source)
    print(f"Dropping {mask.sum()} articles where {field} {match} {patterns}")
    df = df[~mask].reset_index(drop=True)
    print(f"Remaining articles: {len(df)}")
    return df

In [103]:
df = drop_by_field(df, ["Спортът по телевизията"], field="title", source="segabg")

Dropping 37 articles where title startswith ['Спортът по телевизията']
Remaining articles: 51219

### Segabg — Cleaning Summary

- Dropped social media attribution lines 
- Dropped lines starting with emojis (embedded tweet/social media posts) - applied directly on whole dataset, not only on `segabg` source
- Dropped boilerplate TV schedule articles (`Спортът по телевизията`)

## 4.e. BTA

In [104]:
print_source_samples(df, "bta", n=3, random_state=42)

=== BTA (4633 articles) ===

--- Спадът на раждаемостта насочва „Нестле“ към пазара на храни за домашни любимци ---
URL: https://www.bta.bg/bg/news/economy/1139087-spadat-na-razhdaemostta-nasochva-nestle-kam-pazara-na-hrani-za-domashni-lyubim
site.btaСпадът на раждаемостта насочва „Нестле“ към пазара на храни за домашни любимци
Швейцарският концерн „Нестле“ (Nestlé) залага все по-силно на бизнеса с храни за домашни любимци на фона на спадащата раждаемост в световен мащаб, предаде Ройтерс.
Главният изпълнителен директор на компанията Филип Навратил заяви по време на инвеститорска конференция на „Дойче Банк“ (Deutsche Bank), че тенденцията към раждането на по-малко бебета и гледането на повече домашни любимци създава значителен потенциал за растеж.
По думите му собствениците на домашни любимци са все по-склонни да увеличават разходите за тях, тъй като животните все по-често се възприемат като пълноценни членове на семейството.
Компанията произвежда храни за домашни любимци под марките „Пурина“ (Purina), „Фрискис“ (Friskies) и „Гурме“ (Gourmet).
„Котките са растящ сегмент“, посочи Навратил. Според него все повече хора се връщат към работа в офис и ограничават работата от вкъщи, което прави котките по-подходящ домашен любимец в сравнение с кучетата.
От „Нестле“ отбелязват, че печелят позиции именно в премиум сегмента на храните за котки. Компанията разчита на силен научноизследователски капацитет, тъй като производството на котешка храна изисква по-сложни технологии заради специфичните хранителни предпочитания на животните.
В момента концернът изгражда нови производствени мощности за храни за домашни любимци, основно в САЩ, за да отговори на нарастващото търсене.
Според Навратил пазарът на храни за домашни любимци и този на кафето ще растат по-бързо от общия пазар на потребителски стоки. Очакванията са двата сегмента да отбелязват годишен ръст между 3 и 4 на сто, като компанията цели да се развива в горната граница на този диапазон.
/БП/
Потвърждение
Моля потвърдете купуването на избраната новина

--- Хиляди се събраха в центъра на Мадрид срещу нарастващите разходи за жилища, които доведоха до оттегляне на много испанци от пазара ---
URL: https://www.bta.bg/bg/news/world/1132826-hilyadi-se-sabraha-v-tsentara-na-madrid-sreshtu-narastvashtite-razhodi-za-zhilis
site.btaХиляди се събраха в центъра на Мадрид срещу нарастващите разходи за жилища, които доведоха до оттегляне на много испанци от пазара
Хиляди хора се събраха в центъра на Мадрид, за да протестират срещу нарастващите разходи за жилища, които доведоха до оттегляне на много испанци от жилищния пазар, въпреки скорошния икономически бум, особено в градове като столицата и Барселона.
Жилищната криза в Испания е едно от основните политически слаби места на социалистическия премиер Педро Санчес преди изборите през 2027 г., предаде Асошиейтед прес.
Наемите в страната се повишиха от засиленото търсене, включително поради туризма и демографския растеж, свързан с имиграцията, казват анализатори.
Протестиращите скандираха лозунги и държаха транспаранти, подчертаващи правото им на жилище.
„Искаме съседи, а не туристи“, гласеше един от транспарантите.
Протестът беше организиран ден след като десетки хиляди хора протестираха в Мадрид срещу премиера Санчес в момент на политическото напрежение и на обвинения в корупция и недоволство от правителството.
Купуването на жилище в Испания стана недостъпно за мнозина, като пазарният натиск и спекулациите повишиха цените, особено в големите градове и крайбрежните райони.
Миналия месец испанското правителство прие мащабен план на стойност 7 милиарда евро за изграждане на повече обществени жилища през следващите четири години и предоставяне на помощ на младите наематели и купувачи на жилища, които са сред най-засегнатите от високите цени на наемите и жилищата.
Отделен декрет, който би удължил временното замразяване на наемите, не беше приет от парламента, излагайки правителството на Санчес в краткосрочен план на още повече недоволство, свързано с жилищното настаняване.
През последните няколко години испанците излязоха на множество демонстрации в цялата страна, за да протестират срещу високите цени на наемите и жилищата. Основно искане е правителството да предприеме по-строги мерки срещу наемите за туристи, настанени в градските центрове в Испания, която през миналата година прие рекордните 97 милиона международни посетители.
Цените на жилищата са се увеличили с близо 13% на годишна база в края на 2025 г., според данни на статистическата агенция на ЕС Евростат.
Испанската централна банка изчислява, че южноевропейската държава с близо 50 милиона жители не разполага със 700 000 жилища, сравнявайки търсенето с темпа на ново строителство.
/ГГ/
Потвърждение
Моля потвърдете купуването на избраната новина

--- НБУ представи книгата "Свободата на Украйна" с послание за бъдещето на Европа ---
URL: https://www.bta.bg/bg/news/lik/1123703-nbu-predstavi-knigata-svobodata-na-ukrayna-s-poslanie-za-badeshteto-na-evropa
site.bta НБУ представи книгата "Свободата на Украйна" с послание за бъдещето на Европа
На 8 май в Тържествената зала на Централния военен клуб в София се състоя официалното представяне на книгата „Свободата на Украйна“ – издание на Нов български университет, подготвено под съставителството на проф. Георги Фотев и доц. д-р Морис Фадел. Книгата е резултат от научната конференция, организирана от НБУ през април 2025 г., и предлага интердисциплинарен прочит на украинската история, култура, идентичност и европейския контекст на войната.
Събитието събра представители на академичната общност, дипломати, общественици и гости, обединени около идеята за свободата като фундаментална европейска ценност.
Проф. Георги Фотев определи книгата като значим морален и интелектуален акт. „Тази книга е отстояване на нашето национално достойнство и достойнството на нашия народ… Ние искаме да бъдем от страната на тези, които искат да отстояват достойнството на нашия народ“, каза той. Според него не е случайно, че книгата се появява именно в НБУ: „Тя е родена в пространството на свободата, което се казва Нов български университет, който отстоява универсалните и непреходни ценности.“
Доц. д-р Морис Фадел подчерта научната цялост на изданието: „Това е книга, а не сборник, защото тя се подчинява на определена научна логика, свързана с желанието ни по-дълбоко да навлезем в културата, в спецификата на Украйна.“ По думите му изданието има и ясно обществено послание: „Това е книга, която е и политически жест, защото свободата на Украйна е свободата на Европа.“
В изказването си ректорът на НБУ проф. Пламен Дойнов акцентира върху особеното съчетание между академична задълбоченост и ценностна ангажираност. „Тази книга е изключително пристрастна, защото е обладана от една голяма страст и тя е страстта към свободата“, заяви той. Проф. Дойнов припомни, че свободата не е даденост, а постоянен обществен труд, като цитира думите на Радой Ралин – „свободата е като хляба, тя се замесва и се изпича всеки ден. Всички тези изследователи са своеобразните днешни хлебари на нашата свобода.“
Посланикът на Украйна в България Н. Пр. Олеся Илашчук определи изданието като проект с особена обществена значимост. „Издание, което има не само академична стойност, но и обществено важно, актуално значение“, каза тя. В емоционалното си слово посланик Илашчук подчерта нравственото измерение на изпитанието, пред което е изправена Европа: „Войната оголва хората. Тя явно показва кой е способен на съчувствие и смелост и кой на неутралност, предателство или бягство от отговорност.“ Тя изведе и голямата европейска перспектива на разговора: „Свободата на Украйна е единствената гаранция за бъдещето на Европа.“ В края на изказването си тя благодари на Нов български университет „за изградения още един здрав интелектуален мост между Украйна и България.“
Проф. Веселин Методиев, председател на Настоятелството на НБУ, постави книгата в широкия хоризонт на европейската историческа логика. „Свободата на Европа и нейната сила зависи от свободата на Украйна. Това не е просто политическо желание, това е самата логика на историческото развитие на нашия континент“, посочи той. По думите му познанието за Украйна е и част от укрепването на българската перспектива: „Колкото повече знаем за Украйна, толкова повече ще ставаме силни ние тук на Балканите.“
Книгата „Свободата на Украйна“ проследява формирането на украинската национална идентичност, ролята на езика и културата като носители на историческа памет, както и драматичните последици от войната на Русия срещу Украйна. Авторите предлагат задълбочен анализ на механизмите на културното присвояване, подмяната на исторически факти и съвременните политически митове, като същевременно утвърждават правото на Украйна на свободно и суверенно бъдеще.
Представянето завърши с художествен прочит на фрагменти от книгата от актрисата Снежина Петрова, съпроводен от музикално изпълнение на украинската студентка по музика Маргарита Мазур, която се обучава в департамент „Музика“ на Нов български университет.
Според съставителите, книгата е изпълнение на дълг – отстояване на достойнството на Украйна и на безсмъртните европейски ценности. Тя е насочена както към академичните среди, така и към широката четяща публика, която е съпричастна към каузата на мира и правото на всяка нация на самоопределение.
„Украинците не са руснаци. Украйна е нация, пленена от свободата като върховна ценност, която никога не може да бъде пленена от какъвто и да е агресор.“ – проф. Георги Фотев.
Автори на текстовете в книгата са: Албена Стаменова, Aнна Тертична, Биляна Курташева, Велизар Шаламанов, Веселин Методиев, Владислав Димитров, Георги Проданов, Георги Фотев, Евгений Дайнов, Евлоги Станчев, Иван Костов, Йордан Божилов, Йордан Ефтимов, Красен Станчев, Мая Ангелова, Михаил Неделчев, Михаил Станчев, Момчил Методиев, Морис Фадел, Огнян Минчев, Олена Чмир, Олеся Илашчук, Пламен Дойнов, Райна Камберова, Росен Плевнелиев,Тодор Тагарев. Рецензент: проф. д-р Христо П. Тодоров.
Събитието беше организирано с подкрепата на Съюза на офицерите от резерва „Атлантик“.
(Информацията е публикувана без редакторска намеса и на основание договор за партньорство между Българската телеграфна агенция и Нов български университет)
/ХК/
„Час ЛИК“ на БТА е мястото за срещи отблизо с лицата на българската култура, наука, образование и религия. Подкастът може да бъде проследен в интернет страницата и в YouTube канала на БТА.
В допълнение
Избиране на снимки
Моля потвърдете избраните снимки. Това действие не е свързано с плащане. Ако продължите, избраните снимки ще бъдат извадени от баланса на вашите активни абонаментни пакети.
Изтегляне на снимки
Моля потвърдете изтеглянето на избраните снимката/ите
Потвърждение
Моля потвърдете купуването на избраната новина

In [105]:
def strip_prefix(text: str, prefix: str) -> str:
    if not isinstance(text, str):
        return text
    if text.startswith(prefix):
        return text[len(prefix) :].strip()
    return text

In [106]:
df = apply_to_source(df, lambda t: strip_prefix(t, "site.bta"), source="bta")
df = apply_to_source(df, lambda t: truncate_at_sentinel(t, ["/"]), source="bta")

In [107]:
print_source_samples(df, "bta", n=3)

=== BTA (4633 articles) ===

--- Нов общински съветник положи клетва в Общински съвет – Габрово ---
URL: https://www.bta.bg/bg/news/bulgaria/1124615-nov-obshtinski-savetnik-polozhi-kletva-v-obshtinski-savet-gabrovo
Нов общински съветник положи клетва в Общински съвет – Габрово
Нов общински съветник положи клетва в Общински съвет – Габрово. Лена Енева встъпи в състава му на мястото на Николай Косев, който бе избран за народен представител.
В началото на заседанието общинският съветник Иван Иванов обърна внимание на събитията от последните дни, свързани с напрежение в Габрово след масово сбиване. Председателят Климент Кунев посочи, че при изясняване на всички факти по случая ще бъдат поканени компетентни лица и ще бъде организирано изслушване в общинския съвет.
Общинският съвет одобри предложението Лена Енева да бъде член на две комисии.
Съветниците приеха и предложението за избор на Детелин Цветков за управител на „Общински пътнически транспорт“ ЕООД.
Дискусия предизвика точката за подписване на договор за сътрудничество със „Силвър бет“ ЕООД, но предложението беше прието.

--- Пазарът на скоростни електрически велосипеди ще се удвои до 2035 г., като Европа ще генерира най-голямо търсене, прогнозира проучване ---
URL: https://www.bta.bg/bg/news/economy/1125202-pazarat-na-skorostni-elektricheski-velosipedi-shte-se-udvoi-do-2035-g-kato-evr
Пазарът на скоростни електрически велосипеди ще се удвои до 2035 г., като Европа ще генерира най-голямо търсене, прогнозира проучване
Очаква се глобалният пазар на скоростни електрически велосипеди (Speed Pedelec E-Bike), оборудвани със система за подпомагане на педалите и способни да развиват скорости до 45 км в час, да нарасне от 2,80 млрд. долара през 2025 г. до 5,94 млрд. долара през 2035 година. Това сочат заключенията от най-новото проучване на аналитичната компания „Сферикъл Инсайтс Ел Ел Пи“ (Spherical Insights LLP) за развитието на пазара на електрически колелета.
Според прогнозите за периода 2026–2035 г. средногодишен темп на растеж на пазара на скоростни електрически велосипеди ще възлиза на 7,81 на сто. Продажбите ще бъдат тласнати нагоре от нарастващото търсене на устойчив транспорт, увеличаващите се задръствания в градовете и все по-широкото внедряване на електрическата мобилност, посочват експертите.
Осигурените от държавата стимули, напредъкът в разработването на батерии и нарастващото предпочитание на потребителите към екологични варианти за придвижване допълнително ускоряват растежа на пазарите в развитите и нововъзникващите икономики, допълват от „Сферикъл Инсайтс“.
Очаква се от Европа да дойде най-голямото търсене на скоростни електрически велосипеди до 2035 година.
Европа е лидер на пазара благодарение на силната държавна подкрепа за електрическата мобилност и добре развитата велосипедна инфраструктура в страни като Германия, Нидерландия и Белгия, изтъкват експертите.
Потребителите все по-често използват скоростни електрически велосипеди за ежедневно пътуване до работа, като по този начин се намаляват времето за пътуване и отделените в атмосферата въглеродни емисии.
Повишаващите се цени на горивата и строгите екологични норми допълнително насърчават използването на електрически велосипеди. Наличието на утвърдени производители на електрически велосипеди и нарастващите инвестиции в решения за интелигентна мобилност допринасят значително за разширяването на пазара в цяла Европа, отчита проучването.
В Белгия например регистрациите на скоростни електрически велосипеди са се увеличили с 2,8 на сто през първото тримесечие на 2026 г., като 69 процента от новите продажби са на лизинг. Пазарът на подобни употребявани велосипеди в Белгия е отбелязал ръст от 60,8 на сто.
Според проучването Азиатско-тихоокеанският регион ще бъде най-бързо растящият пазар за скоростни електрически велосипеди до 2035 г. заради разрастването на градските райони и увеличаването на трафика.
Градското население в Китай, Япония и Индия продължава да приема електрическите велосипеди като начин на придвижване до работа, както и за доставки, се посочва в публикацията.

--- Близо 200 мача бяха изиграни в рамките на двата дни по време на първото издание на футболния турнир „Купа Радомир“ ---
URL: https://www.bta.bg/bg/news/sport/1142338-blizo-200-macha-byaha-izigrani-v-ramkite-na-dvata-dni-po-vreme-na-parvoto-izdani
Близо 200 мача бяха изиграни в рамките на двата дни по време на първото издание на футболния турнир „Купа Радомир“
Близо 200 мача бяха изиграни в рамките на двата дни по време на първото издание на футболния турнир „Купа Радомир“, каза за БТА кметът на общината Кирил Стоев.
Той допълни, че идеята за турнира се е зародила още в края на 2025 г., като приблизително оттогава тече и подготовката по организацията му.
„Един от най-главните приоритети за мен и целия ми екип е подкрепата на детско-юношеския спорт в града. Една от нашите задачи е и ще бъде да възвърнем интереса към футбола сред подрастващите. Едновременно с това строим спортната зала, което е едно от дългоочакваните събития в града“, каза още Стоев.
Той добави, че едновременно с провеждането на футболния турнир са се състояли регионален турнир по тенис за деца до 14-годишна възраст с домакин Тенис клуб „Радомир“, както и междинен изпит за степен и вътрешен шампионат по карате, организирани от Karate Club Tsanev – клон Радомир.
Мачовете се играха на осем терена на двата стадиона – „Христо Радованов“ и този в кв. „Върба“. Около 600 деца от 48 клуба от страната се включиха в турнира, който беше за възрастовите групи, родени между 2015 и 2018 г., уточни кметът.
„Благодаря на всички, които се включиха в организацията на това събитие – както на колегите от Община Радомир, така и на Българския футболен съюз и спонсорите, без които турнирът нямаше как да придобие тези мащаби“, каза още Кирил Стоев.
Той добави, че за него е било безценно да види радостта в очите на децата, които са имали шанса да се докажат в още един турнир и на още един терен.
Председателят на Областния съвет (ОС) на БФС в Перник Венцислав Василев коментира пред БТА, че е получил отзиви и обратна връзка от голяма част от школите, участвали в първото издание на турнира, които са дали положителна оценка за организацията.
„Община Радомир даде заявка, че градът все по-често ще бъде притегателна сила за развитието на детско-юношеския футбол. Смятам, че оттук нататък ще чуваме все по-често за доказалите се млади таланти, които ще израснат като възпитаници на местния клуб“, добави Василев.
Той допълни, че благодарение на председателя на Съдийската комисия към ОС на БФС в Перник Мартин Никифоров феърплеят и коректните съдийски решения са били неизменна част от всички близо 200 срещи, изиграни в рамките на двата дни.
Ния Пенева получи индивидуалния приз за най-добър състезател. Тя е част от отбора на момчетата в Академия „Мечта“ и тренира футбол от близо две години. На 11 години е.
Младата футболистка споделя, че не е очаквала да спечели индивидуална награда, но е много щастлива от отличието. Тя определя участието си в момчешкия отбор като истинско щастие и казва, че се забавлява по време на тренировките, но същевременно е напълно отдадена на футбола.
„Това е моят спорт и не бих искала да тренирам нищо друго“, категорична е Ния.

### BTA — Cleaning Summary

- Stripped `site.bta` prefix appearing at the start of some articles
- Dropped lines starting with `/` (navigation artifacts from the site structure)

## 4.f. BANKER

In [108]:
print_source_samples(df, "banker", n=3, random_state=42)

=== BANKER (997 articles) ===

--- Най-доброто време за ядене на орехи за максимално усвояване на омега-3 ---
URL: https://banker.bg/2026/05/21/vreme-za-yadene-na-orehi-na-omega-3/
Орехите може да са малки, но са изключително хранителни. Те са удобна храна за съхранение у дома и съдържат фибри, протеини, магнезий и полезни мазнини. Освен това орехите са един от най-добрите растителни източници на омега-3 благодарение на съдържащата се в тях алфа-линоленова киселина (ALA).
Може би знаете, че някои хранителни вещества се усвояват по-добре, когато се приемат с определени храни или по определено време. Затова, ако ядете орехи заради омега-3 ползите им, вероятно се питате дали времето има значение.
Най-доброто време за ядене на орехи
Диетолозите са единодушни: няма конкретно най-добро време с цел максимално усвояване на омега-3. Най-важното е те да присъстват редовно в балансираното хранене.
„Добрата новина е, че независимо кога се консумират, орехите носят ползи за здравето“, казва Рейчъл Блейн, специалист по хранене.
Според диетоложката Ребека Лав времето все пак може да има значение за определени ефекти. Изследвания показват, че добавянето им към закуската може да подпомогне мозъчната функция, паметта и реакциите, а консумацията вечер може да подобри качеството на съня.
Орехите са и добър избор между храненията. Благодарение на комбинацията от фибри, протеини и полезни мазнини, те помагат за засищане и поддържат стабилна енергия.
Какво влияе на усвояването на омега-3
Тъй като омега-3 са мазнини, организмът ги усвоява по същия начин, по който усвоява и останалите мазнини с помощта на жлъчка и храносмилателни ензими.
Те улесняват този процес, защото естествено съдържат нужните полезни мазнини за добро усвояване. Една порция от около 30 грама орехи осигурява приблизително 2,5 грама ALA омега-3 – повече от препоръчителния дневен прием за възрастни.
Изследвания свързват по-високия прием на ALA с по-добро сърдечно и мозъчно здраве.
- Съхранявайте ги на хладно, защото полезните мазнини могат да гранясат.
- Добавяйте ги към салати, овесени ядки, кисело мляко и плодове.
- Използвайте ги и в солени ястия — например в песто, салати или като коричка за риба.
- Подгответе малки порции за междинна закуска.
Те са лесен начин да увеличите приема на омега-3 мастни киселини. Не е нужно да ги ядете в определен час – по-важно е да ги консумирате редовно. Според специалистите именно постоянството помага да получите максималните ползи за мозъка и сърцето.
Четете още: Храни с високо съдържание на захар увреждат паметта по начин, който може да е необратим

--- Intel и Apple са постигнали предварително споразумение за производство на чипове ---
URL: https://banker.bg/2026/05/10/intel-apple-proizvodstvo-na-chipove/
Apple и Intel са постигнали предварително споразумение, според което Intel ще произвежда някои чипове за устройствата на производителя на iPhone, съобщи The Wall Street Journal, позовавайки се на източници.
Преговорите между гигантите продължиха повече от година и се засилиха през последните месеци. Конкретните модели устройства, за които Intel ще доставя компоненти, все още не са ясни, отбелязва от изданието. Мащабът на потенциалното сътрудничество обаче е огромен: Apple доставя над 200 милиона iPhone-а годишно, както и милиони iPad-и и Mac компютри.
Намесата на правителството на САЩ изигра ключова роля за обединяването на компаниите,
съобщава вестникът. Министърът на търговията Хауърд Лътник и президентът на САЩ Доналд Тръмп лично се срещнаха с главния изпълнителен директор на Apple Тим Кук, призовавайки го да диверсифицира веригата си за доставки в полза на американския производител.
Дълго време Apple разчиташе изключително на TSMC.
Както Bloomberg съобщи по-рано, компанията все още е загрижена за използването на процесори, които не са произведени от тайванска компания, опасявайки се, че Intel няма да може да осигури необходимото качество и мащаб на производство на стабилна основа.

--- Партията на Ердоган обсъжда провеждането на предсрочни президентски избори ---
URL: https://banker.bg/2026/05/30/erdogan-predsrochni-prezidentski-izbori/
Управляващата Партия на справедливостта и развитието (ПСР) в Турция е готова да обсъди провеждането на предсрочни президентски избори през ноември 2026 г., според вестник „Джумхуриет“.
За да се предизвикат предсрочни президентски избори, рейтингът на одобрение на Реджеп Ердоган трябва да се увеличи значително чрез мерки за икономическа подкрепа, пише „Джумхуриет“. Според източници на вестника, партията обсъжда увеличение на заплатите за определени групи от населението и пенсионните плащания. Ефективността на предложените мерки ще бъде оценена чрез анкети.
Вестникът отбелязва, че
ръководството на партията все още не е постигнало консенсус относно провеждането на предсрочни избори.
Някои високопоставени членове на ПСР смятат, че провеждането им без значително подобрение на макроикономическите показатели може да бъде рисковано.
На 25 май Апелативният съд в Анкара постанови да отстрани от ръководството на Йозгюр Йозел, председател на опозиционната Републиканска народна партия (CHP), и неговия екип, като предаде ръководството на партията на бившия ѝ лидер Кемал Кълъчдароглу, който е заподозрян в сговор с Партия на справедливостта и развитието.
Следващите президентски избори в Турция трябва да се проведат през 2028 година.
Според турското законодателство, Ердоган не може да участва в тях, но има възможност да измени конституцията или да свика предсрочни избори. Той е на този пост от 28 август 2014 година.
Президентът на Република Турция (Türkiye Cumhuriyeti Cumhurbaşkanı) е държавен глава, той представлява страната в отношенията ѝ с международната общност и олицетворява единството на нацията, гарантира прилагането на конституцията и нормалното функциониране на органите на държавната власт. Срокът на президентския мандат е 7 години, като един човек може да заема този пост не повече от два мандата. Кандидатите за президент на републиката трябва да са навършили 40 г. към момента на избора.

## 4.g. ECONOMIC

In [109]:
print_source_samples(df, "economic", n=3, random_state=42)

=== ECONOMIC (466 articles) ===

--- Здравеопазването като геополитическо оръжие: Европа създава медицински шампиони, но ги губи ---
URL: https://www.economic.bg/bg/a/view/zdraveopazvaneto-kato-geopolitichesko-oryjie-evropa-syzdava-medicinski-shampioni-no-gi-gubi
Здравеопазването като геополитическо оръжие: Европа създава медицински шампиони, но ги губи
Изпълнителният директор на Astellas Pharma за България, Румъния, Унгария и Гърция доц. д-р Светослав Ценов предупреждава, че Европа се нуждае от спешна промяна в регулациите, за да задържи технологиите на бъдещето
Въпреки че Европа остава дом на някои от най-добрите медицински университети и изследователски центрове в света, континентът хронично изостава в една критична фаза – комерсиализацията и мащабирането на своите открития. Този отрезвяващ извод бе в центъра на дискусиите по време на ключовия панел на Green Transition Forum 6.0, посветен на европейската конкурентоспособност.
В дебат, споделяйки сцената с Енрико Лета, автор на знаковия Доклад за бъдещето на Единния пазар, доц. д-р Светослав Ценов, изпълнителен директор на Astellas Pharma за България, Румъния, Унгария и Гърция, очерта ясна диагноза на европейския технологичен и медицински сектор.
Европа обикновено създава шампионите, но впоследствие те се мащабират някъде другаде. Това е тъжната истина“, заяви доц. д-р Ценов.
Той припомни, че допреди 20 години основният въпрос в науката е бил къде са най-добрите университети (като половината от топ 20 все още са в Европа). Днес обаче фокусът е изместен.
Вече не говорим само за създаването на иновацията, а за скоростта, с която тя стига до пациентите. В здравеопазването сме изправени пред сериозна липса на човешки капитал в световен мащаб, и единственият начин да се справим, е чрез бързо внедряване на технологиите“, обясни той.
Допълни, че проблемът не се ограничава само до липсата на капитал, но е пряко свързан с регулаторната мудност и липсата на механизми за бърза пазарна реализация.
Здравеопазването като геополитическо оръжие
Ценов обърна внимание на фундаментална промяна в парадигмата: здравеопазването вече не може да се разглежда само през социална призма. То е стратегически и икономически актив. По думите му, близо 30% от икономическия растеж през последното десетилетие се дължи на подобряването на здравния статус на пациентите.
Данните, които експертът цитира, са показателни за европейския парадокс: 25% от научните публикации в областта на биотехнологиите идват от Европа, но едва 10% от набрания рисков капитал (Venture Capital) за сектора остава на континента. Нещо повече – макар Европа да се гордее с мащабни инвестиционни програми като Horizon Europe, доц. д-р Ценов отбеляза, че едва 8% от техния ресурс е насочен към здравеопазването.
Ярък пример за изпуснатите възможности е иРНК (mRNA) технологията, стояща зад ваксините срещу COVID-19. Въпреки че методологията е разработена в Европа преди повече от 15 години, реалното ѝ пазарно мащабиране се случи в САЩ чрез компании като Moderna, разказа доц. д-р Ценов. Причината? Американското законодателство (като т.нар. Bayh-Dole Act) позволява бърза комерсиализация и патентоване на открития, направени с публични средства – механизъм, който все още липсва в Европа.
Източник на снимката: Dir.bg
Тази диагноза бе категорично подкрепена от Енрико Лета, който посочи разпокъсаността на континента като основен „убиец“ на мащаба.
Ако сте млад стартъп или инвеститор и искате да развивате бизнес тук, веднага се плашите от сложността на правилата. Влизате в една държава, но 27-те различни системи на корпоративно право не ви позволяват лесно да стъпите в останалата част на Европа“, заяви бившият италиански премиер.
Според Лета, ако континентът не намери начин да опрости драстично средата чрез създаването на единен 28-ми режим (т.нар. инициатива EU Inc.), „бъдещето ще бъде управлявано от други“.
Регулаторна скорост срещу технологична скорост
Тезата на доц. д-р Ценов, че Европа трябва да ускори процесите си, намери силна подкрепа сред останалите панелисти. Дан Стратан, изпълнителен директор на RCI Holding, посочи основната асиметрия на нашето време.
Технологичната скорост надвишава институционалната. Иновациите се развиват в реално време, докато правителствата – в процедурно.“
Стратан допълни визията на Ценов с конкретно решение - създаването на „регулаторни пясъчници“ (regulatory sandboxes) – контролирани среди, в които иновациите да се тестват паралелно със създаването на правилата за тях, за да се избегне напускането на стратегически сектори от Европа.
Заместник-министър председателят по управление на европейските средства Атанас Пеканов също подкрепи аргумента за мащабирането, предупреждавайки, че липсата на гъвкавост води до изтичане не само на капитали, но и на най-ценния ресурс.
Европа губи своите спестявания, които отиват към САЩ, където създават работни места за бъдещето, вместо тук. Най-важното обаче са хората – талантите, инженерите, лекарите, които трябва да имат правото да останат и да развиват кариерата си у дома“, категоричен бе Пеканов.
Източник на снимката: Dir.bg
Скритото оръжие: Източна Европа
доц. д-р Светослав Ценов завърши с оптимистична нотка, призовавайки за промяна в перспективата и фокусиране върху потенциала на Централна и Източна Европа (ЦИЕ). Регионът вече не е просто потребител, а генератор на иновации. Той даде пример с румънска AI технология за диагностика на рак на простатата, която съкращава времето за поставяне на диагноза от един месец на един ден.
В България и в другите пазари от ЦИЕ имаме много подобни примери. Трябва да бъдем горди, да вървим напред и да се чува по-силно гласът ни“, призова лидерът от Astellas Pharma.
Ако Европа успее да превърне регулациите си от пречка в катализатор, тя има всички шансове не само да създава следващите световни шампиони, но и да печели мачовете на свой терен.

--- „Няма да се случи“: ЕС губи надежда относно забраната на морските услуги за руски танкери ---
URL: https://www.economic.bg/bg/a/view/es-gubi-nadejda-otnosno-zabranata-na-morskite-uslugi-za-ruski-tankeri
„Няма да се случи“: ЕС губи надежда относно забраната на морските услуги за руски танкери
Официални представители и дипломати в Брюксел стават все по-песимистично настроени относно шансовете за налагане на пълна забрана на морските услуги за руски танкери, тъй като както вътрешни, така и външни фактори натежават срещу амбициозното предложение.
Това няма да се случи“, заяви лаконично един дипломат, цитиран от Euronews.
Забраната беше одобрена в края на април като част от 20-ия пакет санкции, насочен към отслабване на военната икономика на Москва. Мярката предвижда забрана на всички услуги, свързани с морския транспорт, включително банково обслужване, корабоплаване, регистрация под флаг и застраховане, за танкери, превозващи руски петрол.
Важно е да се отбележи, че тази мащабна мярка беше отложена за неопределено време.
Официалната причина за паузата беше желанието да се постигне споразумение на ниво Г-7 по примера на тавана на цените на руския петрол, който беше приет съвместно със съюзниците.
Това беше най-добрият начин да изпратим сигнал, че сме готови“, каза друг дипломат. „Това беше съзнателен избор.“
Останалите членове на Г-7 обаче са показали слаб или никакъв ентусиазъм да последват този подход. Съединените щати дори предприеха действия в обратната посока, като издадоха три последователни изключения от санкциите върху руския петрол, за да се справят със сътресенията, предизвикани от кризата в Ормузкия проток. Последните стъпки на Обединеното кралство също предизвикаха недоумение в Брюксел.
Макар че Европейският съюз категорично отказва да облекчава санкциите, той отложи дългоочакваното предложение за постепенно прекратяване на вноса на руски петрол.
Лидерите на Г-7 ще се срещнат в Евиан, Франция, в средата на юни. Очаква се украинският президент Володимир Зеленски, който настоява за по-строги санкции срещу Русия, също да присъства.
Публично Европейската комисия, балтийските държави и скандинавските страни продължават да настояват забраната на морските услуги да бъде приложена и да увеличи разходите за руския енергиен сектор.
Но официални представители и дипломати признават, че нестабилността на енергийните пазари, съчетана с устойчиво високите цени на петрола, представлява сериозна пречка пред активирането на тази неизпробвана мярка, представена само няколко седмици преди САЩ и Израел да нанесат удари по Иран.
Събитията в Персийския залив очевидно промениха изчисленията по всички въпроси, свързани с енергетиката“, заяви в интервю за Euronews Дейвид О’Съливан, специален пратеник на ЕС по санкциите.
„В момента всички западни икономики се борят с достъпа до енергия на разумни цени и има недостиг на доставки в някои сегменти, например при рафинираните продукти – дизел, авиационно гориво и други“, допълни той.
Затова на този етап няма желание за допълнителни мерки, които биха могли да влошат ситуацията.“
Два решаващи гласа
Освен това Брюксел все още не е получил подкрепата на две държави членки, чиито интереси са пряко засегнати – Гърция и Малта. Първата разполага с мощна корабна индустрия, а втората контролира най-големия корабен регистър в Европа.
Двете средиземноморски държави твърдят, че пълната забрана на морските услуги, ако бъде въведена без координация с Г-7, ще доведе до икономически загуби, ще засили ролята на руския „сенчест флот“ и ще даде предимство на конкурентите от Китай и Индия.
Говорител на външното министерство на Малта предупреди, че едностранни действия от страна на ЕС могат да създадат „пробойни“ в санкционния режим.
Основният риск е фрагментацията. Ако партньорите в коалицията не действат координирано, операторите могат просто да се прехвърлят към други юрисдикции в рамките на същата екосистема, което ще намали ефективността на санкциите. Ето защо координацията е от съществено значение“, заяви говорителят пред Euronews.
„Санкциите трябва да работят на практика, а не само на теория. Ако ключовите партньори не са на една линия, съществува реален риск бизнесът просто да се премести в рамките на същото по-широко коалиционно пространство, което ще подкопае целта на мерките.“
В момента Европейската комисия работи по нов пакет икономически санкции, който се очаква да бъде представен през следващите дни.
Докато надеждите за пълната забрана отслабват, вниманието се насочва към друга инициатива на Г-7 – тавана на цената на руския петрол. Според правилата на ЕС, този таван трябва периодично да се коригира, така че да остане с 15% под средната пазарна цена на руския суров петрол.
Тъй като цената на руския сорт „Уралс“ рязко се повиши вследствие на сътресенията около Ормузкия проток, следващата ревизия, насрочена за 15 юли, вече се очаква да доведе до повишаване, а не до понижаване на тавана.
Сред дипломатите преобладава очакването, че ЕС ще намери нов механизъм за запазване на ограниченията върху цената и ще избегне предоставянето на икономическо облекчение на Москва.

--- Отвъд Nvidia: Най-добре представящите се AI акции в Европа през 2026 г. ---
URL: https://www.economic.bg/bg/a/view/otvyd-nvidia-naj-dobre-predstavjashtite-se-ai-akcii-v-evropa-prez-2026-g
Отвъд Nvidia: Най-добре представящите се AI акции в Европа през 2026 г.
Компаниите, които осигуряват инфраструктурата зад изкуствения интелект – от лазери и оптични чипове до оборудване за тестване и сървъри – са донесли ръстове до 2 200% през 2026 г.
За повечето инвеститори Nvidia, заедно с Micron, AMD и Broadcom, се превърна в лицето на бума на изкуствения интелект, но веригата за доставки на AI се простира далеч отвъд Силициевата долина. В цяла Европа група от до голяма степен пренебрегвани компании, които доставят ключов хардуер за AI центрове за данни, се превърнаха в едни от най-големите победители на фондовите пазари през 2026 г., разказва Euronews.
Потенциалът на Европа в сферата на AI
Европа може и да не е създала AI шампион от мащаба на Nvidia, Microsoft или OpenAI. Вместо това тя е дом на разрастваща се екосистема от компании, които осигуряват инфраструктурата, правеща изкуствения интелект възможен: лазерите, които пренасят данни между графичните процесори, подложките, които свързват усъвършенстваните чипове, сървърите, които обучават модели, и оборудването за тестване, което валидира процесорите, преди да напуснат фабриката.
С ускоряването на разходите за AI центрове за данни тези компании тихомълком се превърнаха в едни от най-големите победители на световните фондови пазари. Няколко акции са поскъпнали със стотици проценти тази година, а една е скочила с повече от 2 200%.
Не всички тези ръстове обаче са подкрепени от текущите финансови резултати. Някои компании продължават да работят на загуба, докато други се търгуват въз основа на очаквания за бъдещо търсене, свързано с AI, а не на настоящи приходи. Инвеститорите на практика залагат, че разходите за AI инфраструктура ще продължат да растат бързо.
Класацията по-долу представя 10-те европейски акции, свързани с AI, които са реализирали най-силен ръст от началото на 2026 г. досега.
Подреждането е базирано на представянето на акциите от началото на годината. Компаниите са включени, ако значителна част от инвестиционната им теза е свързана с AI инфраструктура, производство на полупроводници, фотоника, мрежови технологии, сървъри или сродни технологии. Акции с недостатъчна ликвидност са изключени.
10. Nokia: завръщането като играч в AI мрежите
Nokia Oyj поскъпва със 159.51% от началото на годината. Повечето хора все още я свързват с мобилните телефони, които продаде преди повече от десетилетие, но днес финландската група произвежда оборудване за оптичен транспорт и IP мрежи – а това се превърна в критично важен елемент за AI центровете за данни, където огромни обеми информация се прехвърлят между сървърни шкафове чрез оптични влакна.
Повратният момент дойде под формата на стратегическо признание: през октомври 2025 г. Nvidia придоби дял за 1 млрд. долара (0.87 млрд. евро), свързан със съвместно разработено партньорство.
През първото тримесечие на 2026 г. нетните продажби на Nokia нараснаха с 4% до 4.5 млрд. евро, но продажбите към AI и облачни клиенти скочиха с 49% на годишна база и вече формират около 8% от бизнеса на групата, като през тримесечието са били реализирани нови поръчки за AI и облачни услуги на стойност 1 млрд. евро.
Подразделението Optical Networks отчете ръст от 20%, а ръководството повиши прогнозата си за мрежовата инфраструктура до 12% – 14% растеж за цялата година.
9. ams-OSRAM: производител на осветление, преоткрил се чрез AI фотониката
Австрийско-германската компания ams-OSRAM AG е поскъпнала със 175% през 2026 г., тъй като инвеститорите приветстваха нейния завой към фотониката, задвижвана от AI.
Групата разработва усъвършенствани сензори, технологии за изображения и оптични решения, които позволяват на машините да виждат и взаимодействат с физическия свят.
През май компанията подписа споразумение за разработка с водещ клиент в сферата на AI фотониката за комерсиализация на оптични интерконекти за AI центрове за данни, като същевременно разширява присъствието си и в компоненти за интелигентни очила с AI функционалности.
Трансформацията набира скорост: приходите от полупроводници през първото тримесечие на 2026 г. нараснаха с 9% на годишна база, което засилва увереността в нарастващата роля на компанията в екосистемата на AI инфраструктурата.
8. Technoprobe: тестване на чиповете, които захранват AI
Италианската Technoprobe S.p.A. е поскъпнала със 184.26% през 2026 г. Компанията е световен лидер в производството на тестови карти (probe cards) – прецизните интерфейси, използвани за проверка на чиповете преди доставката им – и тества процесори от типа на тези, произвеждани от Nvidia и AMD.
Търсенето на решения за AI тестване е основният двигател зад преоценката на акциите.
Приходите за цялата 2025 г. са нараснали с 16% до 628 млн. евро, първата половина на 2025 г. е донесла ръст от 35%, а компанията отчита рекордно първо тримесечие на 2026 г. с около 187 млн. евро приходи, което е увеличение от 19% на годишна база и позволява изпълнение на тригодишните цели година по-рано от планираното.
През май Bank of America повиши рейтинга на акциите до „купувай“, посочвайки ръст на печалбите, свързан с графичните процесори.
7. Raspberry Pi Holdings: фаворитът при edge AI или мем акция?
Базираната в Кеймбридж Raspberry Pi Holdings plc е поскъпнала със 198.63%. Компанията продава евтини едноплаткови компютри, популярни сред ентусиастите и все по-често използвани в индустрията и edge изчисленията.
Ръстът ѝ се дължи както на реалното търсене на edge AI решения – полупроводниковите ѝ чипове вече се продават по-добре от самите платки – така и на вълната от интерес в социалните мрежи към използването на AI агенти върху евтини и постоянно работещи устройства.
През 2025 г. приходите нараснаха с 25% до 323.2 млн. долара (281 млн. евро), печалбата преди данъци се увеличи с 63% до 26.5 млн. долара (23 млн. евро), а Jefferies повиши прогнозата си за приходите през 2026 г. с 42% до 511 млн. долара (445 млн. евро).
Няколко анализатори предупредиха, че движението на акциите носи характеристики на меме акция, като те се търгуват при приблизително 50 пъти очакваната печалба.
6. STMicroelectronics: гигантът, насочващ се към центровете за данни
STMicroelectronics поскъпва с 204.28% през 2026 г. и е най-голямата компания в класацията. Базираната в Швейцария полупроводникова група произвежда силови чипове, микроконтролери и сензори и навлиза в производството на оптични продукти, които свързват AI сървърите.
Катализаторът е ориентацията към центровете за данни. През февруари компанията подписа многогодишна сделка за милиарди долари с Amazon Web Services за доставка на изчислителна инфраструктура за облачни и AI приложения и очаква приходите от центрове за данни да надхвърлят 500 млн. долара (435 млн. евро) през 2026 г. и 1 млрд. долара (0.87 млрд. евро) през 2027 г.
Анализаторите стават все по-оптимистично настроени относно AI перспективите на компанията. UBS повиши ценовата си цел до 80 евро от 49 евро, като запази рейтинга „купувай“, позовавайки се на възможности за растеж във фотониката, AI енергийните технологии и сателитните приложения.
След трудна 2025 г., когато приходите спаднаха с около 11% до приблизително 11.8 млрд. долара (10.3 млрд. евро), през първото тримесечие на 2026 г. нетните приходи нараснаха с 23% до 3.10 млрд. долара (2.70 млрд. евро), като радиочестотните и оптичните комуникации отбелязаха ръст от 34%. Компанията прогнозира и около 25% увеличение на приходите през второто тримесечие на годишна база.
5. AIXTRON: доставчикът на „кирки и лопати“, чиито акции изпреварват продажбите
Германската AIXTRON SE е поскъпнала с 234.70%. Компанията произвежда машини за отлагане на слоеве, използвани за създаването на сложните полупроводникови структури, които стоят зад лазерите и оптичните компоненти – оборудване, от което фотонният бум се нуждае.
Позитивните сигнали от американския производител на чипове Marvell помогнаха за изкачването на акциите до най-високите им нива от повече от две десетилетия.
Това обаче вероятно е ясен пример за ситуация, при която цената изпреварва фундаментите: приходите през първото тримесечие на 2026 г. са намалели с 47% на годишна база, тъй като поръчките остават слаби, въпреки портфейла от поръчки за близо 359 млн. евро и целта за около 560 млн. евро приходи през 2026 г.
Berenberg понижи препоръката си до „задържай“ с целева цена от 42 евро, аргументирайки се, че историята за оптиката вече е отразена в цената.
4. AT&S: подложките, които носят AI чиповете
AT&S Austria Technologie & Systemtechnik AG е поскъпнала с 366.46%. Австрийската компания произвежда високотехнологични печатни платки и IC подложки, които свързват модерните процесори с останалата част от системата – неособено атрактивен, но жизненоважен слой от AI хардуерната екосистема.
Компанията увеличава специализираните си производствени мощности за подложки в Китай по силата на дългосрочни договори с клиенти.

In [110]:
df.groupby([df["published_at_dt"].dt.date, "source"]).size().unstack(fill_value=0)

source,24chasa,actualno,banker,bta,economic,fakti,monitor,nova,segabg,standartnews,vesti
published_at_dt,,,,,,,,,,,
2026-04-19,0,0,0,0,0,0,0,5,0,0,0
2026-04-20,115,66,0,0,0,36,0,104,0,0,0
2026-04-21,304,211,0,0,0,183,0,118,0,0,0
2026-04-22,307,212,0,0,0,176,0,117,0,0,0
2026-04-23,315,187,0,0,0,183,0,109,0,0,0
2026-04-24,303,196,0,0,0,182,0,112,3,0,0
2026-04-25,218,80,0,0,0,169,0,75,1,0,0
2026-04-26,162,101,0,0,0,150,0,84,0,0,0
2026-04-27,302,193,0,0,0,155,0,106,3,0,0
2026-04-28,317,170,0,0,0,166,0,110,2,0,0
2026-04-29,287,196,0,0,0,162,0,114,3,0,0
2026-04-30,344,183,0,0,0,169,0,139,4,0,0
2026-05-01,236,74,0,0,0,177,0,113,5,0,0
2026-05-02,195,79,0,0,0,155,0,63,3,0,0
2026-05-03,225,77,0,0,4,163,0,59,10,0,0
2026-05-04,268,190,10,35,16,143,4,96,33,56,53
2026-05-05,290,161,33,140,16,147,111,96,50,136,98
2026-05-06,205,101,26,124,6,144,79,104,34,88,35
2026-05-07,330,196,37,137,18,155,93,122,37,128,146
2026-05-08,315,215,62,192,14,221,123,103,45,115,130
2026-05-09,198,73,23,170,6,153,98,72,34,97,43
2026-05-10,201,75,22,163,6,157,64,69,33,124,52
2026-05-11,291,198,38,132,16,168,103,111,41,101,116
2026-05-12,350,202,36,121,18,161,100,100,44,101,121
2026-05-13,314,199,39,124,14,163,91,117,50,104,115
2026-05-14,291,190,42,148,17,163,88,124,50,137,99
2026-05-15,291,179,35,128,16,160,91,102,39,145,91
2026-05-16,172,91,15,146,5,125,72,98,33,86,60
2026-05-17,167,84,10,164,6,119,69,95,31,110,52
2026-05-18,280,171,33,106,15,149,115,113,38,109,93
2026-05-19,326,191,38,121,16,149,94,103,46,121,94
2026-05-20,316,196,30,119,16,128,97,100,49,98,102
2026-05-21,301,199,37,126,15,147,104,125,51,119,84
2026-05-22,265,200,40,138,19,166,111,123,50,129,91
2026-05-23,235,97,17,173,6,179,91,85,39,98,52
2026-05-24,194,82,14,174,6,174,79,85,43,115,53
2026-05-25,226,102,17,107,6,125,113,81,29,83,48
2026-05-26,210,152,21,101,14,129,91,111,45,103,89
2026-05-27,249,156,31,106,17,142,92,117,43,120,98
2026-05-28,279,163,30,111,14,134,103,129,53,128,113
2026-05-29,307,154,36,126,17,153,127,119,45,139,122
2026-05-30,189,63,20,143,7,147,91,70,36,86,44
2026-05-31,172,84,18,139,7,143,61,54,29,103,42
2026-06-01,259,129,20,86,17,114,102,99,38,116,98
2026-06-02,263,143,24,73,13,109,113,118,48,2,114
2026-06-03,265,134,11,86,14,116,87,128,37,120,104
2026-06-04,299,170,34,117,17,146,103,119,44,136,125
2026-06-05,323,172,30,118,15,149,103,95,44,129,95
2026-06-06,187,68,13,142,7,139,78,79,29,89,53
2026-06-07,161,68,12,136,6,133,70,80,39,102,53
2026-06-08,261,161,23,109,17,129,102,97,40,101,95
2026-06-09,172,104,20,52,7,78,91,72,27,56,74

### Economic & Banker — Cleaning Summary

No source-specific cleaning required — article texts are well-structured with no significant boilerplate, encoding issues, or extraction artifacts.

**Note:** Both sources publish a relatively small number of articles per day compared to the larger sources. The same applies to `segabg`. Whether to keep them depends on the downstream tasks:
- For **event clustering and temporal summarization**, small sources are still valuable — they contribute additional perspectives on the same events covered by larger sources.
- The risk is **underrepresentation** — if an event is covered only by a small source, the cluster may be too thin for meaningful summarization.

**Decision:** Keep all three sources for now and revisit after clustering — if clusters from these sources are consistently too small to summarize, they can be excluded at that stage.

## 4.h. Actualno

In [111]:
print_source_samples(df, "actualno", n=3, random_state=42)

=== ACTUALNO (7338 articles) ===

--- В Разград се хванаха за главите: Ненужен в Лудогорец не иска да си ходи и извива ръцете на шефовете ---
URL: https://www.actualno.com/bgfootball/v-razgrad-se-hvanaha-za-glavite-nenujen-v-ludogorec-ne-iska-da-si-hodi-i-izviva-rycete-na-shefovete-news_2601730.html
Шефовете на Лудогорец се хванаха за главите и се чудят какво да правят с един от ненужните футболисти в състава на „орлите“. Става въпрос за централния бранител на разградчани – Оливие Вердон. Както е известно, националът на Бенин не попада в плановете на клуба за следващия сезон и поради тази причина ръководството търси начин да се раздели с него. На този етап обаче „удрят греда“.
Вердон няма никакво намерение да „скъса“ договора си по взаимно съгласие
Според информация на колегите от „Тема спорт“ ръководството на Лудогорец и Вердон са стартирали преговори за разтрогване на договора му, който е до лятото на 2027 година. Централният бранител обаче е категоричен, че не възнамерява да „скъса“ контракта си по взаимно съгласие. Причината е, че защитникът иска да получи всички дължими суми до края на споразумението – нещо, което не устройва разградчани. В момента двете страни умуват върху различни варианти как да сложат край на взаимоотношенията си.
Бранителят има над 240 мача за „орлите“
Оливие Вердон пристигна в Лудогорец в началото на септември 2020 година от испанския Алавес. Първоначално той бе под наем при „орлите“, но след изтичането на договора за преотстъпване разградчани решиха да го вземат за постоянно, като броиха 1,2 милиона евро за правата му. До момента централният защитник е изиграл общо 241 мача за разградчани във всички турнири, в които се е отчел със 17 попадения и две асистенции. Той е 5-кратен шампион на България, а също така е спечелил 2 пъти Купата на България и 5 пъти Суперкупата на страната.

--- Опасно време в страната: Порои, гръмотевици и риск от наводнения ---
URL: https://www.actualno.com/society/opasno-vreme-v-stranata-poroi-grymotevici-i-risk-ot-navodnenija-news_2602488.html
Предупреждения за опасно и потенциално опасно време са издадени за 13 области на страната за днес. Очакват се интензивни валежи, гръмотевични бури и риск от градушки. Оранжев код е в сила за област Габрово, както и за части от областите Видин, Монтана, Враца, Ловеч, София-област и Кюстендил. Жълт код е обявен за Перник, Благоевград, Пазарджик, Плевен, Велико Търново и Пловдив.
Максималните температури ще бъдат между 22 и 28 градуса, в София – около 22 градуса.
ОЩЕ: Времето ни готви сериозен обрат преди лятото: Симеон Матев с важна прогноза
По Черноморието преди обяд ще преобладава слънчево време, в сутрешните часове – на отделни места с намалена видимост. По-късно през деня ще се развива купесто-дъждовна облачност и на места ще превали и прегърми. Ще духа слаб югоизточен вятър. Максималните температури ще бъдат от 22-24 градуса по северното до 26-28 градуса по южното крайбрежие. Температурата на морската вода е 19 градуса.
В планините в Западна България още преди обяд, а през деня и на изток, ще се развива купеста и купесто-дъждовна облачност. На много места ще има валежи от дъжд и гръмотевични бури. Ще има и градушки. По-интензивни ще са явленията в масивите в Западна България и в Централен Предбалкан. Ще духа умерен югозападен вятър. Максималната температура на височина 1200 метра ще бъде около 17 градуса, на 2000 метра – около 11 градуса.
ОЩЕ: Прогноза за времето - 4 юни 2026 г. (четвъртък)
До края на тази и през първите дни на следващата седмица въздушната маса над страната ще остане неустойчива. Сутрин над повечето райони ще преобладава слънчево време, но около и след обяд и до полунощ ще се развива купеста и купесто-дъждовна облачност. На много места ще има временно интензивни валежи и гръмотевични бури. Ще има и градушки. На по-малко места и с по-малка интензивност ще са валежите в петък.

--- Златни момичета! България е европейски шампион по художествена гимнастика! ---
URL: https://www.actualno.com/moresport/zlatni-momicheta-bylgarija-e-evropejski-shampion-po-hudojestvena-gimnastika-news_2600766.html
Отборът на България спечели отборната титла на Европейското първенство по художествена гимнастика, което се провежда във Варна. Българските момичета събраха резултат от 277.600. Това стана благодарение на майсторството на гимнастичките от индивидуалната надпревара Стилияна Николова, Ева Брезалиева и момичетата от ансамбъла. По-рано през деня Стилияна Николова стана вицеевропейска шампионка, като отстъпи титлата на германската представителка Дария Варфоломеев.
Стилияна Николова е вицеевропейска шампионка по художествена гимнастика
Резултати
Най-добрата българска състезателка събра 118.750 точки. Николова има също сребро от Талин 2025 и е златна медалистка от Будапеща 2024. Победителка в многобоя остана олимпийската и двукратна световна шампионка Даря Варфоломеев (Германия) със 120.150, а трета е защитаващата титлата си Таисия Онофричук (Украйна) със 117.150.
Две българки на финалите на Европейското по художествена гимнастика. Какво предстои? (ВИДЕО)
Ансамблите
При ансамблите европейски шампионки станаха гимнастичките от Испания, следвани от представителките на руската федерация и Израел. Българският ансамбъл се класира на шесто място, след като допусна грешки в смесеното съчетание. Все пак българските момичета ще участват на финала с пет топки, който ще се проведе утре - 31 май 2206 г.
Финали
На 31 май 2026 г. ще се проведат финалите на отделните уреди. Стилияна Николова ще участва във всеки едни финал. Другата ни представителка Ева Брезалиева има три финала - на топка, лента и обръч. Рекорден брой държави участват в настоящето Европейско първенство - 43, с ансамбъл в състезанието ще участват 26 страни.
България води колоната на Евро 2026, момичетата ни без конкуренция в многобоя
"Интересно състезание, мисля, че се справих много добре. Доволна съм от изиграването си, разбира се има какво още да се подобри. Не се пуснах да направя всичко, но и това ще се промени", коментира Стилияна Николова след края на състезанието.

In [112]:
df = apply_to_source(
    df,
    lambda t: drop_lines(
        t, lambda line: line.strip().startswith(("Снимка:", "Източник:"))
    ),
    source="actualno",
)

In [113]:
df = apply_to_source(df, lambda t: drop_lines(t, is_noise_line), source="actualno")

### Actualno — Cleaning Summary

- Dropped lines starting with `Снимка:` and `Източник:` (photo and source attribution labels)
- Dropped lines containing only Latin characters (embedded tweets and foreign-language content)

**Pending decision:** Lines starting with `Още:` are links to related articles. These are not part of the article content but are kept for now — will revisit after evaluating their impact on embeddings.

## 4.i. NOVA

In [114]:
print_source_samples(df, "nova", n=3, random_state=42)

=== NOVA (5139 articles) ===

--- Морето взе първа жертва в навечерието на откриването на летния сезон ---
URL: https://nova.bg/news/view/2026/06/01/539098/%D0%BC%D0%BE%D1%80%D0%B5%D1%82%D0%BE-%D0%B2%D0%B7%D0%B5-%D0%BF%D1%8A%D1%80%D0%B2%D0%B0-%D0%B6%D0%B5%D1%80%D1%82%D0%B2%D0%B0-%D0%B2-%D0%BD%D0%B0%D0%B2%D0%B5%D1%87%D0%B5%D1%80%D0%B8%D0%B5%D1%82%D0%BE-%D0%BD%D0%B0-%D0%BE%D1%82%D0%BA%D1%80%D0%B8%D0%B2%D0%B0%D0%BD%D0%B5%D1%82%D0%BE-%D0%BD%D0%B0-%D0%BB%D0%B5%D1%82%D0%BD%D0%B8%D1%8F-%D1%81%D0%B5%D0%B7%D0%BE%D0%BD/
Снимка: iStock
Жена се удави на плажа в Несебър
Жена се удави на плажа "Олимпийски надежди" в Несебър. Сигналът за забелязана в морето давеща се жена е подаден в неделя около 20:30 ч.
Тялото е извадено от водата, а самоличността на загиналата все още не е установена.
При извършения оглед не са открити видими следи от насилие по тялото на жертвата. На брега са намерени плажната ѝ чанта с летни дрехи и джапанки. Трупът е откаран за аутопсия в Бургас.
Последвайте ни

--- Два тира катастрофираха на пътя Мездра - Ботевград, единият шофьор е откаран в болница ---
URL: https://nova.bg/news/view/2026/05/30/538997/%D0%B4%D0%B2%D0%B0-%D1%82%D0%B8%D1%80%D0%B0-%D0%BA%D0%B0%D1%82%D0%B0%D1%81%D1%82%D1%80%D0%BE%D1%84%D0%B8%D1%80%D0%B0%D1%85%D0%B0-%D0%BD%D0%B0-%D0%BF%D1%8A%D1%82%D1%8F-%D0%BC%D0%B5%D0%B7%D0%B4%D1%80%D0%B0-%D0%B1%D0%BE%D1%82%D0%B5%D0%B2%D0%B3%D1%80%D0%B0%D0%B4-%D0%B5%D0%B4%D0%B8%D0%BD%D0%B8%D1%8F%D1%82-%D1%88%D0%BE%D1%84%D1%8C%D0%BE%D1%80-%D0%B5-%D0%BE%D1%82%D0%BA%D0%B0%D1%80%D0%B0%D0%BD-%D0%B2-%D0%B1%D0%BE%D0%BB%D0%BD%D0%B8%D1%86%D0%B0/
Снимката е илюстративна: iStock
Трафикът в района на инцидента е ограничен
Два тира катастрофираха на пътя Мездра - Ботевград, в района на Скравена.Единият шофьор е откаран в болница, предава кореспондентът на БТА във Враца Лиляна Рашкова.
В района временно е ограничено движението в платното в посока Мездра, съобщават от АПИ. Трафикът в посока Мездра за леки автомобили се осъществява по обходен маршрут – път III-161 Ботевград – Радотина – Рашково – Ребърково. Тежкотоварните автомобили изчакват на място. Трафикът се регулира от Пътна полиция.
От пресцентъра на МВР съобщиха за БТА, че единият камион е с турска регистрация, другият – влекач MAN. Шофьорът на българския товарен автомобил е в болница за уточняване на неговото състояние след инцидента.
Редактор: Ина Григорова
Последвайте ни

--- Очаква се засилен трафик за Деня на труда и Гергьовден ---
URL: https://nova.bg/news/view/2026/04/30/535671/%D0%BE%D1%87%D0%B0%D0%BA%D0%B2%D0%B0-%D1%81%D0%B5-%D0%B7%D0%B0%D1%81%D0%B8%D0%BB%D0%B5%D0%BD-%D1%82%D1%80%D0%B0%D1%84%D0%B8%D0%BA-%D0%B7%D0%B0-%D0%B4%D0%B5%D0%BD%D1%8F-%D0%BD%D0%B0-%D1%82%D1%80%D1%83%D0%B4%D0%B0-%D0%B8-%D0%B3%D0%B5%D1%80%D0%B3%D1%8C%D0%BE%D0%B2%D0%B4%D0%B5%D0%BD/
Снимка: iStock
Основният поток традиционно ще бъде към автомагистралите „Тракия“, „Хемус“ и „Струма“
В почивните дни около 1 май и Гергьовден се очаква засилен трафик по цялата републиканската пътна мрежа. Броят на превозните средства ще достигне около 1 милион и 700 хиляди автомобила за денонощие.
Основният поток традиционно ще бъде към автомагистралите „Тракия“, „Хемус“ и „Струма“. Най-интензивно ще е движението в следобедните и вечерните часове днес, както и до обяд на 1 май. Част от пътуващите ще тръгнат и в деня преди Гергьовден, като комбинират почивния ден с предстоящия уикенд.
20-километрова колона от тирове преди ГКПП "Капитан Андреево"
Редактор: Ралица АтанасоваПоследвайте ни

In [115]:
text = "Новините на NOVA Още от Nova Новините на Нова – емисии Начало Новините на NOVA Новините на NOVA (30.04.2026 - късна) Начало Още от Nova Новините на NOVA (30.04.2026 - късна) Начало Новините на Нова – емисии Новините на NOVA (30.04.2026 - късна) Новините на NOVA (30.04.2026 - късна) 30 април 2026 23:02 Новините на NOVA NEWS (30.04.2026 - 20:00) Новините на NOVA (30.04.2026 - централна) Новините на NOVA (30.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (30.04.2026) Новините на NOVA (30.04.2026 - обедна) Новините на NOVA (30.04.2026 - 9.00) Гледайте цялата емисия Редактор: Ивета Костадинова Последвайте ни NewsLetter Google News Youtube Viber TikTok Instagram Facebook Още от Още от Nova Новините на NOVA NEWS (30.04.2026 - 20:00) Новините на NOVA (30.04.2026 - централна) „Пресечна точка”: За 52-рото Народно събрание и очакванията на президента Илияна Йотова Новините на NOVA (30.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (30.04.2026) Новините на NOVA (30.04.2026 - обедна) Новините на NOVA (30.04.2026 - 9.00) Новините на NOVA (30.04.2026 - 8.00) Новините на NOVA (30.04.2026 - 7.00) Новините на NOVA (30.04.2026 - 6.00) Прогноза за времето (30.04.2026 - сутрешна) Новините на NOVA (29.04.2026 - късна) Новините на NOVA NEWS (29.04.2026 - 20:00) Новините на NOVA (29.04.2026 - централна) „Пресечна точка”: За закриването на „Магазин за хората” и българското здравеопазване Новините на NOVA (29.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (29.04.2026) Новините на NOVA (29.04.2026 - обедна) Новините на NOVA (29.04.2026 - 9.00) Новините на NOVA (29.04.2026 - 8.00) Новините на NOVA (29.04.2026 - 7.00) Новините на NOVA (29.04.2026 - 6.00) Новините на NOVA (28.04.2026 - късна) Новините на NOVA (28.04.2026 - централна) „Пресечна точка”: За съдебната система и за заплатите в държавния сектор Новините на NOVA (28.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (28.04.2026) Новините на NOVA (28.04.2026 - обедна) Новините на NOVA (28.04.2026 - 9.00) Новините на NOVA (28.04.2026 - 8.00) Новините на NOVA (28.04.2026 - 7.00) Новините на NOVA (28.04.2026 - 6.00) Новините на NOVA (27.04.2026 - късна) Новините на NOVA NEWS (27.04.2026 - 20:00) Новините на NOVA (27.04.2026 - централна) 'Пресечна точка': За състава на 52-рото Народно събрание и ръста на цените у нас Новините на NOVA (27.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (27.04.2026) Новините на NOVA (27.04.2026 - обедна) Новините на NOVA (27.04.2026 - 9.00) Новините на NOVA (27.04.2026 - 8.00) Новините на NOVA (27.04.2026 - 7.00) Новините на NOVA (27.04.2026 - 6.00) Новините на NOVA NEWS (26.04.2026 - 20:00) Новините на NOVA (26.04.2026 - централна) Новините на NOVA (26.04.2026 - обедна) Прогноза за времето (26.04.2026 - обедна) Спортни новини (26.04.2026 - обедна) ОЩЕ ОТ КАТЕГОРИЯТА"


def print_wrapped(text: str, words_per_line: int = 100) -> str:
    words = text.split()
    lines = []
    for i in range(0, len(words), words_per_line):
        lines.append(" ".join(words[i : i + words_per_line]))
    return "\n".join(lines)

In [116]:
print(print_wrapped(text, words_per_line=20))

Новините на NOVA Още от Nova Новините на Нова – емисии Начало Новините на NOVA Новините на NOVA (30.04.2026 -
късна) Начало Още от Nova Новините на NOVA (30.04.2026 - късна) Начало Новините на Нова – емисии Новините на NOVA
(30.04.2026 - късна) Новините на NOVA (30.04.2026 - късна) 30 април 2026 23:02 Новините на NOVA NEWS (30.04.2026 - 20:00)
Новините на NOVA (30.04.2026 - централна) Новините на NOVA (30.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (30.04.2026) Новините
на NOVA (30.04.2026 - обедна) Новините на NOVA (30.04.2026 - 9.00) Гледайте цялата емисия Редактор: Ивета Костадинова Последвайте ни NewsLetter
Google News Youtube Viber TikTok Instagram Facebook Още от Още от Nova Новините на NOVA NEWS (30.04.2026 - 20:00) Новините
на NOVA (30.04.2026 - централна) „Пресечна точка”: За 52-рото Народно събрание и очакванията на президента Илияна Йотова Новините на NOVA
(30.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (30.04.2026) Новините на NOVA (30.04.2026 - обедна) Новините на NOVA (30.04.2026
- 9.00) Новините на NOVA (30.04.2026 - 8.00) Новините на NOVA (30.04.2026 - 7.00) Новините на NOVA (30.04.2026 - 6.00)
Прогноза за времето (30.04.2026 - сутрешна) Новините на NOVA (29.04.2026 - късна) Новините на NOVA NEWS (29.04.2026 - 20:00) Новините
на NOVA (29.04.2026 - централна) „Пресечна точка”: За закриването на „Магазин за хората” и българското здравеопазване Новините на NOVA (29.04.2026
- следобедна) Обеден информационен блок на NOVA NEWS (29.04.2026) Новините на NOVA (29.04.2026 - обедна) Новините на NOVA (29.04.2026 -
9.00) Новините на NOVA (29.04.2026 - 8.00) Новините на NOVA (29.04.2026 - 7.00) Новините на NOVA (29.04.2026 - 6.00) Новините
на NOVA (28.04.2026 - късна) Новините на NOVA (28.04.2026 - централна) „Пресечна точка”: За съдебната система и за заплатите в
държавния сектор Новините на NOVA (28.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (28.04.2026) Новините на NOVA (28.04.2026 -
обедна) Новините на NOVA (28.04.2026 - 9.00) Новините на NOVA (28.04.2026 - 8.00) Новините на NOVA (28.04.2026 - 7.00) Новините
на NOVA (28.04.2026 - 6.00) Новините на NOVA (27.04.2026 - късна) Новините на NOVA NEWS (27.04.2026 - 20:00) Новините на
NOVA (27.04.2026 - централна) 'Пресечна точка': За състава на 52-рото Народно събрание и ръста на цените у нас Новините на
NOVA (27.04.2026 - следобедна) Обеден информационен блок на NOVA NEWS (27.04.2026) Новините на NOVA (27.04.2026 - обедна) Новините на NOVA
(27.04.2026 - 9.00) Новините на NOVA (27.04.2026 - 8.00) Новините на NOVA (27.04.2026 - 7.00) Новините на NOVA (27.04.2026 -
6.00) Новините на NOVA NEWS (26.04.2026 - 20:00) Новините на NOVA (26.04.2026 - централна) Новините на NOVA (26.04.2026 - обедна)
Прогноза за времето (26.04.2026 - обедна) Спортни новини (26.04.2026 - обедна) ОЩЕ ОТ КАТЕГОРИЯТА

In [117]:
def check_field_start(df, pattern, field="full_text", source=None):
    mask = df[field].str.startswith(pattern, na=False)
    if source:
        mask = mask & (df["source"] == source)
    print(f"Articles where {field} starts with '{pattern}': {mask.sum()}")
    return df[mask].head()

In [118]:
check_field_start(df, pattern="Новините на NOVA", field="title", source="nova")

Articles where title starts with 'Новините на NOVA': 347

,source,title,url,published_at,full_text,fetched_at,published_at_dt,word_count
216,nova,Новините на NOVA (09.06.2026 - обедна),https://nova.bg/news/view/2026/06/09/540043/%D...,2026-06-09T09:31:39+00:00,Новините на NOVA Още от Nova Новините на Нова ...,2026-06-09T11:19:14.061560+00:00,2026-06-09 09:31:39+00:00,445
536,nova,Новините на NOVA (09.06.2026 - 7.00),https://nova.bg/news/view/2026/06/09/540000/%D...,2026-06-09T04:10:20+00:00,Новините на NOVA Още от Nova Новините на Нова ...,2026-06-09T07:53:22.708802+00:00,2026-06-09 04:10:20+00:00,446
545,nova,Новините на NOVA (09.06.2026 - 8.00),https://nova.bg/news/view/2026/06/09/539999/%D...,2026-06-09T05:12:01+00:00,Новините на NOVA Още от Nova Новините на Нова ...,2026-06-09T07:53:22.708720+00:00,2026-06-09 05:12:01+00:00,446
553,nova,Новините на NOVA (09.06.2026 - 9.00),https://nova.bg/news/view/2026/06/09/539997/%D...,2026-06-09T06:10:50+00:00,Новините на NOVA Още от Nova Новините на Нова ...,2026-06-09T07:53:22.708645+00:00,2026-06-09 06:10:50+00:00,446
727,nova,Новините на NOVA (09.06.2026 - 6.00),https://nova.bg/news/view/2026/06/09/539998/%D...,2026-06-09T03:15:28+00:00,Новините на NOVA Още от Nova Новините на Нова ...,2026-06-09T03:42:30.901240+00:00,2026-06-09 03:15:28+00:00,455

In [119]:
df = drop_by_field(df, ["Новините на NOVA"], field="title", source="nova")

Dropping 347 articles where title startswith ['Новините на NOVA']
Remaining articles: 50872

In [120]:
check_field_start(df, pattern="Прогноза за времето", field="title", source="nova")

Articles where title starts with 'Прогноза за времето': 90

,source,title,url,published_at,full_text,fetched_at,published_at_dt,word_count
217,nova,Прогноза за времето (08.06.2026 - обедна),https://nova.bg/news/view/2026/06/09/540045/%D...,2026-06-09T09:50:13+00:00,Новините на NOVA България Времето Начало Новин...,2026-06-09T11:19:14.061541+00:00,2026-06-09 09:50:13+00:00,667
720,nova,Прогноза за времето (09.06.2026 - сутрешна),https://nova.bg/news/view/2026/06/09/540001/%D...,2026-06-09T03:07:42+00:00,Новините на NOVA Още от Nova Времето Начало Но...,2026-06-09T03:42:30.901272+00:00,2026-06-09 03:07:42+00:00,459
1619,nova,Прогноза за времето (08.06.2026 - обедна),https://nova.bg/news/view/2026/06/08/539917/%D...,2026-06-08T09:45:58+00:00,Новините на NOVA България Времето Начало Новин...,2026-06-08T11:01:54.615019+00:00,2026-06-08 09:45:58+00:00,622
1840,nova,Прогноза за времето (08.06.2026 - сутрешна),https://nova.bg/news/view/2026/06/08/539882/%D...,2026-06-08T03:44:21+00:00,Новините на NOVA България Времето Начало Новин...,2026-06-08T04:14:12.343973+00:00,2026-06-08 03:44:21+00:00,648
2360,nova,Прогноза за времето (07.06.2026 - обедна),https://nova.bg/news/view/2026/06/07/539814/%D...,2026-06-07T09:45:16+00:00,Новините на NOVA Още от Nova Времето Начало Но...,2026-06-07T11:50:32.142609+00:00,2026-06-07 09:45:16+00:00,469

In [121]:
df = drop_by_field(df, "Прогноза за времето", field="title", source="nova")

Dropping 90 articles where title startswith ['Прогноза за времето']
Remaining articles: 50782

In [122]:
df = drop_by_field(df, "Новините на NOVA", field="full_text", source="nova")

Dropping 325 articles where full_text startswith ['Новините на NOVA']
Remaining articles: 50457

In [123]:
df = apply_to_source(
    df, lambda t: truncate_at_sentinel(t, ["Последвайте ни"]), source="nova"
)

In [124]:
df = apply_to_source(
    df,
    lambda t: drop_lines(
        t, lambda line: line.strip().startswith(("Снимка:", "Снимки:"))
    ),
    source="nova",
)

In [125]:
df = apply_to_source(df, lambda t: drop_lines(t, is_noise_line), source="nova")

In [126]:
phrases = [
    "Повече гледайте във видеото",
    "Редактор:",
    "Цялото предаване гледайте във видеото",
]

for phrase in phrases:
    mask = (df["source"] == "nova") & df["full_text"].str.contains(phrase, na=False)
    print(f"'{phrase}': {mask.sum()} articles")

'Повече гледайте във видеото': 396 articles
'Редактор:': 3094 articles
'Цялото предаване гледайте във видеото': 28 articles

In [127]:
df = apply_to_source(
    df,
    lambda t: drop_lines(
        t,
        lambda line: line.strip().startswith(
            (
                "Повече гледайте във видеото",
                "Редактор:",
                "Цялото предаване гледайте във видеото",
            )
        ),
    ),
    source="nova",
)

### Nova — Cleaning Summary

- Dropped articles with `title` or `full_text` starting with `Новините на NOVA` and `Прогноза за времето`
- Truncated text at `Последвайте ни`
- Dropped lines starting with `Снимка:` and `Снимки:` (photo captions)
- Dropped lines starting with `Редактор:` (editor attribution)
- Dropped lines containing only Latin characters (foreign text, social media)
- Dropped social media attribution lines (e.g. `— Reuters (@Reuters) May 8, 2026`)
- Dropped emoji-heavy and `@handle` lines (embedded tweets and TikTok posts)
- Dropped boilerplate lines: `Повече гледайте във видеото`, `Цялото предаване гледайте във видеото`

## 4.j. 24CHASA

In [128]:
print_source_samples(df, "24chasa", n=3, random_state=42)

=== 24CHASA (13052 articles) ===

--- Украинка неуспешно опита да продаде 6-годишния си син за 25 000 долара ---
URL: https://www.24chasa.bg/mezhdunarodni/article/22722534
Украинка се опита да продаде 6-годишния си син за 25 000 долара.
38-годишна жена е била задържана, съобщиха от украинската прокуратура. На жената е повдигнато обвинение за трафик на непълнолетни.
По данни от разследването, след като се развела, тя заживяла с най-малкия си син, докато другите ѝ две деца - на 13 и 16 години - останали при баща си. Жената, която вече е осъждана за кражби, решила да се освободи от грижите за детето, като го продаде.
През март 2026 г. тя намерила „купувач" и се договорила за предаването на момчето срещу парична сума. Мъжът, на когото било предложено да купи детето, сигнализирал органите на реда.
Предаването на детето се състояло на 17 април 2026 г. в град Луцк в рамките на специализирана полицейска операция. Веднага след получаването на парите жената е била задържана.
Съдът вече е определил мярка за неотклонение „задържане под стража", информира DarikNews.
Предстои да бъде дадена и правна оценка на действията на социалните служби, тъй като детето е било на отчет при тях, но до момента не са постъпвали сигнали за проблеми с начина му на живот.
6-годишното момче е настанено в приют под надзора на органите по закрила на детето.

--- Задържаха мъж, блъснал 8 коли след гонка с полицията ---
URL: https://www.24chasa.bg/bulgaria/article/22957734
Софийска районна прокуратура привлече към наказателна отговорност 29-годишен мъж за три престъпления.
Събраните до момента доказателства сочат, че на 30.05.2026 г. в гр. София, ж.к. „Обеля", при управление на лек автомобил „БМВ", Ц.Б. извършил непристойни действия, грубо нарушаващи обществения ред и изразяващи явно неуважение към обществото. След подаден звуков и светлинен сигнал от полицейските служители Ц.Б. не се подчинил на полицейското разпореждане, продължил движението си с превишена скорост, съобщават от прокуратурата. Последвала гонка с полицейския автомобил, създавайки предпоставки за увреждането на публично и частно имущество, както и живота и здравето на гражданите. Ц.Б. реализирал пътнотранспортни произшествия с 8 автомобила, като причинил значителни имуществени вреди.
След това обвиняемият отказал да му бъде извършена проверка по надлежния ред за установяване на употребата на алкохол и наркотични вещества или техни аналози и не изпълнил предписание на контролен орган за изследване по надлежния ред.
По случая се води досъдебно производство.
С постановление на дежурен прокурор Ц.Б. беше задържан за срок до 72 часа.
Днес наблюдаващ прокурор внесе в Софийски районен съд искане за определяне на мярка „задържане под стража" спрямо обвиняемия.

--- Спорт по телевизията днес ---
URL: https://www.24chasa.bg/sport/article/22949288
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп
Последвайте ни в Google News Showcase
Здравейте,
благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър.
Благодарим ви!
Благодарим ви, че се включихте!
Изтеглете новото приложение на "24 часа"

In [129]:
phrase = "Разберете големите новини от последното денонощие накуп Запиши се"

mask = (df["source"] == "24chasa") & df["full_text"].str.contains(phrase, na=False)
print(f"Articles containing phrase: {mask.sum()}\n")

for _, row in df[mask].head().iterrows():
    normalized = re.sub(r"\s+", " ", row["full_text"])
    count = normalized.count(phrase)
    print(f"--- {row['title']} (appears {count}x) ---")
    print_by_words(row["full_text"])
    print()

multi = (
    df[mask]["full_text"]
    .apply(lambda t: re.sub(r"\s+", " ", t).count(phrase) > 1)
    .sum()
)
print(f"Total articles with phrase appearing more than once: {multi}")

Articles containing phrase: 675

--- Цената на петрола на ОПЕК вече е под 97 долара за барел (appears 1x) ---
Цената на петрола на ОПЕК падна под 97 долара за барел Снимка: СНИМКА: Pixabay (илюстративна) "24 часа" в мейла ти.
Разберете големите новини от последното денонощие накуп Запиши се Цената на петрола на Организацията на страните износителки на петрол (ОПЕК)
вчера се понижи за шеста поредна сесия - до 96,31 долара за барел, съобщи днес на страницата си петролният картел.
Петролът на ОПЕК се котира под 97 долара за барел за първи път от 6 март. Един барел петрол на
ОПЕК се продаваше за 97,74 долара в понеделник. На 27 февруари, преди началото на войната на САЩ и Израел срещу
Иран, петролът на ОПЕК се котираше за 70,07 долара за барел. За определяне на цената на петрола на ОПЕК се
използва т. нар. петролна кошница, включваща 12 сорта петрол за износ на страните членки на картела: Сахаран бленд или "Сахарска
смес" (Алжир), Джено (Конго), Зафиро (Екваториална Гвинея), Раби лек (Габон), ирански тежък (Иран), Басра лек (Ирак), Кувейт експорт (Кувейт), Ес
Сидер (Либия), Бони лек (Нигерия), Лек арабски (Саудитска Арабия), Мурбан (ОАЕ) и Мерей (Венецуела). Историческият максимум за "кошницата на ОПЕК"
е цената от 146,05 долара за барел, отчетена на 19 март 2026 година. Предишният максимум от 140,73 долара за барел
бе достигнат на 3 юли 2008 година, припомня БТА. Цената на барел петрол се определя чрез извеждане на средна аритметична
величина от котировките към момента на закриване на търговията с всички сортове от "кошницата на ОПЕК" предходния работен ден. Затвори
Цената на петрола на ОПЕК падна под 97 долара за барел Снимка: СНИМКА: Pixabay (илюстративна) Четете още Петролът на ОПЕК
падна под 107 долара за барел ОПЕК понижи прогнозата за световното търсене на суров петрол Ново поскъпване на петрола след
заканата на Тръмп срещу Иран

--- Сигнали за бомби са получени в училищата в Хърватия, Босна и Херцеговина и Черна гора (appears 1x) ---
Снимка: Снимка: Архив "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Запиши се Сигнали за бомби
бяха получени днес в градове в Хърватия, Босна и Херцеговина и Черна гора, съобщават местните медии. След като вчера бяха
получени десетки фалшиви сигнали за бомби в училища в хърватската столица Загреб, днес отново бяха получени такива сигнали в Приморско-горанския
регион, Западна Хърватия, информира хърватската национална телевизия ХРТ, цитирана от БТА. На адресите на общо 16 училища в района са
пристигнали днес писма с предупреждение за заложена бомба в около 7 ч. сутринта местно време (8 ч. българско време). Училищата
бяха евакуирани, а след проверка на полицията бе установено, че сигналите са фалшиви и учебните часове продължиха по график. По-късно
днес бяха получени сигнали за бомби и в два търговски центъра в град Риека в същия район. Центровете бяха евакуирани,
а полицията все още извършва проверка. ХРТ отбелязва, че от началото на седмицата се наблюдава вълна от фалшиви сигнали за
поставени бомби, а хърватското министерство на науката, образованието и младежта призова извършителите да не всяват паника и страх. Сигнали за
бомби бяха получени днес и в училища в Черна гора, като полицията е установила, че един и съши мейл е
разпратен до различни основни училища в Цетине, Бар, Тузи, Беране и други градове в страната, информира черногорската национална телевизия РТЦГ.
Учебните часове са отменени за днес и се извършва полицейска проверка. Също така до черногорското правителство, полицията и Агенцията за
национална сигурност е изпратен мейл със сигнал за бомба у пътник на черногорското летище. След проверка е установено, че става
въпрос за фалшив сигнал. Черногорската полиция разпространи съобщение, в което се посочва, че от днес до края на учебната година
всяка сутрин ще се извършват щателни проверки на училищата преди началото на учебните часове. Целта е да се осигури безпрепятственото
и сигурно провеждане на часовете. "Апелираме към родителите да обърнат специално внимание на дейностите на децата в киберпространството и да
разговарят с тях за значението на уважението на закона и възможните последици от такова незаконно поведение", се отбелязва в съобщението.
Сигнали за бомби бяха получени и в няколко училища в Сараево, Босна и Херцеговина, тази сутрин, съобщи босненската национална телевизия
БХРТ. Училищата са получили сигналите по електронната поща. Към момента полицията извършва проверка. Преди няколко дни сигнали за поставени бомби
бяха получени и в двата най-големи търговски обекта в центъра на Сараево, но след проверка се установи, че са били
фалшиви, припомня БХРТ. Затвори Снимка: Снимка: Архив Четете още Сигнали за бомби в 4 училища в София Фалшиви сигнали за
бомби опразниха училища в Черна гора и Босна и Херцеговина В училища в цяла Сърбия са получени заплахи за бомба

--- Изтребители се сблъскали в Южна Корея, защото пилотите им снимали (appears 1x) ---
Изтребител СНИМКА: Георги Кюрпанов - Генк (Снимката е илюстративна) "24 часа" в мейла ти. Разберете големите новини от последното денонощие
накуп Запиши се Южнокорейските власти установиха, че през 2021 г. два изтребителя са се сблъскали във въздуха, защото пилотите са
снимали и записвали видео, съобщава Би Би Си. Инцидентът е станал, докато изтребителите са изпълнявали полетна мисия в централния град
Даегу, според Комисията за одит и инспекция в Сеул. Пилотите са оцелели без наранявания, но сблъсъкът е повредил самолетите, което
е струвало на военните 596 000 долара за ремонт. Един от пилотите, който оттогава е напуснал армията, е бил глобен
с 88 милиона вона. Инцидентът се е случил, защото той е искал да направи снимки в чест на последния си
полет с военната си част. Затвори Изтребител СНИМКА: Георги Кюрпанов - Генк (Снимката е илюстративна) Четете още Руски изтребител се
разби при тренировъчен полет над Крим Румънски изтребител се разби по време на съвместно учение с българските ВВС

--- Дeлът на китайските марки автомобили нa бългapcĸия пaзap ce e yвeличил над двa пъти (appears 1x) ---
Снимка: КМГ Снимка: Китайска медийна група "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Запиши се
Ключoвите ВYD и МG, ĸoитo ca cpeд нaй-ycпeшнитe ĸитaйcĸи мapĸи в Eвpoпa, вече сериозно нaвлизaт нa бългapcĸия пaзap.Toвa пocтaвя ĸитaйcĸитe
пpoизвoдитeли пpeд тpaдициoнни aвтoмoбилни марки - тe вeчe имaт нaд двa пъти пo-гoлям дял oт итaлиaнcĸитe мapĸи, продавани на българския
пазар, и изпpeвapвaт взeти зaeднo aмepиĸaнcĸитe и бpитaнcĸитe бpaндoвe, пише КМГ. Toвa oзнaчaвa, чe pъcтът мoжe дa ce ycĸopи дoпълнитeлнo
пpeз cлeдвaщитe мeceци, заключават експерти. „Caмo зa гoдинa ĸитaйcĸитe aвтoмoбилни мapĸи в България ca нaпpaвили пpoбив, ĸoйтo дo пpeди гoдини
изглeждaшe тpyднo пocтижим, като техният дял нa бългapcĸия пaзap ce e увeличил пoвeчe oт двa пъти и вeчe дocтигa 5,9%
пpeз пъpвoтo тpимeceчиe нa 2026 г..",тези данни се цитират и от специализираните икономически издания в страната. Πpoгнoзитe зa pязĸo cвивaнe
нa aвтoмoбилния пaзap cлeд въвeждaнeтo нa eвpoтo в България зaceгa нe ce oпpaвдaвaт. Дaннитe пoĸaзвaт пo-cĸopo cтaбилизиpaнe нa виcoĸи нивa,
отчитат икономисти. Ето и малко статистика: Hяĸoлĸo от най-известните китайски марки като Dоngfеng и Gееlу, мoгaт дa ce пoxвaлят c
тpицифpeн pъcт, който обаче е пocтигнaт cпpямo ниcĸa бaзa пpeз минaлaтa гoдинa. Oт гoлeмитe „игpaчи" на българския пазар, нaй-cepиoзeн pъcт
oтчитa Нуundаі, чиитo пpoдaжби нa пpaĸтиĸa ca ce yдвoили (+97%). Cepиoзнo yвeличeниe в дocтaвĸитe имa cъщo пpи Ореl (+69%), Fіаt
(+65%), Fоrthіng (+54%), Сіtrоеn (+32%), Grеаt Wаll Моtоr (+31%) и ВМW (+20%)., отчитат анализматорите. От друга страна, с нaй-гoлeми cпaдoвe
в peгиcтpaциитe нa гoдишнa бaзa ca Dасіа (-37%), пpи ĸoятo имaшe зaбaвянe зapaди нeoбиĸнoвeнoтo peшeниe eднoвpeмeннo дa oбнoви вcичĸитe cи
мoдeли, и Rеnаult. C 29% нaмaлявaт peгиcтpaциитe нa Fоrd, , а пpи Аudі cпaдът e 17%, пpи Ѕkоdа - 14%.
Cpeд пo-мaлĸитe пaзapни игpaчи пpaви впeчaтлeниe зacилвaщият ce oтлив oт Теѕlа (-15%). Затвори Снимка: КМГ Снимка: Китайска медийна група Четете
още КМГ: Стратегията „печеля-печелиш“ наистина се оказва печеливша КМГ: Международната общност трябва категорично да се противопоставя на новата „милитаризация“ на
Япония Китай планира изграждане на „парник“ на Луната за бъдещи мисии

--- Агенцията по храните затвори кланици в Гергевец и Бяла Слатина (appears 1x) ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Запиши се Българската агенция по безопасност на храните
затвори две кланици - регистрирана в сливенското село Гергевец и нелегална в Бяла Слатина. В кланицата в Гергевец инспектори от
Централното управление на БАБХ и Областната дирекция по безопасност на храните - Сливен, са установили сериозни нарушения на хигиенните изисквания
– мухъл и ръжда в производствените помещения, както и липса на необходимите дезинфектанти. Ще бъдат унищожени 185 кг свинско месо
и месни продукти. Те са без вътрешна идентификационна маркировка, което не позволява да бъдат проследени. На собственика са издадени предписание
и акт за административно нарушение. Дейността на кланицата може да бъде възобновена след отстраняване на всички несъответствия. При друга проверка
инспектори от Областната дирекция за безопасност на храните във Враца откриха нерегистрирано животновъдно стопанство и нелегален цех за месопреработка в
частен имот Бяла Слатина. Гаражът е бил оборудван за производство на месни продукти. Открити са 67 кг месни заготовки, които
са възбранени и насочени за унищожаване в екарисаж. В стопанството са установени две телета и крава без идентификация. Те нямат
право да напускат обекта до извършване на необходимите ветеринарномедицински изследвания. Ако животните са клинично здрави, ще бъдат регистрирани и забраната
за движение ще бъде отменена. Намерени са също две прасета, чийто произход не може да се проследи. Заради риск от
чума по свинете те ще бъдат заклани. На собственика са дадени указания да регистрира животновъдния обект по Закона за ветеринарномедицинската
дейност. Затвори Четете още БАБХ: Има риск месо от огнището с антракс в Силистренско да се разпространи Животни с антракс
от село Черногор били транспортирани към кланица в Исперих Преработвали месо от умрели от антракс животни в Силистренско

Total articles with phrase appearing more than once: 0

**Finding:** The phrase `"Разберете големите новини от последното денонощие накуп Запиши се"` appears in a large portion of `24chasa` articles, always once and always at the beginning — it is a newsletter subscription prompt injected before the actual article content. The real text starts immediately after it.

**Decision:** Strip everything up to and including this phrase, keeping only the content that follows.

In [130]:
def strip_before_sentinel(text: str, sentinel: str) -> str:
    if not isinstance(text, str):
        return text
    idx = text.find(sentinel)
    if idx != -1:
        return text[idx + len(sentinel) :].strip()
    return text

In [131]:
PROMPT = "Разберете големите новини от последното денонощие накуп Запиши се"

mask = (df["source"] == "24chasa") & df["full_text"].str.contains(PROMPT, na=False)
print(f"Cleaning {mask.sum()} 24chasa articles with newsletter prompt")

df = apply_to_source(
    df,
    lambda t: (
        strip_before_sentinel(t, PROMPT)
        if isinstance(t, str) and PROMPT in re.sub(r"\s+", " ", t)
        else t
    ),
    source="24chasa",
)

Cleaning 675 24chasa articles with newsletter prompt

In [132]:
df = apply_to_source(df, lambda t: drop_lines(t, is_noise_line), source="24chasa")

In [133]:
def drop_phrase(text: str, phrases: list[str]) -> str:
    if not isinstance(text, str):
        return text
    for phrase in phrases:
        text = text.replace(phrase, "")
    return text.strip()

In [134]:
PHRASES = [
    '"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп',
]

mask = (df["source"] == "24chasa") & df["full_text"].apply(
    lambda t: any(p in t for p in PHRASES) if isinstance(t, str) else False
)
print(f"Records affected: {mask.sum()}\n")

for _, row in df[mask].iterrows():
    print(f"--- {row['title']} ---")
    print_by_words(row["full_text"])
    print()

Records affected: 252

--- Спорт по телевизията днес ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Последвайте ни в Google News Showcase Здравейте, благодарим
Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите
пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим
ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Само в "24 часа" на 9 юни: Най-пълният кандидат-студентски справочник ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Само в "24 часа" на 9 юни: Специални
страници с най-пълния справочник за кандидат-студентите Защо в България имаме най-високата инфлация в ЕС - анализ на икономиста Георги Ангелов
София опитва да си върне шест вкусни имота в Борисовата градина Вижте първите страници на "24 часа" от 9 юни
през годините до днес. Заглавията са интересни - спомнете си през какво преминаваше България. И сюжети, които обясняват защо сме
там, където сме.

--- Движението в тунел "Топли дол" към Варна бе в активната лента заради разлято гориво ---
Временно движението в тунел "Топли дол" на АМ "Хемус" в посока Варна се осъществява в активната лента поради разлято гориво
на пътното платно, съобщиха от АПИ. Трафикът се регулира от "Пътна полиция". По-късно движението бе възстановено. "24 часа" в мейла
ти. Разберете големите новини от последното денонощие накуп Временно движението в тунел "Топли дол" на АМ "Хемус" в посока Варна
се осъществява в активната лента поради разлято гориво на пътното платно, съобщиха от АПИ. Трафикът се регулира от "Пътна полиция".
По-късно движението бе възстановено. Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да
Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да
персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на
"24 часа"

--- Катастрофа при км 183 от пътя Казанлък - Габрово, движението е в една лента ---
Временно движението при км 183 по път I-5 Казанлък - Габрово се осъществява двупосочно в една лента поради ПТП, съобщиха
от АПИ. Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция". "24 часа"
в мейла ти. Разберете големите новини от последното денонощие накуп Временно движението при км 183 по път I-5 Казанлък -
Габрово се осъществява двупосочно в една лента поради ПТП, съобщиха от АПИ. Шофьорите да се движат с повишено внимание и
съобразена скорост. Трафикът се регулира от "Пътна полиция". Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24
часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива
на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте!
Изтеглете новото приложение на "24 часа"

--- Магия - виж оживялата карикатура на Ивайло Нинов ---
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. "24 часа" в мейла ти. Разберете големите новини от последното денонощие
накуп Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед
към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че
четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп
до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че
се включихте! Изтеглете новото приложение на "24 часа"

--- Катастрофа затвори пътя Казанлък - Габрово ---
Временно е ограничено движението при км 183 по път I-5 Казанлък - Габрово поради ПТП, съобщиха от АПИ. Шофьорите изчакват
на място. "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Временно е ограничено движението при км
183 по път I-5 Казанлък - Габрово поради ПТП, съобщиха от АПИ. Шофьорите изчакват на място. Последвайте ни в Google
News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24
часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия
нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Резултати от контроли ---
Хърватия - Словения 2:1 Мароко - Норвегия 1:1 Гърция - Италия 0:1 Еквадор - Гватемала 3:0 Косово - Андора 3:0
Лихтенщайн - Кипър 0:2 "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Хърватия - Словения 2:1
Мароко - Норвегия 1:1 Гърция - Италия 0:1 Еквадор - Гватемала 3:0 Косово - Андора 3:0 Лихтенщайн - Кипър 0:2
Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се
регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете
и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Спорт по телевизията днес ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Последвайте ни в Google News Showcase Здравейте, благодарим
Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите
пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим
ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Резултати от контроли преди световното ---
Бразилия - Египет 2:1 Венецуела - Турция 1:2 Аржентина - Хондурас 2:0 Кюрасао - Аруба 4:0 Шотландия - Боливия 4:0
Англия - Нова Зеландия 1:0 Кабо Верде - Бермуда 3:0 Ямайка - РЮА 0:1 "24 часа" в мейла ти. Разберете
големите новини от последното денонощие накуп Бразилия - Египет 2:1 Венецуела - Турция 1:2 Аржентина - Хондурас 2:0 Кюрасао -
Аруба 4:0 Шотландия - Боливия 4:0 Англия - Нова Зеландия 1:0 Кабо Верде - Бермуда 3:0 Ямайка - РЮА 0:1
Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се
регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете
и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Спорт по телевизията днес ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Последвайте ни в Google News Showcase Здравейте, благодарим
Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите
пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим
ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- А кога ще махнем “Аз съм българче” от читанката? ---
Прогресивните глупости на депутати удавиха това, което трябваше да чуем от премиера Румен Радев и финансовия министър Гълъб Донев. Вижте
още във видеозавещанието на седмицата "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Прогресивните глупости на
депутати удавиха това, което трябваше да чуем от премиера Румен Радев и финансовия министър Гълъб Донев. Вижте още във видеозавещанието
на седмицата Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим
да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините,
които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Възстановено е движението в участъка от Божан до разклона за Попгруево ---
Възстановено е движението по пътя Iв участъка от село Божан до разклона за Попгруево в община Тервел, съобщиха ог АПИ.
Той беше затворен заради почистване на кална маса, камъни и наноси след падналия снощи дъжд. "24 часа" в мейла ти.
Разберете големите новини от последното денонощие накуп Възстановено е движението по пътя Iв участъка от село Божан до разклона за
Попгруево в община Тервел, съобщиха ог АПИ. Той беше затворен заради почистване на кална маса, камъни и наноси след падналия
снощи дъжд. Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим
да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините,
които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Катастрофа при км 267 на "Тракия" към Бургас, движението е в изпреварващата лента ---
Движението при км 267 на АМ "Тракия" в посока Бургас се осъществява в изпреварващата лента поради ПТП, съобщават от АПИ.
Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция". "24 часа" в мейла
ти. Разберете големите новини от последното денонощие накуп Движението при км 267 на АМ "Тракия" в посока Бургас се осъществява
в изпреварващата лента поради ПТП, съобщават от АПИ. Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се
регулира от "Пътна полиция". Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да
Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да
персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на
"24 часа"

--- От 4 екрана Любен Дилов гледа как стотици се прощават с него ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп От четири екрана писателят и журналист Любен Дилов
гледа как близки и познати се прощават с него в столичния храм "Света София". Те са поставени на площад "Александър
Невски" и излъчват негови изказвания и интервюта. На поклонението му дойдоха колеги и опоненти, бивши председатели на Народното събрание и
културни министри. Те се извиха на опашка пред столичния храм "Света София", за да се простят с Дилов, който почина
във вторник сутринта в правителствена болница след като месец по-рано получи масивен инфаркт в Италия. Поклонението започна в 15 часа,
като сред първите пристигнали бяха колегите му депутати от ГЕРБ. Сред тях бяха съпредседателите на партията Томислав Дончев и Даниел
Митов. Присъстваха и двама бивши председатели на Народното събрание - Рая Назарян и Вежди Рашидов. Като депутат Дилов беше от
малкото, уважавани от всички. Никога не нагруби никого от трибуната, а след новината, че си е отишъл, добра дума за
него казаха добри и опонентите му. Днес на поклонението му дойдоха и представители на ДПС - Халил Летифов и Станислав
Анастасов, както и от ИТН - Тошко Йорданов, Павела Митова, Драгомир Петров и бившият регионален министър Гроздан Караджов. Дойдоха и
издателят на "24 часа" Венелина Гочева и шефът на отдел "Политика" Елица Гилтяй. Очаквайте подробности!

--- Спорт по телевизията днес ---
НА ЖИВО: Пленарно заседание на 52-ото Народно събрание "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп
Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се
регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете
и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Франция падна 1:2 от Кот д'Ивоар в Нант, Испания - Ирак 1:1 (резултати от контроли) ---
Франция - Кот д'Ивоар 1:2 Испания - Ирак 1:1 Швеция - Гърция 2:2 Иран - Мали 2:2 Словения - Кипър
1:1 Андора - Лихтенщайн 2:0 "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Франция - Кот
д'Ивоар 1:2 Испания - Ирак 1:1 Швеция - Гърция 2:2 Иран - Мали 2:2 Словения - Кипър 1:1 Андора -
Лихтенщайн 2:0 Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим
да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините,
които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Само в "24 часа" на 4 юни: Ученици бъркат "автор" с "авторитет" – гради се с лайкове, пада като батерия на телефон ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Само в "24 часа" на 4 юни четете:
Ученици бъркат "автор" с "авторитет" – гради се с лайкове, пада като батерия на телефон Замразяване на заплати и харчове
може да свие дефицит от 9 млрд. евро Над 300 експоната описват жената преди 8000 г. BG-Alert да дава и
съвети за оцеляване, не само да предупреждава за бедствия - интервю с Красимир Димитров, шеф на дирекция "Аварийна помощ и
превенция" в Столичната община Вижте първите страници на "24 часа" от 4 юни през годините до днес. Заглавията са интересни
- спомнете си през какво преминаваше България. И сюжети, които обясняват защо сме там, където сме.

--- Резултати от контроли ---
Нидерландия - Алжир 0:1 ДР Конго - Дания 0:0 Албания - Израел 0:1 Люксембург - Италия 0:1 Полша - Нигерия
2:2 Хаити - Нова Зеландия 4:0 "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Нидерландия -
Алжир 0:1 ДР Конго - Дания 0:0 Албания - Израел 0:1 Люксембург - Италия 0:1 Полша - Нигерия 2:2 Хаити
- Нова Зеландия 4:0 Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да
Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да
персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на
"24 часа"

--- Кой и защо плаче в парламента - виж оживялата карикатура на Ивайло Нинов ---
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. "24 часа" в мейла ти. Разберете големите новини от последното денонощие
накуп Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед
към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Последвайте ни в Google News Showcase Здравейте, благодарим Ви, че
четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите пълен достъп
до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че
се включихте! Изтеглете новото приложение на "24 часа"

--- Вижте многото лица на Любен Дилов (Галерия) ---
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Разнолика и много цветна е биографията на Любен
Дилов-син. Публицистът, журналист и политик почина днес на 61-годишна възраст след тежък инфаркт, който го покоси по време на екскурзия
със семейството му в Италия. Любен Дилов-син е завършил журналистическия факултет на СУ, работил е във вестниците "Поглед" и АБВ.
Бил е главен редактор на в. "Ку-ку", "Експрес" и "Новинар" (чийто съсобственик бе), на списанията "Плейбой" и L'Europeo (на което
е издател и към момента). Сред идеолозите и създателите, а също и главен сценарист на "Ку-ку", "Каналето", "Хъшове", "Шоуто на
Слави". Сценарист и на филма "Ла донна е мобиле" и главен сценарист на тв сериала "7 часа разлика". както и
на още куп продукции. Създател и дълги години председател на "Движение Гергьовден", бе общински съветник от партията в София, както
и народен представител в 40-ото НС. А от 45-ия парламент насам е депутат в коалицията ГЕРБ-СДС. Баща е на три
деца и дядо на двама внуци. А негов баща е световно признатият писател фантаст Любен Дилов. Вижте някои от многото
лица на Любен Дилов в архивите на "24 часа".

--- Блъснаха велосипедист в Карлово ---
Велосипедист е бил блъснат тази сутрин в близост до бул. "Освобождение" в Карлово. Инцидентът е станал в 7,10 часа. Колоездачът
е откаран в болница. 9 са катастрофите в страната от началото на денонощието, при тях са ранени общо 4-ма души.
"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Велосипедист е бил блъснат тази сутрин в близост
до бул. "Освобождение" в Карлово. Инцидентът е станал в 7,10 часа. Колоездачът е откаран в болница. 9 са катастрофите в
страната от началото на денонощието, при тях са ранени общо 4-ма души. Последвайте ни в Google News Showcase Здравейте, благодарим
Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите
пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим
ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Ракетата-носител „Чанджън 12B Y1“ извърши успешно първия си изпитателен полет ---
На 1 юни в 16:40 часа пекинско време бе изстреляна успешно ракетата-носител „Чанджън 12B Y1", пише КМГ. Това бе първият
ѝ изпитателен полет. С нея бяха изведени в полярна орбита спътници от осмата група „Цянфън". "24 часа" в мейла ти.
Разберете големите новини от последното денонощие накуп На 1 юни в 16:40 часа пекинско време бе изстреляна успешно ракетата-носител „Чанджън
12B Y1", пише КМГ. Това бе първият ѝ изпитателен полет. С нея бяха изведени в полярна орбита спътници от осмата
група „Цянфън". Последвайте ни в Google News Showcase Това съдържание е подготвено от журналисти на Китайската медийна група. Здравейте, благодарим
Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24 часа", за да получите
пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим
ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Възстановиха движението на магистрала "Тракия" в посока Бургас ---
Възстановено е движението при км 154 на АМ "Тракия" в посока Бургас, съобщиха от АПИ. То беше ограничено по-рано днес
заради катастрофа. "24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп Възстановено е движението при км 154
на АМ "Тракия" в посока Бургас, съобщиха от АПИ. То беше ограничено по-рано днес заради катастрофа. Последвайте ни в Google
News Showcase Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се регистрирате безплатно в "24
часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете и абонамент за нашия
нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Охрана и отбрана на бюджета - виж оживялата карикатура на Ивайло Нинов ---
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. "24 часа" в мейла ти. Разберете големите новини от последното денонощие

In [135]:
df = apply_to_source(df, lambda t: drop_phrase(t, PHRASES), source="24chasa")

In [136]:
phrase = "Последвайте ни в Google News Showcase"

mask = (df["source"] == "24chasa") & df["full_text"].str.contains(phrase, na=False)
print(f"Articles containing phrase: {mask.sum()}\n")

at_end = 0
not_at_end = 0

for _, row in df[mask].iterrows():
    text = row["full_text"]
    count = text.count(phrase)
    idx = text.find(phrase)
    total_len = len(text)
    position_pct = idx / total_len * 100
    remaining_words = len(text[idx + len(phrase) :].strip().split())

    if remaining_words <= 56:
        at_end += 1
    else:
        not_at_end += 1
        print(f"--- {row['title']} ---")
        print(
            f"Appears {count}x | Position: {position_pct:.0f}% into text | {remaining_words} words after"
        )
        print_by_words(row["full_text"])
        print()

print(f"\nAt end of text  : {at_end}")
print(f"Not at end      : {not_at_end}")

Articles containing phrase: 300

--- Ракетата-носител „Чанджън 12B Y1“ извърши успешно първия си изпитателен полет ---
Appears 1x | Position: 49% into text | 62 words after
На 1 юни в 16:40 часа пекинско време бе изстреляна успешно ракетата-носител „Чанджън 12B Y1", пише КМГ. Това бе първият
ѝ изпитателен полет. С нея бяха изведени в полярна орбита спътници от осмата група „Цянфън". На 1 юни в 16:40
часа пекинско време бе изстреляна успешно ракетата-носител „Чанджън 12B Y1", пише КМГ. Това бе първият ѝ изпитателен полет. С нея
бяха изведени в полярна орбита спътници от осмата група „Цянфън". Последвайте ни в Google News Showcase Това съдържание е подготвено
от журналисти на Китайската медийна група. Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим да се
регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините, които четете
и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"

--- Как един билет може да задвижи голямо потребление? ---
Appears 1x | Position: 41% into text | 62 words after
След концерт, мач или изложение, изхвърляте ли веднага билета си? Ако сте в Китай и правите така, всъщност губите много...
Вижте повече във видеото на КМГ. След концерт, мач или изложение, изхвърляте ли веднага билета си? Ако сте в Китай
и правите така, всъщност губите много... Вижте повече във видеото на КМГ. Последвайте ни в Google News Showcase Това съдържание
е подготвено от журналисти на Китайската медийна група. Здравейте, благодарим Ви, че четете "24 часа" редовно! Искаме да Ви поканим
да се регистрирате безплатно в "24 часа", за да получите пълен достъп до архива на сайта, възможност да персонализирате новините,
които четете и абонамент за нашия нюзлетър. Благодарим ви! Благодарим ви, че се включихте! Изтеглете новото приложение на "24 часа"


At end of text  : 298
Not at end      : 2

In [137]:
df = apply_to_source(
    df,
    lambda t: truncate_at_sentinel(t, ["Последвайте ни в Google News Showcase"]),
    source="24chasa",
)

**Finding:** After thorough analysis, `Последвайте ни в Google News Showcase` followed by a newsletter/app subscription prompt was found to always appear at the end of the article text — it is an advertising/subscription block injected by the site, never part of the actual content.

**Decision:** Truncate everything from this phrase onwards.

In [138]:
df = drop_by_field(df, ["Спорт по телевизията днес"], field="title", source="24chasa")

Dropping 45 articles where title startswith ['Спорт по телевизията днес']
Remaining articles: 50412

In [139]:
short_mask = (df["source"] == "24chasa") & (df["word_count"] < 40)
print(f"24chasa articles under 30 words: {short_mask.sum()}\n")

for _, row in df[short_mask].iterrows():
    print(f"--- {row['title']} ({row['word_count']} words) ---")
    print(row["url"])
    print(row["full_text"])
    print()

24chasa articles under 30 words: 33

--- Ренета Колева става зам.-екоминистър (36 words) ---
https://www.24chasa.bg/bulgaria/article/23002946
Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на околната среда и водите е назначена Ренета Георгиева Колева.
Това съобщиха от правителствената пресслужба. Другият зам.-екоминистър е Костадин Гешев, който бе назначен в края на май.

--- Верижна катастрофа затвори пътя София-Варна край Лясковец (38 words) ---
https://www.24chasa.bg/bulgaria/article/22994997
Временно е затворен главен път София -Варна, в района на разклона за Лясковец, заради катастрофа. Автомобилите се пренасочват през с. Козаревец. Това съобщи ОДМВР - Велико Търново.
По първоначални данни са се ударили три леки автомобила, има пострадали.

--- Южна Корея номинира жена за премиер за пръв път от 20 г. (38 words) ---
https://www.24chasa.bg/mezhdunarodni/article/22993851
Южнокорейският президент И Дже-мьон избра Хан Сонгсук, министър на малките и средните предприятия и стартиращите фирми, за министър-председател, съобщи президентската канцелария, предаде Ройтерс.
Хан ще бъде първата жена министър-председател на Южна Корея от 20 години насам, припомня БТА.

--- "Казанлък рестарт" - изтегли приложението от тук (31 words) ---
https://www.24chasa.bg/bulgaria/article/22982655
"Казанлък рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Горна Оряховица Рестарт" - изтегли приложението от тук
"Пирин Рестарт" - изтегли приложението от тук

--- Пожар гори в заведение в Слънчев бряг, евакуират туристи от хотел (Видео) (38 words) ---
https://www.24chasa.bg/bulgaria/article/22969644
Пожар гори в заведение в курорта Слънчев бряг, съобщи БТА. Евакуирани са всички туристи и персонал от намиращия се в непосредствена близост хотел „Тиара бийч“, казаха от полицията на място.
Районът е отцепен. Огъня гасят два противопожарни автомобила.

--- САЩ: Прехванахме две ирански ракети, насочени към база в Кувейт (39 words) ---
https://www.24chasa.bg/mezhdunarodni/article/22958031
Американските въоръжени сили са прехванали две ирански балистични ракети, насочени към американски военни обекти в Кувейт, съобщи Централното командване на САЩ (CENTCOM), цитирано от Ройтерс и БТА.
От американското военно командване уточниха, че няма данни за пострадали американски военнослужещи.

--- "Горна Оряховица Рестарт" - изтегли приложението от тук (34 words) ---
https://www.24chasa.bg/bulgaria/article/22938058
"Горна Оряховица Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Пазарджик Рестарт" - изтегли от тук безплатно приложението
"Елена Рестарт" - изтегли приложението от тук
НА ЖИВО

--- Катастрофа под дъжда на столичен булевард предизвика огромно задръстване (Видео) (38 words) ---
https://www.24chasa.bg/bulgaria/article/22911071
Проливният дъжд, излял се над столицата в късния следобяд, предизвика автомобилна катастрофа на бул. "Михаил Еминеску" в посока Телевизионната кула, информира потребител във фейсбук групата "Катастрофи в София".
Сблъсъкът предизвика огромно задръстване, както става ясно от публикуваните кадри.

--- Временно движението при км 35 на АМ „Хемус" в посока Варна е само в аварийната лента (38 words) ---
https://www.24chasa.bg/spravochnik/article/22904535
Временно движението при км 35 на АМ „Хемус" в посока Варна се осъществява само в аварийната лента поради пътно-транспортно произшествие, съобщиха от АПИ. Трафикът в активната и изпреварващата лента е ограничен, като движението се регулира от „Пътна полиция".

--- "Пирин Рестарт" - изтегли приложението от тук (30 words) ---
https://www.24chasa.bg/bulgaria/article/22896192
"Пирин Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Елена Рестарт" - изтегли приложението от тук
"Търговище Рестарт" - изтегли приложението от тук

--- Емил Ганчев и Венцислав Катинов са новите зам.-министри на вътрешните работи (37 words) ---
https://www.24chasa.bg/bulgaria/article/22894644
Със заповед на министър-председателя Румен Радев са назначени трима нови заместник-министри.
В Министерството на вътрешните работи поста заместник-министър поемат Емил Ганчев Ганчев и Венцислав Янков Катинов.
Юлия Кирилова Тодорова е назначена за заместник-министър на младежта и спорта.

--- Радев назначи още двама нови зам.-министри - на правосъдието и образованието (32 words) ---
https://www.24chasa.bg/bulgaria/article/22894149
Със заповед на министър-председателя Румен Радев са назначени нови двама заместник-министри.
Станимир Христов Станев е назначен за заместник-министър на правосъдието.
В Министерството на образованието и науката поста заместник-министър поема Сеня Петрова Терзиева-Желязкова.

--- "Пазарджик Рестарт" - изтегли от тук безплатно приложението (33 words) ---
https://www.24chasa.bg/bulgaria/article/22889587
"Пазарджик Рестарт" - изтегли от тук безплатно приложението
Специален проект
Четете още
"Търговище Рестарт" - изтегли приложението от тук
"Габрово Рестарт" - изтегли приложението от тук
НА ЖИВО

--- На 21 май рожден ден имат (35 words) ---
https://www.24chasa.bg/spravochnik/article/22888169
Весела Кюлева-Станкова, собственик на интерхотел “Сандански”
Проф. Кирил Топалов, писател, преводач, педагог, литературен историк и критик, дипломат
Доц. д-р Цветозар Томов, социолог
Д-р Мариета Челебиева, началник на лаборатория по микробиология в УМБАЛ “Софиямед”
Галена, фолкпевица

--- Камион блъсна велосипедист в Свищов, колоездачът е в тежко състояние (39 words) ---
https://www.24chasa.bg/bulgaria/article/22885403
Товарен автомобил е блъснал велосипедист. Произшествието е станало около обяд в Свищов, съобщи ОДМВР -Велико Търново.
По първоначална информация е пострадал колоездачът. Той е транспортиран в болнично заведение, в тежко състояние.
Причините за произшествието са в процес на изясняване.

--- "Елена Рестарт" - изтегли приложението от тук (32 words) ---
https://www.24chasa.bg/bulgaria/article/22882982
"Елена Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Габрово Рестарт" - изтегли приложението от тук
"Шумен Рестарт" - изтегли приложението от тук
НА ЖИВО

--- На 18 май рожден ден имат (34 words) ---
https://www.24chasa.bg/spravochnik/article/22867206
Димитър Николов, кмет на Бургас
Ивет Лалова, европейска шампионка по лека атлетика
Проф. Атанас Славчев, пианист
Калина Константинова, бивш заместник министър-председател по ефективното управление, бивш депутат
Петър Дочев, актьор и водещ на “Преди обед”

--- Катастрофа затрудни движението по „Хемус“ (38 words) ---
https://www.24chasa.bg/spravochnik/article/22858228
Временно движението по автомагистрала "Хемус" при 9-и км в посока Варна се осъществява в изпреварващата лента, съобщиха от Агенция "Пътна инфраструктура".
Промяната на движението се налага заради самокатастрофирал тежкотоварен автомобил.
Трафикът се регулира от екип на "Пътна полиция".

--- Възстановено e движението по "Хемус" при 9-и км в посока Варна (34 words) ---
https://www.24chasa.bg/spravochnik/article/22858570
Възстановено е движението по автомагистрала „Хемус" при 9-и км в посока Варна, съобщиха от Агенция "Пътна инфраструктура"
По-рано от пътната агенция съобщиха, че движението там се осъществява в изпреварващата лента заради самокатастрофирал тежкотоварен автомобил.

--- "Търговище Рестарт" - изтегли приложението от тук (33 words) ---
https://www.24chasa.bg/bulgaria/article/22844051
"Търговище Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Шумен Рестарт" - изтегли приложението от тук
"Велико Търново Рестарт" - изтегли приложението от тук
НА ЖИВО

--- Словакия затвори граничните пунктове с Украйна (38 words) ---
https://www.24chasa.bg/mezhdunarodni/article/22842666
Словакия затвори граничните пунктове с Украйна днес следобед от съображения за сигурност до ново нареждане, съобщи Словашката финансова администрация, цитирана от предаде Ройтерс, цитирана от БТА.
Допълнителна информация за причините за това решение ведомството не предостави, посочи ТАСС.

--- "Габрово Рестарт" - изтегли приложението от тук (31 words) ---
https://www.24chasa.bg/bulgaria/article/22830573
"Габрово Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Велико Търново Рестарт" - изтегли приложението от тук
"Разград Рестарт" - изтегли приложението от тук

--- "Шумен Рестарт" - изтегли приложението от тук (30 words) ---
https://www.24chasa.bg/bulgaria/article/22822957
"Шумен Рестарт" - изтегли приложението от тук
Специален проект
Четете още
"Разград Рестарт" - изтегли приложението от тук
"Бургас Рестарт" - изтегли приложението от тук

--- Камион се вряза в мантинела на АМ „Тракия“ в посока Бургас (38 words) ---
https://www.24chasa.bg/bulgaria/article/22822184
ТИР се е врязал в мантинелата при 41-ия км на АМ "Тракия" в посока Бургас.
Заради инцидента се образува километрично задръстване със стотици автомобили. По предварителна информация шофьорът на тежкотоварния камион е без наранявания, съобщава Bulgaria ON AIR.

--- Временно е ограничено движението в активната лента на АМ "Хемус" в тунел "Топли дол" (посока София) (38 words) ---
https://www.24chasa.bg/spravochnik/article/22788577
Временно е ограничено движението в активната лента на АМ „Хемус" в тунел „Топли дол" (посока София) поради аварийни ремонтни дейности на асфалтовата настилка, съобщават от АПИ. Трафикът се осъществява в изпреварващата лента. Участъкът е сигнализиран с пътни знаци.

--- Заради катастрофа при км 28 на "Тракия" към София бе спряно движението в едната лента (39 words) ---
https://www.24chasa.bg/spravochnik/article/22758141
Временно бе ограничено движението по изпреварващата лента при км 28 на АМ "Тракия" в посока София поради ПТП, съобщиха от АПИ.
Трафикът се осъществява в активната и аварийната лента и се регулира от пътна полиция.
По-късно движението бе възстановено.

--- Почина режисьорът Димитър Аврамов – един от създателите на "Всяка неделя" (38 words) ---
https://www.24chasa.bg/bulgaria/article/22758532
Почина Димитър Аврамов, дългогодишен главен режисьор в Българската национална телевизия.
Той е един от създателите на легендарното предаване "Всяка неделя", автор на множество документални и игрални филми и сериали с престижни български и международни отличия, съобщиха от БНТ.

--- Две партии в Румъния внесоха вота на недоверие срещу правителството на Илие Боложан (34 words) ---
https://www.24chasa.bg/mezhdunarodni/article/22749043
Социалдемократическата партия и Алианс за обединение на румънците внесоха вот на недоверие срещу правителството на Илие Боложан.
Новината съобщи лидерът на АУР Джордже Симион на извънредна пресконференция, предавана на живо в кулоарите на парламента.

--- Катастрофа затруднява движението при км 75 на магистрала "Тракия" към София (37 words) ---
https://www.24chasa.bg/spravochnik/article/22742951
Временно движението при км 75 на АМ "Тракия", в посока София се осъществява в една лента поради катастрофа. Това съобщават от пресцентъра на Агенция "Пътна инфраструктура".
Ограничено е преминаването в активната лента. Трафикът се осъществява в изпреварващата.

--- На 27 април рожден ден имат (38 words) ---
https://www.24chasa.bg/spravochnik/article/22737142
Владимир Карамазов, актьор
Акад. Георги Милошев, геофизик
Александър Томов, бизнесмен, бивш президент на ЦСКА
Цветан Ценков, кмет на Видин
Радослав Лукаев, бивш тенисист и национален състезател
Проф. Веселин Василев, психолог
Ясен Козев, музикант, председател на УС на “Музикаутор”

--- На 25 април рожден ден имат (38 words) ---
https://www.24chasa.bg/spravochnik/article/22729174
Ицхак Финци, актьор
Проф. Маргарита Младенова, театрален режисьор, основател и директор на театър “Сфумато”
Васил Щонов, изпълнителен директор на ТЕЦ “КонтурГлобал Марица Изток 3”, бивш министър на икономиката и енергетиката
Проф. д.ик.н. Румен Георгиев, икономист
Румен Рачев, художник

--- Катастрофа затруднява движението през Прохода на републиката след Мишеморков хан (37 words) ---
https://www.24chasa.bg/bulgaria/article/22727542
Катастрофа временно ограничава движението по път II-55 Прохода на републиката, след Мишеморков хан, в посока Гурково. Това съобщават от пресцентъра на Агенция "Пътна инфраструктура".
Обходът за леките автомобили е през проход "Шипка". Тежкотоварните МПС изчакват на място.

--- Нас само ни нахапа, другите направо ги изяде - виж комикса на Ивайло Нинов (38 words) ---
https://www.24chasa.bg/mneniya/article/22708542
Затвори Четете още Малкия Иванчо казва какво се прави след края на изборния ден Малкият Иванчо се чуди: партиите купуват едно, кандидатите - друго

In [140]:
mask = df["title"].str.contains("изтегли приложението от тук", case=False, na=False)
print(f"Articles containing 'изтегли приложението от тук' in title: {mask.sum()}")

Articles containing 'изтегли приложението от тук' in title: 7

In [141]:
df = drop_by_field(df, ["изтегли приложението от тук"], field="title", match="contains")

Dropping 7 articles where title contains ['изтегли приложението от тук']
Remaining articles: 50405

In [142]:
df = apply_to_source(
    df,
    lambda t: drop_lines(t, lambda line: line.strip().lower().startswith("Снимка:")),
    source="24chasa",
)

In [143]:
mask = df["title"].str.startswith('"24 часа" на', na=False)
print(f'Articles containing "24 часа" на in title: {mask.sum()}\n')

for _, row in df[mask].iterrows():
    print(f"--- {row['title']} ---")
    print_by_words(row["full_text"])
    print()

Articles containing "24 часа" на in title: 2

--- "24 часа" на 16 май: Не, не е чудо, което те прави красив и млад – опасно е! ---
Само в "24 часа" на 16 май четете: Не, не е чудо, което те прави красив и млад – опасно
е! Тренд с пептиди превзе социалните мрежи, инфлуенсъри не просто рекламират неодобрените субстанции – продават ги през профилите си, регулации
няма - съботен очерк. Бангаранга е! Дайте й трофея вече! Дара излиза 12-а във финала на "Евровизия" "Врана" в короната
- неразказаната история на царския дворец А Слави можеше да стане депутат още 1994-а - 5-те удара, след които Трифонов
пак стърчи. А след шестия? Вижте първите страници на "24 часа" от 16 май през годините до днес. Заглавията са
интересни - спомнете си през какво преминаваше България. И сюжети, които обясняват защо сме там, където сме.

--- "24 часа" на 26 април - вижте първите страници през годините ---
Вижте първите страници на "24 часа" от 26 април през годините до днес. Заглавията са интересни - спомнете си през
какво преминаваше България. И сюжети, които обясняват защо сме там, където сме.

In [144]:
mask = df["title"].str.startswith(
    (
        "Вижте отговора на фотозагадката:",
        "Фотозагадка:",
        "Виж отговора на фотозагадката:",
    ),
    na=False,
)
print(f"Articles: {mask.sum()}")

Articles: 12

In [145]:
df = drop_by_field(
    df,
    ['"24 часа" на 26 април'],
    field="title",
    match="contains",
)

Dropping 1 articles where title contains ['"24 часа" на 26 април']
Remaining articles: 50404

In [146]:
df = drop_by_field(
    df,
    [
        "Вижте отговора на фотозагадката:",
        "Фотозагадка:",
        "Виж отговора на фотозагадката:",
    ],
    field="title",
    match="startswith",
)

Dropping 12 articles where title startswith ['Вижте отговора на фотозагадката:', 'Фотозагадка:', 'Виж отговора на фотозагадката:']
Remaining articles: 50392

In [147]:
mask = df["full_text"].str.contains("Малкия Иванчо", na=False)
print(f"Articles containing 'Малкия Иванчо': {mask.sum()}\n")

for _, row in df[mask].iterrows():
    print(f"--- {row['source']} | {row['title']} ---")
    print(row["url"])
    print_by_words(row["full_text"])
    print()

Articles containing 'Малкия Иванчо': 18

--- 24chasa | Магия - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22999378
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Кой и защо плаче в парламента - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22973480
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Охрана и отбрана на бюджета - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22956028
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Защо се качват цените - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22942420
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Пенсиите се вдигат - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22932572
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. НА ЖИВО: Пленарно заседание на 52-ото Народно събрание Анимация карикатура на
седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от
Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Иво Христов и чувствата му към Евровизия - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22913150
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Отпаднала необходимост - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22896588
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Правителството бори цените - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22882492
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. НА ЖИВО: Пленарно заседание на 52-ото Народно събрание Анимация карикатура на
седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от
Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Как ще е успешно посещението на Радев в Бeрлин - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22870870
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Бюджетни неволи - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22853256
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Какво ще прави новата министърка във Външно - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22824579
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Смяна на позициите - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22808540
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Кой ще сваля охраната на политиците - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22799009
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Св. Румен убива ламята - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22792450
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Кой модел разградиха ПП-ДБ - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22775843
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Борбата с купуването на гласове продължава - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22743356
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | На кого вдига телефона главният секретар - виж оживялата карикатура на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22727689
Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов. Всяка седмица очаквайте нова карикатура с хумористичния поглед към
събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук. Анимация карикатура на седмицата от автора на "Малкия Иванчо" Ивайло Нинов.
Всяка седмица очаквайте нова карикатура с хумористичния поглед към събитията, представен от Ивайло Нинов. Останалите карикатури вижте тук.

--- 24chasa | Нас само ни нахапа, другите направо ги изяде - виж комикса на Ивайло Нинов ---
https://www.24chasa.bg/mneniya/article/22708542
Затвори Четете още Малкия Иванчо казва какво се прави след края на изборния ден Малкият Иванчо се чуди: партиите купуват
едно, кандидатите - друго

In [148]:
df = drop_by_field(
    df, ["Малкия Иванчо"], field="full_text", source="24chasa", match="contains"
)

Dropping 18 articles where full_text contains ['Малкия Иванчо']
Remaining articles: 50374

**Finding:** Articles containing `Малкия Иванчо` are comic strips — they consist of image captions and dialogue with no factual news content.

**Decision:** Dropped all such records as they provide no meaningful information for clustering or summarization.

In [149]:
for phrase in ["Четете още", "Снимка:"]:
    mask = (df["source"] == "24chasa") & df["full_text"].str.contains(phrase, na=False)
    print(f"'{phrase}': {mask.sum()} articles\n")
    for _, row in df[mask].head(3).iterrows():
        print(f"--- {row['title']} ---")
        print(f"URL: {row['url']}")
        print_by_words(row["full_text"])
        print()

'Четете още': 620 articles

--- Само в "24 часа" на 28 май: Проучване на "Тренд" за доверието към кабинета "Радев" ---
URL: https://www.24chasa.bg/mneniya/article/22929159
Само в "24 часа" на 28 май: - Румен Радев смени стила на премиера - действа по устав. Интервю с
политолога Димитър Ганев - Търсят 30 милиарда евро от сивата икономика. Не социални пенсии, а помощи ще пестят на НОИ
182 млн. - Минимални заплати според професията - ще се отчита инфлацията и производителността - София като Мадрид - картата
за градския транспорт вече в телефона - Проверка в ДАНС: защо е спряна екстрадицията на собственика на незаконния град край
Варна - Къде да заведем децата си на 1 юни Вижте първите страници на "24 часа" от 28 май през
годините до днес. Заглавията са интересни - спомнете си през какво преминаваше България. И сюжети, които обясняват защо сме там,
където сме. Четете още - Само в "24 часа" на 27 май: Рисковете от наводнения са описани, но не и
как се действа, ако ни залеят - Само в "24 часа" на 26 май: Поне 20 евро повече с кола
до морето, по-евтино с автобус и влак, но ако си сам - Само в "24 часа" на 25 май: Евтин
внос и бързата мода от Китай убиват шивашкия сектор у нас

--- "Пазарджик Рестарт" - изтегли от тук безплатно приложението ---
URL: https://www.24chasa.bg/bulgaria/article/22889587
"Пазарджик Рестарт" - изтегли от тук безплатно приложението Специален проект Четете още "Търговище Рестарт" - изтегли приложението от тук "Габрово
Рестарт" - изтегли приложението от тук НА ЖИВО

--- Цената на петрола на ОПЕК вече е под 97 долара за барел ---
URL: https://www.24chasa.bg/biznes/article/22713199
Цената на петрола на Организацията на страните износителки на петрол (ОПЕК) вчера се понижи за шеста поредна сесия - до
96,31 долара за барел, съобщи днес на страницата си петролният картел. Петролът на ОПЕК се котира под 97 долара за
барел за първи път от 6 март. Един барел петрол на ОПЕК се продаваше за 97,74 долара в понеделник. На
27 февруари, преди началото на войната на САЩ и Израел срещу Иран, петролът на ОПЕК се котираше за 70,07 долара
за барел. За определяне на цената на петрола на ОПЕК се използва т. нар. петролна кошница, включваща 12 сорта петрол
за износ на страните членки на картела: Сахаран бленд или "Сахарска смес" (Алжир), Джено (Конго), Зафиро (Екваториална Гвинея), Раби лек
(Габон), ирански тежък (Иран), Басра лек (Ирак), Кувейт експорт (Кувейт), Ес Сидер (Либия), Бони лек (Нигерия), Лек арабски (Саудитска Арабия),
Мурбан (ОАЕ) и Мерей (Венецуела). Историческият максимум за "кошницата на ОПЕК" е цената от 146,05 долара за барел, отчетена на
19 март 2026 година. Предишният максимум от 140,73 долара за барел бе достигнат на 3 юли 2008 година, припомня БТА.
Цената на барел петрол се определя чрез извеждане на средна аритметична величина от котировките към момента на закриване на търговията
с всички сортове от "кошницата на ОПЕК" предходния работен ден. Затвори Цената на петрола на ОПЕК падна под 97 долара
за барел Снимка: СНИМКА: Pixabay (илюстративна) Четете още Петролът на ОПЕК падна под 107 долара за барел ОПЕК понижи прогнозата
за световното търсене на суров петрол Ново поскъпване на петрола след заканата на Тръмп срещу Иран

'Снимка:': 265 articles

--- Жива салата и няколко капки маслиново масло  – лесен начин за невероятен вкус на трапезата ---
URL: https://www.24chasa.bg/biznes/article/22768660
Представете си салата, която продължава да расте дори след като я занесете вкъщи. Свежа, хрупкава и жива като на рафта
в супермаркета. Живата салата не е просто зеленчук на трапезата, това е нов начин да се насладите на свежестта такава,
каквато би била, ако я отглеждате в домашната градина. „Живата салата често е по-хрупкава и по-свежа от рязаната салата, защото
се пакетира заедно със своя развит корен. Поради начина й на отглеждане, тя успява по-добре да развие пълния си органолептичен
потенциал“, посочва Асен Багашев, управител на „Хепи Фрутс“. Целогодишно в супермаркети „Фантастико“ се предлагат около 7 вида салати, основно от
български производители, а сред тях има и такава с корен, популярни като „жива салата“. Тя се отглежда в хидропонна оранжерия,
което позволява да достигне до търговската верига с напълно запазен корен, разказват производителите. „Живата салата не е нужно да се
слага в хладилник. Тя може до седмица да остане свежа при стайна температура, без значение от относителната влага в помещението.
Полезен трик за грижата й след покупка е сходно с това, което човек прави при покупка на букет рози -
салатата да се сложи във вода, така че живият корен да продължи да запазва свежестта й“, посочват от компанията за
производство на плодове и зеленчуци. По този начин зелените листа ще красят кухнята дълго време, а след това ще бъдат
свежи и на трапезата. Години наред от „Хепи Фрутс“ успешно си партнират с „Фантастико“ и с течение на времето обогатяват
асортимента, който предлагат. „Първите предлагани видове бяха и най-неизвестните тогава за местния пазар - жива салата тип „Джентилина“. Впоследствие бяха
добавени живите салати тип „Мултиколор“ и тип „Копф” салата, които респективно имат атрактивен червен цвят с по-интересни органолептични качества и
свободна завита глава с по-мек вкус. От миналата година компанията започна предлагане и на масовата вече рязана къдрава зелена салата“,
допълва Асен Багашев, управител на „Хепи Фрутс“. От „Фантастико“ се стараят да отговорят на всеки вкус на клиентите целогодишно, но
с особен приоритет са пролетта и лятото, когато е най-активният период за салати през годината. „Развитието на тази категория показва,
че с богат асортимент и атрактивни цени успешно отговаряме на повишеното търсене в най-активния сезон за консумация на салати. Данните
показват, че салата „Айсберг“ е най-предпочитана сред нашите клиенти, следвана от традиционната зелена салата. С добър ръст в продажбите са
и живата салата „Джентилина“, „Копф” салата и био зелена салата“, споделя Рени Яврийска, директор „Клиентско преживяване и пазарни анализи” във
„Фантастико груп“. За да бъде още по-свежа салатата на трапезата, тя има нужда и от няколко капки маслиново масло. Във
„Фантастико“ клиентите могат да намерят 14 вида, зад които стоят дългогодишни традиции и внимание към суровината. Някои от тях се
предлагат не само на българския пазар, но и в десетки държави по света. „Спадът в средните цени на маслиновото масло
през последната година стимулира покупките и доведе до устойчив ръст в закупените количества през цялата 2025 г. и първото тримесечие
на 2026 г. Разширеното портфолио от нови продукти и предпочитани разфасовки от 1 л и 750 мл затвърждават интереса на
клиентите, особено през пролетно- летния сезон, когато се отчита двуцифрен ръст спрямо предходната година“, посочва Рени Яврийска, директор „Клиентско преживяване
и пазарни анализи“. Снимка: Амперел На рафтовете в търговската верига има разнообразие от маслинови масла - от такива, които са
подходящи за дресинг за салати, сосове и гарнитури, до такива, които са благоприятни за готвене, пържене и печене. „Екстра върджин
маслиновите масла Minerva и Terra Creta пристигат на трапезата от най-добрите производители в Гърция. Произвеждат се при условия, които запазват
уникалния вкус, изискания аромат и хранителните вещества на маслиновото масло. Те притежават отличителния интензивен аромат на прясно набрани маслини от
сорта Коронейки, ценени заради изключителния си вкус. Истинска хармония от плодови и горчиви нотки“, посочва Симона Божилова, продуктов мениджър в
категория „Маслинови масла“ в „Амперел“. Експертите често описват аромата на студено пресованото маслиново масло с нотки на прясно окосена трева,
зелени билки и понякога доматени листа. „Качественото гръцко маслиново масло има лека, приятна горчивина и пикантен завършек в гърлото, което
е знак за високо съдържание на антиоксиданти. Въпреки че е силно като аромат, гръцкото маслиново масло често се описва като
„по-меко и по-деликатно“ на небцето в сравнение с някои по-остри сортове от други региони“, допълват вносителите. Маслиновото масло е неразделна
част от средиземноморската кухня и култура, а днес то заема заслужено място и на родната трапеза. „Спирайки се на продукт
с марката Minerva, потребителите могат да бъдат спокойни за качеството, вкуса и ползите от маслиновото масло за своята трапеза и
за семейството си. В случай, че изберат Terra Creta клиентите ще получат продукт с изключителна свежест и ниска киселинност, награждавано
качество, пълна проследимост на производството, отличен вкусов профил и не на последно място - устойчивост и прозрачност с грижа за
околната среда“, споделя Симона Божилова от „Амперел“. Салатата да бъде свежа, а маслиновото масло внимателно подбрано - в супермаркети „Фантастико“
този избор е лесен, защото зад продуктите стоят отговорни производители, устойчиви практики и грижа към потребителите.

--- Ултрамаротонец преплува рекордните 55 км в пълна с крокодили река ---
URL: https://www.24chasa.bg/mezhdunarodni/article/22773975
Ултрамаратонец преплува рекордните 55 км в пълна с крокодили австралийска река. Анди Доналдсън завършва пътешествието в река Орд в Западна
Австралия за по-малко от 12 часа. Той и екипът му са били наясно с опасностите, които предстоят. Напомнил им го
е и огромен 2,5-метров сладководен крокодил, чакащ на стартовата рампа, пише "Гардиън". Доналдсън, британско-австралийски ултрамаратонски плувец, се е канил да
се впусне в 55-километровото предизвикателство от езерото Аргайл до Кунунура в Източен Кимбърли, надявайки се да стане първият човек, завършил
изтощителното плуване за издръжливост. Към трудността се добавя и фактът, че река Орд в отдалечена Западна Австралия е добре известна
със своите влечугоподобни обитатели. Популацията на сладководните крокодили наброява 5500 – по един крокодил на всеки 10 метра от плуването
му. „Беше просто вълшебно", казва Доналдсън. За щастие на 35-годишния плувец, сладководните крокодили са по-малки и по-плахи от своите соленоводни
събратя – най-големите влечуги в света – и е малко вероятно да се приближат до хора. Екипът на Доналдсън е
направил проучването си предварително и той никога не се е чувствал застрашен от дивата природа около него, която включва също
орли, рибарски скопи, котки, корморани, дартери, костенурки и големи сомове. „Беше малко изнервящо да плувам в открити води", каза Доналдсън.
„Винаги има риск от дивата природа. Но в същото време хората използват тази река всеки ден за развлечение. „Казват, че
„страхът е широк една миля и дълбок един инч" – възприеманият страх е много по-голям, отколкото всъщност се оказва. „Винаги
има лек прилив на адреналин, ако видите нещо, когато сте там, или ако докоснете някаква морска трева или нещо подобно,
но всъщност не видях нищо по време на плуването. Беше до голяма степен плуване по правилата. „Както винаги, безопасността е
на първо място. Не се излагаме умишлено на опасност. Ако има нещо, което изглежда заплашително, спираме, защото искаме да бъдем
умни и искаме да използваме тези предизвикателства, за да споделяме положителни послания, а не негативизъм и страх." Британско-австралийски атлет преплува
55 км в пълната с крокодили река Орд в Западна Австралия, за да постави световен рекорд – видео Британско-австралийски атлет
преплува 55 км в пълната с крокодили река Орд в Западна Австралия, за да постави световен рекорд – видео След
като успешно премина трасето и финишира пред стотици хора, наредени по бреговете на реката в Кунунура, той постигна рекордно време
от 11 часа и 51 минути, подобрявайки резултата, поставен от Симон Блейзър, която беше първият човек, завършил плуването с време
от 16 часа и 13 минути през 2024 г. – и беше част от екипа за поддръжка на Доналдсън във
вторник. Доналдсън каза, че е „на луната", че е завършил плуването. „Беше просто магическо – плуване през тези древни клисури,
червените скали, изгревът беше просто впечатляващ там", каза той. Гледка на Джоно Ридлър, плуващ в океана Делфини, жилещи риби и
„солен език": епично океанско плуване около Ню... Източното крайбрежие на Зеландия Прочетете още „Имах възможността да плувам на невероятни места
по целия свят, като Хавай, Гърция и Хърватия. Но бих казал без съмнение, че това е най-доброто плуване, което някога
съм правил. Това е най-красивото място за плуване, което някога съм преживявал. Беше просто невероятно." Започвайки по тъмно в 5:38
ч. сутринта, Доналдсън успя да наложи добро темпо в ранните часове на плуването си, докато палещото слънце над Кимбърли не
покачи живака до 34°C и не накара помощните лодки да се опитат да му осигурят сянка. Липсата на сол –
и следователно намалената плаваемост – в сладководните води допълнително усложнила нещата. „Особено когато започнете да се уморявате, бедрата ви увисват
и позицията на тялото ви не е толкова добра, така че се чувствате сякаш влачите краката си много повече", каза
той. Неочакван насрещен вятър и участък от „мъртва вода" – където няма течение – направиха нещата още по-трудни, но с
подкрепата на големия си екип той стигна до плажа Swim Beach, на 6 км от градчето Кунунура, до 17:29 ч.
Анди Доналдсън плува в река Орд до помощния си каяк и лодка Вижте изображението на цял екран Плувното предизвикателство „От
язовир до язовир" на Доналдсън добавя още един рекорд към името му. Снимка: Бен Броуди Докато се приближаваше към финалната
линия, местните плувци присъединиха се към него във водата за последните 200 метра. „Тези предизвикателства никога не се постигат сами",
каза той. „Винаги имате шкипер, гребец и треньор във водата, хора, които познават добре речните системи, така че сте в
сигурни ръце, можете да се ориентирате в тези трудни участъци. „Екипът, енергията и насърчението ви вдигат, когато започнете да се
колебаете."

--- Цената на петрола на ОПЕК вече е под 97 долара за барел ---
URL: https://www.24chasa.bg/biznes/article/22713199
Цената на петрола на Организацията на страните износителки на петрол (ОПЕК) вчера се понижи за шеста поредна сесия - до
96,31 долара за барел, съобщи днес на страницата си петролният картел. Петролът на ОПЕК се котира под 97 долара за
барел за първи път от 6 март. Един барел петрол на ОПЕК се продаваше за 97,74 долара в понеделник. На
27 февруари, преди началото на войната на САЩ и Израел срещу Иран, петролът на ОПЕК се котираше за 70,07 долара
за барел. За определяне на цената на петрола на ОПЕК се използва т. нар. петролна кошница, включваща 12 сорта петрол
за износ на страните членки на картела: Сахаран бленд или "Сахарска смес" (Алжир), Джено (Конго), Зафиро (Екваториална Гвинея), Раби лек
(Габон), ирански тежък (Иран), Басра лек (Ирак), Кувейт експорт (Кувейт), Ес Сидер (Либия), Бони лек (Нигерия), Лек арабски (Саудитска Арабия),
Мурбан (ОАЕ) и Мерей (Венецуела). Историческият максимум за "кошницата на ОПЕК" е цената от 146,05 долара за барел, отчетена на
19 март 2026 година. Предишният максимум от 140,73 долара за барел бе достигнат на 3 юли 2008 година, припомня БТА.
Цената на барел петрол се определя чрез извеждане на средна аритметична величина от котировките към момента на закриване на търговията
с всички сортове от "кошницата на ОПЕК" предходния работен ден. Затвори Цената на петрола на ОПЕК падна под 97 долара
за барел Снимка: СНИМКА: Pixabay (илюстративна) Четете още Петролът на ОПЕК падна под 107 долара за барел ОПЕК понижи прогнозата
за световното търсене на суров петрол Ново поскъпване на петрола след заканата на Тръмп срещу Иран

In [150]:
phrase_pattern = re.compile(r"\sЗатвори\s+[А-Я]")

In [151]:
mask = (df["source"] == "24chasa") & df["full_text"].str.contains(
    phrase_pattern, na=False
)
print(f"Articles containing 'Затвори' followed by uppercase: {mask.sum()}\n")

for _, row in df[mask].head(20).iterrows():
    match = phrase_pattern.search(row["full_text"])
    if match:
        idx = match.start()
        total_len = len(row["full_text"])
        position_pct = idx / total_len * 100
        after = row["full_text"][idx:].strip()
        print(f"--- {row['title']} ---")
        print(f"Position: {position_pct:.0f}% into text")
        print(f"{after[:200]}")
        print()

Articles containing 'Затвори' followed by uppercase: 619

--- Цената на петрола на ОПЕК вече е под 97 долара за барел ---
Position: 82% into text
Затвори Цената на петрола на ОПЕК падна под 97 долара за барел Снимка: СНИМКА: Pixabay (илюстративна) Четете още Петролът на ОПЕК падна под 107 долара за барел ОПЕК понижи прогнозата за световното тър

--- Сигнали за бомби са получени в училищата в Хърватия, Босна и Херцеговина и Черна гора ---
Position: 92% into text
Затвори Снимка: Снимка: Архив Четете още Сигнали за бомби в 4 училища в София Фалшиви сигнали за бомби опразниха училища в Черна гора и Босна и Херцеговина В училища в цяла Сърбия са получени заплахи

--- Изтребители се сблъскали в Южна Корея, защото пилотите им снимали ---
Position: 74% into text
Затвори Изтребител СНИМКА: Георги Кюрпанов - Генк (Снимката е илюстративна) Четете още Руски изтребител се разби при тренировъчен полет над Крим Румънски изтребител се разби по време на съвместно учен

--- Дeлът на китайските марки автомобили нa бългapcĸия пaзap ce e yвeличил над двa пъти ---
Position: 86% into text
Затвори Снимка: КМГ Снимка: Китайска медийна група Четете още КМГ: Стратегията „печеля-печелиш“ наистина се оказва печеливша КМГ: Международната общност трябва категорично да се противопоставя на нова

--- Агенцията по храните затвори кланици в Гергевец и Бяла Слатина ---
Position: 87% into text
Затвори Четете още БАБХ: Има риск месо от огнището с антракс в Силистренско да се разпространи Животни с антракс от село Черногор били транспортирани към кланица в Исперих Преработвали месо от умрели

--- АПИ уволняват служителя си, хванат да кара пиян ---
Position: 91% into text
Затвори Белезници СНИМКА: Pixabay Четете още Служител на АПИ карал пиян служебната си кола, било му втори път за седмица

--- Обвиниха шефката на тотото в Пловдив в натиск над подчинен да напусне, тя отрича ---
Position: 92% into text
Затвори Минка Сърнешка
Кадър: Фейсбук Четете още Човек припадна в РИК - Пловдив, линейка го отведе Изборите в Пловдив и областта тръгнаха, пред секциите кръжат полицаи Комисията за личните данни за ис

--- Мъж е задържан за отвличане в Ябланица ---
Position: 72% into text
Затвори Полиция Снимка: Георги Кюрпанов-Генк Четете още Отложиха делото за изнасилване срещу Ръсел Бранд за октомври Мъж от село Ковачица отвлече бившата си приятелка ГДБОП разби бруталната банда на Б

--- Ще почиват ли европейците у нас вместо в Дубай? ---
Position: 97% into text
Затвори Курортът Албена може да приеме в междинния сезон европейци, които не могат да реализират почивката си в Дубай.
СНИМКА: ГЕТИ Четете още Авиокомпании от цял свят вдигат цените на билетите заради

--- Нови финансови облекчения и социални мерки в Гърция ---
Position: 87% into text
Затвори Кириакос Мицотакис СНИМКА: Екс/Kyriakos Mitsotakis Четете още Мицотакис обявява пакет от 500 млн. евро за гражданите, подкрепен от икономическия „свръхизлишък" Монако и Гърция обединяват сили

--- Китай тържествено посрещна останките на мъчениците от Китайската народна доброволческа армия ---
Position: 66% into text
Затвори Снимка: КМГ Снимка: Китайска медийна група Четете още Дeлът на китайските марки автомобили нa бългapcĸия пaзap ce e yвeличил над двa пъти КМГ: Стратегията „печеля-печелиш“ наистина се оказва п

--- Бленджини обяви 31 волейболисти за националния на България ---
Position: 88% into text
Затвори Джанлоренцо Бленджини СНИМКА: ГЕОРГИ КЮРПАНОВ Четете още Босът на световния волейбол пред "24 часа": България вдъхновява целия свят, брат ми Любо Ганев ръководи процеса Българските волейболист

--- Белгия дава на Украйна 15 установки "Гепард" ---
Position: 77% into text
Затвори Снимка: СНИМКА: Pixabay (илюстративна) Четете още Премиерът на Белгия призова ЕС да преговаря с Русия за прекратяване на войната в Украйна Чехия няма да продава леки изтребители на Украйна Изм

--- За първи път в България: лектори от Anthropic идват на BASSCOM AI Conference ---
Position: 87% into text
Затвори Четете още Георги Шарков - министър на електронното управление - най-добрият експерт по киберсигурност Доц. Георги Шарков: Правим учения "Кибершок" - вървят атаки на Кремъл срещу Европа и чест

--- Илияна Йотова: Оставката на Сарафов трябваше да се случи отдавна ---
Position: 84% into text
Затвори Илияна Йотова Снимка: Георги Кюрпанов Четете още Коя е Ваня Стефанова - новият и.ф. главен прокурор Ваня Стефанова стана и.ф. главен прокурор Сарафов остана и.ф. главен прокурор 2 години и 10

--- DEVIN и фондация „Биоразнообразие“ създадоха първия в България наръчник за възстановяване и опазване на торфища ---
Position: 99% into text
Затвори Чаирски езера

--- Запрянов: Обучението на висококвалифицирани кадри е огромна отговорност не само към Българската армия, но и към обществото ---
Position: 93% into text
Затвори Атанас Запрянов Снимка: Министерство на отбраната Четете още Запрянов: Историческата памет за Априлското въстание има не само символно, но и практическо значение Атанас Запрянов посреща 76 г.

--- СОС реши: Четвърта градска болница се влива във Втора МБАЛ ---
Position: 90% into text
Затвори Зам.-председателят на здравната комисия към СОС Саад Алуани обяснява състоянието на Четвърта градска болница.
СНИМКА: ПРЕСЦЕНТЪР НА СОС Четете още Тази битка не свършва с изборите. Тя започва

--- 62-годишна почина, след като я блъсна товарен автомобил в село Вокил ---
Position: 68% into text
Затвори Полиция Снимка: Георги Кюрпанов-Генк Четете още Задържаха шофьорите на обърнатия автобус, двете загинали жени още са под него Две млади жени са ранени при катастрофа край Мадан Катастрофа зара

--- Саудитска Арабия дари на България 25 тона фурми ---
Position: 80% into text
Затвори Четете още Пловдивски полицаи иззеха 22 тона крадени фурми при спецакция, арестуваха 5-има

In [152]:
def truncate_at_pattern(text: str, pattern) -> str:
    if not isinstance(text, str):
        return text
    match = pattern.search(text)
    if match:
        return text[: match.start()].strip()
    return text

In [153]:
df = apply_to_source(
    df, lambda t: truncate_at_pattern(t, phrase_pattern), source="24chasa"
)

In [154]:
print_source_samples(df, "24chasa", n=3)

=== 24CHASA (12969 articles) ===

--- Спасителят на украинци край Малко Търново: Бетонна стена е спряла рейса, без нея нямаше да има оцелели ---
URL: https://www.24chasa.bg/bulgaria/article/22828636
- Единствената мисъл на граничния полицай Ивелин Арабаджиев, докато вадел хората от автобуса, била да не гръмне работещият двигател
- Преди 10 г. той помага на премръзнали мигранти, сред които и 3-годишни деца
Още един достоен българин влиза в редиците на кампанията на вестник "24 часа" - това е младши експерт Ивелин Арабаджиев, командир на отделение във Втора група за охрана на държавната граница в ГПУ-Малко Търново. На 22 април т.г. с риск за собствения си живот той спасява пътници от украински туристически автобус, който потегля неуправляемо на собствен ход и пропада в дере.
При инцидента загиват двама души, но жертвите вероятно щяха да са много повече, ако не бе намесата на младия граничен полицай.
За достойната си постъпка полицай Арабаджиев бе награден
от служебния министър на МВР Емил Дечев и от областния управител на Бургас Добромир Гюлев с почетен знак на МВР - трета степен.
На церемонията в столицата присъстваха изпълняващият длъжността главен секретар на МВР главен комисар Георги Кандев, директорът на ГД "Гранична полиция" главен комисар Антон Златанов, представители на политическото ръководство на МВР.
Буквално за часове граничният полицай Арабаджиев се превърна в медийна звезда, макар светлините на прожекторите да не са му слабост.
Пред "24 часа" той признава, че не е очаквал такъв медиен шум, но е удовлетворен от факта, че е оценен от ръководството на МВР, и то с най-високо отличие. Нещо, което мотивира и останалите му колеги.
"Познавам добре хората, с които работя. Бих казал, че
всички служители в ГПУ - Малко Търново, са отдадени на службата, стараят се, няма огъване
Като се каже, че ще действаме – правим го, не гоним час, работно време. Колективно действаме във всяка ситуация и началниците ни са винаги с нас и зад нас", казва граничният полицай.
След инцидента с украинския автобус Арабаджиев няколко пъти минава по маршрута, но едва на 10-ия ден след случая спира, за да огледа отново терена и да анализира ситуацията.
"Наклонът на пътя там, където стана инцидентът, е около 45 градуса. Има бетонна стена - като дренажна, с цел да не пропада настилката. Потегляйки назад, шасито на автобуса се опира в тази бетонна стена и по този начин не му позволява да тръгне надолу в дерето. Иначе нямаше да има оцелели", разсъждава младият полицай.
На 22 април по време на дежурство младши експерт Арабаджиев получава информация, че на около 2 км преди граничния пункт Малко Търново има спрял автобус, който пречи на движението. Полицаят отива на мястото и установява, че автобус с украинска регистрация е аварирал почти перпендикулярно на пътя, създавайки сериозна опасност за тежък инцидент.
От двамата шофьори разбира, че е свършило горивото и се наложило да заредят с туба от близка бензиностанция.
Със служебната кола и включени светлини Арабаджиев регулира
движението от и към ГКПП.
"Когато пристигнах, шофьорите бяха налели една туба гориво, имаше още две до автобуса. Рейсът беше аварирал през двете платна, колите го заобикаляха. В 6,50 ч при опит за стартиране двигателят запали и всички бяха радостни. Пред автобуса имаше 7-8 човека и първоначално помислих, че само това са пътниците, не знаех, че вътре има още. Всичките хора навън започнаха да се смеят, да ръкопляскат. И само
няколко секунди по-късно автобусът тръгна назад
Когато рейсът падна, едното дърво се прекърши, а по-дебелото задържа автобуса", разказва полицай Арабаджиев.
Той предава по радиостанцията какво се е случило и скача в дерето, чувайки писъците на хората. Успява да изкърти задния люк и започва да вади пътниците един по един. Вижда и двете жертви – пътнички, премазани под прозорците, които най-вероятно са спели в момента на ужасния инцидент.
"Когато погледнах в автобуса, видях, че е пълен. Вътре гледката беше потресаваща – хора, багаж, седалки. Всичко беше с главата надолу. Видях едната жертва, проверих я - не дишаше. Видях и другата загинала жена – тя беше под първата.
Започнах с жестове да указвам на хората да идват към мен,
двигателят все още работеше. По-слабите жени и деца ги вадех през рамо, но склонът беше много голям, даже след като свърши цялата офанзива и се прибрах, забелязах, че и кубинките ми са се скъсали.
На по-тежките им поемах краката и стъпвайки на мен, слизаха надолу. Последните 7-8 човека ги изкарахме с колегите от районното, които пристигнаха. Автобусът буквално се държеше на косъм. Но важното е, че успяхме да извадим всички, за да не стане по-голяма трагедия", разказва полицаят.
Единствената му мисъл, докато спасявал хората, била да не се запали автобусът, защото през първите 10-15 минути двигателят продължавал да работи. Чак след това, премисляйки станалото, си дал сметка, че е съществувала реална опасност и за неговия живот – дървото да не издържи и всички да полетят в дерето.
Най-много го боли, че никой от преминаващите автомобили не спира,
за да му помогне. Но си има и свое обяснение: "Работата на служителя с пагон непрекъснато ни сблъсква с различни ситуации. От чисто човешка гледна точка – бях на мястото, помогнах, направих каквото мога. Мисля, че всеки би трябвало да постъпи така".
На въпрос дали е действал по инструкция, или по сърце, отговаря: "Надали има такава инструкция, която описва как да се действа - трябва да си помагаме, да имаме големи сърца."
Оказва се, че не за пръв път спасява човешки животи. Преди 10 г. Арабаджиев е награден заедно с негови колеги отново за спасителна операция.
Министърът на вътрешните работи тогава награждава 9 служители на ГПУ - Малко Търново, защото на 6 февруари 2016 г. спасяват 17 мигранти от измръзване.
"Бях дневна смяна, в гората имаше около 60 см сняг. Първо открих двама нелегални мигранти, които с жестове показаха, че има още. След издирване намерих групата - беше буквално до българо-турската граница.
Имаше измръзнали деца, едно 15-годишно беше починало,
имаше още двама измръзнали. Бяха сирийци, около 15 души. Между тях имаше 4 деца на по 3-4 г. Тъй като не можеше да слезе техника в района, се наложи да изваждаме всички с носилки и одеяла. Първо изкарахме децата и две жени, транспортирахме ги до УМБАЛ - Бургас, с линейка и с наш транспорт", спомня си граничният полицай.
Докато тече спасителната операция, граничарите успяват да стоплят най-премръзналите в свой секретен пост близо до границата, в който бумтяла печка с дърва.
Да пази държавната граница, за 35-годишния полицай е мечта, към която се стреми от тийнейджър. А и е нещо, което го кара да се чувства на мястото си, защото е роден и израснал в Малко Търново. Познава и обича Странджа планина, където от дете е впечатлен от камуфлажните униформи и присъствието на граничните полицаи.
"Започнах кариерата си в ГПУ - Малко Търново, и така вече 12 години.
Не съжалявам за избора си, бих казал, че това е моето място, моята работа
Гордея се с това, че съм граничен полицай", казва командирът на отделение във Втора група за охрана на държавната граница в ГПУ - Малко Търново.
Но най-щастлива и горда със своя татко е 7-годишната му дъщеря Димана, която завършва първи клас.

--- Младежкият парламент организира лов на съкровища за празника на Русе ---
URL: https://www.24chasa.bg/bulgaria/article/22765263
За празника на Русе Младежкият парламент към Общинския младежки дом организира интерактивен лов на съкровище под наслов „Опознай Русе, за да го обикнеш". Събитието ще се проведе на 6 май с начален час 13:00 ч., като регистрацията ще започне на място пред Съдебната палата в 12:30 ч.
Инициативата е насочена към младите хора и всички граждани, които желаят да преоткрият красотата и богатата история на града чрез едно вълнуващо и различно преживяване.
Участниците ще имат възможност да се включат в отбори от двама до четирима души и да преминат през специално подготвен маршрут, който ще ги отведе из малки улички и по-слабо познати кътчета на Русе. По пътя те ще решават разнообразни задачи и предизвикателства, съчетаващи логика, ориентиране и екипна работа, като същевременно ще научават любопитни факти за града.
Организаторите призовават желаещите да пристигнат навреме, за да заявят участието си и да получат необходимите стартови материали. За най-бързо справилите се отбори са предвидени награди.

--- Един загинал и 36 ранени при взрив на сух док в Ню Йорк (Видео) ---
URL: https://www.24chasa.bg/mezhdunarodni/article/22902793
Взрив на сух док в Ню Йорк взе жертва и рани 36 души. Експлозията избухна, докато на място работеха пожарникари, отзовали се на повикване за пожар и опитвали да спасят двама блокирани, съобщиха властите, цитирани от Ройтерс и БТА.
Двама огнеборци са в болница. Единият от тях е с фрактура в областта на слепоочието и мозъчен кръвоизлив и е интубиран, допълниха властите. Състоянието на колегата му също е тежко, но е показало признаци на подобрение.
"Това беше сложна и доста динамична извънредна ситуация", коментира пред репортери кметът на Ню Йорк Зохран Мамдани. "Аварийно-спасителните служби опитаха да направят всичко по силите си. Те се втурнаха към опасността само и само други да успеят да се измъкнат в безопасност."
Властите не уточниха повече подробности за загиналия, освен че е цивилен.
Щом огънят бъде загасен, ще започне цялостно разследване, каза Мамдани.
Пожарникарите се отзовали на сигнал за пожар в мазе и двама блокирани работници и вече били на местопроизшествието, когато последвал взривът, посочиха властите.
Инцидентът се е разиграл в Ричмънд Терас в Статън Айланд, район на Ню Йорк, намиращ се оттатък пристанището, срещу Манхатън.

### 24chasa — Cleaning Summary

- Dropped daily road condition reports (`Вижте какво е състоянието на пътищата`) — structured government bulletins, not news articles
- Dropped photo puzzle articles (`Фотозагадка:`, `Виж/Вижте отговора на фотозагадката:`)
- Dropped comic strip articles containing `Малкия Иванчо`
- Dropped boilerplate app promotion articles (`изтегли приложението от тук` in title)
- Dropped articles with title containing `"24 часа" на` (daily digest covers)
- Dropped daily TV schedule articles (`Спорт по телевизията днес`)
- Stripped newsletter prompt appearing before article content (`Разберете големите новини от последното денонощие накуп Запиши се`)
- Removed inline newsletter subscription block (`"24 часа" в мейла ти. Разберете големите новини от последното денонощие накуп`)
- Truncated everything after `Последвайте ни в Google News Showcase` (subscription/ad block always at end)
- Truncated everything after `Затвори [Uppercase]` pattern (UI navigation artifact injected at end of text)
- Dropped lines starting with `Снимка:` (photo captions)
- Dropped lines containing only Latin characters (embedded tweets, foreign text)
- Dropped social media attribution lines
- Dropped emoji-heavy and `@handle` lines (embedded social media posts)

## 4.k. Fakti

In [155]:
print_source_samples(df, "fakti", n=3, random_state=42)

=== FAKTI (7583 articles) ===

--- Щедри заплати и трикове: Как вербуват руснаци за фронта ---
URL: https://fakti.bg/world/1058740-shtedri-zaplati-i-trikove-kak-verbuvat-rusnaci-za-fronta
Поради липсата на достатъчно желаещи да се бият на фронта, руските вербовчици измислят нови начини да примамват нови попълнения във войната срещу Украйна. Руското издание "Верстка" е открило обяви, в които се предлага на желаещи да сключат договор за служба "в тила на специалната военна операция (СВО)" в Беларус или Китай. В една от тях се обещава: "Няма да има никакви командировки в горещите точки и по линиите на бойно съприкосновение". Уточнява се, че ситуацията в Беларус е стабилна, има развита инфраструктура, а за много руски граждани мястото не е отдалечено от дома им. Освен това става ясно, че военната служба ще се извършва на територията на съюзната държава с гаранции и заплащане от Министерството на отбраната на Руската федерация.
Според "Верстка" през май 2026 г. в платформата „Авито“ са били публикувани около 50 такива „обяви“ от работодатели със странни наименования като „Военна доблест“, „Път към победата“, „Рубеж – родина СВО“, „Служба с достойнство“, „Верният път“ и „Армейският път“. Всички те са се регистрирали на тази платформа в периода от март до декември 2025 г., съобщава руското издание.
Заплати до 260 000 рубли, опрощаване на дългове и големи "бонуси"
В обявите, които са почти идентични като съдържание и оформление, се търсят хора от всякакви националности, включително на възраст над 45 години и дори пенсионери със здравословни проблеми, без опит и военна книжка, а също така и осъждани с изтекла присъда или с условно наказание.
Основно им предлагат да станат охранители на „тилови складове“ в Беларус, служители „в производството на боеприпаси“ в Китай, техници за сглобяване и изпитатели на безпилотни летателни апарати. За такава „работа“ се предлагат заплати от 230 до 260 хиляди рубли на месец (около 3000 евро по актуалния разменен курс).
Освен това са предвидени еднократни плащания за „наемане на работа“ – от 2,3 млн. до 3,1 млн. рубли (около 32 000 евро), както и 10 млн. рубли (около около 116 000 евро) „за преместване на новото място“. Говори се също за "опрощаване на дългове" до същата сума и „облекчения за семейството“, посочва „Верстка“. Разходите за пътуване „до новата служба“, за настаняване в казармите, за храна и екипировка се поемат от „работодателя“.
По информация на изданието „The Moscow Times“, през първото тримесечие на 2026 г. около 70 500 руснаци са подписали договори за военна служба или са се записали като доброволци в руските въоръжени сили. Средният дневен темп на набиране на нови кадри е спаднал до 800 души на ден, което е най-ниската стойност от първото тримесечие на 2024 година насам. В сравнение със същия период на 2025 г. този показател е намалял с 20 процента, а спрямо последните месеци на миналата година – с повече от 40%.
Набиране на военнослужещи в армията на Руската федерация
Както ДВ вече писа, военните комисии в Русия масово са започнали да изпращат писма до мъжете в наборна възраст и на резервисти с искане да се явят „по разпореждане“ и „за уточняване на данни“. Опасения относно засилена мобилизация в Русия по-рано изрази украинският президент Володимир Зеленски. Според него Кремъл се стреми да компенсира големите загуби на руската армия в Украйна и да увеличи „окупационния контингент“.
Въпреки че от ноември 2022 г. формално Русия не провежда принудителна мобилизация, правозащитници говорят за интензивно продължаващо набиране на кадри. Именно в този капан може да попадне всеки, решил да се яви във военната комисия. Затова правозащитниците препоръчват с военните комисии да се общува само дистанционно, или чрез пълномощни, издадени на близък човек.
Автор: Роман Сулима
Напиши коментар:
КОМЕНТАРИ КЪМ СТАТИЯТА
1 Тити
07:13 04.06.2026
2 ЕВРЕИНА БРОНЩАЙН
ЕВРЕИНА ШАЛОМОВИЧ
СЪЗДАДЕ ЕДИН СБИРЩАЙН
ОТ КРАДЦИ УБЙИЦИ
ПРЕСТЪПНИЦИ И ПИЯНДУРНИЦИ.
НОВИЯТ ЕЛИТ НА РУСИЯ
07:13 04.06.2026

--- Владислав Панев: Над 140 млн. лв. е чистата печалба за Вълка, част от тях са били за Доган ---
URL: https://fakti.bg/bulgaria/1058955-vladislav-panev-nad-140-mln-lv-e-chistata-pechalba-za-valka-chast-ot-tah-sa-bili-za-dogan
Бившият директор на Българската банка за развитие (ББР) Стоян Мавродиев е задържан в Белград.
"Вероятно чадър е имало над всички, които напуснаха България малко преди да се появи заповедта за ареста им. Бягат в Сърбия - все държави, с които нямаме споразумение за екстрадиция. Оста Будапеща - Белград - София се разпада. Орбан падна, Борисов също и неговите контакти се разпадат един по един. Ще видим какво ще стане с Вучич", заяви депутатът от "Демократична България" Владислав Панев в "Денят ON AIR".
"Мавродиев беше в центъра със случая за 150 млн. лева, които е отпуснал на Румен Гайтански - Вълка. Над 140 млн. лв. е чистата печалба за Вълка. Сега става ясно от показанията на Гайтански, че част от тези 150 млн. лв. са били за Ахмед Доган. Показанията са давани по времето на Главчев. Гайтански получава парите чисти наготово. Преди 10 години стойността на парите беше по-различна", допълни той за Bulgaria ON AIR.
Отговорност за свръхдефицита носят всички управляващи от времето на Ковид-19 досега, убеден е той.
"Когато защитим дребните производители от веригите да не им изкупуват продукцията евтино, това не намалява цените. Верният ход е да се намали бюджетният дефицит. Парите не остават в България, защото конкурентоспособността на икономиката е намаляла. Трябва да видим бюджета и доколко ще има мерки за потискане на бюджетния дефицит. Ситуацията с финансите е лоша, не е фатална", посочи гостът.
По думите му по време на бюджетната процедура се събира информация от всички ведомства и дават силно завишени сметки.
"Бащата на Евгени Симеонов е бил депутат от ДПС от 2017 г. до 2021 г. и е приятел на Румен Радев. Не ми вдъхва доверие, че този човек има нужната компетенция да управлява такова предприятие", обясни депутатът от ДБ.
Напиши коментар:
КОМЕНТАРИ КЪМ СТАТИЯТА
1 Сатана Z
21:37 04.06.2026
2 Прав е
21:37 04.06.2026
3 Сатана Z
Коментиран от #5, #11
21:39 04.06.2026
4 Овчар
Коментиран от #7
21:39 04.06.2026
5 Този коментар е премахнат от модератор.
6 Ауууу
21:44 04.06.2026
7 нормално
До коментар #4 от "Овчар":
След като 7 милона блеят и преживят21:45 04.06.2026
8 среднощен
"Хората зад Доган" вече се изнервят... Скоро ще изгори "политически бушон"...
21:46 04.06.2026
9 Сила
35 години контролира и ограбва БГ то ....егати нещастната територия !!!!
21:48 04.06.2026
10 Този коментар е премахнат от модератор.
11 Точен сте в цифрите господине
До коментар #3 от "Сатана Z":
Както каза Бойко Борисов едни хора ощетиха същата тази държава и народ с над 6 млрд.лв.-България ще плати 6.8 млрд. лв. на Турция по газовата сделка на президента Радев
Това е задължителната такса за услугата на "Боташ", която "Булгаргаз" може дори да не използва. Мунчо отиде на крака при падишах Ердоган да му подари нашите клети ,кървави народни пари...А подставения подписал министър на енергетиката Росен Христов си купи кабриолет за 477 хиляди Европа да вози манекенки до Париж а за народа блъскат само за консумативи.. и за благодарност мунчо го сложи в борда на ДКК на заплата 12 хиляди еврака. .Всекиму-своето
Коментиран от #13, #16
21:56 04.06.2026
12 .....
21:59 04.06.2026
13 Ха,ха
До коментар #11 от "Точен сте в цифрите господине":
Да я плаща виновника,бг не им е бащиния.Коментиран от #14
22:00 04.06.2026
14 6-те милиарда да плати мунчо ли
До коментар #13 от "Ха,ха":
Не му се плаща нещо а половин милион еврака всеки ден плаща народа от държавния бюджет! Тоест от нашите данъци ,осигуровки и нови заеми на държавата!22:04 04.06.2026
15 За Прокопиев няма ли,
22:05 04.06.2026
16 Изгледайте добре видеото
До коментар #11 от "Точен сте в цифрите господине":
2 мин.и 45 сек.е. Журналисти изчакаха пиара на премиера и народен представител Слави Василев от ПБ и го попитаха защо България плашат по половин милион долара на Турция и заради това Булгаргаз е пред фалит и задлъжня с 600 милиона евро и Слави Василев каза че им плащаме фиктивни пари ...Вижте добре кои ви управляват...Коментиран от #21, #23, #24
22:11 04.06.2026
17 Това истина ли е
И какво от тук насетне?
22:14 04.06.2026
18 кой му дреме
22:17 04.06.2026
19 АМИ
ДА ЧУКАТ КАМЪНИ.
АКО ЛИ НЕ, НИЕ ЩЕ ГИ ПРЕ...ЧУКАМЕ.
22:17 04.06.2026
20 Един
22:19 04.06.2026
21 Ужaaaac това е потресаащо
До коментар #16 от "Изгледайте добре видеото":
Тези пари не са излезли от нашия и неговия джоб а от Булгаргаз хххахаха...Че Булгаргаз е Българската компания за транзит на газ който плащаме всички ние. Но се радвам че такива избрахте все пак...Това заслужава този народ22:24 04.06.2026
22 Дзак
22:35 04.06.2026
23 Анонимен
До коментар #16 от "Изгледайте добре видеото":
Очевидно този договор е наложен от екстрената ситуация с отказа от директни доставки от Газпром. Какво може да отговори Слави ВасилевКоментиран от #25
22:41 04.06.2026
24 ван мaaмy
До коментар #16 от "Изгледайте добре видеото":
Какъв потрес само..... уважаеми зрители....22:59 04.06.2026
25 Той
До коментар #23 от "Анонимен":
не може да върже две приказки в някъв смисъл.23:00 04.06.2026

--- Мъж с експлозиви към тялото си държи заложници в банка в Калифорния ---
URL: https://fakti.bg/world/1058489-maj-s-eksplozivi-kam-taloto-si-darji-zalojnici-v-banka-v-kalifornia
Въоръжен мъж, за когото се смята, че има експлозиви, прикрепени към тялото му, се е барикадирал в помещение на банков клон в град Бейкърсфилд, Калифорния, заедно с няколко заложници.
Ситуацията е изключително динамична и се следи в реално време от американските медии като CBS News и NBC News.
Нападателят е нахлул в банковия клон, разположен на кръстовището на Chester Avenue и 17-а улица в центъра на града, около 13:00 часа местно време на 2 юни (около 23:00 часа българско време). Извършителят е пълнолетен мъж, който твърди, че носи бомба. Според полицията в Бейкърсфийлд до момента той не е предявил конкретни искания.
Броят на хората, блокирани вътре, все още не е уточнен, но органите на реда ги описват като "служители и членове на местната общност". Благодарение на преговорите, водени по телефона, един от заложниците е бил успешно освободен невредим. Към момента няма данни за пострадали или ранени лица.
На място са разположени екипи на SWAT, сапьори, преговарящи при кризи, екипи с дронове и кучета. Местната полиция получава директна помощ на терен от офиса на ФБР в Сакраменто и Министерството на вътрешната сигурност на САЩ.
Всички околни сгради в центъра на Бейкърсфийлд са евакуирани. Кметството, полицейското управление и съседните административни сгради са под пълна блокада. Около района са разположени медицински палатки за триаж в случай на извънредна ситуация.
Инцидентът съвпада с провеждането на вътрешнопартийните избори в щата Калифорния. Поради близостта на банковия клон до ключови административни сгради и евакуациите, някои от кандидатите вече отмениха официалните си събития в изборната нощ от съображения за сигурност.
Напиши коментар:
КОМЕНТАРИ КЪМ СТАТИЯТА
1 Краварстан
Коментиран от #4
05:04 03.06.2026
2 През
05:34 03.06.2026
3 Щом има кочита
06:29 03.06.2026
4 Че краваристан
До коментар #1 от "Краварстан":
От десетки години не е бела държава06:30 03.06.2026
5 Този коментар е премахнат от модератор.
6 ООрана държава
06:39 03.06.2026
7 Лопата Орешник
06:52 03.06.2026

In [156]:
df = apply_to_source(
    df,
    lambda t: truncate_at_sentinel(t, ["Поставете оценка:", "Напиши коментар:"]),
    source="fakti",
)

### Fakti — Cleaning Summary

- Truncated everything after `Поставете оценка:` or `Напиши коментар:` — these mark the start of the comment section appended to the article by the site, containing UI boilerplate with no news content

## 5. General Noise Removal

In [157]:
noise_lines = []

for _, row in df.iterrows():
    if not isinstance(row["full_text"], str):
        continue
    for line in row["full_text"].split("\n"):
        if is_noise_line(line):
            noise_lines.append(
                {"source": row["source"], "title": row["title"], "line": line.strip()}
            )

print(f"Total noise lines found: {len(noise_lines)}\n")

for item in noise_lines[:20]:
    print(f"[{item['source']}] {item['title']}")
    print(f"  >> {item['line']}")
    print()

Total noise lines found: 1619

[monitor] Гледайте международните приятелски мачове
  >> Diema Sport

[monitor] Гледайте международните приятелски мачове
  >> Diema Sport 2

[monitor] Гледайте международните приятелски мачове
  >> Diema Sport 3

[monitor] Гледайте международните приятелски мачове
  >> Nova Sport

[monitor] Гледайте международните приятелски мачове
  >> MAX Sport 1

[monitor] Гледайте международните приятелски мачове
  >> MAX Sport 2

[monitor] Гледайте международните приятелски мачове
  >> MAX Sport 3

[monitor] Гледайте международните приятелски мачове
  >> MAX Sport 4

[monitor] Гледайте международните приятелски мачове
  >> EUROSPORT

[monitor] СЛЕД ЖЕСТОКОТО ЗЕМЕТРЕСЕНИЕ: Жертвите във Филипините са над 40! (ВИДЕО)
  >> More wild footage from today’s massive earthquake in the Philippines. pic.twitter.com/Cdylad2d7W

[monitor] СЛЕД ЖЕСТОКОТО ЗЕМЕТРЕСЕНИЕ: Жертвите във Филипините са над 40! (ВИДЕО)
  >> — Breaking911 (@Breaking911) June 8, 2026

[monitor] ХОЛИВУДСКА МОДА: Дъщерята на Джей Ло стана момче! (СНИМКИ)
  >> Filho de Jennifer Lopez começou a usar seu nome retificado e se chama Oskar Muñiz. 🏳️⚧️ pic.twitter.com/5bOi0fdLv7

[monitor] ХОЛИВУДСКА МОДА: Дъщерята на Джей Ло стана момче! (СНИМКИ)
  >> — POPTime (@poptime) June 2, 2026

[fakti] Носител на Грами беше открит намушкан до смърт в Лондон
  >> Songwriter Talay Riley, who worked with Britney Spears, found dead at 35 https://t.co/I1idjB5QKv pic.twitter.com/i475ulfLTQ

[fakti] Носител на Грами беше открит намушкан до смърт в Лондон
  >> — New York Post (@nypost) June 8, 2026

[standartnews] Биохакинг: Новата мания превзема и България
  >> longevity,

[standartnews] Биохакинг: Новата мания превзема и България
  >> anti-aging,

[fakti] В Гърция: ЦСКА продължава да следи ситуацията с Кирил Десподов
  >> Σύμφωνα με το https://t.co/NwN38ZbbZD, υπάρχει ενδιαφέρον από την CSKA Sofia για την απόκτηση του Kiril Despodov, ο οποίος ανήκει στον #paokfc.

[fakti] В Гърция: ЦСКА продължава да следи ситуацията с Кирил Десподов
  >> — The Sports Share by Ser 🇬🇷 (@TheSportsShare) June 8, 2026

[fakti] В Гърция: ЦСКА продължава да следи ситуацията с Кирил Десподов
  >> Η υπόθεση συνδέεται με σενάρια που προέρχονται από τη Βουλγαρία και αφορούν πιθανή επιστροφή του παίκτη στο εγχώριο πρωτάθλημα, καθώς ο… pic.twitter.com/S22Wu1eehe

In [158]:
df["full_text"] = df["full_text"].apply(lambda t: drop_lines(t, is_noise_line))

### Global Noise Line Removal

Applied across the entire dataset — dropped lines matching any of the following patterns:

- Lines containing only Latin characters (English text, foreign-language content)
- Lines starting with `—`/`–` followed by Latin content (social media quotes, foreign attributions)
- Lines starting with `@handle` (embedded TikTok/Twitter posts)
- Social media attribution lines matching `(@handle) date` pattern
- Emoji-heavy lines

## Removing inline separators

In [159]:
mask = df["full_text"].str.contains(r"(?:-\s*){5,}", regex=True, na=False)
print(f"Articles with inline separators: {mask.sum()}")
print(df[mask]["source"].value_counts().to_string())
print()

for _, row in df[mask].head(5).iterrows():
    print(f"--- [{row['source']}] {row['title']} ---")
    print_by_words(row["full_text"])
    print()

Articles with inline separators: 27
source
bta             9
fakti           8
segabg          4
actualno        3
24chasa         1
standartnews    1
monitor         1

--- [24chasa] България спечели отборната титла на европейското по художествена гимнастика във Варна ---
България спечели отборната титла при жените на Европейското първенство по художествена гимнастика във Варна, а ансамбълът зае шесто място в
многобоя. Националките Стилияна Николова, Ева Брезалиева при жените и София Иванова, Маргарита Василева, Магдалина Миневска, Емилия Обретенова, Рая Божилова и
Магдалена Вълкова събраха от десетте си изигравания 277.600 точки. На второ място е Израел с 274.650 точки, а на трето
Русия с 274.650 точки. В топ 6 са още Испания с 274.600, Германия с 269.600, Италия с 269.150 и други.
България е отборен шампион при жените през 2022, 2023, 2024, единствено миналата година отстъпи пред Италия, а сега отново е
номер 1 на Стария континент. Европейското първенство е квалификация за Световното. Първите 12 тима от индивидуалните пресявки (осем съчетания) имат
право да участват на Световното първенство с пълни отбори, а останалите държави - с по една гимнастичка. Ансамбълът на България
в състав София Иванова, Маргарита Василева, Магдалина Миневска, Емилия Обретенова, Рая Божилова и Магдалена Вълкова завърши на шесто място в
многобоя със сбор от 49.750 точки. Възпитаничките на Весела Димитрова изиграха с малки неточности изпълнението си с пет топки и
имат оценка от 26.650 точки (13.0 трудност, 6.150 изпълнение, 7.500 артистичност) и са с пета оценка на този уред. Във
втората композиция с три обръча и два чифта бухалки българките направиха доста сериозни грешки, включително уред извън терена, и получиха
23.100 (12.0 трудност, 4.650 изпълнение, 6.750 артистичност, 0.300) наказание и останаха девети (първа резерва). Испания защити европейската си титла със
сбор от 57.650 точки (28.850 пет топки и 28.800 на три обръча и два чифта бухалки). Сребърното отличие е за
Русия с 53.450 (26.950 и 26.500), а на трета позиция остана Израел с 53.350 (26.700 и 26.650). До момента България
има пет медала от шампионата - три златни в отборната надпревара при жените, при девойките, на Сияна Алекова на обръч,
както и два сребърни - на Стилияна Николова и на Деа Емилова на финала на бухалки при девойките. Утре от
12:00 часа започват финалите на отделните уреди при жените и при ансамблите, където Стилияна Николова ще играе на всичките четири
уреда, Ева Брезалиева - на три, а ансамбълът на пет топки. Отборно класиране: 1. България - 277.600 точки 2. Израел
- 274.650 3. Русия - 274.650 класиране, многобой ансамбли: 1. Испания - 57.650 точки (28.850 пет топки и 28.800 на
три обръча и два чифта бухалки) 2. Русия - 53.450 (26.950 и 26.500) 3. Израел - 53.350 (26.700 и 26.650)
-------------------------------------------- 6. БЪЛГАРИЯ - 49.750 (26.650 и 23.100)

--- [segabg] Съдът не е достатъчен да сложи юзди на хищническото кредитиране ---
Всеки ден хиляди българи с ниски доходи биват неусетно завличани във финансово блато, от което измъкване няма. Потиснати от безпаричие
и липса на алтернативи, те посягат към примамливите реклами за „пари до минути“ - бързите кредити. Резултатът? Попадане в безмилостен
финансов капан, задвижван от хищническо кредитиране и грубо, съзнателно погазване на съществуващия Закон за потребителския кредит. Безразборното кредитиране представлява и
обществен проблем, тъй като допринася за инфлационен натиск и води до свръхзадлъжнялост на лицата и техните семейства — социално и
обществено нетърпимо явление. Посочените рискове са предмет на регулиране на най-високо равнище в правото на Европейския съюз, включително в Договора
за функционирането на Европейския съюз, и имат приоритетен характер. С ключово значение са две евродирективи - за неравноправните клаузи в
потребителските договори и за договорите за потребителски кредит. Крайният срок за транспониране на новата Директива (ЕС) 2023/2225 за потребителския кредит
изтече още на 20 ноември 2025 г. Държавата ни вече е в закъснение, а крайната дата за реалното й прилагане
– 20 ноември 2026 г., наближава застрашително. Прозорецът от време се затваря и ако не бъдат взети спешно адекватни мерки,
законът ще остане формален, беззъб документ. Съдът не е достатъчен Адвокати и съдии, които ежедневно се сблъскваме в съдебните зали
с лихварството под маската на „бърза финансова помощ“, настояваме за решения, които ще действат превантивно и ще сложат край на
законовото безсилие пред търговската безскрупулност. Като адвокати ежедневно печелим дела срещу фирми за бързи кредити, доказвайки нищожност и неравноправност на
клаузите им. Но съдебната зала лекува симптомите, а не болестта. Огромната част от притиснатите до стената граждани са твърде уплашени,
бедни или правно неинформирани, за да потърсят съд. Те просто биват смазвани от кредитната преса. Нужни са не последващи дела,
а мощна превантивна административна спирачка, която да действа автоматично на пазара и да сложи юзди на финансовия произвол Настояваме за
въвеждането на механизми за бързо и безкомпромисно разрешаване на споровете и пресичане на злоупотребите още в зародиш. Предлагаме създаването на
национален регистър със списък на обявените за неравноправни клаузи. Това не е екзотична идея. Съдът на ЕС вече е приел,
че подобни механизми са съвместими с правото на ЕС. Смисълът е прост - когато една клауза по същество е идентична
или равностойна на вече обявена за неравноправна от съда и вписана в националния регистър, националните институции и съдилища директно да
я считат за неравноправна, без значение как е формулирана. Това ще отреже възможността на фирмите да сменят просто по някоя
дума, за да заобикалят закона. Клауза от „черния списък“ означава автоматична недействителност – край на шиканирането. За да има мярката
пълна ефективност и да отговаря на европейските стандарти за „реално възпиращи“ санкции, е нужно ключово изменение в Закона за защита
на потребителя: ако търговец предлага или продължава да прилага клауза, вписана в "черния списък", санкцията се връзва за оборота, така
че нарушението да не може да се планира като нормален разход. Предлагаме механизъм на три стъпки: при първо нарушение КЗП
налага висока глоба, при повторно нарушение увеличава санкцията до 4 % от годишния оборот; при системност КЗП мотивирано сезира БНБ,
а БНБ може да стигне до отнемане на лиценз и изваждане от пазара. Редица държави вече са го въвели, като
Холандия и Полша. Настояваме и за радикален удар срещу залагането на финансови капани, като се въведат две нови основания за
обявяване на договорите за недействителни. Първият капан щраква още преди потребителят изобщо да е подписал документа – чрез скриване на
истината. Когато една фирма спести или умишлено подведе човека с непълна или невярна преддоговорна информация, тя реално го мами на
самия старт. Затова предлагаме в тези случаи договорът да се обяви за недействителен, а фирмата да загуби правото на всякакви
лихви и такси. Второто абсолютно основание за недействителност удря право в сърцето на безочливата безотговорност – неизпълнение на задължението за
проверка на кредитоспособността. В практиката ни постоянно се натъкваме на брутални случаи на хора с по 10, 15 или дори
20 висящи бързи кредита, които физически не могат да ги погасяват. И тук лъсва целият цинизъм: макар това обстоятелство да
е пределно видно в Централния кредитен регистър, фирмите за бързи кредити продължават да отпускат на тези хора нови и нови
заеми. Правят го, защото отлично знаят, че все някой накрая ще плати „сметката“ – притиснатият човек ще изпадне в паника
и ще затъне още по-дълбоко, теглейки нов заробващ кредит, за да върне стария. Или пък целият този хищнически риск просто
ще бъде калкулиран и преразпределен върху гърба на останалите редовни кредитополучатели. Когато законът каже, че такъв договор е напълно нищожен,
фирмите сами ще започнат да проверяват регистрите, вместо да завличат хората в бездънната пропаст. Предлагаме и таван на възнаградителната лихва
– не повече от три пъти законната лихва. Разумна печалба, а не лихварство. И задължение кредиторите да предоставят копие от
договора по всяко време – нещо, което Съдът на ЕС вече е потвърдил като право на потребителя. Предлагаме строга забрана
на записите на заповед и менителниците като обезпечение по потребителски кредити. В момента кредиторите принуждават хората да подписват бланкови записи
на заповед, след което джиросват вземането на колекторски фирми. Потребителят губи правото да се защити с възражения по основния договор.
Това е класическо заобикаляне на закона – практика, която Съдът на ЕС изрично осъжда, а редица държави (Белгия, Франция, Полша,
Чехия) са я забранили категорично. Настояваме да се промени и изчисляването на законната лихва за забава, когато кредиторът недобросъвестно е
получил пари, които трябва да върне, защото са събрани на основание неравноправна клауза, като лихвата се начислява и без покана.
Масов трик на фирмите за бързи кредити е да принуждават хората да плащат огромни суми под формата на различни измислени
такси, неустойки и всякакви други незаконни начисления – като например абсурдни санкции за неосигуряване на поръчител в рамките на дни.
Досега, когато съдът обяви тези практики за незаконни, законната лихва върху надплатеното се дължеше едва от датата на поканата до
фирмата. Ние предлагаме при доказана недобросъвестност законната лихва да се дължи автоматично още от самия момент, в който потребителят е
платил тези пари без правно основание. Това ще има мощен и незабавен възпиращ ефект срещу тези порочни практики. Предлагаме също
и ясна промяна в тази връзка: законната лихва на потребителя за забава по потребителски задължения да се изчислява като референтния
процент + 5 процентни пункта, вместо сегашния „наказателен“ модел ЕЦБ + 8 процентни пункта, който у нас важи като обща
законна лихва за просрочени парични задължения. Така лихвата ще остане достатъчна да дисциплинира забавата, но няма да „надува“ дълга непропорционално
и да превръща просрочието в източник на свръхпечалба. Подобен по-умерен подход съществува в Германия, Италия, Хърватска Полша. Време е за
превенция, а не за социално безразличие Промените, които предлагаме, не са просто правна козметика – те са жизненоважна социална спирачка.
Транспонирането на директивата е исторически шанс за българския законодател да докаже, че е на страната на своите граждани, а не
на страната на финансовите хищници. Новата европейска директива поставя акцент върху предотвратяването на свръхзадлъжнялостта, прозрачността и отговорното кредитиране. България има
шанс да използва този момент разумно. Ако обаче общественият дебат остане слаб, а решенията се формират основно под натиска на
икономически интереси, има риск отново да се приеме закон, който изглежда добре на хартия, но не решава реалния проблем. Въпросът
не е дали съдът в крайна сметка ще отмени поредната незаконна клауза. Въпросът е колко още хора ще преминат през
години на дългова спирала, запори и унижение, преди държавата да постави реални граници пред хищническото кредитиране. Законът трябва да действа
като предпазна бариера, а не като линейка след катастрофата. ------------------------------- Адвокат Десислава Филипова е участник в редица законодателни инициативи, свързани
с изменения в Закона за защита на потребителите, Закона за кредитите за недвижими имоти на потребителите и Гражданския процесуален кодекс.
Тя е председател на фондация „Център за европейска интеграция на България и за защита правата на човека“, чиито основни цели
са усъвършенстване на българското законодателство в съответствие с правото на ЕС и Европейската конвенция за правата на човека, както и
защита на лица, засегнати от незаконосъобразни практики на банки и частни съдебни изпълнители.

--- [bta] Локомотив Пловдив спечели пловдивското дерби от последния кръг на футболното първенство ---
Локомотив Пловдив спечели пловдивското дерби от последния кръг на футболното първенство Първенство по футбол на България, мачове от 38-ия кръг
на efbet Лига: втора четворка: Локомотив (Пловдив) - Ботев (Пловдив) - 2:1 (1:1) голмайстори: 1:0 Жоел Цварц 21, 1:1 Никола
Илиев 34, 2:1, Жоел Цварц 54 Черно море (Варна) - Арда (Кърджали) - 2:3 (1:0) голмайстори: 1:0 Асен Дончев 8,
1:1 Борсент Карагарен 46, 1:2 Бирсент Карагарен 53, 2:2 Давид Телеш 55, 2:3 Серкан Юсеин 72 първа четворка, по-късно днес:
ЦСКА 1948 - Левски Лудогорец (Разград) - ЦСКА от миналата седмица: трета осмица: Славия - Монтана 2:0 (1:0) голмайстори: 1:0
Емилиян Гогев 45+3, 2:0 Кристиян Балов 65 пропусната дузпа: Роберто Райчев (Славия) 75 Ботев Враца - Берое 3:0 (1:0) голмайстори:
1:0 Мичи Нтело 25, Мартин Петков 48, 3:0 Касим Хаджи 90+1 Септември София - Добруджа 1:1 (1:0) голмайстори: 1:0 Мартин
Христов 33, 1:1 Георги Трифонов 72 пропусната дузпа: Бертран Фурие (Септември) 83 червени картони: Галин Иванов (Септември) 90+4, Божидар Томовски
(Септември) 90+7, Вашко Оливейра (Добруджа) 90+4, Антон Иванов (Добруджа) 90+8 Спартак Варна - Локомотив София 3:0 (2:0) голмайстор: 3:0 Георг
Стояновски 8, 30, 62 класиране: 1. Левски 35 25 5 5 71:25 80 точки - шампион 2. ЦСКА 1948 (Сф)
35 20 6 9 54:35 66 3. Лудогорец 35 18 10 7 60:25 64 4. ЦСКА (София) 35 18 9
8 47:29 63 - - - - - - - - - - - - - - - - -
- - - - - - - - - 5. Локомотив (Пловдив) 36 14 13 9 36:41 55 - бараж
за Лига на конференциите 6. Арда (Кърджали) 36 15 9 12 42:34 54 7. Черно море 36 14 12 10
40:34 54 8. Ботев (Пловдив) 36 13 7 16 49:45 46 - - - - - - - - -
- - - - - - - - - - - - - - - - - 9. Ботев (Враца)
37 13 14 10 36:32 53 10. Локомотив (София) 37 11 14 12 51:48 47 11. Славия 1913 (София) 37
12 10 15 42:44 46 12. Спартак (Варна) 37 8 13 16 35:57 37 13. Септември (София) 37 9 9
19 32:64 36 - бараж за оставане 14. Берое (Стара Загора) 37 7 13 17 28:52 34 - изпада 15.
Добруджа 1919 (Добрич) 37 8 7 22 28:52 31 - изпада 16. Монтана 37 4 11 22 21:55 23 -
изпада

--- [bta] Спартак Варна победи Локомотив София и запази мястото си в елита, Септември София завърши наравно с Добруджа и ще играе бараж ---
Спартак Варна победи Локомотив София и запази мястото си в елита, Септември София завърши наравно с Добруджа и ще играе
бараж Първенство на България по футбол, мачове от 37-ия кръг в Първа лига: трето осмица Славия - Монтана 2:0 (1:0)
голмайстори: 1:0 Емилиян Гогев 45+3, 2:0 Кристиян Балов 65 пропусната дузпа: Роберто Райчев (Славия) 75 Ботев Враца - Берое 3:0
(1:0) голмайстори: 1:0 Мичи Нтело 25, Мартин Петков 48, 3:0 Касим Хаджи 90+1 Септември София - Добруджа 1:1 (1:0) голмайстори:
1:0 Мартин Христов 33, 1:1 Георги Трифонов 72 пропусната дузпа: Бертран Фурие (Септември) 83 червени картони: Галин Иванов (Септември) 90+4,
Божидар Томовски (Септември) 90+7, Вашко Оливейра (Добруджа) 90+4, Антон Иванов (Добруджа) 90+8 Спартак Варна - Локомотив София 3:0 (2:0) голмайстор:
3:0 Георг Стояновски 8, 30, 62 понеделник: втора четворка Черно море - Арда Кърджали Локомотив Пловдив - Ботев Пловдив първа
четворка ЦСКА 1948 - Левски Лудогорец - ЦСКА класиране: 1. Левски 35 25 5 5 71:25 80 точки - шампион
2. ЦСКА 1948 (Сф) 35 20 6 9 54:35 66 3. Лудогорец 35 18 10 7 60:25 64 4. ЦСКА
(София) 35 18 9 8 47:29 63 - - - - - - - - - - - - -
- - - - - - - - - - - - - 5. Черно море 35 14 12 9
38:31 54 6. Локомотив (Пловдив) 35 13 13 9 34:40 52 7. Арда (Кърджали) 35 14 9 12 39:32 51
8. Ботев (Пловдив) 35 13 7 15 48:43 46 - - - - - - - - - - -
- - - - - - - - - - - - - - - 9. Ботев (Враца) 37 13
14 10 36:32 53 10. Локомотив (София) 37 11 14 12 51:48 47 11. Славия 1913 (София) 37 12 10
15 42:44 46 12. Спартак (Варна) 37 8 13 16 35:57 37 13. Септември (София) 37 9 9 19 32:64
36 - бараж за оставане 14. Берое (Стара Загора) 37 7 13 17 28:52 34 - изпада 15. Добруджа 1919
(Добрич) 37 8 7 22 28:52 31 - изпада 16. Монтана 37 4 11 22 21:55 23 - изпада

--- [bta] Славия победи Монтана в Първа лига ---
Славия победи Монтана в Първа лига Първенство на България по футбол, мачове от 37-ия кръг в Първа лига: трето осмица
Славия - Монтана 2:0 (1:0) голмайстори: 1:0 Емилиян Гогев 45+3, 2:0 Кристиян Балов 65 пропусната дузпа: Роберто Райчев (Славия) 75
по-късно днес: Ботев Враца - Берое Септември София - Добруджа Спартак Варна - Локомотив София понеделник: втора четворка Черно море
- Арда Кърджали Локомотив Пловдив - Ботев Пловдив първа четворка ЦСКА 1948 - Левски Лудогорец - ЦСКА класиране: 1. Левски
35 25 5 5 71:25 80 точки - шампион 2. ЦСКА 1948 (Сф) 35 20 6 9 54:35 66 3.
Лудогорец 35 18 10 7 60:25 64 4. ЦСКА (София) 35 18 9 8 47:29 63 - - - -
- - - - - - - - - - - - - - - - - - - -
- - 5. Черно море 35 14 12 9 38:31 54 6. Локомотив (Пловдив) 35 13 13 9 34:40 52
7. Арда (Кърджали) 35 14 9 12 39:32 51 8. Ботев (Пловдив) 35 13 7 15 48:43 46 - -
- - - - - - - - - - - - - - - - - - - -
- - - - 9. Ботев (Враца) 36 12 14 10 33:32 50 10. Локомотив (София) 36 11 14 11
51:45 48 11. Славия 1913 (София) 37 12 10 15 42:44 46 12. Септември (София) 36 9 8 19 31:63
35 13. Берое (Стара Загора) 36 7 13 16 28:49 34 14. Спартак (Варна) 36 7 13 16 32:57 34
15. Добруджа 1919 (Добрич) 36 8 6 22 27:51 30 - изпада 16. Монтана 37 4 11 22 21:55 23
- изпада

In [160]:
def remove_inline_separators(text: str) -> str:
    if not isinstance(text, str):
        return text
    return re.sub(r"(?:-\s*){5,}", " ", text).strip()

In [161]:
df["full_text"] = df["full_text"].apply(remove_inline_separators)

## Removing HTML entities

In [162]:
mask = df["full_text"].str.contains(r"&\w+;", regex=True, na=False)
print(f"Articles with HTML entities: {mask.sum()}")
print(df[mask]["source"].value_counts().to_string())

Articles with HTML entities: 13
source
actualno    13

In [163]:
mask = (df["source"] == "actualno") & df["full_text"].str.contains(
    r"&\w+;", regex=True, na=False
)
print(f"Actualno articles with HTML entities: {mask.sum()}\n")

for _, row in df[mask].iterrows():
    print(f"--- {row['title']} ---")
    print_by_words(row["full_text"])
    print()

Actualno articles with HTML entities: 13

--- Почти 12 милиона евро субсидия: Кой колко получава и кои са големите губещи? (СНИМКИ) ---
Почти 12 милиона евро субсидия: Кой колко получава и кои са големите губещи? (СНИМКИ) 22 април 2026, 16:31 часа 1675
прочитания 0 коментара Снимка: БГНЕС 11 милиона и 731 хиляди евро - това е размерът на държавната субсидия, която ще
си разпределят партиите и коалициите след предсрочните парламентарни избори на 19 април, сочат изчисленията на Actualno.com според предварителните резултати от
вота. От тях най-голямата сума респективно ще отиде за "Прогресивна България" - над 5,924 милиона евро. Как се изчислява -
всяка партия, събрала над 1% подкрепа, получава субсидия. За коалициите прагът е 4%. Ситуацията с резултатите е доста специфична на
тези избори и показва, че това е ироничен урок за част от формациите, които се явиха, но покриват едва половината
критерии. Такъв е случая с БСП и АПС, които имат над 1%, но се явиха като коалиции и затова остават
без финансови средства. Това принуди лидерът на социалистите Крум Зарков вече да съобщи, че със заем и без субсидия БСП
ще свива разходите след изборния провал . Електоралният срив на ИТН пък ги остави под прага на процента и те
също остават без пари от държавата.Още: Още: Вълната на Радев отнесе от парламента Хамид Хамид, Станислав Анастасов, Красен Кралев и
още бивши остриета (СНИМКИ) Кой колко взема? Въпреки липсата на редовен бюджет след превалутирането партиите получават по 4,10 евро на
действителен глас. Ето и колко пари ще получават всички формации според таблицата на Actualno.com : &lt;img src="https://public.flourish.studio/visualisation/28648831/thumbnail" mce_src="https://public.flourish.studio/visualisation/28648831/thumbnail" width="100%" alt="visualization"
/&gt; ГЕРБ-СДС ще имат право на близо 1,780 млн. евро субсидия. ПП-ДБ ще вземат над 1, 670 млн. евро. ДПС
ще разчитат на близо 946 000 евро от държавата. А "Възраждане" - на над 565 000. Сред партиите, които остават
извън парламента, но също са преминали бариерата за получаване на субсидия, са МЕЧ и "Величие". Те ще вземат съотв. над
428 000 евро и над 421 000 евро. Независими и обективни новини - Actualno.com ги представя и във Viber! Последвайте
ни тук! Още: Шамар за бившата власт: Половин милион гласа по-малко след протести, нахалство и феномена Радев (СНИМКИ) Последвайте ни
в Google News Showcase , за да получавате още актуални новини. Ивайло Илиев Отговорен редактор партийна субсидия предсрочни парламентарни избори
авторски 52 Народно събрание

--- Най-важните новини за деня, 21 април 2026 г. ---
Най-важните новини за деня, 21 април 2026 г. 21 април 2026, 22:00 часа 1399 прочитания 0 коментара Снимка: iStock Редакционният
екип на Actualno.com ви представя най-важните новини за изминалия ден, 21 април 2026 г. КИТАЙСКИ КОМЕНТАР: РУСКИТЕ РАКЕТИ ВЕЧЕ СА
НАСОЧЕНИ КЪМ ЕВРОПА. БЛИЗО ЛИ Е ВОЙНА С НАТО? На 15 април целият свят беше шокиран от изявлението на заместник-председателя
на Съвета за сигурност на Русия Дмитрий Медведев . Той предупреди Европа, че тя е на мушката на руските ракети,
пише в анализ китайското издание "Соху". Дали това беше обявяване на война на НАТО? Или хитра тактика за психологическа война?
АНТРАКС МОЖЕ ДА ДОВЕДЕ ДО СМЪРТ: ШЕФЪТ НА БАБХ ЗА ОПАСНАТА ЗАРАЗА ПО ЖИВОТНИТЕ Случаят на антракс е много опасен
и животните са преработвани в различни продукти – умиращите и мъртви такива за лична консумация. Буквални умрели животни са превръщани
в мезета. Това заяви директорът на БАБХ д-р Ангел Мавровски пред БНТ. Независими и обективни новини - Actualno.com ги представя
и във Viber! Последвайте ни тук! 6 ПРИЧИНИ РАДЕВ ДА НЕ СТАНЕ "НОВИЯТ ОРБАН", НЯМА МЯСТО ЗА БЕЗПОКОЙСТВО: УКРАИНСКИ ПРОЧИТ
Изборите в България донесоха убедителна победа на бившия президент Румен Радев , който се смята за проруски настроен и чиято
партия "Прогресивна България" спечели 44.6%, от местата в парламента. Радев обаче няма да стане "новият Орбан", така че няма нужда
да се притеснявате. Така коментира българските избори известният украински журналист, писател и телевизионен водещ Виталий Портников в канала си в
YouTube. АКО НЕ ИЗЛЪЧИМ НЕЗАВИСИМ ВСС НЕ СМЕ НАРОД, А МЪРША: СЪДИЯ ДАДЕ РЕЦЕПТАТА ЗА ОЗДРАВЯВАНЕТО НА СЪДЕБНАТА ВЛАСТ „Народното
събрание да се вслушва във волята на обществото. Ако не успеем да намерим 11 човека, които не са обвързани с
политически зависимости за обществената квота на Висшия съдебен съвет (ВСС), тогава не сме народ, а мърша“. Това заяви пред БНТ
Татяна Жилова, бивш председател на Съюза на съдиите в България, а сега съдия в Единния патентен съд на ЕС. УЧЕБНИЯТ
МАТЕРИАЛ ДА БЪДЕ НАМАЛЕН С 35% СЕГА, А НЕ ПРЕЗ 2029 Г.: УЧИТЕЛСКИЯТ СИНДИКАТ С НОВО ИСКАНЕ Незабавно намаляване на
учебния материал, без забавяне от няколко години. За това настоя Синдикат "Образование" към КТ "Подкрепа" в своя позиция във Фейсбук.
НЯМА ПАРИ В БЮДЖЕТА: РУСИЯ ОСТАВЯ ХАЗАРТА ЗА НЕПЪЛНОЛЕТНИ. ТРУДНО НИ Е: РУСКА КОНСТАТАЦИЯ ЗА ЗАПОРОЖИЕ (ОБЗОР - ВИДЕО) Руското
министерство на финансите поиска забраната за залагания от непълнолетни и недееспособни лица да бъде отложена. Причината – трябват пари за
руския бюджет. Министърът на финансите Антон Силуанов поиска от вицепремиера Дмитрий Григоренко да отложи разглеждането на законопроект на Държавната дума,
забраняващ залаганията за непълнолетни, недееспособни лица и разследвани от руските правоохранителни органи (в изпълнителни производства). В резултат на това разглеждането
на документа е отложено за есента, съобщава руският икономически и бизнес ежедневник "Комерсант". "ДРУЖБАТА НИ С ДПС НИ ДОНЕСЕ ТОЗИ
ОТЛИВ И КРАХ": ГЕРБ ПРИЗНА ЗА КОРУПЦИЯ В ПАРТИЯТА, БОРИСОВ ОБЯВИ НОВА ПОСОКА (ВИДЕО) "Изводите за нас са ясни, в
опозиция няма да имамен икакви зависимости. Където работихме с " ДПС Ново начало " претърпяхме крах. Дружбата ни с ДПС
ни донесе този отлив, с ПП-ДБ още 100 хиляди гласа отлив, това е равносметката. Много умно Румен Радев се обяви
срещу всички и спечели, народът си го избра за вожд. Ще бъдем опозиция, няма да имаме зависимости." ВНУШИТЕЛНИЯТ БРОЙ ГЛАСОВЕ
И УСПЕХ НА РАДЕВ, ИЗПРЕВАРИЛИ БОРИСОВ ОТ 2009 Г. И НАПОМНИЛИ ЗА РЕКОРД НА ИВАН КОСТОВ (СНИМКИ) 1 444 924
гласа за изборна победа - неочаквана електорална вълна, донесла едноличната победа на "Прогресивна България" на вота на 19 април. Стойност,
която доближава максимално последната подобна ярка изборна победа и вълна на ГЕРБ през 2009 г., показва исторически преглед на Actualno.com
. КРУМ ЗАРКОВ ПОИСКА ВОТ НА ДОВЕРИЕ И ОБЯВИ МАЩАБЕН ПРОЦЕС НА ПРОМЯНА В БСП Лидерът на БСП Крум Зарков
ще поиска вот на доверие от Националния съвет на левицата тази събота, след като формацията остана извън 52-рото Народно събрание
на предсрочните избори на 19 април. Резултатът на столетницата е под 4-процентовата бариера и бе определен като "много лош" от
бившия служебен министър на правосъдието. Ако не получи доверието на органа, той ще подаде оставка, стана ясно от думите му
на брифинг днес, 21 април. ПРЕДИ ДА ДОЙДЕ РАДЕВ: НАДЕЖДА НЕЙНСКИ ПРИЗОВА ЕС ДА СЕ РАЗБЪРЗА СЪС ЗАЕМА ЗА УКРАЙНА
И НОВИЯ ПАКЕТ САНКЦИИ СРЕЩУ РУСИЯ Служебният министър на външните работи Надежда Нейнски представи България в редовното месечно заседание на
Съвет „Външни работи“ на Европейския съюз, което се проведе днес, 21 април, в Люксембург. В рамките му министрите обсъдиха ключови
теми, включително руската агресия срещу Украйна, ситуацията в Близкия изток, Южен Кавказ и Судан. По време на разговорите, посветени на
Украйна, България - чрез Надежда Нейнски - подчерта необходимостта от единство и последователна подкрепа от страна на ЕС и съюзниците,
предадоха от пресцентъра на МВнР. "ДЕМОКРАТИЧНА БЪЛГАРИЯ" ЩЕ ИМА ПОВЕЧЕ ДЕПУТАТИ ОТ "ПРОДЪЛЖАВАМЕ ПРОМЯНАТА" В КОАЛИЦИЯТА (СПИСЪК) За първи път
" Демократична България " ще има повече народни представители от партньорите в коалицията от " Продължаваме промяната " в новия
52-и парламент, показват предварителните изчисления на разпределението на мандатите. Часове след края на обработката на изборните протоколи и сметките с
преференциалния вот предстои обявяването и на пълния списък с избраните за нови 240 депутати, а според данни на "Дневник" формацията
на Асен Василев ще има 16 депутати, а ДБ - 21 депутати. "ОТ КУХНЯТА" НА БРЮКСЕЛ: БЪЛГАРИЯ Е ТЕЖКО ЗАВИСИМА
ОТ ЕВРОФОНДОВЕТЕ И "СЛЕДВАЩИЯТ ПРИЯТЕЛ НА ПУТИН" ЩЕ ВНИМАВА Европейският съюз гледа с тревога към България след убедителната изборна победа
на "Прогресивна България" и Румен Радев във вота на 19 април, която ще даде на формацията 131 места и пълно
мнозинство в 52-рото Народно събрание. Причината за безпокойството е заявеното желание на бившия президент за възстановяване на диалога с Русия,
която вече пета година води агресивна война в Украйна - призив, който се хареса на Кремъл . &lt;img src="https://public.flourish.studio/visualisation/28555533/thumbnail" mce_src="https://public.flourish.studio/visualisation/28555533/thumbnail"
width="100%" alt="visualization" /&gt; &lt;img src="https://public.flourish.studio/visualisation/28594182/thumbnail" mce_src="https://public.flourish.studio/visualisation/28594182/thumbnail" width="100%" alt="visualization" /&gt; КАК РАДЕВ СЪБРА ПОДКРЕПА: ОБЯСНЯВА БОРЯНА ДИМИТРОВА (ВИДЕО) В последното проучване,
което публикувахме, попитахме хората какво предпочитат - една партия да има мнозинство или да има коалиционно управление? 49% казаха, че
предпочитат една партия да има мнозинство. ПРОГНОЗА ЗА ВРЕМЕТО - 22 АПРИЛ 2026 Г. (СРЯДА) На 22 април 2026 г.
атмосферното налягане ще е малко по-ниско от средното за месеца. Ще започне да се повишава. Очакваните минимални температури ще бъдат
между 4° и 9°, в София – около 4°. Облачността ще е предимно значителна и на места ще има валежи
от дъжд. По-интензивни и с гръмотевици ще са явленията в крайните южни и североизточни райони. Вятърът ще е слаб до
умерен от север, в Източна България от изток. Максималните температури ще бъдат между 10° и 15°, в София – около
11°, показва прогнозата за времето на НИМХ. Последвайте ни в Google News Showcase , за да получавате още актуални новини.
Actualno.com Отговорен редактор новини

--- "От кухнята" на Брюксел: България е тежко зависима от еврофондовете и "следващият приятел на Путин" ще внимава ---
"От кухнята" на Брюксел: България е тежко зависима от еврофондовете и "следващият приятел на Путин" ще внимава 21 април 2026,
17:14 часа 5673 прочитания 0 коментара Снимка: Getty Images Европейският съюз гледа с тревога към България след убедителната изборна победа
на "Прогресивна България" и Румен Радев във вота на 19 април, която ще даде на формацията 131 места и пълно
мнозинство в 52-рото Народно събрание. Причината за безпокойството е заявеното желание на бившия президент за възстановяване на диалога с Русия,
която вече пета година води агресивна война в Украйна - призив, който се хареса на Кремъл . &lt;img src="https://public.flourish.studio/visualisation/28555533/thumbnail" mce_src="https://public.flourish.studio/visualisation/28555533/thumbnail"
width="100%" alt="visualization" /&gt; &lt;img src="https://public.flourish.studio/visualisation/28594182/thumbnail" mce_src="https://public.flourish.studio/visualisation/28594182/thumbnail" width="100%" alt="visualization" /&gt; Победата на Радев е важна, "защото е вероятно той да обърне
България отново към Москва", коментират на 21 април водещите на подкаста Brussels Playbook на брюкселското издание Politico. "Когато беше президент,
Радев не разкритикува руската инвазия в Украйна, но осъди санкциите срещу Русия", припомнят те. Въпреки това отбелязват, че Радев "не
изключва да сформира коалиция с проевропейски партии, за да направи правителството по-стабилно, особено ако те му помогнат да се изправи
срещу корупцията – нещо, зад което Брюксел би застанал". Още: Няма такава шизофрения: България не може да преживее отказа на
СССР да я вземе за 16-та република ЕС реши проблема "Орбан", но се появи нов Журналистът Иън Уишърт отбеляза, че
за ЕС може би изглежда така, че все едно е разрешил един проблем и се е отървал от унгарския премиер
Виктор Орбан, "който създаваше проблеми в продължение на 16 години, а изведнъж се появява нов – в България, който иска
сближаване с Москва". Брюксел наистина наблюдаваше изкъсо изборите. Председателят на Европейската комисия Урсула фон дер Лайен и председателят на Европейския
съвет Антонио Коща поздравиха Радев, подчертавайки европейския път на България. "Но, разбира се, ще е предизвикателство. Не само заради залитането
към Русия, но той (Радев) беше против и приемането на еврото от страна на България", припомня ководещата. Всичко за войната
в Украйна на живо във Viber канала ни! Последвайте ни тук! Още: Внушителният брой гласове и успех на Радев, изпреварили
Борисов от 2009 г. и напомнили за рекорд на Иван Костов (СНИМКИ) "Следващият приятел на Путин" Не е изненадващо, че
някои евродепутати изразиха остри критики към Радев. Австрийският член на Европарламента от социалдемократите Андреас Шийдер нарече Радев „следващия приятел на
Путин“ и каза, че Виктор Орбан му предава щафетата, цитираха думите му водещите на подкаста . Снимка: БГНЕС Те пуснаха
и кратък откъс от думите на Румен Радев след изборната победа, в които той наблегна на това, че Европа се
нуждае от "критично мислене и прагматизъм" и че е станала "жертва на амбицията си да е морален лидер в свят
без правила": Радев даде пример с Макрон и Мерц: Диалогът с Русия трябва да се върне (ВИДЕО) . Ще натиска
ли Радев ЕС в полза на Москва: зависимостта от еврофондовете е фактор "Това, че България ще има най-проруското и антиевропейско
правителство от комунизма насам, означава ли, че ЕС ще има проблем?", попита единият от водещите, а другият отвърна с информация
от "кухнята". "Това, което чуваме от дипломати, е, че той (Радев) е поставен в друга лига спрямо Орбан. Ще разчита
на по-малко конфронтации, няма да е толкова систематичен в блокирането на решения. В крайна сметка България остава тежко зависима от
еврофондовете", каза тя, намеквайки, че потенциалният бъдещ премиер на България няма да иска да рискува предвидените евросредства за страната ни.
Още: Асен Василев с пророчески думи преди "сглобката": До 18-24 месеца проруските сили ще вземат превес в парламента (ВИДЕО) Виктор
Орбан редовно блокираше решения на ЕС в полза на Украйна, включително заема от 90 милиарда евро, и пакети от санкции
срещу Русия. Сега той отстъпи в Унгария на Петер Мадяр от дясноцентристката формация "Тиса", който се очаква да подобри отслабените
връзки между Будапеща и Брюксел. Те изтъняха най-вече заради проблемите на Унгария да гарантира върховенството на закона и свободата на
медиите при управлението на "Фидес". И докато лидерът на "Прогресивна България" още не е стъпил в Брюксел - за първи
път като премиер, служебният външен министър зове ЕС да приеме важни решения в подкрепа на Украйна: Преди да дойде Радев:
Надежда Нейнски призова ЕС да се разбърза със заема за Украйна и новия пакет санкции срещу Русия . Последвайте ни
в Google News Showcase , за да получавате още актуални новини. Димитър Радев Отговорен редактор Еврофондове Европейски съюз Русия Виктор
Орбан предсрочни парламентарни избори Румен Радев Politico война Украйна предсрочни парламентарни избори 2026 Прогресивна България

--- Със заем и без субсидия: БСП свива разходите след изборния провал ---
Със заем и без субсидия: БСП свива разходите след изборния провал 21 април 2026, 14:46 часа 945 прочитания 0 коментара
Снимка: БГНЕС БСП завършва кампанията си за изборите "без особени задължения", но свива разходите оттук нататък, обяви лидерът на столетницата
Крум Зарков. В средата на март той обяви, че формацията ще изтегли банков заем, за да финансира предизборната си кампания,
защото наличните ѝ средства са се оказали недостатъчни. Резултатът от парламентарния вот - 3,02% подкрепа - означава не само оставане
извън 52-рия парламент, но и загуба на държавната субсидия. Причината е, че БСП участва в изборите в коалиция – "БСП-Обединена
левица", а според Закона за политическите партии субсидии получават само коалициите, получили над 4% от действителните гласове ( партиите получават
субсидия за получен над 1% ). Още: След "унизителните 3%" на изборите: Гуцанов поиска оставката на Крум Зарков &amp;amp;lt;img src="https://public.flourish.studio/visualisation/28594182/thumbnail"
mce_src="https://public.flourish.studio/visualisation/28594182/thumbnail" width="100%" alt="visualization" /&amp;amp;gt; Крум Зарков: "Финансовата ситуация не е драматична" „Ние финансирахме напълно публично нашата кампания със заем, но
финансовата ситуация към момента в БСП не е драматична, доколкото ние усвоихме част от този заем. Очакваме последната субсидия, на
която ще имаме право този месец. И, общо взето, завършваме тази кампания без особени задължения. Всичко тук е финансово изрядно
и изплатено. Проблемът наистина ще дойде с издръжката оттук нататък, но този проблем е преодолим“, каза Зарков. Независими и обективни
новини - Actualno.com ги представя и във Viber! Последвайте ни тук! Снимка: БГНЕС "Естествено, ще трябва да вземем необходимите действия
за свиване на разходите. Но както гласеше една стара поговорка: „Един проблем ако се решава с пари, не е точно
проблем“. В този ред на мисли – това са трудности, които са напълно преодолими с действията на една задружна партия
и нейните съмишленици“, допълни той. Крум Зарков обяви, че ще иска вот на доверие от Националния съвет на БСП и
че ще си подаде оставката като председател, ако не го получи: Крум Зарков поиска вот на доверие и обяви мащабен
процес на промяна в БСП . Последвайте ни в Google News Showcase , за да получавате още актуални новини. Димитър
Радев Отговорен редактор БСП партийна субсидия предсрочни парламентарни избори субсидия Крум Зарков предсрочни парламентарни избори 2026

--- Внушителният брой гласове и успех на Радев, изпреварили Борисов от 2009 г. и напомнили за рекорд на Иван Костов (СНИМКИ) ---
Внушителният брой гласове и успех на Радев, изпреварили Борисов от 2009 г. и напомнили за рекорд на Иван Костов (СНИМКИ)
21 април 2026, 14:01 часа 1271 прочитания 0 коментара Снимка: "Прогресивна България" 1 444 924 гласа за изборна победа -
неочаквана електорална вълна, донесла едноличната победа на "Прогресивна България" на вота на 19 април. Стойност, която доближава максимално последната подобна
ярка изборна победа и вълна на ГЕРБ през 2009 г., показва исторически преглед на Actualno.com . На 5 юли 2009
г. формацията на Боико Борисов за първи път участва в парламентарни избори и ги печели с резултат от 39,7% при
избирателна активност от 60,20%. Те получават 116 мандата, след като за тях са гласували 1 678 641 души - рекорд,
неподобрен след появата на НДСВ през 2001 г. На следващите редовни избори за парламент - на 12 май, 2013 г.
ГЕРБ печелят 30,535%, или гласовете на 1 081 605 души. Те получават 97 мандата в парламента при 51,33% избирателна активност.
В следващите избори до 2021 г., които печелят, ГЕРБ запазва първото си място на победители, но все с резултати около
милион гласа. На 5 октомври 2014 г., когато има предсрочни парламентарни избори, ГЕРБ са първи, като получават 32,67%, или гласовете
на 1 072 491 души. Те си осигуряват 84 мандата в парламента при 46,66% избирателна активност. На предсрочните избори на
26 март 2017 г. ГЕРБ вдигат отново леко своя резултат, като получават 33,54%, или гласовете на 1 147 292. Те
си осигуряват 95 мандата при 54,07% избирателна активност. Още: Шамар за бившата власт: Половин милион гласа по-малко след протести, нахалство
и феномена Радев (СНИМКИ) До сега, когато "Прогресивна България" поставя нов рекорд за последните 17 години. Историческите успехи Все така
ненадминати и до днес обаче остават блестящите изборни победи с по над милион гласа за СДС, БСП, ОДС и НДСВ
в първите десет години от демократичната ни история. Въпреки сериозните исторически различия между отделните случаи и фундаментално отличаващата се обществено-политическа
ситуация около всеки отделен вот, то абсолютните стойности на гласове могат да се сравнят. Независими и обективни новини - Actualno.com

In [164]:
def decode_html_entities(text: str) -> str:
    if not isinstance(text, str):
        return text
    prev = None
    while prev != text:
        prev = text
        text = html.unescape(text)
    return text


df["full_text"] = df["full_text"].apply(decode_html_entities)

In [165]:
# Word count recheck after all cleaning
df["word_count"] = df["full_text"].fillna("").apply(lambda x: len(x.split()))
short = df[df["word_count"] < 30]
print(f"Articles under 30 words after cleaning: {len(short)}")
print(short[["source", "title", "word_count"]].to_string())

Articles under 30 words after cleaning: 178
             source                                                                                                                                                          title  word_count
1513            bta                    За учебната 2025/2026 година чуждестранните студенти в Софийския университет са 1431 и са от 55 държави, съобщиха за БТА от висшето училище           3
2860            bta                       Четири са вече жертвите на вчерашната катастрофа между автобус и две коли в София; скоростта на автомобилите е била между 104 и 150 км/ч          24
3604            bta  Двама души загубиха живота си в катастрофа с две леки коли и автобус на градския транспорт в София, шофьорите на леките автомобили са се движили със 150 км/ч          28
6075            bta      Предложението за асоциирано членство на Украйна е възможност, която Киев трябва да използва, каза евродепутатът Дейвид Макалистър пред Европейския нюзрум          26
7519            bta                                                                                               Баскетболният Цървена звезда избра испанец за нов старши треньор          24
9210   standartnews                                                                                                                            Рожден ден днес има култова актриса          22
9826        24chasa                                                                                                       Иванчо казва защо Варна трябва да е домакин на Евровизия           0
10120  standartnews                                                                                                                              Рожден ден днес има култов актьор          19
10248           bta                                                                Френският Пари Сен Жермен спечели за втора поредна година Шампионската лига на Европа по футбол          25
10890           bta                                                                 КНА: Кипърката д-р Николета Деметриу е сред носителите на наградата „Европа Ностра“ за 2026 г.          21
12301  standartnews                                                                                                                             Вижте кой празнува рожден ден днес          22
13540  standartnews                                                                                                                    Рожден ден днес имат легендарни композитори          29
13631           bta                                                                              Кристъл Палас победи Райо Валекано и триумфира с трофея в Лигата на конференциите          23
14970       24chasa                                                                                                         Резултати, голмайстори и крайно класиране в Първа лига           0
15143           bta                                                      Дисциплинарната комисия наложи глоби на клубовете за общо близо 11 000 евро след последния кръг за сезона          26
16283       24chasa                                                                                                     Резултати от последния кръг в серия "А" и крайно класиране           0
16299       24chasa                                                                                              Резултати от последния кръг в Примера дивисион и крайно класиране           0
16326       24chasa                                                                                                Резултати от последния кръг във Висшата лига и крайно класиране           0
16998       24chasa                                                                                                       Резултати, голмайстори и крайно класиране във Втора лига           0
17056           bta                                                                                СФК Амиго Северозапад е новият шампион на България по футзал за сезон 2025/2026          13
18157       24chasa                                                                                                          Програма за последния кръг във Втора лига и класиране           0
18225           bta                                                                                Стоян Арсов ще свири мача между Лудогорец и ЦСКА от последния кръг в Първа лига          28
18863           bta                    Над 70 л/кв.м дъжд са се излели за 40 минути над Велико Търново и съседните населени места тази вечер, съобщиха от областната администрация           3
19107          nova                                                                                                                         Янез Янша е новият премиер на Словения          26
19372          nova                                                                                                           Полицията с акция срещу наркоразпространение в София          16
19417       24chasa                                                                                                                       Накъде с децата през уикенда (23-24 май)          22
19440       24chasa                                                                                                           Програма за последния кръг в Първа лига и класирания           0
21261       24chasa                                                                                                    "Пазарджик Рестарт" - изтегли от тук безплатно приложението          28
22688           bta                                                                     САЩ задържаха свързан с Иран петролен танкер в Индийския океан, съобщи „Уолстрийт Джърнъл“          13
22732           bta                                                                          Подкрепата за Доналд Тръмп е спаднала до 35%, показва ново допитване на Ройтерс/Ипсос          13
22898          nova                                                                                     Лилия Стоянович е новият заместник-министър на труда и социалната политика          28
23222       24chasa                                                                                   Резултати, голмайстори, класирания и програма за последния кръг в Първа лига           0
24026       24chasa                                                                                                  Резултати от последния кръг в Бундеслигата и крайно класиране           0
24128       24chasa                                                                                                                       Резултати от кръга в Испания и класиране           0
24359       24chasa                                                                                                     Резултати и голмайстори от кръга в Първа лига + класирания           0
24367       24chasa                                                                                                                Резултати от 36-ия кръг в серия "А" и класиране           0
25104  standartnews                                                                                                                       Рожден ден днес има европейска шампионка          24
25587       24chasa                                                                                                     Резултати от предпоследния кръг във Втора лига и класиране           0
25967           bta                                                           Триумф за Дара и България на Евровизия, благодарим за силните емоции, каза президентът Илияна Йотова          18
26044  standartnews                                                                                                       Рожден ден днес има легенда на художествената гимнастика          23
27073           bta                                                        Нападателят Стивън Стоянчов бе избран от привържениците на Етър за Футболист номер 1 на сезон 2025/2026          16
27277       24chasa                                                                                                                Програма за кръга във Втора лига и класиране+тв           0
27420           bta                                             Нова рубрика в мобилното приложение "еЗдраве" е открита по повод Деня на съпричастност със засегнатите от ХИВ/СПИН          17
27424           bta                     С бдение пред църквата „Св. Висарион Смоленски“ в Смолян ще бъде отбелязан Международният ден за съпричастност със засегнатите от ХИВ/СПИН          20
27991           bta                                                   С вечерно бдение РЗИ-Стара Загора ще отбележи Международния ден за съпричастност със засегнатите от ХИВ/СПИН          15
28198           bta                                               Столичната галерия Monument представя експозицията „Пътуващият паметник“ на артистичния тандем Мисирков/Богданов          11
28315  standartnews                                                                                                   Ето го новият победител в "Хелс китчън"! Прибра 50 хил. евро          29
28450           bta                                                                                         Българската метъл група Axecutor открива концерта на Possessed в София          12
29348           bta                                                                                                              Левандовски напуска Барселона след края на сезона          18
29624           bta                                                                             Първите два отбора в българското първенство завършиха при равен резултат в Разград          20
30363           bta                                                                                               Вятър със скорост до 86 км/час събори дървета и клони в Русенско           6
30663           bta                                                                 Общо 42 паралелки са заложени в държавния план-прием за учебната 2026/2027 г. в област Разград          11
30992       24chasa                                                                                                         Резултати от 35-ия кръг в Примера дивисион и класиране           0
31216       24chasa                                                                                                            Резултати от 36-ия кръг на Висшата лига и класиране           0
31482       24chasa                                                                                              Резултати, голмайстори и класиране след 32-ия кръг във Втора лига           0
31516       24chasa                                                                                                                   Резултати от 36-ия кръг в Италия и класиране           0
32106       24chasa                                                                                                                  Малкият Иванчо казва какъв вирус вилнее у нас           0
32239       24chasa                                                                                                     Резултати от предпоследния кръг в Бундеслигата и класиране           0
32718          nova                                                                                                                Назначиха двама заместник-министри на финансите          22
32744       24chasa                                                                                                               Резултати, голмайстори и класирания в Първа лига           0
33567      actualno                                                     Hristijan Mickoski unveils controversial monument in Albania in violation of the Prespa Agreement (PHOTOS)           0
33614           bta                                                              Йесид Валбуена донесе победа на Берое над Добруджа (Добрич) в среща от първенството на efbet Лига          24
33887       24chasa                                                                                                           Програма за 32-ия кръг във Втора лига и класиране+тв           0
33922       monitor                                                                                                          СТРАХОТНО СВЕТЛИННО ШОУ НА "ГЕРЕНА"! (ВИДЕО + СНИМКИ)          25
33963           bta                                                                                                              Спартак Варна победи Славия в среща от Първа лига          17
34566           bta                                                                                                                  Лудогорец победи Левски в среща от Първа лига          16
34672           bta                                                                                                           Черно море надигра Ботев Пловдив с два гола от дузпи          18
34891           bta                                          Монтана направи нова грешка в битката за оцеляване и трябваше да се задоволи само с точка от мача с Локомотив (София)          29
35410  standartnews                                                                                                                         Рожден ден днес има легендарен щангист          25
35413           bta                                                       Екипът на Венецианското биенале организира вечер под надслов „Биенале на словото / Несъгласието и мирът“          11
35573           bta                                                                         С гол на Мохамед Брахими ЦСКА (Сф) победи ЦСКА 1948 и излезе на 2-о място в efbet Лига          26
35756       24chasa                                                                                                          Резултати и голмайстори от полуфиналите в Лига Европа           0
35898       24chasa                                                                                                                    Програма за кръга в Първа лига и класирания           0
35906       24chasa                                                                                              Резултати и голмайстори от полуфиналите в Лигата на конференциите           0
36012           bta                              В библиотеката в Благоевград бяха представени историите на световноизвестни личности, които през живота си са били и библиотекари          23
36784           bta                                                                                             „Пътуващият паметник” на тандема Мисирков/Богданов гостува в София           5
36917  standartnews                                                                                                                           Рожден ден днес имат култови актриси          18
37097       24chasa                                                                                                             Резултати и програма за 1/2-финалите в Лига Европа           0
37320       24chasa                                                                                                      Резултати, голмайстори, класиране и програма в Първа лига           0
37354       24chasa                                                                                                 Резултати и програма за 1/2-финалите в Лигата на конференциите           0
37672       24chasa                                                                                                    Резултати и голмайстори от полуфиналите в Шампионската лига           0
38466       24chasa                                                                                                                        Накъде с децата през уикенда (9-10 май)          22
38576       24chasa                                                                                                        Резултати, голмайстори и програма на кръга в Първа лига           0
39004       24chasa                                                                                                          Как се реди кабинетът - вижте комикса на Ивайло Нинов           0
39407       24chasa                                                                                                Резултати и голмайстори от 31-ия кръг на Втора лига и класиране           0
39413       24chasa                                                                                                       Резултати и програма за полуфиналите в Шампионската лига           0
39418       24chasa                                                                                                           Резултати от 35-ия кръг във Висшата лига и класиране           0
39512       24chasa                                                                                                               Резултати от 35-ия кръг на серия "А" и класиране           0
39875       24chasa                                                                                                         Резултати от 34-ия кръг в Примера дивисион и класиране           0
40600       24chasa                                                                                                             Резултати от 32-ия кръг в Бундеслигата и класиране           0
40843       24chasa                                                                                  Резултати и голмайстори от втория кръг в плейофите на Първа лига и класирания           0
42087       24chasa                                                                                          Защо на колоездачите от Джиро д'Италия ще им трябват дълбоки грайфери           0
42148       24chasa                                                                                                            Програма за 31-ия кръг на Втора лига и класиране+тв           0
42657       24chasa                                                                                           Програма за втория кръг в плейофната фаза на Първа лига и класирания           0
42719       24chasa                                                                                        Резултати и голмайстори от първите 1/2-финали в Лигата на конференциите           0
42730       24chasa                                                                                                    Резултати и голмайстори от първите полуфинали в Лига Европа           0
43635       24chasa                                                                                                                         Накъде с децата през уикенда (2-3 май)          22
44356       24chasa                                                                                                            Политическите дъвки - вижте комикса на Ивайло Нинов           0
45387       24chasa                                                                                                            Резултати от 31-ия кръг на Бундеслигата и класиране           0
46472       24chasa                                                                                                                                           Как МВР бори Картофа           0
47288       24chasa                                                                                               Програма за първия кръг от плейофната фаза на елита и класирания           0
47486       24chasa                                                                                                              Програма за 30-ия кръг във Втора лига и класиране           0
47675       24chasa                                                                                                                     Накъде с децата през уикенда (25-26 април)          22

In [166]:
short_mask = df["word_count"] < 30
print(f"Articles under 30 words across whole dataset: {short_mask.sum()}\n")

for _, row in df[short_mask].iterrows():
    print(f"--- {row['title']} ({row['word_count']} words) ---")
    print(row["url"])
    print(row["full_text"])
    print()

Articles under 30 words across whole dataset: 178

--- За учебната 2025/2026 година чуждестранните студенти в Софийския университет са 1431 и са от 55 държави, съобщиха за БТА от висшето училище (3 words) ---
https://www.bta.bg/bg/news/lik/1142704-za-uchebnata-2025-2026-godina-chuzhdestrannite-studenti-v-sofiyskiya-universitet
За учебната 2025

--- Четири са вече жертвите на вчерашната катастрофа между автобус и две коли в София; скоростта на автомобилите е била между 104 и 150 км/ч (24 words) ---
https://www.bta.bg/bg/news/bulgaria/1142045-chetiri-sa-veche-zhertvite-na-vcherashnata-katastrofa-mezhdu-avtobus-i-dve-koli-
Четири са вече жертвите на вчерашната катастрофа между автобус и две коли в София; скоростта на автомобилите е била между 104 и 150 км

--- Двама души загубиха живота си в катастрофа с две леки коли и автобус на градския транспорт в София, шофьорите на леките автомобили са се движили със 150 км/ч (28 words) ---
https://www.bta.bg/bg/news/bulgaria/1141760-dvama-dushi-zagubiha-zhivota-si-v-katastrofa-s-dve-leki-koli-i-avtobus-na-gradsk
Двама души загубиха живота си в катастрофа с две леки коли и автобус на градския транспорт в София, шофьорите на леките автомобили са се движили със 150 км

--- Предложението за асоциирано членство на Украйна е възможност, която Киев трябва да използва, каза евродепутатът Дейвид Макалистър пред Европейския нюзрум (26 words) ---
https://www.bta.bg/bg/news/world/1139844-predlozhenieto-za-asotsiirano-chlenstvo-na-ukrayna-e-vazmozhnost-koyato-kiev-tr
Предложението за асоциирано членство на Украйна е възможност, която Киев трябва да използва, каза евродепутатът Дейвид Макалистър пред Европейския нюзрум
Германският евродепутат от Европейската народна партия

--- Баскетболният Цървена звезда избра испанец за нов старши треньор (24 words) ---
https://www.bta.bg/bg/news/sport/1139059-basketbolniyat-tsarvena-zvezda-izbra-ispanets-za-nov-starshi-trenyor
Баскетболният Цървена звезда избра испанец за нов старши треньор
Баскетболният Цървена звезда (Белград) е избрал нов старши треньор след разочароващия край на сезон 2025

--- Рожден ден днес има култова актриса (22 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-ima-kultova-aktrisa-635599.html
Рожден ден днес празнуват:
Пламена Гетова, актриса
Калин Георгиев, бивш главен секретар на МВР
Георги Станчев, композитор и певец
Надя Попова, поетеса

--- Иванчо казва защо Варна трябва да е домакин на Евровизия (0 words) ---
https://www.24chasa.bg/mneniya/article/22950318


--- Рожден ден днес има култов актьор (19 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-ima-kultov-aktyor-635418.html
Рожден ден днес празнуат:
Николай Сотиров, актьор
Веселин Тодоров, изпълнителен директор на „Сиела“
Лияна Панделиева, журналистка
Васил Сотиров, писател

--- Френският Пари Сен Жермен спечели за втора поредна година Шампионската лига на Европа по футбол (25 words) ---
https://www.bta.bg/bg/news/sport/1137195-frenskiyat-pari-sen-zhermen-specheli-za-vtora-poredna-godina-shampionskata-liga-
ОБНОВЕНА Френският Пари Сен Жермен спечели за втора поредна година Шампионската лига на Европа по футбол
Шампионска лига на Европа - финал за сезон 2025

--- КНА: Кипърката д-р Николета Деметриу е сред носителите на наградата „Европа Ностра“ за 2026 г. (21 words) ---
https://www.bta.bg/bg/news/balkans/1136868-kna-kiparkata-d-r-nikoleta-demetriu-e-sred-nositelite-na-nagradata-evropa-nost
КНА: Кипърката д-р Николета Деметриу е сред носителите на наградата „Европа Ностра“ за 2026 г.
Тридесетте носители на наградите „Европейско наследство“

--- Вижте кой празнува рожден ден днес (22 words) ---
https://www.standartnews.com/balgariya-obshtestvo/vizhte-koy-praznuva-rozhden-den-dnes-635268.html
Рожден ден днес празнуват:
Рени, попфолк певица
Ген. Драгомир Димитров, бивш шеф на разузнаването
Даниел Дянков, художник
Петя Аврамова, инженер, бивш министър

--- Рожден ден днес имат легендарни композитори (29 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-imat-legendarni-kompozitori-635132.html
Рожден ден днес празнуват:
Развигор Попов, композитор
Стефан Димитров, композитор
Владимир Костов, журналист
Чавдар Шинов, сценарист и писател
Денита Василева, Ръководител, здравна комуникация и лекарствена информация в УМБАЛ „Софиямед“

--- Кристъл Палас победи Райо Валекано и триумфира с трофея в Лигата на конференциите (23 words) ---
https://www.bta.bg/bg/news/sport/1134912-kristal-palas-pobedi-rayo-valekano-i-triumfira-s-trofeya-v-ligata-na-konferentsi
Кристъл Палас победи Райо Валекано и триумфира с трофея в Лигата на конференциите
Финал в турнира по футбол Лига на конференциите, сезон 2025

--- Резултати, голмайстори и крайно класиране в Първа лига (0 words) ---
https://www.24chasa.bg/sport/article/22922662


--- Дисциплинарната комисия наложи глоби на клубовете за общо близо 11 000 евро след последния кръг за сезона (26 words) ---
https://www.bta.bg/bg/news/sport/1133897-distsiplinarnata-komisiya-nalozhi-globi-na-klubovete-za-obshto-blizo-11-000-evro
Дисциплинарната комисия наложи глоби на клубовете за общо близо 11 000 евро след последния кръг за сезона
Решения на Дисциплинарната комисия на БФС:
36-ти кръг ППФЛ

--- Резултати от последния кръг в серия "А" и крайно класиране (0 words) ---
https://www.24chasa.bg/sport/article/22914079


--- Резултати от последния кръг в Примера дивисион и крайно класиране (0 words) ---
https://www.24chasa.bg/sport/article/22914640


--- Резултати от последния кръг във Висшата лига и крайно класиране (0 words) ---
https://www.24chasa.bg/sport/article/22914967


--- Резултати, голмайстори и крайно класиране във Втора лига (0 words) ---
https://www.24chasa.bg/sport/article/22911020


--- СФК Амиго Северозапад е новият шампион на България по футзал за сезон 2025/2026 (13 words) ---
https://www.bta.bg/bg/news/sport/1132869-sfk-amigo-severozapad-e-noviyat-shampion-na-balgariya-po-futzal-za-sezon-2025-20
СФК Амиго Северозапад е новият шампион на България по футзал за сезон 2025

--- Програма за последния кръг във Втора лига и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22905425


--- Стоян Арсов ще свири мача между Лудогорец и ЦСКА от последния кръг в Първа лига (28 words) ---
https://www.bta.bg/bg/news/sport/1132424-stoyan-arsov-shte-sviri-macha-mezhdu-ludogorets-i-tsska-ot-posledniya-krag-v-par
Стоян Арсов ще свири мача между Лудогорец и ЦСКА от последния кръг в Първа лига
Съдийски назначения за срещите от последния, 36-и кръга в Първа лига, сезон 2025

--- Над 70 л/кв.м дъжд са се излели за 40 минути над Велико Търново и съседните населени места тази вечер, съобщиха от областната администрация (3 words) ---
https://www.bta.bg/bg/news/bulgaria/1132163-nad-70-l-kv-m-dazhd-sa-se-izleli-za-40-minuti-nad-veliko-tarnovo-i-sasednite-nas
Над 70 л

--- Янез Янша е новият премиер на Словения (26 words) ---
https://nova.bg/news/view/2026/05/22/538128/%D1%8F%D0%BD%D0%B5%D0%B7-%D1%8F%D0%BD%D1%88%D0%B0-%D0%B5-%D0%BD%D0%BE%D0%B2%D0%B8%D1%8F%D1%82-%D0%BF%D1%80%D0%B5%D0%BC%D0%B8%D0%B5%D1%80-%D0%BD%D0%B0-%D1%81%D0%BB%D0%BE%D0%B2%D0%B5%D0%BD%D0%B8%D1%8F/
51 депутати подкрепиха лидера на десницата
Парламентът на Словения избра Янез Янша за министър-председател.
51 депутати подкрепиха лидера на десницата, а 36 бяха против.
Източник: БГНЕС

--- Полицията с акция срещу наркоразпространение в София (16 words) ---
https://nova.bg/news/view/2026/05/22/538116/%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B8%D1%8F%D1%82%D0%B0-%D1%81-%D0%B0%D0%BA%D1%86%D0%B8%D1%8F-%D1%81%D1%80%D0%B5%D1%89%D1%83-%D0%BD%D0%B0%D1%80%D0%BA%D0%BE%D1%80%D0%B0%D0%B7%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2-%D1%81%D0%BE%D1%84%D0%B8%D1%8F/
Има задържани
Полицията провежда специализирана операция срещу наркоразпространение в София.
По информация на NOVA има задържани.

--- Накъде с децата през уикенда (23-24 май) (22 words) ---
https://www.24chasa.bg/ozhivlenie/article/22899069
Ето няколко идеи къде да заведете децата в София този уикенд.

Ето няколко идеи къде да заведете децата в София този уикенд.

--- Програма за последния кръг в Първа лига и класирания (0 words) ---
https://www.24chasa.bg/sport/article/22900342


--- "Пазарджик Рестарт" - изтегли от тук безплатно приложението (28 words) ---
https://www.24chasa.bg/bulgaria/article/22889587
"Пазарджик Рестарт" - изтегли от тук безплатно приложението
Специален проект
Четете още
"Търговище Рестарт" - изтегли приложението от тук
"Габрово Рестарт" - изтегли приложението от тук
НА ЖИВО

--- САЩ задържаха свързан с Иран петролен танкер в Индийския океан, съобщи „Уолстрийт Джърнъл“ (13 words) ---
https://www.bta.bg/bg/news/world/1129603-sasht-zadarzhaha-svarzan-s-iran-petrolen-tanker-v-indiyskiya-okean-saobshti-uo
Подкрепата за Доналд Тръмп е спаднала до 35%, показва ново допитване на Ройтерс

--- Подкрепата за Доналд Тръмп е спаднала до 35%, показва ново допитване на Ройтерс/Ипсос (13 words) ---
https://www.bta.bg/bg/news/world/1129598-podkrepata-za-donald-tramp-e-spadnala-do-35-pokazva-novo-dopitvane-na-royters-
Подкрепата за Доналд Тръмп е спаднала до 35%, показва ново допитване на Ройтерс

--- Лилия Стоянович е новият заместник-министър на труда и социалната политика (28 words) ---
https://nova.bg/news/view/2026/05/19/537732/%D0%BB%D0%B8%D0%BB%D0%B8%D1%8F-%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%BE%D0%B2%D0%B8%D1%87-%D0%B5-%D0%BD%D0%BE%D0%B2%D0%B8%D1%8F%D1%82-%D0%B7%D0%B0%D0%BC%D0%B5%D1%81%D1%82%D0%BD%D0%B8%D0%BA-%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%8A%D1%80-%D0%BD%D0%B0-%D1%82%D1%80%D1%83%D0%B4%D0%B0-%D0%B8-%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D0%BD%D0%B0%D1%82%D0%B0-%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0/
Това се случи със заповед на министър-председателя Румен Радев
Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на труда и социалната политика е назначена Лилия Петрова Стоянович.

--- Резултати, голмайстори, класирания и програма за последния кръг в Първа лига (0 words) ---
https://www.24chasa.bg/sport/article/22880129


--- Резултати от последния кръг в Бундеслигата и крайно класиране (0 words) ---
https://www.24chasa.bg/sport/article/22874968


--- Резултати от кръга в Испания и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22874286


--- Резултати и голмайстори от кръга в Първа лига + класирания (0 words) ---
https://www.24chasa.bg/sport/article/22873476


--- Резултати от 36-ия кръг в серия "А" и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22873827


--- Рожден ден днес има европейска шампионка (24 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-ima-evropeyska-shampionka-634016.html
Рожден ден днес празнуват:
Ивет Лалова, лекоатлетка, европейска шампионка
Димитър Николов, икономист, кмет на Бургас
Атанас Славчев, пианист
Емил Емилов, актьор
Вълчан Петров, художник

--- Резултати от предпоследния кръг във Втора лига и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22865729


--- Триумф за Дара и България на Евровизия, благодарим за силните емоции, каза президентът Илияна Йотова (18 words) ---
https://www.bta.bg/bg/news/bulgaria/1127578-triumf-za-dara-i-balgariya-na-evroviziya-blagodarim-za-silnite-emotsii-kaza-pr
Триумф за Дара и България на Евровизия, благодарим за силните емоции, каза президентът Илияна Йотова
"Триумф за DARA

--- Рожден ден днес има легенда на художествената гимнастика (23 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-ima-legenda-na-hudozhestvenata-gimnastika-633829.html
Рожден ден днес имат:
Лилия Игнатова, легендарна шампионка по художествена гимнастика
Пламен Макариев, философ
Румен Леонидов, поет и журналист
Стефка Минева, оперна певица

--- Нападателят Стивън Стоянчов бе избран от привържениците на Етър за Футболист номер 1 на сезон 2025/2026 (16 words) ---
https://www.bta.bg/bg/news/sport/1127225-napadatelyat-stivan-stoyanchov-be-izbran-ot-privarzhenitsite-na-etar-za-futbolis
Нападателят Стивън Стоянчов бе избран от привържениците на Етър за Футболист номер 1 на сезон 2025

--- Програма за кръга във Втора лига и класиране+тв (0 words) ---
https://www.24chasa.bg/sport/article/22855946


--- Нова рубрика в мобилното приложение "еЗдраве" е открита по повод Деня на съпричастност със засегнатите от ХИВ/СПИН (17 words) ---
https://www.bta.bg/bg/news/bulgaria/1126986-nova-rubrika-v-mobilnoto-prilozhenie-ezdrave-e-otkrita-po-povod-denya-na-sapri
Нова рубрика в мобилното приложение "еЗдраве" е открита по повод Деня на съпричастност със засегнатите от ХИВ

--- С бдение пред църквата „Св. Висарион Смоленски“ в Смолян ще бъде отбелязан Международният ден за съпричастност със засегнатите от ХИВ/СПИН (20 words) ---
https://www.bta.bg/bg/news/bulgaria/1126989-s-bdenie-pred-tsarkvata-sv-visarion-smolenski-v-smolyan-shte-bade-otbelyazan-
С бдение пред църквата „Св. Висарион Смоленски“ в Смолян ще бъде отбелязан Международният ден за съпричастност със засегнатите от ХИВ

--- С вечерно бдение РЗИ-Стара Загора ще отбележи Международния ден за съпричастност със засегнатите от ХИВ/СПИН (15 words) ---
https://www.bta.bg/bg/news/bulgaria/1126489-s-vecherno-bdenie-rzi-stara-zagora-shte-otbelezhi-mezhdunarodniya-den-za-saprich
С вечерно бдение РЗИ-Стара Загора ще отбележи Международния ден за съпричастност със засегнатите от ХИВ

--- Столичната галерия Monument представя експозицията „Пътуващият паметник“ на артистичния тандем Мисирков/Богданов (11 words) ---
https://www.bta.bg/bg/news/lik/1126255-stolichnata-galeriya-monument-predstavya-ekspozitsiyata-patuvashtiyat-pametnik-
Столичната галерия Monument представя експозицията „Пътуващият паметник“ на артистичния тандем Мисирков

--- Ето го новият победител в "Хелс китчън"! Прибра 50 хил. евро (29 words) ---
https://www.standartnews.com/lifestyle-lyubopitno/eto-go-noviyat-pobeditel-v-hels-kitchan-pribra-50-hil-evro-633663.html
Денис Морейра-Денисиньо е големият победител в осмия сезон на "Хелс китчън"!
Бразилецът триумфира след оспорвана битка със Симона Спирова и грабна голямата награда от 50 000 евро.
Очаквайте подробности!

--- Българската метъл група Axecutor открива концерта на Possessed в София (12 words) ---
https://www.bta.bg/bg/news/lik/1126365-balgarskata-metal-grupa-axecutor-otkriva-kontserta-na-possessed-v-sofiya
Българската метъл група Axecutor открива концерта на Possessed в София
Българската траш

--- Левандовски напуска Барселона след края на сезона (18 words) ---
https://www.bta.bg/bg/news/sport/1125593-levandovski-napuska-barselona-sled-kraya-na-sezona
Левандовски напуска Барселона след края на сезона
Нападателят Роберт Левандовски ще напусне Барселона в края на сезон 2025

--- Първите два отбора в българското първенство завършиха при равен резултат в Разград (20 words) ---
https://www.bta.bg/bg/news/sport/1125506-parvite-dva-otbora-v-balgarskoto-parvenstvo-zavarshiha-pri-raven-rezultat-v-razg
Първите два отбора в българското първенство завършиха при равен резултат в Разград
Първенство на България по футбол, срещи от 34

--- Вятър със скорост до 86 км/час събори дървета и клони в Русенско (6 words) ---
https://www.bta.bg/bg/news/bulgaria/1125042-vyatar-sas-skorost-do-86-km-chas-sabori-darveta-i-kloni-v-rusensko
Вятър със скорост до 86 км

--- Общо 42 паралелки са заложени в държавния план-прием за учебната 2026/2027 г. в област Разград (11 words) ---
https://www.bta.bg/bg/news/lik/1124734-obshto-42-paralelki-sa-zalozheni-v-darzhavniya-plan-priem-za-uchebnata-2026-2027
Общо 42 паралелки са заложени в държавния план-прием за учебната 2026

--- Резултати от 35-ия кръг в Примера дивисион и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22837023


--- Резултати от 36-ия кръг на Висшата лига и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22836038


--- Резултати, голмайстори и класиране след 32-ия кръг във Втора лига (0 words) ---
https://www.24chasa.bg/sport/article/22833410


--- Резултати от 36-ия кръг в Италия и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22834084


--- Малкият Иванчо казва какъв вирус вилнее у нас (0 words) ---
https://www.24chasa.bg/mneniya/article/22829220


--- Резултати от предпоследния кръг в Бундеслигата и класиране (0 words) ---
https://www.24chasa.bg/sport/article/22830051


--- Назначиха двама заместник-министри на финансите (22 words) ---
https://nova.bg/news/view/2026/05/11/536750/%D0%BD%D0%B0%D0%B7%D0%BD%D0%B0%D1%87%D0%B8%D1%85%D0%B0-%D0%B4%D0%B2%D0%B0%D0%BC%D0%B0-%D0%B7%D0%B0%D0%BC%D0%B5%D1%81%D1%82%D0%BD%D0%B8%D0%BA-%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B8-%D0%BD%D0%B0-%D1%84%D0%B8%D0%BD%D0%B0%D0%BD%D1%81%D0%B8%D1%82%D0%B5/
Това са Людмила Петкова и Росица Велкова-Желева
Министър-председателят Румен Радев назначи двама заместник-министър на финансите.
Това са Людмила Петкова и Росица Велкова-Желева.

--- Резултати, голмайстори и класирания в Първа лига (0 words) ---
https://www.24chasa.bg/sport/article/22826234


--- Hristijan Mickoski unveils controversial monument in Albania in violation of the Prespa Agreement (PHOTOS) (0 words) ---
https://www.actualno.com/balkani/hristijan-mickoski-unveils-controversial-monument-in-albania-in-violation-of-the-prespa-agreement-photos-news_2592259.html


--- Йесид Валбуена донесе победа на Берое над Добруджа (Добрич) в среща от първенството на efbet Лига (24 words) ---
https://www.bta.bg/bg/news/sport/1123020-yesid-valbuena-donese-pobeda-na-beroe-nad-dobrudzha-dobrich-v-sreshta-ot-parve
Йесид Валбуена донесе победа на Берое над Добруджа (Добрич) в среща от първенството на efbet Лига
Първенство на България по футбол, срещи от 33

--- Програма за 32-ия кръг във Втора лига и класиране+тв (0 words) ---
https://www.24chasa.bg/sport/article/22812696


--- СТРАХОТНО СВЕТЛИННО ШОУ НА "ГЕРЕНА"! (ВИДЕО + СНИМКИ) (25 words) ---
https://telegraph.bg/sport/futbol-bulgaria/strahotno-svetlinno-shou-na-gerena-vizhte-kadri-ot-unikalnite-neshta-v-nebeto-za-levski-video-snimki-491052
Невероятно светлинно имаше над ст. "Георги Аспарухов" малко преди награждаването на Левски като шампион на България! Вижте кадри от уникалната атмосфера.
Герена
Герена
Герена
Герена

--- Спартак Варна победи Славия в среща от Първа лига (17 words) ---
https://www.bta.bg/bg/news/sport/1122881-spartak-varna-pobedi-slaviya-v-sreshta-ot-parva-liga
Спартак Варна победи Славия в среща от Първа лига
Първенство на България по футбол, срещи от 33

--- Лудогорец победи Левски в среща от Първа лига (16 words) ---
https://www.bta.bg/bg/news/sport/1122687-ludogorets-pobedi-levski-v-sreshta-ot-parva-liga
Лудогорец победи Левски в среща от Първа лига
Първенство на България по футбол, срещи от 33

--- Черно море надигра Ботев Пловдив с два гола от дузпи (18 words) ---
https://www.bta.bg/bg/news/sport/1122648-cherno-more-nadigra-botev-plovdiv-s-dva-gola-ot-duzpi
Черно море надигра Ботев Пловдив с два гола от дузпи
Първенство на България по футбол, срещи от 33

--- Монтана направи нова грешка в битката за оцеляване и трябваше да се задоволи само с точка от мача с Локомотив (София) (29 words) ---
https://www.bta.bg/bg/news/sport/1122580-montana-napravi-nova-greshka-v-bitkata-za-otselyavane-i-tryabvashe-da-se-zadovol
Монтана направи нова грешка в битката за оцеляване и трябваше да се задоволи само с точка от мача с Локомотив (София)
Първенство на България по футбол, среща от 33

--- Рожден ден днес има легендарен щангист (25 words) ---
https://www.standartnews.com/balgariya-obshtestvo/rozhden-den-dnes-ima-legendaren-shtangist-632998.html
Рожден ден днес празнуват:
Александър Върбанов, легендарен щангист
Пламен Юруков, бизнесмен и политик
Панчо Пасков, фехтовач
Станислав Памукчиев, художник
Захари Иванов, поет
Стайко Мурджев, режисьор

--- Екипът на Венецианското биенале организира вечер под надслов „Биенале на словото / Несъгласието и мирът“ (11 words) ---
https://www.bta.bg/bg/news/lik/1122358-ekipat-na-venetsianskoto-bienale-organizira-vecher-pod-nadslov-bienale-na-slovo

In [167]:
df = df[df["word_count"] >= 30].reset_index(drop=True)
print(f"Remaining articles: {len(df)}")

Remaining articles: 50196

## Checking for duplicated paragraphs

In [168]:
def has_duplicate_paragraphs(text: str) -> bool:
    if not isinstance(text, str):
        return False
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    return len(paragraphs) != len(set(paragraphs))


mask = df["full_text"].apply(has_duplicate_paragraphs)
print(f"Articles with duplicate paragraphs: {mask.sum()}")
print(df[mask]["source"].value_counts().to_string())
print()

for _, row in df[mask].head(10).iterrows():
    print(f"--- {row['title']} ({row['word_count']} words) ---")
    print(f"URL: {row['url']}")
    print_by_words(row["full_text"])
    print()

Articles with duplicate paragraphs: 103
source
24chasa    103

--- Движението в тунел "Топли дол" към Варна бе в активната лента заради разлято гориво (72 words) ---
URL: https://www.24chasa.bg/spravochnik/article/22999268
Временно движението в тунел "Топли дол" на АМ "Хемус" в посока Варна се осъществява в активната лента поради разлято гориво
на пътното платно, съобщиха от АПИ. Трафикът се регулира от "Пътна полиция". По-късно движението бе възстановено. Временно движението в тунел
"Топли дол" на АМ "Хемус" в посока Варна се осъществява в активната лента поради разлято гориво на пътното платно, съобщиха
от АПИ. Трафикът се регулира от "Пътна полиция". По-късно движението бе възстановено.

--- Катастрофа при км 183 от пътя Казанлък - Габрово, движението е в една лента (76 words) ---
URL: https://www.24chasa.bg/spravochnik/article/22999350
Временно движението при км 183 по път I-5 Казанлък - Габрово се осъществява двупосочно в една лента поради ПТП, съобщиха
от АПИ. Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция". Временно движението
при км 183 по път I-5 Казанлък - Габрово се осъществява двупосочно в една лента поради ПТП, съобщиха от АПИ.
Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция".

--- Катастрофа затвори пътя Казанлък - Габрово (44 words) ---
URL: https://www.24chasa.bg/spravochnik/article/22999886
Временно е ограничено движението при км 183 по път I-5 Казанлък - Габрово поради ПТП, съобщиха от АПИ. Шофьорите изчакват
на място. Временно е ограничено движението при км 183 по път I-5 Казанлък - Габрово поради ПТП, съобщиха от АПИ.
Шофьорите изчакват на място.

--- Резултати от контроли (48 words) ---
URL: https://www.24chasa.bg/sport/article/22997315
Хърватия - Словения 2:1 Мароко - Норвегия 1:1 Гърция - Италия 0:1 Еквадор - Гватемала 3:0 Косово - Андора 3:0
Лихтенщайн - Кипър 0:2 Хърватия - Словения 2:1 Мароко - Норвегия 1:1 Гърция - Италия 0:1 Еквадор - Гватемала 3:0
Косово - Андора 3:0 Лихтенщайн - Кипър 0:2

--- Резултати от контроли преди световното (68 words) ---
URL: https://www.24chasa.bg/sport/article/22994434
Бразилия - Египет 2:1 Венецуела - Турция 1:2 Аржентина - Хондурас 2:0 Кюрасао - Аруба 4:0 Шотландия - Боливия 4:0
Англия - Нова Зеландия 1:0 Кабо Верде - Бермуда 3:0 Ямайка - РЮА 0:1 Бразилия - Египет 2:1 Венецуела -
Турция 1:2 Аржентина - Хондурас 2:0 Кюрасао - Аруба 4:0 Шотландия - Боливия 4:0 Англия - Нова Зеландия 1:0 Кабо
Верде - Бермуда 3:0 Ямайка - РЮА 0:1

--- А кога ще махнем “Аз съм българче” от читанката? (50 words) ---
URL: https://www.24chasa.bg/mneniya/article/22987850
Прогресивните глупости на депутати удавиха това, което трябваше да чуем от премиера Румен Радев и финансовия министър Гълъб Донев. Вижте
още във видеозавещанието на седмицата Прогресивните глупости на депутати удавиха това, което трябваше да чуем от премиера Румен Радев и
финансовия министър Гълъб Донев. Вижте още във видеозавещанието на седмицата

--- Възстановено е движението в участъка от Божан до разклона за Попгруево (70 words) ---
URL: https://www.24chasa.bg/spravochnik/article/22985177
Възстановено е движението по пътя Iв участъка от село Божан до разклона за Попгруево в община Тервел, съобщиха ог АПИ.
Той беше затворен заради почистване на кална маса, камъни и наноси след падналия снощи дъжд. Възстановено е движението по пътя
Iв участъка от село Божан до разклона за Попгруево в община Тервел, съобщиха ог АПИ. Той беше затворен заради почистване
на кална маса, камъни и наноси след падналия снощи дъжд.

--- Катастрофа при км 267 на "Тракия" към Бургас, движението е в изпреварващата лента (72 words) ---
URL: https://www.24chasa.bg/spravochnik/article/22986040
Движението при км 267 на АМ "Тракия" в посока Бургас се осъществява в изпреварващата лента поради ПТП, съобщават от АПИ.
Шофьорите да се движат с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция". Движението при км 267
на АМ "Тракия" в посока Бургас се осъществява в изпреварващата лента поради ПТП, съобщават от АПИ. Шофьорите да се движат
с повишено внимание и съобразена скорост. Трафикът се регулира от "Пътна полиция".

--- Франция падна 1:2 от Кот д'Ивоар в Нант, Испания - Ирак 1:1 (резултати от контроли) (50 words) ---
URL: https://www.24chasa.bg/sport/article/22981830
Франция - Кот д'Ивоар 1:2 Испания - Ирак 1:1 Швеция - Гърция 2:2 Иран - Мали 2:2 Словения - Кипър
1:1 Андора - Лихтенщайн 2:0 Франция - Кот д'Ивоар 1:2 Испания - Ирак 1:1 Швеция - Гърция 2:2 Иран -
Мали 2:2 Словения - Кипър 1:1 Андора - Лихтенщайн 2:0

--- Резултати от контроли (52 words) ---
URL: https://www.24chasa.bg/sport/article/22974627
Нидерландия - Алжир 0:1 ДР Конго - Дания 0:0 Албания - Израел 0:1 Люксембург - Италия 0:1 Полша - Нигерия
2:2 Хаити - Нова Зеландия 4:0 Нидерландия - Алжир 0:1 ДР Конго - Дания 0:0 Албания - Израел 0:1 Люксембург
- Италия 0:1 Полша - Нигерия 2:2 Хаити - Нова Зеландия 4:0

In [169]:
def remove_duplicate_paragraphs(text: str) -> str:
    if not isinstance(text, str):
        return text
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    seen = []
    for p in paragraphs:
        if p not in seen:
            seen.append(p)
    return "\n\n".join(seen)

In [170]:
mask = df["full_text"].apply(has_duplicate_paragraphs)
print(f"Articles with duplicate paragraphs before cleaning: {mask.sum()}")

df["full_text"] = df["full_text"].apply(remove_duplicate_paragraphs)

mask = df["full_text"].apply(has_duplicate_paragraphs)
print(f"Articles with duplicate paragraphs after cleaning: {mask.sum()}")

Articles with duplicate paragraphs before cleaning: 103
Articles with duplicate paragraphs after cleaning: 0

In [171]:
row = df[df["url"] == "https://www.24chasa.bg/bulgaria/article/22853733"].iloc[0]
print_by_words(row["full_text"])

Георги Тодоров е назначен за заместник-министър на туризма. "Със заповед на министър-председателя Румен Радев на длъжността заместник-министър на туризма е
назначен Георги Георгиев Тодоров", съобщават от правителствената информационна служба.

## 6. Title cleaning

In [172]:
mask = df["title"].str.contains(r"<[a-zA-Z]", regex=True, na=False)
print(f"Titles with HTML: {mask.sum()}")
print(df[mask]["source"].value_counts().to_string())
print()

for _, row in df[mask].head(10).iterrows():
    print(f"[{row['source']}] {row['title']}")

Titles with HTML: 515
source
vesti    515

[vesti] <p>Ким Чен-ун и Си Дзинпин с ключова среща в Пхенян, какво договориха</p>
[vesti] <p>Зеленски с &bdquo;желязна&ldquo; подкрепа от Чарлз III и покана за историческа визита</p>
[vesti] <p>Фалстарт на делото за побоя над директора на полицията в Русе</p>
[vesti] <p>Кой е новият и.ф. главен секретар на МВР Любомир Николов</p>
[vesti] <p>Опит за селфи с мечка&nbsp;прати трима туристи в болница</p>
[vesti] <p>Капанът на съюзите поглъща Доналд Тръмп</p>
[vesti] <p>Пътнически самолет кацна аварийно заради пукнато предно стъкло</p>
[vesti] <p>Отстраниха главния прокурор на МНС заради обвинения в сексуално посегателство</p>
[vesti] <p>Ето кой ще заеме временно поста на Георги Кандев</p>
[vesti] <p>11-метрови вълни удариха Уелингтън, стотици бяха евакуирани</p>

In [173]:
df["title"] = df["title"].apply(strip_html)
df["title"] = df["title"].apply(decode_html_entities)

In [174]:
short_titles = df[df["title"].str.split().str.len() < 3]
print(f"Titles under 3 words: {len(short_titles)}\n")

for _, row in short_titles.iterrows():
    print(f"--- [{row['source']}] {row['title']} ---")
    print(f"URL: {row['url']}")
    print_by_words(row["full_text"])
    print()

Titles under 3 words: 20

--- [actualno] Диагноза "Тартюф" ---
URL: https://www.actualno.com/scene/diagnoza-tartuf-news_2604626.html
Всичко и всички са фейк - гòрко оплаква GenZ своето време! Как да не са, като социални (ко)медии ежедневно изтъпанчват
на сцена. Ежедневно пред онлайн публика. При това не само GenZ, а все по-често мама, тате, бате, баба, дядо… Световъртеж
в техно водовъртеж. Спокойствие? Лично пространство? Скрупули? Ех – отлетяха…! Докато залисан си в играта, роля погуби… същината. Нещо си
отива. Друго късо дава. Човешкото на късо – маската продава! Роден актьор е човек – нали прякор му е homo
ludens. Роден актьор за невидим режисьор. Лесно поддава. Играе - не роптае. Влезе ли в роля, понякога трябва да иде
на театър, за да се събуди как да излезе. Да иде на театър, за да… избегне психиатър. Гледам "Тартюф или
лицемерът". Лилия Абаджиева поставя бароковата комедия на Жан-Батист Молиер в Малък градски театър "Зад канала". Както се убеждавам малко по-късно,
представление талантливо, живо, правдиво. Докато чакам да започне, мислите ми се отнасят към шоуто, което увенча десетилетното наше догонване. Сигурно
то създава на GenZ усещане, че всичко живо вече е фалшиво. Още: Започнаха репетициите на "Свръхпредел" от Били Колинс в
Народния театър Добре де. Дадохме всичко от себе си. Докрай се раздадохме. Каквото поискаха, дадохме, за да ни вземат. Да
сме при… цивилизованите. А сега GenZ роптае, че всичко и всички били фейк. Че гледаш го едно, а то друго.
И все разпитват за миналото. При нас как било. Понякога помечтават. Идеализират. По техен си начин. Но имахме ли избор,
питам се? На фона на трезвия, рационалистичен, материално свръхпотентен, техно свят, към който се бяхме запътили? С мекотата, наивността и
състрадателността, които си заминаха с предходното поколение, им приличахме на домашни котенца. А политиците ни – на домашни кученца. Но
нали православие почти дванайсет века учи да бъдем именно такива – човеколюбиви, състрадателни, отзивчиви…? Нито опит имахме, нито сила. Като
парникови растения, които изведнъж са изнесени да оцеляват навън… Десетилетия слушахме, че корени пуснала цивилизацията в Европа и в САЩ.
Че нас ни подминала. Нищо, че държавата ни по-стара е от всички в Европа и почти пет пъти и половина
по-стара от САЩ. Древност и стойност на културно наследство май по-добре да не сравняваме, защото онези, които увещаваха, знаеха защо
го правят. Или не знаеха…? Как можеш да знаеш нещо в свят, в който го гледаш едно, а то друго.
В различни векове, от различни господари все слушахме какви сме твари. Че нашето не става, че тяхното е блян. И
си намерихме дума, как да успеем – чуждопоклонничество. Поклонихме се и вече сме там. В трезвия, рационалистичен, материално свръхпотентен, техно
свят. Така че GenZ да свиква. Познавайки основната линия на сюжета, още в първите сцени на постановката се загнездва в
съзнанието ми въпрос. Дали на някаква угроза, Тартюф е диагноза? Имаме демокрация, припомням си. Нека всеки сам прецени. Междувременно сценичен
декор и костюми на Васил Абаджиев са свързали с време, в което Европа счита Франция за свой цивилизационен еталон. Там
някъде трябва да са устоите на днешното, подсещам се. От там някъде трябва да е тръгнало онова, от което GenZ
пропищя. Още: Лилия Абаджиева: Взираме се само в лайк машините - а те са машини за ентропия Като в машина
на времето в театралната зала седим между настояще и епохата на Краля Слънце. Две епохи си говорят. А с режисьорска
помощ - и разбират. От време на време Абаджиева допълва диалога със съвременна реч. Понякога вмъква и теми от бъдещето,
погледнато от времето на Молиер, които същевременно за нас днешните са в миналото. Като тест за вниманието и историческата памет
на зрителя. По-важно обаче е, че това смесване на епохи премахва времевата рамка. Сега, казвам си, мисълта може да обгърне
епохите ведно. Да огледа цялото. В режисирано безвремие, над историческа конкретика непрѐходно изплува като каймак. Каймак по рецепта на Абаджиева
– гъст, вкусен. Подтиква за размисъл. Случаен недъг от време на френски класицизъм ли е кариеристът Тартюф? Или е структурен,
цивилизационен бъг, произлязъл от антропоцентричния възглас на съвременника му Декарт? Декарт не превъзнесе ли човека - и себе си, и
нас, и всички други? Не се ли предовери на разума като написа: "cogito ergo sum"? Защото премахва наследени задръжки ли,
приелата ни цивилизация хареса "cogito ergo sum" за свое вековно мото? А какво още премахва не разбра ли? Ами ако
в задръжките е имало мъдрост отвъд илюзионизма на човешкия разум? Дали си е отишла заедно със задръжките, та сега го
гледаш едно, а то друго…? Разбирате, нали? Все пак с него сме социализирани. "Cogito ergo sum" рационално погледнато - каквито
са ни учили да бъдем – не превърна ли без да иска нравственост в резултатност? Не превърна ли "възлюби ближния"
в "победи ближния"? Дори победата да е тартюфска. Колкото и тартюфската да е по човешки имагинерна. Случайност ли е тогава
Тартюф или правило? Може би онова, което кара GenZ да пита, след като всичко и всички са фейк къде да
търси стойност? На сцената Тартюф се вихри самонадеяно, като да настъпва новото време. В ролята на престорен праведник пъди доброто
от лицето на Земята. Привижда ми се стар лозунг от социализма – "Дела, дела и само дела!" А Тартюф като
да допълва: "Доброто остави на баба си!" Още по време на френския класицизъм ли Бог обърна на Земята гръб? Лилия
Абаджиева се е заела с текста на Молиер в двойна роля. Тя е едновременно режисьор и хореограф. И в двете
успява. В крайна сметка, няма миг от интерпретацията ѝ, който да не поддържа зрителско внимание. Не го могат много режисьори.
Увлича зрителския поглед с шуртящо сценично движение. Освен чрез реплики и актьорска игра то се излива в хореографски жестове. Получава
се пластичен разказ, който обаче изисква от актьора да играе на предел на физически сили. От друга страна хореографската образност
облекчава разбирането на римувания молиеров диалог, прекрасно преведен от Стоян Бакърджиев. Впечатление прави и друго. Типични за времето ни политкоректни
предписания се маркират маргинално. В крайна сметка не за тях плаща публиката… Почти задължителна за сцената в наши дни хомоеротика
е загатната "между другото", вместо - както нерядко – натъртена. А дали псувнята като сатиричен, осъвременяващ и побългаряващ стилов елемент
е достатъчно да е една вместо чутите три, е въпрос на вкус. Не си струва разгорещени спорове, които чух след
края на пиесата. Абаджиева е формирала за представлението актьорски екип, който с плът и кръв предава режисьорския замисъл. Забележителни са
Леонид Йовчев в ролята на Тартюф и Александър Кадиев като Орегон. Като цяло слаба игра няма. Диагноза ли е в
крайна сметка Тартюф, не иска да си тръгне въпросът. Лъжесветец с ледена рационалност. Рационално погледнато, той е успешен… Не по-малко
от днешен кариерист, капиталист, политик… С престорен патос стратегически оцелява, че и социално расте. "Cogito ergo sum" е вятър в
платната му. Почти успява всичко да заграби на своя благодетел Орегон. Да го докара до просешка тояга. Безмилостно мами и
манипулира състоятелния буржоа, на чиято жена и имущество е хвърлил око. Нали важен е резултатът…? А преди това Орегон е
спасил Тартюф от… просешка тояга. Приютил го е от улицата. Направил го е член на семейството си. Издържал го е.
Гласувал му е доверие. След пиесата се натъквам на нещо колкото интересно, толкова смущаващо. В главата на приятелка, тя бе
породила една друга мисъл, хрумнала за съжаление и на мен. Тартюф бездарникът, който оцелява и израства с едното безскрупулно лицемерие
не е ли огледален образ на политик от българския преход? Странно, казвам си. Да ти се доплаче. Двама независими един
от друг българи, гледайки постановката, свързват лъжесветеца с едно и също – с български политик в демократично настояще. Ласкае, мами,
докато власт му дадем. После краде овластилите го. Всичко живо е фалшиво, чувам да стене GenZ… Новите, шампионите по електорално
доверие, дали пък ще изненадат? Дали въпреки тартюфовия бъг ще сбъднат приказка една, за която толкова много дадохме…? Автор: Иво
Алексиев

--- [24chasa] Петдесетница е! ---
URL: https://www.24chasa.bg/spravochnik/article/22949243
8 Неделя след Пасха - Петдесетница На Петдесетия ден от Господното възкресение Дух Свети слязъл над апостолите във вид на
огнени езици и ги обдарил с благодатните дарове. Празникът се нарича Петдесетница, защото това събитие е станало в деня на
старозаветния празник Петдесетница, който отбелязвали петдесет дни след юдейската Пасха. Руската православна Църква го нарича Ден на светата Троица. За
старозаветните Петдесетница бил един от трите велики празника. Първоначално празникът отбелязвал завършването на жътвата на ечемика. Празнувал се с приношение
на хляб и жертвени животни като ден на радост и благодарност, припомнящ странстванията в пустинята и освобождението от Египет. В
по-късни времена на този ден се отбелязвало получаването на Синайското законодателство, петдесет дни след излизането на евреите от Египет. Празникът
бил тържествен и радостен, в Ерусалим се стичало голямо множество хора, за да принесат в благодарност на Бога установената от
закона жертва. За апостолите денят бил двойно свят, защото е денят на Възкресението - неделния ден. Събрани в Сионската горница,
където пребивавали в постоянна молитва след Възнесението на Христос, сред тях била и св. Богородица, и други вярващи - всичко
сто и двадесет души. В десет часа сутринта (третия час по еврейско време), настанал голям чул шум от небето. Като
че ли вихрушка се спуснала над къщата, дето били събрани. И "явиха им се езици като огнени, които се разделяха,
и седна по един на всеки от тях. И те всички се изпълниха със Светия Дух" (Деян. 2:2-3). Това бил
видим знак на благодатните дарове на Светия Дух. Бидейки безтелесен, Светият Дух избрал чувственото знамение. "Но никой не бива да
си мисли - поучава св. Лъв Велики, - че в това, което било видимо за телесните очи, се е явило
Божественото същество на Светия Дух. Човешкият взор, както не може да вижда Отца и Сина, така не може да види
и Светия Дух". Още щом божественият огън пламнал в душите на апостолите, изпълнени с даровете на Духа те започнали да
прослявят величието на Бога, като заговорили на разни, непознати за тях дотогава чуждоземни езици. Тъй простите галилейски рибари били умъдрени,
духовно просветени в разбиране на истините на вярата. Това им дало бодрост, сила и мъжество да идат по всички краища
на света за проповед на Евангелието, с готовност да отдадата и живота си за вярата Христова. Шумът от небето привлякъл
към къщата множество юдеи "и всички се чудеха и маеха" (Деян. 2:7). Послучай празника в Иерусалим на тоя ден са
се били събрали хора от най-различни народности. И всеки чувал на своя си език думи, прославящи Бога. Като не могли
да си обяснят това необикновено чудо, мнозина от насъбралите се помислили, че апостолите са просто пияни от сладкото вино, въпреки
ранния час. Тогава свети апостол Петър произнесъл първата християнска проповед. Пояснил на множеството, че апостолите не са пияни, а изпълнени
от Дух Свети, и ги приканил към покаяние. Думите му проникнали в сърцата на слушащите го юдеи. В този ден
приели вярата в Христа, кръстили се и се присъединили към първата християнска общност около три хиляди души (Деян. 2:1-41). Трикратно
Иисус Христос дарил на учениците Си Светия Дух: преди страданията - неявно (Мат. 10:20), след възкресението Си, духвайки върху тях
- явно (Йоан 20:22) и в този момент, когато им Го изпраща съществено.

--- [monitor] Английските евробойци! ---
URL: https://telegraph.bg/sport/futbol-svqt/anglijskite-evrobojci-kristyl-palas-se-prisyedini-kym-elitna-kompaniia-492827
С победата си на финала в Лигата на Конференциите над Райо Валекано Кристъл Палас стана 14-тият английски тим с трофей
в евротурнир. Отбелязваме, че в тази класация попадат и британските представители, спечелили предшественика на Купата на УЕФА – Купата на
панаирните градове, който обаче не е бил под егидата на УЕФА. Ливърпул - 13 трофея Ливърпул води класацията за най-успешен
английски тим в Европа със своите 13 трофея в евротурните. „Червените“ триумфират 6 пъти в КЕШ/ШЛ, 3 пъти в Купата
на УЕФА/Лига Европа, и 4 пъти завоюват Суперкупата на УЕФА. Първото отличие е спечелено във финала за Купата на УЕФА
през 1972/73, когато е победен Борусия Мьонхенгладбах с общ резултат 3:2. Челси - 9 трофея Челси заема второто място след
Ливърпул. Най-успешните години на „сините“ идват след идването на руския милиардер Роман Абрамович (2003), когато са завоювани 7 от 9-те
трофея. Първият континентален трофей е КНК през 1971 г., когато „сините“ побеждават Реал Мадрид с 2:1 в преиграване след равенство
1:1 в първия сблъсък. През сезон 2024/25 отборът от „Стамфорд Бридж“ победи друг испански представител – Реал Бетис, във финала
на Лигата на Конференциите за последния оттогава континентален трофей. По този начин те станаха първият отбор в историята, спечелил КЕШ/Шампионска
лига, Купата на УЕФА/Лига Европа, КНК и Лигата на Конференциите. Манчестър Юнайтед - 6 трофея 20-кратният английски шампион Манчестър Юнайтед
е първият тим на Острова, спечелил КЕШ. Това се случва през 1968 г., когато е разбит Бенфика с 4:1 на
домашния финал на „Уембли“. Последният трофей е през 20917 година в Лига Европа под ръководството на Жозе Моуриньо. Тотнъм -
4 трофея „Шпорите“ са спечелили четири европейски трофея, но без КЕШ/ШЛ. С първото си европейско отличие триумфират през сезон 1962/63
в турнира КНК, когато Атлетико Мадрид е разгромен с 5:1. Те вкусиха от успеха и в Купата на УЕФА през
1972 г. и 1984 г. За последно ликуваха във финала на Лига Европа на „Сан Мамес“ в Билбао през 2024/25,
когато беше победен Манчестър Юнайтед с 1:0 след гол на Бренън Джонсън. Цялата разработка четете в днешния брой на "Мач
Телеграф"

--- [24chasa] Брауни бисквити ---
URL: https://www.24chasa.bg/spravochnik/article/22910851
Кой готви "За любителите на шоколада предлагам рецепта за брауни бисквити, подходящи и за изпращане на абитуриент", пише ни Марияна
Бончева. Продукти 240 г черен шоколад, 115 г масло, 40 г брашно, 2 суп. лъж. натурално какао, 2 яйца, 3/4
чаша захар, 1/2 суп. лъж. сварено еспресо, 1/4 ч. лъж. бакпулвер, 1/8 ч. лъж. сол, 1 ванилия Начин на приготвяне
Загряваме фурната до 180°. Застиламе 2 тави с хартия за печене. Пресяваме заедно брашното, какаото, бакпулвера и солта. Разбиваме с
миксер яйцата, добавяме захарта, еспресото и ванилията и разбиваме на висока скорост за 10 мин., докато се получи плътна смес.
Слагаме маслото в огнеупорен съд на водна баня. Добавяме нарязания шоколад и разбъркваме, докато се разтопи. Внимателно добавяме шоколадовата смес
в яйчената смес и разбъркваме за кратко. Добавяме брашното и бъркаме до получаване на еднородно тесто. От него оформяме топчета
и ги редим в тавите, като ги сплескваме във формата на бисквити. Оставяме разстояние между тях, тъй като нарастват по
време на печенето. Печем, докато бисквитките станат лъскави и напукани - 8-9-мин. След още 5-6 мин ги изваждаме. По желание
може да поръсим с кристалчета натурална черноморска сол.

--- [monitor] БЕРОЕ ИЗПАДНА ---
URL: https://telegraph.bg/sport/futbol-bulgaria/beroe-izpadna.-starozagorci-zagubiha-02-ot-botev-vraca-i-se-prostiha-s-elita-na-bylgariia-492226
Берое е третият отбор след Монтана и Добруджа, който изпада от Първа лига. Това стана след като в последния кръг
старозагорци паднаха 0:3 от Ботев Враца. Головете вкараха Мичи Нтело, Касим Хаджи и Мартин Петков. Берое за последно бе новак
през сезон 2009/10 и от тогава бе неизменна част от родния елитен футбол. В началните минути на срещата липсваха опасните
ситуации пред двамата вратари. В 14-ата минута Тижан Сона отправи удар, който бе избит с лекота от Марин Орлинов. Три
минути по-късно Хуанка Пинеда навлезе с финт в наказателното поле, преодолявайки двама, но центрирането му бе изчистено от играч на
Ботев Враца. Стефан Гаврилов се опита да изведе Факундо Аларкон в 20-ата минута, но Марин Орлинов улови преди нападателят на
Берое да успее да стигне до топката. След центриране от свободен удар на Радослав Цонев, Лазар Боянов стреля покрай вратата
на Артур Мота в 22-рата минута. Ботев Враца поведе в 25-ата минута, когато Мичи Нтело тръгна на контраатака сам срещу
Мота, който опита да излезе, за да го спре, но нападателят на врачани го преодоля за 1:0. След попадението врачани
се активизираха и тръгнаха в търсене на втори гол. В 36-ата минута Мартин Смоленски се озова на добра позиция, но
ударът му с глава премина покрай целта. Марко Борнино затрудни Орлинов в 40-ата минута с изстрел от дистанция, но Факундо
Аларкон не успя да се ориентира добре в ситуацията и да засече отбитата от вратаря топка, след което и Борнино
не успя да отправи втори изстрел. Факундо Костантини получи от Хуанка Пинеда извън наказателното поле и стреля по земя, но
Орлинов лесно спаси. При следващата атака на Берое Илия Юруков изчисти топката, която Исмаел Ферер опита да центрира по земя.
При последвалото центриране стражът на врачани изби, а Стефан Гаврилов пробва воле от дистанция, който профуча покрай вратата. Хуанка Пинеда
продължаваше да тормози защитата на Ботев Враца отляво, но бранителите на врачани бяха добре организирани и се справяха с набезите
на доминиканеца. След почивката Хосу Урибе вкара втори централен нападател в лицето на Йесид Валбуена, който замени Стефан Гаврилов. Ботев
Враца вкара второ попадение в 48-ата минута, когато Радослав Цонев намери Мартин Петков, а той отблизо матира Мота.Марко Борнино центрира
към Йесид Валбуена в 50-ата минута, но колумбиецът с глава стреля над вратата. Четири минути след това Милен Стоев блокира
Факундо Аларкон, който бе на добра позиция, като заралии имаха претенции за нарушение на Стоев. В 58-ата минута след центриране
от корнер Аларкон бе близо до попадение, но отново стреля покрай целта. Заралии владееха повече топката в следващите минути, но
не успяваха да застрашат Марин Орлинов. Изстрел на Хуанка Пинеда в 83-ата минута мина над вратата. В продължението Касим Хаджи
оформи крайното 3:0, след като остана сам срещу Артур Мота.

--- [monitor] Неоспоримите! ---
URL: https://telegraph.bg/sport/futbol-svqt/neosporimite-arsenal-proektira-titlata-kato-s-inzhenerna-preciznost-492043
Триумфът на Арсенал във Висшата лига през 2025-26 е рядко срещан в съвременния футбол. Ако изключим класическите компоненти като подготовката
на отбора, добрия треньор и разходите за трансфери, то той е символ на вярата в процеса и приемствеността. Титлата е
резултат от дългосрочния план, в който на „Емирейтс“ повярваха още в началото. Затова след всеки трите неуспешни опита за покоряване
на върха, те се завръщаха по-силни и мотивирани. И най-накрая го постигнаха. И ако преди 20 години „артилеристите“ бяха наричани
„Непобедимите“, то сега станаха „Неоспоримите“. Но когато говорим за целенасочен процес, трябва да погледнем по-дълбоко. Години преди Арсенал да стане
отново шампион, ръководството се зае да разработва проект, планиран да даде краен резултат между 2023 и 2027 г. И успяха,
назначавайки двама бивши играчи на клуба в лицето на техническия директор Еду Гаспар и мениджъра Микел Артета. Бразилецът дойде на
„Емирейтс“ през лятото на 2019 г, а испанецът – през декември същата година. Пристигането на Еду предизвика радикално преструктуриране на
футболните операции на клуба. Голяма част от скаутския отдел беше разформирована и заменен от новосформирано звено за футболно разузнаване. Този
иновативен екип бе натоварен със задачата да изгради подробна и ясна картина за бъдещето на Арсенал. Те предвидиха потенциални промени
в управлението на съперниците, като например напускането на Юрген Клоп от Ливърпул. Или кога точно пикът във формата на Салах,
Ван Дайк и Кевин Де Бройне ще започне да пада надолу. Това не беше напълно точна прогноза, но предостави рамка.
Селекцията след това беше съобразено с тези прогнози, което позволи на Арсенал да сформира отбор, разчетен да достигне пика, когато

### Title Cleaning Summary

- Stripped HTML tags from titles (all `<p>` wrappers from `vesti`)
- Decoded HTML entities (e.g. `&quot;` → `"`, `&bdquo;` → `„`, `&ldquo;` → `"`)
- Short titles are valid

In [176]:
for source, threshold in [("24chasa", 3000), ("fakti", 2000)]:
    outliers = df[
        (df["source"] == source) & (df["word_count"] > threshold)
    ].sort_values("word_count", ascending=False)
    print(f"=== {source} > {threshold} words: {len(outliers)} ===")
    for _, row in outliers.head(5).iterrows():
        print(f"  [{row['word_count']} words] {row['title']}")
        print(f"  URL: {row['url']}")
        print_by_words(row["full_text"])
        print()

=== 24chasa > 3000 words: 18 ===
  [13275 words] Вижте ситуацията по пътищата на страната в момента
  URL: https://www.24chasa.bg/spravochnik/article/22910525
Ето информация от "Пътна структура" за състоянието на шосетата в страната. I.МЕТЕОРОЛОГИЧНА ОБСТАНОВКА: През първата половина на нощта валежи ще
има главно в планинските райони. До сутринта ще отслабнат и ще спрат. Облачността в повечето места ще се разкъса и
намалее. В източните райони ще е със слаб северозападен вятър. В останалата част от страната вятърът ще стихне и главно
в западната част от Дунавската равнина ще има ниска слоеста облачност и намалена видимост. Утре преди обяд ще бъде предимно
слънчево. Около и след обяд ще се развива купеста облачност, но само на отделни места, главно в планинските райони ще
превали краткотраен дъжд. Вятърът ще е слаб от север-северозапад, в Източна България до умерен от север-североизток. Максималните температури в повечето
места ще бъдат между 22° и 27°, в София – около 24°. ОГРАНИЧЕНИЯ ЗА ТЕЖКОТОВАРНИ МПС: Във връзка с очаквания
интензивен трафик за почивните дни временно ще се ограничава движението на тежкотоварните камиони над 12 т по най-натоварените пътни направления
АМ „Тракия", по АМ „Хемус" - в участъка от изхода на София (при км 0) до пътната връзка при кръгово
кръстовище с път I-4 (87-ми км), по АМ „Струма" и по път I-1 в отсечката от п. в. „Симитли" (376-ти
км) до п. в. „Кресна" на АМ „Струма" (402-ри км). Целта е да се улесни пътуването, да се повиши безопасността
на движение, да се ограничат предпоставките за пътни инциденти поради неправилно изпреварване и образуването на колона от тежкотоварни автомобили при
засиления трафик. • В последния почивен ден – 25 май /понеделник/, от 12 ч. до 20 ч. ще е ограничено
движението на тежкотоварните камиони, пътуващи към София. Ограничението не важи за пътните превозни средства над 12 т, които извършват обществен
превоз на пътници, както и за моторните превозни средства, които превозват опасни товари (ADR), живи животни, бързоразвалящи се хранителни продукти
и товари на температурен режим и специализирани екарисажни камиони, пътуващи по АМ „Хемус", АМ „Струма" и участъка от път I-1
в област Благоевград. На АМ „Тракия" забраната не важи за моторни превозни средства, които извършват обществен превоз на пътници. Също
на АМ „Тракия", за пътуващите в посока София, забраната не се отнася за МПС с опасни товари (ADR) в участъка
от п. в. „Ихтиман" (34-ти км) до п. в. „Вакарел" (23-ти км). II. СЪСТОЯНИЕ НА АВТОМАГИСТРАЛИТЕ: АМ „Тракия": Област София:
Движението при Мухово от км 44+400 до км 46+480 в посока Бургас се осъществява с повишено внимание поради обезопасяване на
пътния участък в аварийната лента. Срок до 31.12.2026 г.; На 20 май от 22:30 ч. ще се работи по профилактиката
на тол камерата на АМ „Тракия" при км 0 в района на комплекс „Черната котка", в посока Бургас. От 23:30
ч. аналогични дейности ще се изпълняват в платното към Бургас на магистралата при 19-и км, в района на Крушовица. На
21 май в 0:30 ч. ще се работи по тол камерата в платното за Бургас при 24-и км в района
на Вакарел, а около 1:30 ч. дейности ще се извършват в платното за Бургас при 54-и км в района на
тунел „Траянови врата". На 21 май около 2:30 ч. ще започват работите по тол рамките в платното за София, като
първо ще се изпълняват по съоръжението при тунел „Траянови врата", а след това около 3:30 ч. ще продължат по рамката
в района на Вакарел. В 4:30 ч. ще се работи при Крушовица в платното в посока София, а около 5:30
ч. в същото платно при входа на София при км 0. Област Пазарджик: Движението в участъка от км 66+750 до
км 80+050 посока Бургас се осъществява с повишено внимание и с ограничение на скоростта до 100 км/ч поради неравности. Участъкът
е сигнализиран с пътни знаци. Срок до отстраняването им. Движението в участъка от км 67+950 до км 80+250 посока София
се осъществява с повишено внимание и с ограничение на скоростта до 100 км/ч поради неравности. Участъкът е сигнализиран с пътни
знаци. Срок до отстраняването им. Област Стара Загора: Движението от км 156+000 до км 208+000 посока София се осъществява с
повишено внимание и стесняване на едната лента за движение поради ръчно и машинно косене на тревни площи. Водачите на МПС
да се движат със съобразена скорост съгласно създадената организация на движение. Трафикът е сигнализиран с временна сигнализация и пътни знаци.
Срок до 29.05.2026 г.; Движението от км 208+000 до км 229+000 посока София се осъществява с повишено внимание поради машинно
косен на тревни площи. Участъкът е сиганлизиран с пътни знаци. Срок до 26.05.2026 г.; Област Сливен: Движение с повишено внимание
от км 229+286 до км 273+354 в двете посоки поради почистване на канавки.Участъците са сигнализирани с пътни знаци. Срок до
29.05.2026 г.; Област Ямбол: Движението в участъка от км от 272+000 до км 277+000 посока Бургас се ограничава поради ремонтни
дейности на дилатационни фуги на мостово съоръжение. Движението се осъществява двупосочно в платното посока София. Срок до 30.05.2026 г; Движението
в участъка от км от 282+000 до км 287+000 посока Бургас се ограничава поради ремонтни дейности на дилатационни фуги на
мостово съоръжение. Движението се осъществява двупосочно в платното посока София. Срок до 30.05.2026 г; Област Бургас: Движението в участъка от
км 342+100 до км 348+250 посока Бургас се осъществява с повишено внимание в активната и изпреварващата лента във връзка с
обезопасяване на участък от пътното платно - аварийна лента при км 346+800 ляво. Скоростта е ограничена до 80 км/ч. Водачите
да се движат с повишено внимание съобразена скорост. Участъкът е сигнализиран с пътни знаци. Срок до 25.05.2026 г. АМ „Хемус":
Област София: Движението от км 1+240 до км 8+500 в посока Варна се осъществява с повишено внимание и с ограничение
на скоростта до 90 км/ч, а МПС над 12 т се движат само в аварийната лента, с цел повишаване на
безопасността на движение през зимните месеци, поради незадоволителното състояние на настилката. Участъкът е сигнализиран с пътни знаци. Срок до 27.05.2026
г.; Движението от км 34+600 до км 34+100 посока София се осъществява с повишено внимание поради обследване на анкерна стена
на път I-1 при км 210+200. Ограничена е външната активна лента, като движението се извършва в активната и изпреварващата лента.
Срок до 27.05.2026 г.; Движението от км 39+372 до км 42+680 „Топли дол" в двете посоки се обособяват две ленти
посока София – Варна и две ленти посока Варна – София. При необходимост и аварийни ситуации в лява тунелна тръба
ще се обособява двупосочно движение в дясна тунелна тръба – една лента за посока София и една лента за посока
Варна. Срок до 28.05.2026 г. Затваряне на външната активна лента на АМ „Хемус" в посока София от км 34+600 до
км 34+100, като движението се осъществява в средна активна и изпреварваща лента във връзка с обследване на анкерна стена на
път I-1 при км 210+200. Срок до 25.05.2026 г.; Временно движението на АМ Хемус от км 36+372 до км 42+680,
района на тунел Топли дол се обособяват по две ленти посока София и посока Варна. При необходимост в аварийни ситуаций
се особособява по една лента посока София и по една лента посока Варна. Срок до 26.05.2026 г. Област Ловеч: Въведена
е временна организация на движението с ограничителни елементи тип „Ню Джърси" в участъка от км 87+400 до км 87+675 в
лявото платно. Срок до 12.12.2027 г.; Движението в участъка п.в. „Боаза" - п.в. „Дерманци" от км 87+800 до км 98+150
е ограничено за МПС над 12,5 т. Участъкът е сигнализиран с пътни знаци. Срок до 12.12.2027 г.; Област Варна: Движението
в участъка п.в. „Летище" – надлез Игнатиево от км 418+900 до км 421+543 посока София е ограничено поради ремонтни дейности
на асфалтовата настилка. Движението се осъществява двупосочно в платното посока Варна. Участъкът е сигнализиран с пътни знаци. Срок до 15.07.2026
г. Област Шумен: Движението в посока София от км 350+000 до км 363+000 е ограничено поради извършване на ремонтни дейности.
Движението се осъществява двупосочно в платното посока Варна. Участъкът е сигнализиран с пътни знаци. Срок до 31.07.2026 г. АМ „Струма":
Област София: Движението в участъка от км 10+430 до км 10+200 посока София се осъществява с повишено внимание поради почистване
на откос при 10+300, ограничено е движението в аварийната лента. Участъкът е сигнализиран с пътни знаци. Срок до 27.05.2026 г.;
Област Перник: Движението в участъка от км 12+450 до км 10+430 посока София се осъществява с повишено внимание поради почистване
на откоси, ограничено е движението в аварийната лента. Участъкът е сигнализиран с пътни знаци. Срок до 27.05.2026 г. Движението в
участъка от км 16+000 до км 18+000 в посока София се осъществява с повишено внимание поради аварийни дейности за почистване
на откоси в часовия диапазон от 10:00 до 16:00 часа. Затворена за движение е външната активна лента, като движението се
осъществява в изпреварващата и активната лента. Участъкът е сигнализиран с пътни знаци. Срок до 31.12.2026 г.; Област Благоевград: Движението в
участъка от км 97+500 до км 104+300 посока София е ограничено поради констатирано свлачище при км 103+300. Движението се пренасочва
по обходен маршрут: - от АМ „Струма" на км 104+300 по пътна връзка с път I-1 „София – Кулата" до
п.в. „Благоевград Юг" и ограничение на скоростта до началото на обходния маршрут до 70 км/ч. Водачите да се движат с
повишено внимание и съобразена скорост съгласно създадената организация на движение. Срок до 20:00 ч на 27.05.2026 г. Движение с повишено
внимание и ограничение по АМ ,,Струма'' в участъка от км 103+000 до км 104+200 ,поради предстоящ засилен трафик и обезопасяване
на участък с констатирано свлачище на АМ ,,Струма" при км 103+300 се ограничава лентата за принудително спиране в лявото платно
от км 103+000 до км 103+600 за движение посока София. Движението се осъществява в активната и изпреварваща лента за движение
и ограничение на скоростта до 90 км/ч ,посредством табели и пътни знаци . Водачите да се движат с повишено внимание
и съобразена скорост съгласно създадената организация на движение. Срок от 11:00 часа на 25.05.2026 г. до 20:00 часа на 25.05.2026
г. АМ „Марица": Област Хасково: Движението от км 29+000 до км 29+100 в посока ГКПП "Капитан Андреево" се осъществява в
изпреварващата пътна лента поради компрометирана дилатационна фуга. Участъка е сигнализиран с пътни знаци. Срок до 31.05.2026 г АМ „Черно море":
няма въведени ограничения. АМ „Европа": няма въведени ограничения. ІІI. ВЪВЕДЕНИ ОГРАНИЧЕНИЯ ПО ОСНОВНИТЕ ПЪТНИ НАПРАВЛЕНИЯ: 1. Проходи: - „Върбишки" –
затворен за всички МПС. Срок: целогодишно; - „Златишки" – затворен за всички МПС. Срок: целогодишно; - „Пампорово" – затворен за
всички МПС; - „Котленски" – отворен за всички МПС; - „Печинско" – отворен за всички МПС. - „Превала" – отворен
за всички МПС. - „Предел" – отворен за всички МПС - „Приморски" – отворен за всички МПС. - „Републиката" –
отворен за всички МПС; - „Ришки" – отворен за всички МПС; - „Рожен" – отворен за всички МПС; - „Айтоски"
– забранен за МПС над 12 т в участъка Ябълчево – Айтос.; - „Вратник" – отворен за всички МПС; -„Троянски"
– отворен за всички МПС, като движението се осъществява с пропусквателен режим през 30 мин. - „Дюлински" – забранен за
МПС над 3,5 т; - „Петрохан" – забранен за МПС над 12 т в двете посоки, както и тегленето на
ремаркета, както и движението на МПС с дължина над 12 м; - „Твърдишки" – забранен за МПС над 10 т;
- „Шипка" – забранено е движението на МПС, предназначени за превоз на товари с технически допустима максимална маса над 12
т от категория N3, както и тегленето на ремаркета и полуремаркета с технически допустима максимална маса над 10 т от
категория О4. Срок до 31.03.2027 г. IV. СЪСТОЯНИЕ НА РЕПУБЛИКАНСКАТА ПЪТНА МРЕЖА: ОГРАНИЧЕНИЯ В ДВИЖЕНИЕТО НА МПС ПО ПЪРВОКЛАСНАТА ПЪТНА
МРЕЖА: - път I-1 /Е79/ Граница Румъния - о.п. Видин - Димово - Ружинци - Белотинци - о.п. Монтана -
о.п. Враца - Мездра - Ботевград - Горни Богров - о. п. София - Даскалово - о.п. Дупница - о.п.
Благоевград - о.п. Симитли - Кресна - Кулата - граница Гърция: Област Враца: Движението в участъка Враца – Мездра от
км 151+490 до км 161+000 се осъществява в една поради ремонтни дейности на асфалтовата настилка. Участъкът е сигнализиран с пътни
знаци. Срок 30.10.2026 г. Област София: Временно движението по път I-1 София - Ботевград се осъществява в една лента от
км 207+285 до 208+190 посока Ботевград поради ремонт на виадукт Коренишки дол. Движението на скоростта се ограничава до 30 км.
Срок до 26.05.2026 г. Ограничаване на движението по път I-1 от км 204+500 до км 209+505, като строителят ще работи
в една лента и ще се осигурява достъп на автомобили със специален режим на движение, както и други МПС с
локално движение. В участъка от км 204+500 до км 205+220 /отбивката за с. Стъргел/ ще бъде пропускано транзитно движение в
посока Ботевград – Стъргел. От страна Ботевград маршрутът е сигнализиран при кръстовището за Врачеш при км 196+685, а от страна
на с. Стъргел - при кръстовището за с. Стъргел при с. Горно Камарци. Предвидени са знаци при кръстовището за яз.
Бебреш при км 200+698. Срок 28.05.2026 г. Движението в участъка София – Ботевград от км 208+190 до км 207+285 се
осъществява двупосочно в една лента поради извършване на аварийно ремонтно-възстановителни дейности на виадукт при км 36+450 – „Коренишки дол" долно
строене. Срок до 20.05.2026 г.; Движението в участъка Ботевград – София от км 209+600 до км 212+600 в района на
анкерната стена при км 210+500 е ограничено за всички МПС поради аварийно състояние на стената. Обходен маршрут: АМ „Хемус". Срок
до 29.05.2026 г.; До изграждането на ПВ „Люти дол" и възможността за цялостно пропускане на движението по възела, пътните връзки
ще останат затворени и участъка от съществуващия път І-1 /Е-79/ до разклона за с. Типченица в с. Люти дол ще
остане затворен за движение и достъпа до с. Люти дол ще бъде ограничен. За осигуряване на достъп от и за
с. Люти дол ще се използват обходни маршрути за движение по път III-161 и по общински път VRC-2094 - с.
Типченица - с. Липница - с. Новачене. За насочване на движението по обходните маршрути ще бъде поставена необходимата сигнализация в
с. Люти дол, на ПВ „Новачене" и ПВ „Ребърково", която е показана на съответните чертежи. За да се осигури безопасното
пропускане на движението в условията на продължаващо строителство и укрепване на свлачищните участъци, които са от км 175+440 до км
175+570; от км 176+470 до км 176+650; от км 178+880 до км 179+070; от км 179+510 до км 179+560; от
км 179+860 до км 176+910 проектът за временна организация на движение предвижда преминаването през участъка от км 174+400 до км
180+800 да се осъществява през участъци от съществуващия път І-1 /Е-79/ и двупосочно в по едно от платната на новоизградения
път. На местата за превключвания между стар и нов път са изградени временни етапни връзки първата ще бъде от км
175+250 до км 175+585, а от км 175+585 до км 176+300 движението ще се осъществява по новоизграденото ляво платно двупосочно,
при км 176+300 по изградена временна етапна връзка движението се прехвърля по съществуващия път І-1 /Е-79/ до км 177+000 където
е изградена друга временна етапна връзка между съществуващия път І-1 /Е-79/ и новоизградения път, като движението ще се осъществява по
лявото платно двупосочно до км 178+000, където ще премине в дясното платно двупосочно до км 178+800. В участъка от км
178+800 до км 179+300 преминаването ще става по обходен път през трасето на съществуващия път І-1 /Е-79/ и от км
179+300 до км 180+800 движението ще продължи в новоизграденото дясно платно двупосочно. За изграждането на дясното платно в участъка от
км 191+960 до км 192+240, където досега за преминаване на движението действа етапна връзка, която е изградена като едностранно кръстовище
с път I-1 Скравена – Ботевград, като тя трябва да бъде разрушена, с което направлението Скравена-Ботевград и обратно остава самостоятелно
без връзка с новоизградения път. В участъка на строителните дейности е направена нова временна организация на движение. Участъкът е сигнализиран
с пътни знаци на съответното им километрично положение съгласно чертежите. За строителството на ПВ „Ботевград" при км 193+337 се предвижда
нова временна организация като движението ще се пропуска в лявото платно двупосочно само по направлението Мездра -София и обратно до
приключване на строителните дейности по дясното платно и прилежащите връзки. Връзките №2 „Ботевград-Мездра" и №4 „София-Ботевград" ще бъдат затворени за
да се избегне объркване на водачите и направа на нарушения като навлизане в насрещното или обратни завой, които биха били
предпоставка за сериозни ПТП. Строителството предвижда и разрушаване на връзка №3 „Ботевград-София", която е направена за временното пропускане на движението
двупосочно и сега трябва да се изпълни проектно, изграждане на връзка №1 „Мездра-Ботевград" и постоянното кръстовище с път І-1 Скравена-Ботевград.
Направленията Мездра -Ботевград, София-Ботевград и обратно, и населените места, за които достъпа е свързан с тези направления ще се насочат
по обходни маршрути през пътния възел на път ІI-17 и I-3 за Ботевград и ПВ „Новачене" по път І-1 /Е-79/.
Срок до 26.05.2026 г.; Движението на товарни МПС над 15 т в участъка от Александров мост /Княжево/ до границата с
област Перник от км 276+162 до км 282+485 е ограничено. Срок до 30.09.2026 г.; Движението в участъка Жерково - Елешница
от км 224+600 до км 229+700 е ограничено за всички МПС поради намален габарит на пътното платно. Срок до 30.09.2026
г; Реверсивно движение по път София – Владая – Перник: Участък 1: от км 276+040 до км 277+610, като се
обособяват 2 ленти за движение в посока София. Всеки работен ден от 06:00 ч. до 10:30 ч. Последен празничен ден
и всяка неделя от 12:00 ч. до 20:00 ч. Участък 2: от км 278+567 до км 282+000, като се обособяват
2 ленти за движение в посока София от км 278+567 до км 281+800. Последен празничен ден и всяка неделя от
12:00 ч. до 20:00 ч. Срок до 03.09.2026 г.; Област Перник: Въвежда се реверсивно движение по път I-1 София -
Кулата в участъка от км 285+772 до км 286+920 както следва: - Всеки работен ден, обособяване на две ленти за
движение в посока София, за времето от 6:00 ч. до 10:00 ч. - През последен празничен ден и всяка неделя,
се обособяват две ленти за движение в посока София, за времето от 10:00 ч. до 19:00 ч. Водачите да се
движат с повишено внимание и съобразена скорост, съгласно създадената организация на движение. Срок до 30.09.2026 г. Област Благоевград: Движението в
участъка от км 383+450 до км 383+770 се осъществява в една лента в посока ГКПП „Кулата" поради ремонтни дейности на
асфалтовата настилка на мостово съоръжение. Участъкът е сигнализиран с пътн изнаци. Движението се пренасочва по обходния път на „Малкия тунел"
и ограничение на скоростта до 30км/ч. Срок до 12:00 ч. на 26.05.2026 г.; Движение с повишено внимание при км 398+900
до км 399+105 в гр. Кресна поради поставяне на временна светофарна уредба, функционираща в режим ,,при поискване", на пешеходна пътека
на кръстовище между републикански път I-1 София – Кулата и път III – 1082 , III – 108 – Рибник
– Лебница – Струма – Вълково – Микрево – Кресна в гр. Кресна. Движението се регулира от пътни знаци и
сигналисти. Водачите да се движат с повишено внимание и съобразена скорост, съгласно създадената организация за движение. Срок до 31.08.2026 г.
- път І-2 /Е-70/ Граница Румъния - Русе - Цар Калоян - о.п. Разград - о.п. Шумен - Девня -
Варна: няма въведени ограничения. Област Русе: Движението по Дунав мост при Русе в участъка от км 0+000 до км 1+507
на работни участъци по 400 м се осъществява в една лента с пропускатаелен режим поради основен ремонт на мостовото съоръжение.
Максимална допустима ширина на преминаващите МПС 2.55 м и обща маса до 60 т. Участъкът е сигнализиран от пътни знаци.
Ограничението на скоростта е до 20 км/ч. Движението се регулира от адаптивна светофарна уредба. Срок до 10.07.2026 г.; - път
І-3 /Е-83/ Гара Бяла - о.п. Плевен - Луковит - Коритна - Ябланица - Ботевград: няма въведени ограничения. - път

There are still outliers for words distribution, but they are valid texts, so all good

In [177]:
len(df)

50196

## 7. Media-type suffixes in titles and full_text

Check how many articles carry `(видео)`, `(снимка)`, `(снимки)`, `(снимка+видео)`, `(видео+снимка)` — appended by CMS editors as metadata tags, not actual article content.

In [178]:
MEDIA_PATTERNS = ["(видео)", "(снимка)", "(снимки)", "(снимка+видео)", "(видео+снимка)", "(видео+снимки)", "(снимки, видео)"]

def media_re(p):
    # Allow optional spaces around + so (снимка+видео) matches (снимка + видео) too
    return re.escape(p).replace(r"\+", r"\s*\+\s*")

combined = "|".join(media_re(p) for p in MEDIA_PATTERNS)

# Per-pattern counts
for field in ["title", "full_text"]:
    print(f"--- {field} ---")
    for p in MEDIA_PATTERNS:
        n = df[field].str.contains(media_re(p), case=False, na=False, regex=True).sum()
        if n:
            print(f"  {p:<22}: {n}")
    total = df[field].str.contains(combined, case=False, na=False, regex=True).sum()
    print(f"  {'TOTAL':<22}: {total}")
    print()

--- title ---
  (видео)               : 1536
  (снимка)              : 112
  (снимки)              : 536
  (снимка+видео)        : 1
  (видео+снимка)        : 12
  (видео+снимки)        : 98
  (снимки, видео)       : 23
  TOTAL                 : 2318

--- full_text ---
  (видео)               : 1780
  (снимка)              : 92
  (снимки)              : 440
  (снимка+видео)        : 2
  (видео+снимка)        : 9
  (видео+снимки)        : 128
  (снимки, видео)       : 6
  TOTAL                 : 2317

In [179]:
# Per-source breakdown
for field in ["title", "full_text"]:
    mask = df[field].str.contains(combined, case=False, na=False, regex=True)
    print(f"{field} ({mask.sum()} affected):")
    print(df[mask]["source"].value_counts().to_string())
    print()

title (2318 affected):
source
actualno        1059
24chasa          389
nova             364
fakti            256
monitor          193
standartnews      37
vesti             20

full_text (2317 affected):
source
actualno    1727
nova         426
monitor      102
vesti         35
fakti         17
24chasa       10

In [180]:
def strip_media_suffixes(text: str) -> str:
    if not isinstance(text, str):
        return text
    return re.sub(combined, "", text, flags=re.IGNORECASE).strip()

In [181]:
df["title"] = df["title"].apply(strip_media_suffixes)
df["full_text"] = df["full_text"].apply(strip_media_suffixes)

In [182]:
mask = df["title"].str.contains(combined, case=False, na=False, regex=True)
print(f"Remaining titles with media suffixes: {mask.sum()}")

Remaining titles with media suffixes: 0

In [183]:
mask = df["full_text"].str.contains(combined, case=False, na=False, regex=True)
print(f"Remaining fill_text with media suffixes: {mask.sum()}")

Remaining fill_text with media suffixes: 0

## 8.Updated articles posted in the same time

In [184]:
def inspect_source_duplicate_similarity(
    df: pd.DataFrame, source: str, threshold: float = 0.5
):
    source_df = df[df["source"] == source].copy()
    groups_found = 0
    high_title_sim = 0
    high_text_sim = 0

    for published_at, group in source_df.groupby("published_at_dt"):
        if len(group) < 2:
            continue

        titles = group["title"].fillna("").tolist()
        texts = group["full_text"].fillna("").tolist()
        urls = group["url"].tolist()
        fetched = group["fetched_at"].tolist()

        try:
            title_sim = cosine_similarity(TfidfVectorizer().fit_transform(titles))[0][1]
            text_sim = cosine_similarity(TfidfVectorizer().fit_transform(texts))[0][1]
        except ValueError:
            continue

        groups_found += 1
        if title_sim >= threshold:
            high_title_sim += 1
        if text_sim >= threshold:
            high_text_sim += 1

        if title_sim < threshold and text_sim < threshold:
            continue

        print(
            f"Published: {published_at} | Title sim: {title_sim:.3f} | Text sim: {text_sim:.3f}"
        )
        for t, u, f in zip(titles, urls, fetched):
            print(f"  [{f}] {t}")
            print(f"    {u}")
        print()

    print(
        f"Source: {source} | Total groups: {groups_found} | Title sim >= {threshold}: {high_title_sim} | Text sim >= {threshold}: {high_text_sim}"
    )

In [185]:
same_time_all = df.groupby(["source", "published_at_dt"]).filter(lambda x: len(x) > 1)
summary = same_time_all.groupby("source")["published_at_dt"].count()
print("Articles with duplicate timestamps per source:")
print(summary.sort_values(ascending=False))

Articles with duplicate timestamps per source:
source
24chasa         2702
actualno        1250
nova             676
vesti            353
bta              316
segabg           281
standartnews      30
fakti              2
Name: published_at_dt, dtype: int64

In [186]:
inspect_source_duplicate_similarity(df, "fakti", threshold=0.7)

Source: fakti | Total groups: 1 | Title sim >= 0.7: 0 | Text sim >= 0.7: 0

In [187]:
inspect_source_duplicate_similarity(df, "segabg", threshold=0.7)

Published: 2026-05-04 12:38:11+00:00 | Title sim: 0.570 | Text sim: 1.000
  [2026-05-05T10:07:18.707630+00:00] 47-годишна литовка намушка четирима във Варна
    https://www.segabg.com/hot/category-bulgaria/47-godishna-litovka-namushka-chetirima-vuv-varna
  [2026-05-04T19:45:07.875690+00:00] 47-годишна жена от Литва намушка четирима души във Варна
    https://www.segabg.com/hot/category-bulgaria/47-godishna-zhena-litva-namushka-chetirima-dushi-vuv-varna

Published: 2026-05-04 17:14:05+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-05T02:55:05.912365+00:00] Бившият шеф на пациентска организация излиза на свобода срещу 60 000 евро
    https://www.segabg.com/category-bulgaria/bivshiyat-shef-na-pacientska-organizaciya-izliza-na-svoboda-sreshtu-60-000-evro
  [2026-05-04T19:45:07.875658+00:00] Бившият шеф на пациентска организация излиза на свобода срещу 60 000 евро
    https://www.segabg.com/hot/category-bulgaria/bivshiyat-shef-na-pacientska-organizaciya-izliza-na-svoboda-sreshtu-60-000-evro

Published: 2026-05-05 06:32:21+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-05T16:13:56.235658+00:00] В Турция цигари ще се продават срещу лична карта
    https://www.segabg.com/category-foreign-country/turciya-cigari-shte-se-prodavat-sreshtu-lichna-karta
  [2026-05-05T10:07:18.707440+00:00] В Турция цигари ще се продават срещу лична карта
    https://www.segabg.com/hot/category-foreign-country/turciya-cigari-shte-se-prodavat-sreshtu-lichna-karta

Published: 2026-05-05 09:18:59+00:00 | Title sim: 0.639 | Text sim: 1.000
  [2026-05-05T15:33:02.974585+00:00] Взривът край колата на Гешев трета година остава мистерия
    https://www.segabg.com/category-bulgaria/vzrivut-kray-kolata-na-geshev-treta-godina-ostava-misteriya
  [2026-05-05T10:07:18.707409+00:00] Взривът край колата на Гешев трета година затруднява прокуратурата
    https://www.segabg.com/hot/category-bulgaria/vzrivut-kray-kolata-na-geshev-treta-godina-zatrudnyava-prokuraturata

Published: 2026-05-05 09:22:16+00:00 | Title sim: 0.858 | Text sim: 1.000
  [2026-05-05T15:33:02.974839+00:00] A to JazZ ще разчита на дарения, за да спаси 15-ото си издание
    https://www.segabg.com/category-culture/jazz-shte-razchita-na-dareniya-za-da-spasi-15-oto-si-izdanie
  [2026-05-05T10:07:18.707861+00:00] A to JazZ ще разчита на дарения за 15-ото си издание
    https://www.segabg.com/category-culture/jazz-shte-razchita-na-dareniya-za-15-oto-si-izdanie

Published: 2026-05-05 13:30:30+00:00 | Title sim: 0.345 | Text sim: 1.000
  [2026-05-05T21:06:17.327374+00:00] Радев трябва много да реже - от айфони до цели министерства
    https://www.segabg.com/category-video/radev-tryabva-mnogo-da-rezhe-ayfoni-celi-ministerstva
  [2026-05-05T15:33:02.974362+00:00] В държавата има много за рязане - от разходи за айфони до цели министерства
    https://www.segabg.com/category-video/durzhavata-ima-mnogo-za-ryazane-razhodi-za-ayfoni-celi-ministerstva

Published: 2026-05-05 14:36:41+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-05T19:25:40.174381+00:00] МЗ забранява захарта за децата до 2 години
    https://www.segabg.com/category-zdrave/mz-zabranyava-zaharta-za-decata-2-godini
  [2026-05-05T15:33:02.974389+00:00] МЗ забранява захарта за децата до 2 години
    https://www.segabg.com/hot/category-zdrave/mz-zabranyava-zaharta-za-decata-2-godini

Published: 2026-05-05 15:35:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T03:25:02.759109+00:00] Йотова ще връчи мандата на ПБ на 7 май
    https://www.segabg.com/category-bulgaria/yotova-shte-vruchi-mandata-na-pb-na-7-may
  [2026-05-05T19:25:40.173811+00:00] Йотова ще връчи мандата на ПБ на 7 май
    https://www.segabg.com/hot/category-bulgaria/yotova-shte-vruchi-mandata-na-pb-na-7-may

Published: 2026-05-05 16:30:13+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T06:32:11.326032+00:00] Свлачището до Пампорово може да тръгне отново
    https://www.segabg.com/category-bulgaria/svlachishteto-pamporovo-mozhe-da-trugne-otnovo
  [2026-05-05T17:45:37.584390+00:00] Свлачището до Пампорово може да тръгне отново
    https://www.segabg.com/hot/category-bulgaria/svlachishteto-pamporovo-mozhe-da-trugne-otnovo

Published: 2026-05-05 19:36:57+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T06:32:11.326245+00:00] Везенков е за 4-ти път във Final 4 на Евролигата
    https://www.segabg.com/category-sport/vezenkov-e-za-4-ti-put-vuv-final-4-na-evroligata
  [2026-05-05T21:06:17.327400+00:00] Везенков е за 4-ти път във Final 4 на Евролигата
    https://www.segabg.com/hot/category-sport/vezenkov-e-za-4-ti-put-vuv-final-4-na-evroligata

Published: 2026-05-06 09:00:21+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T17:44:10.819407+00:00] МЗ създава електронен регистър на онкоболните
    https://www.segabg.com/category-zdrave/mz-suzdava-elektronen-registur-na-onkobolnite
  [2026-05-06T10:22:54.972150+00:00] МЗ създава електронен регистър на онкоболните
    https://www.segabg.com/hot/category-zdrave/mz-suzdava-elektronen-registur-na-onkobolnite

Published: 2026-05-06 17:25:18+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T19:50:18.277102+00:00] Италианската оценка преди BG старта на "Джирото": Перфето!
    https://www.segabg.com/category-sport/italianskata-ocenka-predi-bg-starta-na-dzhiroto-perfeto
  [2026-05-06T17:44:10.818829+00:00] Италианската оценка преди BG старта на "Джирото": Перфето!
    https://www.segabg.com/hot/category-sport/italianskata-ocenka-predi-bg-starta-na-dzhiroto-perfeto

Published: 2026-05-06 19:34:27+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-07T06:38:55.176018+00:00] Москва се опаса с още над 40 кули с ПВО
    https://www.segabg.com/category-the-war/moskva-se-opasa-oshte-nad-40-kuli-pvo
  [2026-05-06T19:50:18.276683+00:00] Москва се опаса с още над 40 кули с ПВО
    https://www.segabg.com/hot/category-the-war/moskva-se-opasa-oshte-nad-40-kuli-pvo

Published: 2026-05-07 09:01:42+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-07T14:19:02.635903+00:00] Интерпол задържа 270 души в мегакция срещу фалшиви лекарства
    https://www.segabg.com/category-bulgaria/interpol-zadurzha-270-dushi-megakciya-sreshtu-falshivi-lekarstva
  [2026-05-07T10:28:12.665449+00:00] Интерпол задържа 270 души в мегакция срещу фалшиви лекарства
    https://www.segabg.com/hot/category-bulgaria/interpol-zadurzha-270-dushi-megakciya-sreshtu-falshivi-lekarstva

Published: 2026-05-07 09:49:41+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-07T14:19:02.635894+00:00] Премиерът Гюров нарече министрите си спартанци
    https://www.segabg.com/category-bulgaria/premierut-gyurov-nareche-ministrite-si-spartanci
  [2026-05-07T10:28:12.665426+00:00] Премиерът Гюров нарече министрите си спартанци
    https://www.segabg.com/hot/category-bulgaria/premierut-gyurov-nareche-ministrite-si-spartanci

Published: 2026-05-07 12:21:29+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-07T17:51:29.243440+00:00] Съдът реши приемът в детските градини в София да е по новите правила
    https://www.segabg.com/category-education/sudut-reshi-priemut-detskite-gradini-sofiya-da-e-po-novite-pravila
  [2026-05-07T14:19:02.635707+00:00] Съдът реши приемът в детските градини в София да е по новите правила
    https://www.segabg.com/hot/category-education/sudut-reshi-priemut-detskite-gradini-sofiya-da-e-po-novite-pravila

Published: 2026-05-07 15:59:17+00:00 | Title sim: 0.780 | Text sim: 1.000
  [2026-05-08T06:00:37.629057+00:00] Изненадите в кабинета на Радев - някои невзрачни, други - комични
    https://www.segabg.com/hot/category-bulgaria/iznenadite-kabineta-na-radev-nyakoi-nevzrachni-drugi-komichni
  [2026-05-07T17:51:29.242901+00:00] Изненадите в кабинета на Радев - някои трагични, други - комични
    https://www.segabg.com/hot/category-bulgaria/iznenadite-kabineta-na-radev-nyakoi-tragichni-drugi-komichni

Published: 2026-05-08 03:40:02+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-08T07:55:11.246888+00:00] Кризата с горивата оскъпява и ученическите екскурзии
    https://www.segabg.com/hot/category-education/krizata-gorivata-oskupyava-i-uchenicheskite-ekskurzii
  [2026-05-08T06:00:37.628913+00:00] Кризата с горивата оскъпява и ученическите екскурзии
    https://www.segabg.com/hot/category-bulgaria/krizata-gorivata-oskupyava-i-uchenicheskite-ekskurzii

Published: 2026-05-08 08:20:53+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-08T11:20:19.111891+00:00] "Мяра": Българите очакват от ПБ бюджет и овладяване на цените
    https://www.segabg.com/category-bulgaria/myara-bulgarite-ochakvat-pb-byudzhet-i-ovladyavane-na-cenite
  [2026-05-08T09:26:11.113387+00:00] "Мяра": Българите очакват от ПБ бюджет и овладяване на цените
    https://www.segabg.com/hot/category-bulgaria/myara-bulgarite-ochakvat-pb-byudzhet-i-ovladyavane-na-cenite

Published: 2026-05-09 03:12:24+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-09T06:20:16.993010+00:00] Румъния бори адското чакане на Дунав мост с трасе за предплащане
    https://www.segabg.com/hot/category-foreign-country/rumuniya-bori-adskoto-chakane-na-dunav-most-trase-za-predplashtane
  [2026-05-09T03:21:42.156770+00:00] Румъния бори адското чакане на Дунав мост с трасе за предплащане
    https://www.segabg.com/hot/category-bulgaria/rumuniya-bori-adskoto-chakane-na-dunav-most-trase-za-predplashtane

Published: 2026-05-09 12:03:03+00:00 | Title sim: 0.261 | Text sim: 1.000
  [2026-05-09T14:54:21.992997+00:00] Норвегия се връща към газови находища, затворени миналия век
    https://www.segabg.com/hot/category-economy/norvegiya-se-vrushta-kum-gazovi-nahodishta-zatvoreni-minaliya-vek
  [2026-05-09T13:23:55.388139+00:00] Норвегия рестартира три стари газови находища
    https://www.segabg.com/hot/category-economy/norvegiya-restartira-tri-stari-gazovi-nahodishta

Published: 2026-05-10 06:58:02+00:00 | Title sim: 0.818 | Text sim: 1.000
  [2026-05-10T11:02:20.540984+00:00] Един от пострадалите от "Джирото" е в "Пирогов"
    https://www.segabg.com/hot/category-sport/edin-postradalite-dzhiroto-e-pirogov
  [2026-05-10T09:41:03.890611+00:00] Един от пострадалите от "Джирото" е в стабилно състояние в "Пирогов"
    https://www.segabg.com/hot/category-sport/edin-postradalite-dzhiroto-e-stabilno-sustoyanie-pirogov

Published: 2026-05-10 08:12:31+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-10T17:00:00.800152+00:00] Пхенян ще нанесе ядрен удар при покушение срещу Ким
    https://www.segabg.com/category-foreign-country/phenyan-shte-nanese-yadren-udar-pri-pokushenie-sreshtu-kim
  [2026-05-10T09:41:03.890588+00:00] Пхенян ще нанесе ядрен удар при покушение срещу Ким
    https://www.segabg.com/hot/category-foreign-country/phenyan-shte-nanese-yadren-udar-pri-pokushenie-sreshtu-kim

Published: 2026-05-10 08:33:23+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-11T17:57:25.620802+00:00] Половината сделки се сключват с до 10% отстъпка от цената на имота
    https://www.segabg.com/hot/polovinata-sdelki-se-sklyuchvat-10-otstupka-cenata-na-imota
  [2026-05-10T17:00:00.800004+00:00] Половината сделки се сключват с до 10% отстъпка от цената на имота
    https://www.segabg.com/hot/category-economy/polovinata-sdelki-se-sklyuchvat-10-otstupka-cenata-na-imota

Published: 2026-05-10 10:00:40+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-10T13:24:56.067456+00:00] Гърци готвят блокада с трактори на пункт "Кулата"
    https://www.segabg.com/category-economy/gurci-gotvyat-blokada-traktori-na-punkt-kulata
  [2026-05-10T11:02:20.540954+00:00] Гърци готвят блокада с трактори на пункт "Кулата"
    https://www.segabg.com/hot/category-economy/gurci-gotvyat-blokada-traktori-na-punkt-kulata

Published: 2026-05-10 12:15:07+00:00 | Title sim: 0.695 | Text sim: 1.000
  [2026-05-10T14:56:28.883925+00:00] Правят се големи промени при тестовете за алкохол и дрога на пътя
    https://www.segabg.com/hot/category-bulgaria/pravyat-se-golemi-promeni-pri-testovete-za-alkohol-i-droga-na-putya
  [2026-05-10T13:24:56.067100+00:00] Правят се важни промени при пробите за алкохол и дрога на пътя
    https://www.segabg.com/hot/category-bulgaria/pravyat-se-vazhni-promeni-pri-probite-za-alkohol-i-droga-na-putya

Published: 2026-05-10 17:30:22+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-11T07:45:44.678456+00:00] Голям пожар с гъст черен дим горя в София
    https://www.segabg.com/category-bulgaria/golyam-pozhar-gust-cheren-dim-gorya-sofiya
  [2026-05-10T20:52:34.362037+00:00] Голям пожар с гъст черен дим горя в София
    https://www.segabg.com/hot/category-bulgaria/golyam-pozhar-gust-cheren-dim-gorya-sofiya

Published: 2026-05-11 09:27:35+00:00 | Title sim: 0.054 | Text sim: 1.000
  [2026-05-11T15:00:24.224130+00:00] Приходите от осигуровки растат по-бързо от разходите за пенсии
    https://www.segabg.com/hot/category-bulgaria/prihodite-osigurovki-rastat-po-burzo-razhodite-za-pensii
  [2026-05-11T11:27:03.953271+00:00] За година средната пенсия се е увеличила с 42 евро
    https://www.segabg.com/hot/category-bulgaria/za-godina-srednata-pensiya-se-e-uvelichila-42-evro

Published: 2026-05-11 13:36:34+00:00 | Title sim: 0.835 | Text sim: 1.000
  [2026-05-11T17:57:25.620643+00:00] Влади Ковачев от Времето на БНТ става герой в канибалска пънк драма
    https://www.segabg.com/category-culture/vladi-kovachev-vremeto-na-bnt-stava-geroy-kanibalska-punk-drama
  [2026-05-11T15:00:24.224487+00:00] Влади Ковачев от времето на БНТ става герой в криминална пънк драма
    https://www.segabg.com/category-culture/vladi-kovachev-vremeto-na-bnt-stava-geroy-kriminalna-punk-drama

Published: 2026-05-12 09:04:13+00:00 | Title sim: 0.752 | Text sim: 1.000
  [2026-05-12T14:32:12.496802+00:00] БАБХ установи, че стотици стада са фантомни
    https://www.segabg.com/hot/category-economy/babh-ustanovi-che-stotici-stada-sa-fantomni
  [2026-05-12T10:36:28.274962+00:00] БАБХ установи, че хиляди стада са фантомни
    https://www.segabg.com/hot/category-economy/babh-ustanovi-che-hilyadi-stada-sa-fantomni

Published: 2026-05-12 10:08:57+00:00 | Title sim: 0.706 | Text sim: 0.955
  [2026-05-12T14:32:12.496701+00:00] Ася Панджерова подаде оставка като зам.-министър на образованието
    https://www.segabg.com/hot/category-education/asya-pandzherova-podade-ostavka-kato-zam-ministur-na-obrazovanieto
  [2026-05-12T10:36:28.274918+00:00] Зам.-министърката на образованието Ася Панджерова подаде оставка
    https://www.segabg.com/hot/category-education/zam-ministurkata-na-obrazovanieto-asya-pandzherova-podade-ostavka

Published: 2026-05-12 12:18:50+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-12T18:03:05.213698+00:00] Зеленски не фигурира в разследването за пране на пари срещу Ермак
    https://www.segabg.com/category-foreign-country/zelenski-ne-figurira-razsledvaneto-za-prane-na-pari-sreshtu-ermak
  [2026-05-12T14:32:12.496761+00:00] Зеленски не фигурира в разследването за пране на пари срещу Ермак
    https://www.segabg.com/hot/category-foreign-country/zelenski-ne-figurira-razsledvaneto-za-prane-na-pari-sreshtu-ermak

Published: 2026-05-13 12:56:46+00:00 | Title sim: 0.921 | Text sim: 0.934
  [2026-05-13T18:05:41.313705+00:00] България изненадващо бе само с посланик на натовска среща на върха
    https://www.segabg.com/hot/category-foreign-country/bulgariya-iznenadvashto-be-samo-poslanik-na-natovska-sreshta-na-vurha
  [2026-05-13T14:41:35.131317+00:00] България е изненадващо само с посланик на натовска среща на върха
    https://www.segabg.com/hot/category-foreign-country/bulgariya-e-iznenadvashto-samo-poslanik-na-natovska-sreshta-na-vurha

Published: 2026-05-13 12:59:00+00:00 | Title sim: 0.085 | Text sim: 1.000
  [2026-05-13T21:28:50.893084+00:00] Радев се разплаща за даренията с постове
    https://www.segabg.com/category-video/radev-se-razplashta-za-dareniyata-postove
  [2026-05-13T14:41:35.131278+00:00] Спонсорите на Радев са зад скандалните назначения
    https://www.segabg.com/category-video/sponsorite-na-radev-sa-zad-skandalnite-naznacheniya

Published: 2026-05-14 09:23:57+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-14T14:22:29.654311+00:00] 15 от 16 клуба в Първа лига поискаха ултимативно нов договор за ТВ права
    https://www.segabg.com/category-sport/15-16-kluba-purva-liga-poiskaha-ultimativno-nov-dogovor-za-tv-prava
  [2026-05-14T10:25:46.617313+00:00] 15 от 16 клуба в Първа лига поискаха ултимативно нов договор за ТВ права
    https://www.segabg.com/hot/category-sport/15-16-kluba-purva-liga-poiskaha-ultimativno-nov-dogovor-za-tv-prava

Published: 2026-05-14 11:52:09+00:00 | Title sim: 1.000 | Text sim: 0.982
  [2026-05-14T17:54:48.432905+00:00] МОН обеща пълна анонимност на матурите
    https://www.segabg.com/category-education/mon-obeshta-pulna-anonimnost-na-maturite
  [2026-05-14T14:22:29.653947+00:00] МОН обеща пълна анонимност на матурите
    https://www.segabg.com/hot/category-education/mon-obeshta-pulna-anonimnost-na-maturite

Published: 2026-05-14 13:34:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-14T17:54:48.432700+00:00] Водачът на бунта срещу британския премиер подаде оставка като министър
    https://www.segabg.com/category-foreign-country/vodachut-na-bunta-sreshtu-britanskiya-premier-podade-ostavka-kato-ministur
  [2026-05-14T14:22:29.653918+00:00] Водачът на бунта срещу британския премиер подаде оставка като министър
    https://www.segabg.com/hot/category-foreign-country/vodachut-na-bunta-sreshtu-britanskiya-premier-podade-ostavka-kato-ministur

Published: 2026-05-15 03:10:08+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-15T06:58:39.906109+00:00] Стотици милиони видяха България заради "Джирото"
    https://www.segabg.com/hot/category-media/stotici-milioni-vidyaha-bulgariya-zaradi-dzhiroto
  [2026-05-15T03:41:20.945862+00:00] Стотици милиони видяха България заради "Джирото"
    https://www.segabg.com/hot/category-sport/stotici-milioni-vidyaha-bulgariya-zaradi-dzhiroto

Published: 2026-05-15 08:47:06+00:00 | Title sim: 0.774 | Text sim: 1.000
  [2026-05-16T09:44:25.650458+00:00] Софийският фестивал на науката ни "разхожда" от микропластмаси до космическо инженерство
    https://www.segabg.com/category-education/sofiyskiyat-festival-na-naukata-ni-razhozhda-mikroplastmasi-kosmichesko-inzhenerstvo
  [2026-05-15T10:28:57.906776+00:00] Софийският фестивал на науката ще ни "разходи" от микропластмаси до космическо инженерство
    https://www.segabg.com/category-education/sofiyskiyat-festival-na-naukata-shte-ni-razhodi-mikroplastmasi-kosmichesko-inzhenerstvo

Published: 2026-05-15 16:13:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-16T11:04:25.400448+00:00] Мотористи блокираха ключови пътища в страната заради "Гражданска отговорност"
    https://www.segabg.com/category-bulgaria/motoristi-blokiraha-klyuchovi-putishta-stranata-zaradi-grazhdanska-otgovornost
  [2026-05-15T17:41:57.698123+00:00] Мотористи блокираха ключови пътища в страната заради "Гражданска отговорност"
    https://www.segabg.com/hot/category-bulgaria/motoristi-blokiraha-klyuchovi-putishta-stranata-zaradi-grazhdanska-otgovornost

Published: 2026-05-15 18:17:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-16T11:04:25.400520+00:00] Гърция е №2 по плажове "Син флаг"
    https://www.segabg.com/category-foreign-country/gurciya-e-no2-po-plazhove-sin-flag
  [2026-05-15T19:42:53.046958+00:00] Гърция е №2 по плажове "Син флаг"
    https://www.segabg.com/hot/category-foreign-country/gurciya-e-no2-po-plazhove-sin-flag

Published: 2026-05-16 10:41:50+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-16T14:59:53.799595+00:00] Делото срещу правилата за изследователските университети се гледа на закрито
    https://www.segabg.com/category-education/deloto-sreshtu-pravilata-za-izsledovatelskite-universiteti-se-gleda-na-zakrito
  [2026-05-16T11:04:25.400224+00:00] Делото срещу правилата за изследователските университети се гледа на закрито
    https://www.segabg.com/hot/category-education/deloto-sreshtu-pravilata-za-izsledovatelskite-universiteti-se-gleda-na-zakrito


In [188]:
inspect_source_duplicate_similarity(df, "bta", threshold=0.7)

Published: 2026-05-05 15:05:00+00:00 | Title sim: 1.000 | Text sim: 0.883
  [2026-05-05T16:13:48.135656+00:00] Президентът Илияна Йотова ще връчи мандата за съставяне на правителство на 7 май
    https://www.bta.bg/bg/news/bulgaria/1120064-prezidentat-iliyana-yotova-shte-vrachi-mandata-za-sastavyane-na-pravitelstvo-na-
  [2026-05-05T15:32:43.295435+00:00] Президентът Илияна Йотова ще връчи мандата за съставяне на правителство на 7 май
    https://www.bta.bg/bg/news/bulgaria/1120042-prezidentat-iliyana-yotova-shte-vrachi-mandata-za-sastavyane-na-pravitelstvo-na-

Published: 2026-05-07 14:10:00+00:00 | Title sim: 1.000 | Text sim: 0.667
  [2026-05-07T14:18:48.663588+00:00] Кандидатът за премиер от "Прогресивна България" Румен Радев представи структура и състав на проектокабинет
    https://www.bta.bg/bg/news/bulgaria/1120749-kandidatat-za-premier-ot-progresivna-balgariya-rumen-radev-predstavi-struktura
  [2026-05-07T14:18:48.663519+00:00] Кандидатът за премиер от "Прогресивна България" Румен Радев представи структура и състав на проектокабинет
    https://www.bta.bg/bg/news/bulgaria/1121186-kandidatat-za-premier-ot-progresivna-balgariya-rumen-radev-predstavi-struktura

Published: 2026-05-08 07:22:00+00:00 | Title sim: 0.723 | Text sim: 0.928
  [2026-05-08T09:26:01.370849+00:00] Няма да подкрепим предложеното правителство, но му пожелаваме успех да премахне предпоставките за политическа криза, заявиха от "Демократична България"
    https://www.bta.bg/bg/news/bulgaria/1121647-nyama-da-podkrepim-predlozhenoto-pravitelstvo-no-mu-pozhelavame-uspeh-da-premah
  [2026-05-08T07:54:50.940214+00:00] Няма да подкрепим предложеното правителство, но му пожелаваме успех да премахне предпоставките за политическа криза, заяви Божидар Божанов от ДБ
    https://www.bta.bg/bg/news/bulgaria/1121553-nyama-da-podkrepim-predlozhenoto-pravitelstvo-no-mu-pozhelavame-uspeh-da-premah

Published: 2026-05-09 19:00:00+00:00 | Title sim: 0.877 | Text sim: 0.996
  [2026-05-09T20:48:53.567915+00:00] Творци дават нов живот на бивша фабрика за стомана в Германия, включена в списъка на ЮНЕСКО за световното културно наследство
    https://www.bta.bg/bg/news/lik/1122686-tvortsi-davat-nov-zhivot-na-bivsha-fabrika-za-stomana-v-germaniya-vklyuchena-v-
  [2026-05-09T19:06:39.264828+00:00] Десетки творци вдъхват нов живот на бивша фабрика за стомана в Германия, включена в списъка на ЮНЕСКО за световното културно наследство
    https://www.bta.bg/bg/news/lik/1122686-desetki-tvortsi-vdahvat-nov-zhivot-na-bivsha-fabrika-za-stomana-v-germaniya-vkl

Published: 2026-05-10 19:40:00+00:00 | Title sim: 1.000 | Text sim: 0.679
  [2026-05-10T20:52:27.021604+00:00] Априлската епопея бележи едни от най-славните времена в българската история с величие и трагизъм, каза президентът Илияна Йотова в Бяла черква
    https://www.bta.bg/bg/news/bulgaria/1123036-aprilskata-epopeya-belezhi-edni-ot-nay-slavnite-vremena-v-balgarskata-istoriya-s
  [2026-05-10T20:52:27.021582+00:00] Априлската епопея бележи едни от най-славните времена в българската история с величие и трагизъм, каза президентът Илияна Йотова в Бяла черква
    https://www.bta.bg/bg/news/bulgaria/1123040-aprilskata-epopeya-belezhi-edni-ot-nay-slavnite-vremena-v-balgarskata-istoriya-s

Published: 2026-05-11 20:58:00+00:00 | Title sim: 0.367 | Text sim: 0.808
  [2026-05-11T22:57:21.465123+00:00] Служители в британското правителство подадоха оставки, министри призоваха премиера Стармър да насрочи оттеглянето си от поста
    https://www.bta.bg/bg/news/world/1123853-sluzhiteli-v-britanskoto-pravitelstvo-podadoha-ostavki-ministri-prizovaha-premi
  [2026-05-11T21:20:22.605243+00:00] Британската вътрешна министърка е казала на премиера Стармър да насрочи оттеглянето си от поста, пише в. "Таймс"
    https://www.bta.bg/bg/news/world/1123848-britanskata-vatreshna-ministarka-e-kazala-na-premiera-starmar-da-nasrochi-ottegl

Published: 2026-05-13 19:16:00+00:00 | Title sim: 1.000 | Text sim: 0.206
  [2026-05-13T21:28:38.419855+00:00] Сенатът на САЩ утвърди Кевин Уорш за нов президент на Федералния резерв
    https://www.bta.bg/bg/news/economy/1125507-senatat-na-sasht-utvardi-kevin-uorsh-za-nov-prezident-na-federalniya-rezerv
  [2026-05-13T21:28:38.419680+00:00] Сенатът на САЩ утвърди Кевин Уорш за нов президент на Федералния резерв
    https://www.bta.bg/bg/news/economy/1125526-senatat-na-sasht-utvardi-kevin-uorsh-za-nov-prezident-na-federalniya-rezerv

Published: 2026-05-14 19:43:00+00:00 | Title sim: 0.927 | Text sim: 0.998
  [2026-05-14T21:12:58.187335+00:00] Априлското въстание и последвалите бунтове на българите бяха тема в първия ден на форум в Разлог, посветен на 150 години от Априлската епопея
    https://www.bta.bg/bg/news/lik/1126406-aprilskoto-vastanie-i-posledvalite-buntove-na-balgarite-byaha-tema-v-parviya-den
  [2026-05-14T19:49:37.864049+00:00] Априлското въстание и последвалите въстанията на българите бяха тема в първия ден на форум в Разлог, посветен на 150 години от Априлската епопея
    https://www.bta.bg/bg/news/lik/1126406-aprilskoto-vastanie-i-posledvalite-vastaniyata-na-balgarite-byaha-tema-v-parviya

Published: 2026-05-16 23:04:00+00:00 | Title sim: 1.000 | Text sim: 0.944
  [2026-05-17T03:40:12.567647+00:00] България спечели тазгодишното издание на „Евровизия“
    https://www.bta.bg/bg/news/bulgaria/1127541-balgariya-specheli-tazgodishnoto-izdanie-na-evroviziya-
  [2026-05-17T03:40:12.567629+00:00] България спечели тазгодишното издание на „Евровизия“
    https://www.bta.bg/bg/news/bulgaria/1127549-balgariya-specheli-tazgodishnoto-izdanie-na-evroviziya-
  [2026-05-17T03:40:12.567621+00:00] България спечели тазгодишната юбилейна „Евровизия“ и ще бъде домакин на следващото издание на конкурса
    https://www.bta.bg/bg/news/bulgaria/1127550-balgariya-specheli-tazgodishnata-yubileyna-evroviziya-i-shte-bade-domakin-na-s

Published: 2026-05-17 15:59:00+00:00 | Title sim: 0.557 | Text sim: 0.745
  [2026-05-17T16:59:45.250003+00:00] Дара се завърна в София след победата на „Евровизия"
    https://www.bta.bg/bg/news/lik/1127765-dara-se-zavarna-v-sofiya-sled-pobedata-na-evroviziya-
  [2026-05-17T16:59:45.249925+00:00] Направихме нещо много голямо за българската музика, каза Дара, която се завърна в София след победата на „Евровизия"
    https://www.bta.bg/bg/news/lik/1127820-napravihme-neshto-mnogo-golyamo-za-balgarskata-muzika-kaza-dara-koyato-se-zava

Published: 2026-05-18 16:11:00+00:00 | Title sim: 0.166 | Text sim: 0.773
  [2026-05-18T16:49:47.709789+00:00] Мерц поздрави България с победата на „Евровизия“ в началото на пресконференцията си с Румен Радев
    https://www.bta.bg/bg/news/world/1128579-merts-pozdravi-balgariya-s-pobedata-na-evroviziya-v-nachaloto-na-preskonferent
  [2026-05-18T16:49:47.709712+00:00] Радвам се, че България върви по пътя на европейската солидарност, каза германският канцлер Фридрих Мерц
    https://www.bta.bg/bg/news/world/1128595-radvam-se-che-balgariya-varvi-po-patya-na-evropeyskata-solidarnost-kaza-german

Published: 2026-05-18 19:21:00+00:00 | Title sim: 0.483 | Text sim: 0.964
  [2026-05-18T21:15:28.708788+00:00] ЕС удължи санкциите срещу лица и юридически обекти, свързани с режима на бившия сирийски президент Башар Асад, с още една година
    https://www.bta.bg/bg/news/world/1128676-es-udalzhi-sanktsiite-sreshtu-litsa-i-yuridicheski-obekti-svarzani-s-rezhima-na
  [2026-05-18T19:48:18.266567+00:00] ЕС удължи санкциите срещу свързани с режима на Асад с още година; премахна сирийски правителства от санкционния списък
    https://www.bta.bg/bg/news/world/1128676-es-udalzhi-sanktsiite-sreshtu-svarzani-s-rezhima-na-asad-s-oshte-godina-premahn

Published: 2026-05-19 17:08:00+00:00 | Title sim: 1.000 | Text sim: 0.877
  [2026-05-19T18:08:46.228391+00:00] Гответе се за „Евровизия 2027" в България, призова генералният директор на БНТ Милена Милотинова
    https://www.bta.bg/bg/news/lik/1129409-gotvete-se-za-evroviziya-2027-v-balgariya-prizova-generalniyat-direktor-na-bn
  [2026-05-19T18:08:46.228223+00:00] Гответе се за „Евровизия 2027" в България, призова генералният директор на БНТ Милена Милотинова
    https://www.bta.bg/bg/news/lik/1129558-gotvete-se-za-evroviziya-2027-v-balgariya-prizova-generalniyat-direktor-na-bn

Published: 2026-05-19 21:26:00+00:00 | Title sim: 1.000 | Text sim: 0.857
  [2026-05-19T23:04:52.200018+00:00] Писателката Ян Шуан-цзъ от Тайван спечели Международната награда „Букър”
    https://www.bta.bg/bg/news/lik/1129611-pisatelkata-yan-shuan-tsza-ot-tayvan-specheli-mezhdunarodnata-nagrada-bukar-
  [2026-05-19T23:04:52.199998+00:00] Писателката Ян Шуан-цзъ от Тайван спечели Международната награда „Букър”
    https://www.bta.bg/bg/news/lik/1129614-pisatelkata-yan-shuan-tsza-ot-tayvan-specheli-mezhdunarodnata-nagrada-bukar-

Published: 2026-05-20 19:22:00+00:00 | Title sim: 0.420 | Text sim: 0.926
  [2026-05-20T21:58:15.114076+00:00] АПА: Бивш служител на австрийското разузнаване бе осъден на 49 месеца затвор по обвинения в шпионаж в полза на Русия
    https://www.bta.bg/bg/news/world/1130423-apa-bivsh-sluzhitel-na-avstriyskoto-razuznavane-be-osaden-na-49-mesetsa-zatvor-
  [2026-05-20T21:58:15.113962+00:00] Бивш австрийски разузнавач бе осъден на 49 месеца затвор за шпионаж в полза на Русия; според прокуратурата българите, осъдени в Лондон, също са служели за свръзка
    https://www.bta.bg/bg/news/world/1130430-bivsh-avstriyski-razuznavach-be-osaden-na-49-mesetsa-zatvor-za-shpionazh-v-polza

Published: 2026-05-22 19:30:00+00:00 | Title sim: 0.862 | Text sim: 1.000
  [2026-05-22T21:13:51.135702+00:00] АП: Държавите от НАТО са объркани от решението на Тръмп да разположи 5000 американски военнослужещи в Полша
    https://www.bta.bg/bg/news/world/1132138-ap-darzhavite-ot-nato-sa-obarkani-ot-reshenieto-na-tramp-da-razpolozhi-5000-ame
  [2026-05-22T19:50:56.414870+00:00] АП: Държави в НАТО са объркани от решението на Тръмп да разположи 5000 американски военнослужещи в Полша
    https://www.bta.bg/bg/news/world/1132138-ap-darzhavi-v-nato-sa-obarkani-ot-reshenieto-na-tramp-da-razpolozhi-5000-amerik

Published: 2026-05-23 20:43:00+00:00 | Title sim: 0.816 | Text sim: 0.977
  [2026-05-23T22:55:51.334581+00:00] Йоана Илиева се класира на 17-о място за Световната купа на сабя в Лима
    https://www.bta.bg/bg/news/sport/1132560-yoana-ilieva-se-klasira-na-17-o-myasto-za-svetovnata-kupa-na-sabya-v-lima
  [2026-05-23T20:56:31.613139+00:00] Йоана Илиева завърши на 17-о място за Световната купа на сабя в Лима
    https://www.bta.bg/bg/news/sport/1132560-yoana-ilieva-zavarshi-na-17-o-myasto-za-svetovnata-kupa-na-sabya-v-lima

Published: 2026-05-24 16:20:00+00:00 | Title sim: 1.000 | Text sim: 0.866
  [2026-05-24T17:05:31.063684+00:00] Буквите имат особено значение за нас, 24 май не е носталгия, а бъдеще, заяви президентът Илияна Йотова на традиционния прием по случай празника
    https://www.bta.bg/bg/news/bulgaria/1132896-bukvite-imat-osobeno-znachenie-za-nas-24-may-ne-e-nostalgiya-a-badeshte-zayav
  [2026-05-24T17:05:31.063627+00:00] Буквите имат особено значение за нас, 24 май не е носталгия, а бъдеще, заяви президентът Илияна Йотова на традиционния прием по случай празника
    https://www.bta.bg/bg/news/bulgaria/1132909-bukvite-imat-osobeno-znachenie-za-nas-24-may-ne-e-nostalgiya-a-badeshte-zayav

Published: 2026-05-29 20:34:00+00:00 | Title sim: 0.562 | Text sim: 0.975
  [2026-05-30T03:38:07.212149+00:00] Федерален съдия постанови премахване на името на Тръмп от наименованието на центъра "Кенеди"
    https://www.bta.bg/bg/news/world/1136906-federalen-sadiya-postanovi-premahvane-na-imeto-na-tramp-ot-naimenovanieto-na-tse
  [2026-05-29T21:53:45.422189+00:00] Федерален съдия постанови, че добавянето на името на Тръмп към „Кенеди център“ е незаконно
    https://www.bta.bg/bg/news/world/1136906-federalen-sadiya-postanovi-che-dobavyaneto-na-imeto-na-tramp-kam-kenedi-tsenta

Published: 2026-05-31 05:13:00+00:00 | Title sim: 0.835 | Text sim: 0.978
  [2026-05-31T11:42:30.730041+00:00] Близо 800 души бяха арестувани във Франция след победата на ПСЖ на финала на Шампионската лига
    https://www.bta.bg/bg/news/sport/1137229-blizo-800-dushi-byaha-arestuvani-vav-frantsiya-sled-pobedata-na-pszh-na-finala-n
  [2026-05-31T08:49:54.166896+00:00] Над 400 души бяха арестувани във Франция след победата на ПСЖ на финала на Шампионската лига
    https://www.bta.bg/bg/news/sport/1137229-nad-400-dushi-byaha-arestuvani-vav-frantsiya-sled-pobedata-na-pszh-na-finala-na-

Published: 2026-06-05 19:03:00+00:00 | Title sim: 1.000 | Text sim: 0.698
  [2026-06-05T19:59:00.093155+00:00] Двама от пострадалите при катастрофата на „Челопешко шосе" в София са в критично състояние, установени са 14 участници в произшествието
    https://www.bta.bg/bg/news/bulgaria/1141737-dvama-ot-postradalite-pri-katastrofata-na-chelopeshko-shose-v-sofiya-sa-v-krit
  [2026-06-05T19:59:00.093138+00:00] Двама от пострадалите при катастрофата на „Челопешко шосе" в София са в критично състояние, установени са 14 участници в произшествието
    https://www.bta.bg/bg/news/bulgaria/1141745-dvama-ot-postradalite-pri-katastrofata-na-chelopeshko-shose-v-sofiya-sa-v-krit

Published: 2026-06-05 19:30:00+00:00 | Title sim: 0.916 | Text sim: 1.000
  [2026-06-05T21:41:07.157024+00:00] В Казанлък беше коронясана 58-ата Царица Роза Деница Малчева
    https://www.bta.bg/bg/news/bulgaria/1141747-v-kazanlak-beshe-koronyasana-58-ata-tsaritsa-roza-denitsa-malcheva
  [2026-06-05T19:59:00.093038+00:00] В Казанлък беше коронясана Деница Малчева за 58-ата Царица Роза
    https://www.bta.bg/bg/news/bulgaria/1141747-v-kazanlak-beshe-koronyasana-denitsa-malcheva-za-58-ata-tsaritsa-roza
  [2026-06-05T19:59:00.093028+00:00] Норвежец е арестуван в Русия, заяви външното министерство на Норвегия
    https://www.bta.bg/bg/news/world/1141658-norvezhets-e-arestuvan-v-rusiya-zayavi-vanshnoto-ministerstvo-na-norvegiya

Published: 2026-06-05 20:50:00+00:00 | Title sim: 1.000 | Text sim: 0.759
  [2026-06-05T21:41:07.156881+00:00] Двама от участниците в катастрофата на ул. „Челопешко шосе" са неправоспособни, каза заместник-градският прокурор на София Ангел Кънев
    https://www.bta.bg/bg/news/bulgaria/1141767-dvama-ot-uchastnitsite-v-katastrofata-na-ul-chelopeshko-shose-sa-nepravosposo
  [2026-06-05T21:41:07.156830+00:00] Двама от участниците в катастрофата на ул. „Челопешко шосе" са неправоспособни, каза заместник-градският прокурор на София Ангел Кънев
    https://www.bta.bg/bg/news/bulgaria/1141768-dvama-ot-uchastnitsite-v-katastrofata-na-ul-chelopeshko-shose-sa-nepravosposo

Published: 2026-06-06 19:01:00+00:00 | Title sim: 0.793 | Text sim: 0.999
  [2026-06-06T21:07:57.336190+00:00] Кухненските гъби за съдове отделят микропласмаси при употреба, но миенето с много вода вреди повече на околната среда, установи проучване
    https://www.bta.bg/bg/news/lik/1140824-kuhnenskite-gabi-za-sadove-otdelyat-mikroplasmasi-pri-upotreba-no-mieneto-s-mno
  [2026-06-06T19:27:14.979546+00:00] Кухненските гъби отделят микропласмаси при употреба, но използването на много вода вреди повече на околната среда, установи проучване
    https://www.bta.bg/bg/news/lik/1140824-kuhnenskite-gabi-otdelyat-mikroplasmasi-pri-upotreba-no-izpolzvaneto-na-mnogo-v

Published: 2026-06-07 07:33:00+00:00 | Title sim: 1.000 | Text sim: 0.776
  [2026-06-07T09:17:31.677245+00:00] Посетители от страната и чужбина събра ритуалът „Розобер“ в розовите градини край Казанлък, гост е президентът Илияна Йотова
    https://www.bta.bg/bg/news/bulgaria/1142156-posetiteli-ot-stranata-i-chuzhbina-sabra-ritualat-rozober-v-rozovite-gradini-k
  [2026-06-07T09:17:31.677191+00:00] Посетители от страната и чужбина събра ритуалът „Розобер“ в розовите градини край Казанлък, гост е президентът Илияна Йотова
    https://www.bta.bg/bg/news/bulgaria/1142163-posetiteli-ot-stranata-i-chuzhbina-sabra-ritualat-rozober-v-rozovite-gradini-k

Source: bta | Total groups: 143 | Title sim >= 0.7: 19 | Text sim >= 0.7: 21

In [189]:
inspect_source_duplicate_similarity(df, "vesti", threshold=0.7)

Published: 2026-05-05 03:45:00+00:00 | Title sim: 0.063 | Text sim: 0.833
  [2026-05-05T10:07:47.065231+00:00] "Прогресивна България": До края на седмицата ще има правителство
    https://www.vesti.bg/bulgaria/progresivna-bylgariiado-kraia-na-sedmicata-shte-ima-pravitelstvo-6258729
  [2026-05-05T06:20:11.295865+00:00] Старт на консултациите: Президентът се среща с парламентарните групи
    https://www.vesti.bg/bulgaria/start-na-konsultaciite-prezidentytse-sreshta-s-parlamentarnite-grupi-6258729

Published: 2026-05-05 09:10:00+00:00 | Title sim: 0.580 | Text sim: 0.911
  [2026-05-05T15:33:44.268320+00:00] Две земетресения разлюляха Сърбия, едното е причинило сериозни щети
    https://www.vesti.bg/sviat/dve-zemetreseniia-razliuliaha-syrbiia-ednoto-e-prichinilo-seriozni-shteti-6258762
  [2026-05-05T10:07:47.064850+00:00] Две земетресения разлюляха Сърбия
    https://www.vesti.bg/sviat/dve-zemetreseniia-razliuliaha-syrbiia-6258762

Published: 2026-05-05 18:09:00+00:00 | Title sim: 0.669 | Text sim: 0.974
  [2026-05-05T21:06:39.604489+00:00] Зеленски за Русия: Абсолютен цинизъм
    https://www.vesti.bg/sviat/zelenski-za-rusiia-absoliuten-cinizym-6258834
  [2026-05-05T19:26:01.952446+00:00] Зеленски за Русия: Аабсолютен цинизъм
    https://www.vesti.bg/sviat/zelenski-za-rusiia-aabsoliuten-cinizym-6258834

Published: 2026-05-07 05:41:00+00:00 | Title sim: 0.226 | Text sim: 0.783
  [2026-05-07T10:28:33.993542+00:00] Денят на истината за Близкия изток: Очаква се ключовият отговор на Иран към Тръмп
    https://www.vesti.bg/sviat/deniat-na-istinata-za-blizkiia-iztok-ochakva-se-kliuchoviiat-otgovor-na-iran-kym-trymp-6258885
  [2026-05-07T06:39:19.488613+00:00] Мир или „мащабни бомбардировки“: Тръмп даде последен шанс на Иран за споразумение
    https://www.vesti.bg/sviat/mir-ili-mashtabni-bombardirovki-trymp-dade-posleden-shans-na-iran-za-sporazumenie-6258885

Published: 2026-05-08 04:02:00+00:00 | Title sim: 0.095 | Text sim: 0.899
  [2026-05-08T09:26:33.519501+00:00] България има ново редовно правителство с премиер Румен Радев
    https://www.vesti.bg/bulgaria/bylgariia-ima-novo-redovno-pravitelstvo-s-premier-rumen-radev-6259013
  [2026-05-08T07:55:35.401981+00:00] НА ЖИВО: НС гласува състава и структурата на предложения от Румен Радев кабинет
    https://www.vesti.bg/bulgaria/na-zhivo-ns-glasuva-systava-i-strukturata-na-predlozheniia-ot-rumen-radev-kabinet-6259013
  [2026-05-08T06:00:58.989523+00:00] НС гласува състава и структурата на предложения от Румен Радев кабинет
    https://www.vesti.bg/bulgaria/ns-glasuva-systava-i-strukturata-na-predlozheniia-ot-rumen-radev-kabinet-6259013

Published: 2026-05-08 07:35:00+00:00 | Title sim: 0.603 | Text sim: 1.000
  [2026-05-08T09:26:33.519282+00:00] Еврото поскъпна спрямо долара
    https://www.vesti.bg/sviat/evroto-poskypna-spriamo-dolara-6259037
  [2026-05-08T07:55:35.401748+00:00] Еврото поскъпва спрямо долара
    https://www.vesti.bg/pari/evroto-poskypva-spriamo-dolara-6259037

Published: 2026-05-08 08:19:00+00:00 | Title sim: 0.474 | Text sim: 0.966
  [2026-05-08T11:20:36.485554+00:00] Простреляха жена в центъра на Варна, извършителят се издирва
    https://www.vesti.bg/bulgaria/prostreliaha-zhena-v-centyra-na-varna-izvyrshiteliat-se-izdirva-6259042
  [2026-05-08T09:26:33.519226+00:00] Жена е простреляна в центъра на Варна
    https://www.vesti.bg/bulgaria/zhena-e-prostreliana-v-centyra-na-varna-6259042

Published: 2026-05-08 12:49:00+00:00 | Title sim: 0.127 | Text sim: 1.000
  [2026-05-08T15:28:21.510906+00:00] Модният избор на Кралица Камила, който изненада всички
    https://www.vesti.bg/lyubopitno/modniiat-izbor-na-kralica-kamila-kojto-iznenada-vsichki-6259090
  [2026-05-08T13:56:45.422119+00:00] Кралица Камила току-що дебютира с изненадваща нова визия – нарушавайки традицията
    https://www.vesti.bg/lyubopitno/kralica-kamila-toku-shto-debiutira-s-iznenadvashta-nova-viziia-narushavajki-tradiciiata-6259090

Published: 2026-05-08 13:53:00+00:00 | Title sim: 1.000 | Text sim: 0.998
  [2026-05-08T15:28:21.510823+00:00] Война за милиони под носа на полицията: Как Къро и Анджело Димов се сблъскаха с най-опасната банда в Кейптаун
    https://www.vesti.bg/sviat/vojna-za-milioni-pod-nosa-na-policiiata-kak-kyro-i-andzhelo-dimov-se-sblyskaha-s-naj-opasnata-banda-v-kejptaun-6259084
  [2026-05-08T13:56:45.422021+00:00] Война за милиони под носа на полицията: Как Къро и Анджело Димов се сблъскаха с най-опасната банда в Кейптаун
    https://www.vesti.bg/bulgaria/vojna-za-milioni-pod-nosa-na-policiiata-kak-kyro-i-andzhelo-dimov-se-sblyskaha-s-naj-opasnata-banda-v-kejptaun-6259084

Published: 2026-05-09 14:41:00+00:00 | Title sim: 0.776 | Text sim: 1.000
  [2026-05-09T16:59:32.361444+00:00] Идентифицираха „нулевия пациент“ на хантавируса на круизния кораб
    https://www.vesti.bg/sviat/identificiraha-nuleviiapacient-na-hantavirusa-na-kruizniia-korab-6259146
  [2026-05-09T14:54:40.536056+00:00] Идентифицираха „нулевия пациент“ на хантавируса
    https://www.vesti.bg/sviat/identificiraha-nuleviiapacient-na-hantavirusa-6259146

Published: 2026-05-09 18:34:00+00:00 | Title sim: 0.752 | Text sim: 1.000
  [2026-05-09T20:49:18.240735+00:00] Кой е Виджай – актьорът, който навлезе в индийската политика
    https://www.vesti.bg/sviat/koj-e-vidzhaj-aktioryt-kojto-navleze-v-indijskata-politika-6259156
  [2026-05-09T19:07:07.268951+00:00] Кой е Виджай – актьорът, който разтърси индийската политика
    https://www.vesti.bg/sviat/koj-e-vidzhaj-aktioryt-kojto-raztyrsi-indijskata-politika-6259156

Published: 2026-05-10 05:22:00+00:00 | Title sim: 0.407 | Text sim: 0.772
  [2026-05-10T11:02:39.684475+00:00] Четирима задържани за нападението срещу автобус в Перник
    https://www.vesti.bg/bulgaria/chetirima-zadyrzhani-za-napadenieto-sreshtuavtobus-v-pernik-6259165
  [2026-05-10T06:36:12.224182+00:00] „Чу се силен гръм”: Очевидец разказа за нападението срещу автобус в Перник
    https://www.vesti.bg/bulgaria/chu-se-silen-grym-ochevidec-razkaza-za-napadenieto-sreshtu-avtobus-v-pernik-6259165

Published: 2026-05-10 10:45:00+00:00 | Title sim: 0.758 | Text sim: 1.000
  [2026-05-10T13:25:34.691511+00:00] Откриха телата на двама сингапурци, загинали след изригването на вулкана Дуконо
    https://www.vesti.bg/sviat/otkriha-telata-na-dvama-singapurci-zaginali-sled-izrigvaneto-na-vulkana-dukono-6259179
  [2026-05-10T11:02:39.684312+00:00] Откриха телата на двама сингапурски граждани, загинали след изригването на вулкана Дуконо в Индонезия
    https://www.vesti.bg/sviat/otkriha-telata-na-dvama-singapurski-grazhdani-zaginali-sled-izrigvaneto-na-vulkana-dukono-v-indoneziia-6259179

Published: 2026-05-11 11:12:00+00:00 | Title sim: 0.122 | Text sim: 1.000
  [2026-05-11T15:00:44.236318+00:00] Изолираха в болница в Атина грък, евакуиран от засегнатия от хантавирус круизен кораб
    https://www.vesti.bg/sviat/izoliraha-v-bolnica-v-atina-gryk-evakuiran-ot-zasegnatiia-ot-hantavirus-kruizen-korab-6259272
  [2026-05-11T11:27:23.734666+00:00] Случаят с хантавируса на круизния кораб стигна до Балканите: Поставиха евакуиран в Атина под 45-дневна карантина
    https://www.vesti.bg/sviat/sluchaiat-s-hantavirusa-na-kruizniia-korab-stigna-do-balkanite-postaviha-evakuiran-v-atina-pod-45-dnevna-karantina-6259272

Published: 2026-05-11 13:33:00+00:00 | Title sim: 0.135 | Text sim: 0.921
  [2026-05-11T17:57:45.033649+00:00] Партиите реагираха на предложенията на "Прогресивна България"
    https://www.vesti.bg/bulgaria/partiite-reagiraha-na-predlozheniiata-na-progresivna-bylgariia-6259295
  [2026-05-11T15:00:44.236140+00:00] ДПС към "Прогресивна България": Първа стъпка в правилната посока
    https://www.vesti.bg/bulgaria/dps-kym-progresivna-bylgariia-pyrva-stypka-v-pravilnata-posoka-6259295

Published: 2026-05-14 08:33:00+00:00 | Title sim: 0.304 | Text sim: 0.997
  [2026-05-14T14:22:59.896268+00:00] Съдът отхвърли искането на обвинения по делото „Сияна“
    https://www.vesti.bg/bulgaria/sydyt-othvyrli-iskaneto-na-obvineniia-po-deloto-siiana-6259587
  [2026-05-14T10:26:15.699696+00:00] Десето заседание за смъртта на Сияна: Обвиненият по делото поиска по-лека мярка
    https://www.vesti.bg/bulgaria/deseto-zasedanie-za-smyrtta-na-siiana-obvineniiat-po-deloto-poiska-po-leka-miarka-6259587

Published: 2026-05-14 10:31:00+00:00 | Title sim: 0.231 | Text sim: 0.998
  [2026-05-14T19:50:12.784410+00:00] Шофьорската книжка на Михаил Кашеров е била отнета за четири месеца
    https://www.vesti.bg/bulgaria/shofiorskata-knizhka-na-mihail-kasherov-e-bila-otneta-za-chetiri-meseca-6259615
  [2026-05-14T17:55:13.468774+00:00] Новият областен управител на Сливен отрече за отнета шофьорска книжка в Германия
    https://www.vesti.bg/bulgaria/noviiat-oblasten-upravitel-na-sliven-otreche-za-otneta-shofiorska-knizhka-v-germaniia-6259615
  [2026-05-14T14:22:59.896077+00:00] Изяснява се случай с новия областен управител на Сливен и отнета шофьорска книжка в Германия
    https://www.vesti.bg/bulgaria/iziasniava-se-sluchaj-s-noviia-oblasten-upravitel-na-sliven-i-otneta-shofiorska-knizhka-v-germaniia-6259615

Published: 2026-05-14 11:57:00+00:00 | Title sim: 0.758 | Text sim: 1.000
  [2026-05-14T19:50:12.784291+00:00] Разбиха схема за 240 млн. евро с хранителни добавки, представяни като лекарства
    https://www.vesti.bg/bulgaria/razbiha-shema-za-240-mln.-evro-s-hranitelni-dobavki-predstaviani-kato-lekarstva-6259628
  [2026-05-14T14:22:59.895971+00:00] Разбиха схема за хранителни добавки, представяни като лекарства
    https://www.vesti.bg/bulgaria/razbiha-shema-za-hranitelni-dobavki-predstaviani-kato-lekarstva-6259628

Published: 2026-05-14 19:06:00+00:00 | Title sim: 0.413 | Text sim: 1.000
  [2026-05-15T06:59:00.540593+00:00] Дара е първият финалист от втория полуфинал на „Евровизия“
    https://www.vesti.bg/lyubopitno/dara-e-pyrviiat-finalist-ot-vtoriia-polufinal-na-evroviziia-6259658
  [2026-05-14T22:59:36.440704+00:00] Дара се класира първа за финала на „Евровизия“ от втория полуфинал
    https://www.vesti.bg/lyubopitno/dara-se-klasira-pyrva-za-finala-na-evroviziia-ot-vtoriia-polufinal-6259658
  [2026-05-14T19:50:12.784090+00:00] Дара откри втория полуфинал на „Евровизия“ с „Бангаранга“
    https://www.vesti.bg/lyubopitno/dara-otkri-vtoriia-polufinal-na-evroviziia-s-bangaranga-6259658

Published: 2026-05-16 22:28:00+00:00 | Title sim: 0.119 | Text sim: 0.960
  [2026-05-17T03:40:35.879572+00:00] „О, Боже мой!“: Исторически триумф за DARA, България спечели „Евровизия“ 2026
    https://www.vesti.bg/bulgaria/o-bozhe-moj-istoricheski-triumf-za-dara-bylgariia-specheli-evroviziia-2026-6259817
  [2026-05-16T22:50:56.612857+00:00] Грандиозен финал във Виена: DARA е временният победител на „Евровизия“
    https://www.vesti.bg/bulgaria/grandiozen-final-vyv-viena-dara-e-vremenniiat-pobeditel-na-evroviziia-6259817

Published: 2026-05-17 04:27:00+00:00 | Title sim: 0.395 | Text sim: 0.859
  [2026-05-17T11:11:00.848023+00:00] "БлагоДара": Звезди и политици поздравиха DARA след победата на „Евровизия“
    https://www.vesti.bg/bulgaria/blagodara-zvezdi-i-politici-pozdraviha-dara-sled-pobedata-na-evroviziia-6259819
  [2026-05-17T06:48:35.232472+00:00] "БлагоДара": Вълна от звездни поздравления след триумфа на DARA на "Евровизия"
    https://www.vesti.bg/bulgaria/blagodara-vylna-ot-zvezdni-pozdravleniia-sled-triumfa-na-dara-na-evroviziia-6259819

Published: 2026-05-18 08:02:00+00:00 | Title sim: 0.089 | Text sim: 1.000
  [2026-05-18T13:52:02.470437+00:00] DARA: Няма магия - има по 9 часа работа на ден и никаква омраза
    https://www.vesti.bg/bulgaria/daraniama-magiia-ima-po-9-chasa-rabota-na-den-i-nikakva-omraza-6259896
  [2026-05-18T08:09:10.950206+00:00] Зад кулисите на триумфа: DARA разкри подробности за подготовката си за "Евровизия"
    https://www.vesti.bg/bulgaria/zad-kulisite-na-triumfa-dara-razkri-podrobnosti-za-podgotovkata-si-za-evroviziia-6259896

Published: 2026-05-19 10:42:00+00:00 | Title sim: 0.135 | Text sim: 0.737
  [2026-05-19T15:31:55.692451+00:00] Търсят българин и румънки след срутване на сграда в Германия
    https://www.vesti.bg/sviat/tyrsiat-bylgarin-i-rumynki-sled-srutvane-na-sgrada-v-germaniia-6260020
  [2026-05-19T11:23:39.165571+00:00] Сграда се срути в Германия, издирват трима души под отломките
    https://www.vesti.bg/sviat/sgrada-se-sruti-v-germaniia-izdirvat-trima-dushi-pod-otlomkite-6260020

Published: 2026-05-20 07:29:00+00:00 | Title sim: 0.242 | Text sim: 1.000
  [2026-05-20T10:54:46.156638+00:00] Парадокс: Най-скъпата скоростна влакова линия в света ще се окаже по-бавна и по-скъпа
    https://www.vesti.bg/sviat/paradoks-naj-skypata-skorostna-vlakova-liniia-v-sveta-shte-se-okazhe-po-bavna-i-po-skypa-6260092
  [2026-05-20T07:49:04.103962+00:00] Проект за милиарди се провали: Влаковете в Англия ще са по-бавни и по-скъпи
    https://www.vesti.bg/sviat/proekt-za-miliardi-se-provali-vlakovete-v-angliia-shte-sa-po-bavni-i-po-skypi-6260092

Published: 2026-05-21 07:41:00+00:00 | Title sim: 0.777 | Text sim: 1.000
  [2026-05-21T11:37:27.818528+00:00] Ванеса Тръмп обяви, че е диагностицирана с рак
    https://www.vesti.bg/sviat/vanesa-trymp-obiavi-che-e-diagnosticirana-s-rak-6260195
  [2026-05-21T08:02:08.565736+00:00] Ванеса Тръмп с лична изповед: Обяви, че е диагностицирана с рак
    https://www.vesti.bg/sviat/vanesa-trymp-s-lichna-izpoved-obiavi-che-e-diagnosticirana-s-rak-6260195

Published: 2026-05-22 03:47:00+00:00 | Title sim: 0.368 | Text sim: 0.800
  [2026-05-22T07:51:03.890376+00:00] Правната комисия обедини в един общ законопроект промените в НПК
    https://www.vesti.bg/bulgaria/pravnata-komisiia-obedini-v-edin-obsht-zakonoproekt-promenite-v-npk-6260267
  [2026-05-22T03:55:11.043591+00:00] Правната комисия с извънредно заседание заради промените в НПК
    https://www.vesti.bg/bulgaria/pravnata-komisiia-s-izvynredno-zasedanie-zaradi-promenite-v-npk-6260267

Published: 2026-05-22 04:04:00+00:00 | Title sim: 0.927 | Text sim: 0.698
  [2026-05-22T10:56:12.072396+00:00] На първо четене: НС отново създаде Комисия за противодействие на корупцията
    https://www.vesti.bg/bulgaria/na-pyrvo-chetene-ns-otnovo-syzdade-komisiia-za-protivodejstvie-na-korupciiata-6260270
  [2026-05-22T07:51:03.890350+00:00] На първо четене: НС създаде Комисия за противодействие на корупцията
    https://www.vesti.bg/bulgaria/na-pyrvo-chetene-ns-syzdade-komisiia-za-protivodejstvie-na-korupciiata-6260270

Published: 2026-05-22 05:56:00+00:00 | Title sim: 0.319 | Text sim: 0.757
  [2026-05-22T10:56:12.072342+00:00] Българската делегация в Рим подари ръчно тъкан чипровски килим на папа Лъв XIV
    https://www.vesti.bg/sviat/bylgarskata-delegaciia-v-rim-podari-rychno-tykan-chiprovski-kilim-na-papa-lyv-xiv-6260276
  [2026-05-22T07:51:03.890296+00:00] Папа Лъв XIV приема във Ватикана българската делегация, водена от председателя на НС
    https://www.vesti.bg/sviat/papa-lyv-xiv-priema-vyv-vatikana-bylgarskata-delegaciia-vodena-ot-predsedatelia-na-ns-6260276

Published: 2026-05-22 19:58:00+00:00 | Title sim: 0.820 | Text sim: 1.000
  [2026-05-23T09:57:40.165532+00:00] Бивол, кръстен на Тръмп, ще бъде пожертван за Курбан байрам
    https://www.vesti.bg/sviat/bivol-krysten-na-trymp-shte-byde-pozhertvan-za-kurban-bajram-6260360
  [2026-05-22T21:14:17.700075+00:00] Бивол, кръстен на Тръмп, ще бъде пожертван за Курбайн байрам
    https://www.vesti.bg/sviat/bivol-krysten-na-trymp-shte-byde-pozhertvan-za-kurbajn-bajram-6260360

Published: 2026-05-28 17:20:00+00:00 | Title sim: 0.752 | Text sim: 1.000
  [2026-05-28T20:28:36.616962+00:00] Москва с остра критика към правителството на Радев
    https://www.vesti.bg/sviat/moskva-s-ostra-kritika-kym-pravitelstvoto-na-radev-6260833
  [2026-05-28T17:37:13.044793+00:00] Русия с остра критика към правителството на Радев
    https://www.vesti.bg/sviat/rusiia-s-ostra-kritika-kym-pravitelstvoto-na-radev-6260833

Published: 2026-05-29 07:38:00+00:00 | Title sim: 0.353 | Text sim: 1.000
  [2026-05-29T13:13:29.937114+00:00] Скандал във Варна: Украинска гимнастичка запуши ушите си със слушалки, докато звучеше руският химн
    https://www.vesti.bg/bulgaria/skandal-vyv-varna-ukrainska-gimnastichka-zapushi-ushite-si-sys-slushalki-dokato-zvucheshe-ruskiiat-himn-6260874
  [2026-05-29T08:02:32.309136+00:00] Със слушалки и покрити очи: Украинска гимнастичка отказа да чуе руския химн във Варна
    https://www.vesti.bg/bulgaria/sys-slushalki-i-pokriti-ochi-ukrainska-gimnastichka-otkaza-da-chue-ruskiia-himn-vyv-varna-6260874

Published: 2026-06-01 14:12:00+00:00 | Title sim: 0.747 | Text sim: 0.615
  [2026-06-01T21:37:17.195162+00:00] Иран прекратява преговорите със САЩ, Тръмп отрича
    https://www.vesti.bg/sviat/iran-prekratiava-pregovorite-sys-sasht-trymp-otricha-6261143
  [2026-06-01T17:46:55.523126+00:00] Иран прекратява преговорите със САЩ
    https://www.vesti.bg/sviat/iran-prekratiava-pregovorite-sys-sasht-6261143

Published: 2026-06-01 17:17:00+00:00 | Title sim: 0.709 | Text sim: 0.965
  [2026-06-01T21:37:17.195050+00:00] КОНПИ обвини СГС в нарушение, съдът опроверга
    https://www.vesti.bg/bulgaria/konpi-obvini-sgs-v-narushenie-sydyt-oproverga-6261155
  [2026-06-01T17:46:55.522985+00:00] КОНПИ обвини СГС в нарушение
    https://www.vesti.bg/bulgaria/konpi-obvini-sgs-v-narushenie-6261155

Published: 2026-06-02 10:11:00+00:00 | Title sim: 0.252 | Text sim: 1.000
  [2026-06-02T16:39:25.390242+00:00] Прокурорският син се е сбил отново в затвора, искат по-тежък режим
    https://www.vesti.bg/bulgaria/prokurorskiiat-sin-se-e-sbil-otnovo-v-zatvora-iskat-po-tezhyk-rezhim-6261222
  [2026-06-02T10:30:17.074491+00:00] Васил Михайлов с ново нарушение зад решетките, искат по-тежък режим
    https://www.vesti.bg/bulgaria/vasil-mihajlov-s-novo-narushenie-zad-reshetkite-iskat-po-tezhyk-rezhim-6261222

Published: 2026-06-03 07:35:00+00:00 | Title sim: 0.054 | Text sim: 0.721
  [2026-06-03T11:06:32.891061+00:00] Гаранции за произход и емисионен фактор: как бизнесът доказва по-устойчив избор
    https://www.vesti.bg/energia_na_badeshteto/garancii-za-proizhod-i-emisionen-faktor-kak-biznesyt-dokazva-po-ustojchiv-izbor-6261123
  [2026-06-03T11:06:32.891051+00:00] Какво означава зелен ток за един бизнес на практика
    https://www.vesti.bg/energia_na_badeshteto/kakvo-oznachava-zelen-tok-za-edin-biznes-na-praktika-6261122

Published: 2026-06-04 15:42:00+00:00 | Title sim: 0.000 | Text sim: 0.810
  [2026-06-04T20:09:45.295952+00:00] Наводнения в Североизточна България, изпускат язовир
    https://www.vesti.bg/bulgaria/navodneniia-v-severoiztochna-bylgariia-izpuskat-iazovir-6261547
  [2026-06-04T16:57:30.561200+00:00] BG-Alert се задейства заради риск от наводнение в Котел
    https://www.vesti.bg/bulgaria/bg-alert-se-zadejstva-zaradi-risk-ot-navodnenie-v-kotel-6261547

Published: 2026-06-05 08:01:00+00:00 | Title sim: 0.217 | Text sim: 1.000
  [2026-06-05T12:43:02.103685+00:00] Жена загина в пожар в дома си в Благоевград, друга е ранена
    https://www.vesti.bg/bulgaria/zhena-zagina-v-pozhar-v-doma-si-v-blagoevgrad-druga-e-ranena-6261584
  [2026-06-05T08:15:52.014132+00:00] Пожар в апартамент в Благоевград отне живота на 67-годишна жена
    https://www.vesti.bg/bulgaria/pozhar-v-apartament-v-blagoevgrad-otne-zhivota-na-67-godishna-zhena-6261584

Published: 2026-06-05 10:01:00+00:00 | Title sim: 0.092 | Text sim: 1.000
  [2026-06-05T16:32:25.929435+00:00] ЕК иска България да махне плоския данък
    https://www.vesti.bg/bulgaria/ek-iska-bylgariia-da-mahne-ploskiia-danyk-6261600
  [2026-06-05T12:43:02.103508+00:00] ЕК с тревога за бюджета на България: Започва процедура за прекомерен дефицит и нови изисквания за реформи
    https://www.vesti.bg/bulgaria/ek-s-trevoga-za-biudzheta-na-bylgariia-zapochva-procedura-za-prekomeren-deficit-i-novi-iziskvaniia-za-reformi-6261600

Published: 2026-06-05 10:48:00+00:00 | Title sim: 0.119 | Text sim: 0.924
  [2026-06-05T19:59:25.509285+00:00] Милошев с остри обвинения за НДК, Татарова отговори
    https://www.vesti.bg/bulgaria/miloshev-s-ostri-obvineniia-za-ndk-tatarova-otgovori-6261602

In [190]:
inspect_source_duplicate_similarity(df, "nova", threshold=0.7)

Published: 2026-04-23 05:00:25+00:00 | Title sim: 0.802 | Text sim: 0.992
  [2026-04-23T09:47:56.601934+00:00] Високи температури, следвани от бури с градушки, през следващите дни
    https://nova.bg/news/view/2026/04/23/534810/%D0%B2%D0%B8%D1%81%D0%BE%D0%BA%D0%B8-%D1%82%D0%B5%D0%BC%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B8-%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D0%BD%D0%B8-%D0%BE%D1%82-%D0%B1%D1%83%D1%80%D0%B8-%D1%81-%D0%B3%D1%80%D0%B0%D0%B4%D1%83%D1%88%D0%BA%D0%B8-%D0%BF%D1%80%D0%B5%D0%B7-%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D1%89%D0%B8%D1%82%D0%B5-%D0%B4%D0%BD%D0%B8/
  [2026-04-23T06:08:26.648955+00:00] Летни температури, следвани от бури с градушки, през следващите дни
    https://nova.bg/news/view/2026/04/23/534810/%D0%BB%D0%B5%D1%82%D0%BD%D0%B8-%D1%82%D0%B5%D0%BC%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B8-%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D0%BD%D0%B8-%D0%BE%D1%82-%D0%B1%D1%83%D1%80%D0%B8-%D1%81-%D0%B3%D1%80%D0%B0%D0%B4%D1%83%D1%88%D0%BA%D0%B8-%D0%BF%D1%80%D0%B5%D0%B7-%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D1%89%D0%B8%D1%82%D0%B5-%D0%B4%D0%BD%D0%B8/

Published: 2026-04-23 06:50:22+00:00 | Title sim: 0.747 | Text sim: 0.694
  [2026-04-23T17:25:37.181158+00:00] Челен сблъсък между влакове в Дания
    https://nova.bg/news/view/2026/04/23/534823/%D1%87%D0%B5%D0%BB%D0%B5%D0%BD-%D1%81%D0%B1%D0%BB%D1%8A%D1%81%D1%8A%D0%BA-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%B2%D0%BB%D0%B0%D0%BA%D0%BE%D0%B2%D0%B5-%D0%B2-%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D1%81%D0%BD%D0%B8%D0%BC%D0%BA%D0%B8/
  [2026-04-23T09:47:56.601838+00:00] Челен сблъсък между влакове в Дания, има пострадали
    https://nova.bg/news/view/2026/04/23/534823/%D1%87%D0%B5%D0%BB%D0%B5%D0%BD-%D1%81%D0%B1%D0%BB%D1%8A%D1%81%D1%8A%D0%BA-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%B2%D0%BB%D0%B0%D0%BA%D0%BE%D0%B2%D0%B5-%D0%B2-%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8%D0%BC%D0%B0-%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%B4%D0%B0%D0%BB%D0%B8-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D1%81%D0%BD%D0%B8%D0%BC%D0%BA%D0%B8/

Published: 2026-04-23 07:53:00+00:00 | Title sim: 0.896 | Text sim: 0.648
  [2026-04-23T11:13:08.231931+00:00] Русия нанесе удари в Запорожка, Житомирска област и Днипро, има загинали
    https://nova.bg/news/view/2026/04/23/534831/%D1%80%D1%83%D1%81%D0%B8%D1%8F-%D0%BD%D0%B0%D0%BD%D0%B5%D1%81%D0%B5-%D1%83%D0%B4%D0%B0%D1%80%D0%B8-%D0%B2-%D0%B7%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D0%BA%D0%B0-%D0%B6%D0%B8%D1%82%D0%BE%D0%BC%D0%B8%D1%80%D1%81%D0%BA%D0%B0-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82-%D0%B8-%D0%B4%D0%BD%D0%B8%D0%BF%D1%80%D0%BE-%D0%B8%D0%BC%D0%B0-%D0%B7%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D0%B8/
  [2026-04-23T09:47:56.601794+00:00] Русия нанесе удари в Запорожка и Житомирска област, има загинали
    https://nova.bg/news/view/2026/04/23/534831/%D1%80%D1%83%D1%81%D0%B8%D1%8F-%D0%BD%D0%B0%D0%BD%D0%B5%D1%81%D0%B5-%D1%83%D0%B4%D0%B0%D1%80%D0%B8-%D0%B2-%D0%B7%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D0%BA%D0%B0-%D0%B8-%D0%B6%D0%B8%D1%82%D0%BE%D0%BC%D0%B8%D1%80%D1%81%D0%BA%D0%B0-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82-%D0%B8%D0%BC%D0%B0-%D0%B7%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0%D0%BB%D0%B8/

Published: 2026-04-24 03:34:01+00:00 | Title sim: 0.868 | Text sim: 0.656
  [2026-04-24T09:47:58.553622+00:00] След героичната му постъпка: Наградиха полицая, спасил хора от автобуса край ГКПП „Малко Търново”
    https://nova.bg/news/view/2026/04/24/534918/%D1%81%D0%BB%D0%B5%D0%B4-%D0%B3%D0%B5%D1%80%D0%BE%D0%B8%D1%87%D0%BD%D0%B0%D1%82%D0%B0-%D0%BC%D1%83-%D0%BF%D0%BE%D1%81%D1%82%D1%8A%D0%BF%D0%BA%D0%B0-%D0%BD%D0%B0%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D1%85%D0%B0-%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B0%D1%8F-%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%BB-%D1%85%D0%BE%D1%80%D0%B0-%D0%BE%D1%82-%D0%B0%D0%B2%D1%82%D0%BE%D0%B1%D1%83%D1%81%D0%B0-%D0%BA%D1%80%D0%B0%D0%B9-%D0%B3%D0%BA%D0%BF%D0%BF-%D0%BC%D0%B0%D0%BB%D0%BA%D0%BE-%D1%82%D1%8A%D1%80%D0%BD%D0%BE%D0%B2%D0%BE/
  [2026-04-24T06:10:38.808892+00:00] След героичната му постъпка: Награждават полицая, спасил хора от автобуса край ГКПП „Малко Търново”
    https://nova.bg/news/view/2026/04/24/534918/%D1%81%D0%BB%D0%B5%D0%B4-%D0%B3%D0%B5%D1%80%D0%BE%D0%B8%D1%87%D0%BD%D0%B0%D1%82%D0%B0-%D0%BC%D1%83-%D0%BF%D0%BE%D1%81%D1%82%D1%8A%D0%BF%D0%BA%D0%B0-%D0%BD%D0%B0%D0%B3%D1%80%D0%B0%D0%B6%D0%B4%D0%B0%D0%B2%D0%B0%D1%82-%D0%BF%D0%BE%D0%BB%D0%B8%D1%86%D0%B0%D1%8F-%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%BB-%D1%85%D0%BE%D1%80%D0%B0-%D0%BE%D1%82-%D0%B0%D0%B2%D1%82%D0%BE%D0%B1%D1%83%D1%81%D0%B0-%D0%BA%D1%80%D0%B0%D0%B9-%D0%B3%D0%BA%D0%BF%D0%BF-%D0%BC%D0%B0%D0%BB%D0%BA%D0%BE-%D1%82%D1%8A%D1%80%D0%BD%D0%BE%D0%B2%D0%BE/

Published: 2026-04-24 08:22:42+00:00 | Title sim: 0.758 | Text sim: 0.919
  [2026-04-24T13:42:06.359305+00:00] Първи случаи на морбили във Варна, нови - в София, Плевен, Враца и Ловеч
    https://nova.bg/news/view/2026/04/24/534967/%D0%BF%D1%8A%D1%80%D0%B2%D0%B8-%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B8-%D0%BD%D0%B0-%D0%BC%D0%BE%D1%80%D0%B1%D0%B8%D0%BB%D0%B8-%D0%B2%D1%8A%D0%B2-%D0%B2%D0%B0%D1%80%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D0%B8-%D0%B2-%D1%81%D0%BE%D1%84%D0%B8%D1%8F-%D0%BF%D0%BB%D0%B5%D0%B2%D0%B5%D0%BD-%D0%B2%D1%80%D0%B0%D1%86%D0%B0-%D0%B8-%D0%BB%D0%BE%D0%B2%D0%B5%D1%87/
  [2026-04-24T09:47:58.553291+00:00] Нови случаи на морбили в София, Плевен, Враца и Ловеч
    https://nova.bg/news/view/2026/04/24/534967/%D0%BD%D0%BE%D0%B2%D0%B8-%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B8-%D0%BD%D0%B0-%D0%BC%D0%BE%D1%80%D0%B1%D0%B8%D0%BB%D0%B8-%D0%B2-%D1%81%D0%BE%D1%84%D0%B8%D1%8F-%D0%BF%D0%BB%D0%B5%D0%B2%D0%B5%D0%BD-%D0%B2%D1%80%D0%B0%D1%86%D0%B0-%D0%B8-%D0%BB%D0%BE%D0%B2%D0%B5%D1%87/

Published: 2026-04-24 13:01:23+00:00 | Title sim: 0.191 | Text sim: 0.841
  [2026-04-24T15:11:12.590520+00:00] Историческа победа: Карлос Насар спечели четвърта европейска титла
    https://nova.bg/news/view/2026/04/24/535001/%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0-%D0%BF%D0%BE%D0%B1%D0%B5%D0%B4%D0%B0-%D0%BA%D0%B0%D1%80%D0%BB%D0%BE%D1%81-%D0%BD%D0%B0%D1%81%D0%B0%D1%80-%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BB%D0%B8-%D1%87%D0%B5%D1%82%D0%B2%D1%8A%D1%80%D1%82%D0%B0-%D0%B5%D0%B2%D1%80%D0%BE%D0%BF%D0%B5%D0%B9%D1%81%D0%BA%D0%B0-%D1%82%D0%B8%D1%82%D0%BB%D0%B0/
  [2026-04-24T13:42:06.359130+00:00] Карлос Насар - с европейско злато в изхвърлянето
    https://nova.bg/news/view/2026/04/24/535001/%D0%BA%D0%B0%D1%80%D0%BB%D0%BE%D1%81-%D0%BD%D0%B0%D1%81%D0%B0%D1%80-%D1%81-%D0%B5%D0%B2%D1%80%D0%BE%D0%BF%D0%B5%D0%B9%D1%81%D0%BA%D0%BE-%D0%B7%D0%BB%D0%B0%D1%82%D0%BE-%D0%B2-%D0%B8%D0%B7%D1%85%D0%B2%D1%8A%D1%80%D0%BB%D1%8F%D0%BD%D0%B5%D1%82%D0%BE/

Published: 2026-04-24 13:56:13+00:00 | Title sim: 0.183 | Text sim: 0.990
  [2026-04-24T17:01:25.393224+00:00] Последно пренареждане: Водачите на листи обявиха от кой район ще бъдат депутати
    https://nova.bg/news/view/2026/04/24/535016/%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%BE-%D0%BF%D1%80%D0%B5%D0%BD%D0%B0%D1%80%D0%B5%D0%B6%D0%B4%D0%B0%D0%BD%D0%B5-%D0%B2%D0%BE%D0%B4%D0%B0%D1%87%D0%B8%D1%82%D0%B5-%D0%BD%D0%B0-%D0%BB%D0%B8%D1%81%D1%82%D0%B8-%D0%BE%D0%B1%D1%8F%D0%B2%D0%B8%D1%85%D0%B0-%D0%BE%D1%82-%D0%BA%D0%BE%D0%B9-%D1%80%D0%B0%D0%B9%D0%BE%D0%BD-%D1%89%D0%B5-%D0%B1%D1%8A%D0%B4%D0%B0%D1%82-%D0%B4%D0%B5%D0%BF%D1%83%D1%82%D0%B0%D1%82%D0%B8/
  [2026-04-24T15:11:12.590446+00:00] Обявиха от кои МИР новите депутати влизат в парламента
    https://nova.bg/news/view/2026/04/24/535016/%D0%BE%D0%B1%D1%8F%D0%B2%D0%B8%D1%85%D0%B0-%D0%BE%D1%82-%D0%BA%D0%BE%D0%B8-%D0%BC%D0%B8%D1%80-%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D0%B5-%D0%B4%D0%B5%D0%BF%D1%83%D1%82%D0%B0%D1%82%D0%B8-%D0%B2%D0%BB%D0%B8%D0%B7%D0%B0%D1%82-%D0%B2-%D0%BF%D0%B0%D1%80%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%D0%B0/

Published: 2026-04-24 15:53:10+00:00 | Title sim: 1.000 | Text sim: 0.698
  [2026-04-24T20:53:31.588314+00:00] Дете е в кома след падане от тераса на НДК
    https://nova.bg/news/view/2026/04/24/535027/%D0%B4%D0%B5%D1%82%D0%B5-%D0%B5-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%B0-%D1%81%D0%BB%D0%B5%D0%B4-%D0%BF%D0%B0%D0%B4%D0%B0%D0%BD%D0%B5-%D0%BE%D1%82-%D1%82%D0%B5%D1%80%D0%B0%D1%81%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%B4%D0%BA-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D1%81%D0%BD%D0%B8%D0%BC%D0%BA%D0%B8/
  [2026-04-24T17:01:25.393165+00:00] Дете е в кома след падане от тераса на НДК
    https://nova.bg/news/view/2026/04/24/535027/%D0%B4%D0%B5%D1%82%D0%B5-%D0%B5-%D0%B2-%D0%BA%D0%BE%D0%BC%D0%B0-%D1%81%D0%BB%D0%B5%D0%B4-%D0%BF%D0%B0%D0%B4%D0%B0%D0%BD%D0%B5-%D0%BE%D1%82-%D1%82%D0%B5%D1%80%D0%B0%D1%81%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%B4%D0%BA-%D1%81%D0%BD%D0%B8%D0%BC%D0%BA%D0%B8/

Published: 2026-04-25 09:14:56+00:00 | Title sim: 0.298 | Text sim: 0.897
  [2026-04-25T13:10:39.643276+00:00] Почти единодушно: БСП гласува вот на доверие на Крум Зарков
    https://nova.bg/news/view/2026/04/25/535077/%D0%BF%D0%BE%D1%87%D1%82%D0%B8-%D0%B5%D0%B4%D0%B8%D0%BD%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D0%BE-%D0%B1%D1%81%D0%BF-%D0%B3%D0%BB%D0%B0%D1%81%D1%83%D0%B2%D0%B0-%D0%B2%D0%BE%D1%82-%D0%BD%D0%B0-%D0%B4%D0%BE%D0%B2%D0%B5%D1%80%D0%B8%D0%B5-%D0%BD%D0%B0-%D0%BA%D1%80%D1%83%D0%BC-%D0%B7%D0%B0%D1%80%D0%BA%D0%BE%D0%B2/
  [2026-04-25T10:48:23.842356+00:00] Спешен пленум на БСП: Ще поискат ли оставката на Крум Зарков, след като не успяха да влязат в НС
    https://nova.bg/news/view/2026/04/25/535077/%D1%81%D0%BF%D0%B5%D1%88%D0%B5%D0%BD-%D0%BF%D0%BB%D0%B5%D0%BD%D1%83%D0%BC-%D0%BD%D0%B0-%D0%B1%D1%81%D0%BF-%D1%89%D0%B5-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%D1%82-%D0%BB%D0%B8-%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D0%BA%D1%80%D1%83%D0%BC-%D0%B7%D0%B0%D1%80%D0%BA%D0%BE%D0%B2-%D1%81%D0%BB%D0%B5%D0%B4-%D0%BA%D0%B0%D1%82%D0%BE-%D0%BD%D0%B5-%D1%83%D1%81%D0%BF%D1%8F%D1%85%D0%B0-%D0%B4%D0%B0-%D0%B2%D0%BB%D1%8F%D0%B7%D0%B0%D1%82-%D0%B2-%D0%BD%D1%81/

Published: 2026-04-25 11:36:40+00:00 | Title sim: 0.788 | Text sim: 1.000
  [2026-04-25T14:44:21.179285+00:00] Агенция „Митници“ предупреди за измама с таксата за Дунав мост: Кои са официалните канали за плащане
    https://nova.bg/news/view/2026/04/25/535090/%D0%B0%D0%B3%D0%B5%D0%BD%D1%86%D0%B8%D1%8F-%D0%BC%D0%B8%D1%82%D0%BD%D0%B8%D1%86%D0%B8-%D0%BF%D1%80%D0%B5%D0%B4%D1%83%D0%BF%D1%80%D0%B5%D0%B4%D0%B8-%D0%B7%D0%B0-%D0%B8%D0%B7%D0%BC%D0%B0%D0%BC%D0%B0-%D1%81-%D1%82%D0%B0%D0%BA%D1%81%D0%B0%D1%82%D0%B0-%D0%B7%D0%B0-%D0%B4%D1%83%D0%BD%D0%B0%D0%B2-%D0%BC%D0%BE%D1%81%D1%82-%D0%BA%D0%BE%D0%B8-%D1%81%D0%B0-%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%BD%D0%B8%D1%82%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8-%D0%B7%D0%B0-%D0%BF%D0%BB%D0%B0%D1%89%D0%B0%D0%BD%D0%B5/
  [2026-04-25T13:10:39.643181+00:00] Агенция „Митници“ предупреди за измама с таксата за Дунав мост: Кои са единствените официални канали
    https://nova.bg/news/view/2026/04/25/535090/%D0%B0%D0%B3%D0%B5%D0%BD%D1%86%D0%B8%D1%8F-%D0%BC%D0%B8%D1%82%D0%BD%D0%B8%D1%86%D0%B8-%D0%BF%D1%80%D0%B5%D0%B4%D1%83%D0%BF%D1%80%D0%B5%D0%B4%D0%B8-%D0%B7%D0%B0-%D0%B8%D0%B7%D0%BC%D0%B0%D0%BC%D0%B0-%D1%81-%D1%82%D0%B0%D0%BA%D1%81%D0%B0%D1%82%D0%B0-%D0%B7%D0%B0-%D0%B4%D1%83%D0%BD%D0%B0%D0%B2-%D0%BC%D0%BE%D1%81%D1%82-%D0%BA%D0%BE%D0%B8-%D1%81%D0%B0-%D0%B5%D0%B4%D0%B8%D0%BD%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%B8%D1%82%D0%B5-%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%BD%D0%B8-%D0%BA%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8/

Published: 2026-04-26 04:53:00+00:00 | Title sim: 0.193 | Text sim: 0.975
  [2026-04-26T09:04:55.874462+00:00] Христофор Караджов: Възможно е мишена на стрелеца във Вашингтон да е бил журналист, а не Тръмп
    https://nova.bg/news/view/2026/04/26/535141/%D1%85%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%84%D0%BE%D1%80-%D0%BA%D0%B0%D1%80%D0%B0%D0%B4%D0%B6%D0%BE%D0%B2-%D0%B2%D1%8A%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE-%D0%B5-%D0%BC%D0%B8%D1%88%D0%B5%D0%BD%D0%B0-%D0%BD%D0%B0-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%B5%D1%86%D0%B0-%D0%B2%D1%8A%D0%B2-%D0%B2%D0%B0%D1%88%D0%B8%D0%BD%D0%B3%D1%82%D0%BE%D0%BD-%D0%B4%D0%B0-%D0%B5-%D0%B1%D0%B8%D0%BB-%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%B8%D1%81%D1%82-%D0%B0-%D0%BD%D0%B5-%D1%82%D1%80%D1%8A%D0%BC%D0%BF/
  [2026-04-26T06:08:43.992996+00:00] Христофор Караджов: Медийни проучвания сочат, че нападателят във Вашингтон е работил като учител
    https://nova.bg/news/view/2026/04/26/535141/%D1%85%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%84%D0%BE%D1%80-%D0%BA%D0%B0%D1%80%D0%B0%D0%B4%D0%B6%D0%BE%D0%B2-%D0%BC%D0%B5%D0%B4%D0%B8%D0%B9%D0%BD%D0%B8-%D0%BF%D1%80%D0%BE%D1%83%D1%87%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D1%87%D0%B0%D1%82-%D1%87%D0%B5-%D0%BD%D0%B0%D0%BF%D0%B0%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D1%8F%D1%82-%D0%B2%D1%8A%D0%B2-%D0%B2%D0%B0%D1%88%D0%B8%D0%BD%D0%B3%D1%82%D0%BE%D0%BD-%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B8%D0%BB-%D0%BA%D0%B0%D1%82%D0%BE-%D1%83%D1%87%D0%B8%D1%82%D0%B5%D0%BB/

Published: 2026-04-26 07:10:19+00:00 | Title sim: 0.820 | Text sim: 0.968
  [2026-04-26T16:49:25.492162+00:00] Детето, паднало от тераса на НДК, остава в много тежко състояние
    https://nova.bg/news/view/2026/04/26/535147/%D0%B4%D0%B5%D1%82%D0%B5%D1%82%D0%BE-%D0%BF%D0%B0%D0%B4%D0%BD%D0%B0%D0%BB%D0%BE-%D0%BE%D1%82-%D1%82%D0%B5%D1%80%D0%B0%D1%81%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%B4%D0%BA-%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B0-%D0%B2-%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D1%82%D0%B5%D0%B6%D0%BA%D0%BE-%D1%81%D1%8A%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5/
  [2026-04-26T09:04:55.874365+00:00] Детето, паднало от тераса на НДК, остава в изключително тежко състояние
    https://nova.bg/news/view/2026/04/26/535147/%D0%B4%D0%B5%D1%82%D0%B5%D1%82%D0%BE-%D0%BF%D0%B0%D0%B4%D0%BD%D0%B0%D0%BB%D0%BE-%D0%BE%D1%82-%D1%82%D0%B5%D1%80%D0%B0%D1%81%D0%B0-%D0%BD%D0%B0-%D0%BD%D0%B4%D0%BA-%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B0-%D0%B2-%D0%B8%D0%B7%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D0%B5%D0%BB%D0%BD%D0%BE-%D1%82%D0%B5%D0%B6%D0%BA%D0%BE-%D1%81%D1%8A%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5/

Published: 2026-04-26 08:53:00+00:00 | Title sim: 0.000 | Text sim: 0.991
  [2026-04-26T10:49:27.248805+00:00] Служебният кабинет подготви и внесе в парламента пакет от законодателни мерки
    https://nova.bg/news/view/2026/04/26/535156/%D1%81%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B8%D1%8F%D1%82-%D0%BA%D0%B0%D0%B1%D0%B8%D0%BD%D0%B5%D1%82-%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%B2%D0%B8-%D0%B8-%D0%B2%D0%BD%D0%B5%D1%81%D0%B5-%D0%B2-%D0%BF%D0%B0%D1%80%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82%D0%B0-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82-%D0%BE%D1%82-%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%D0%BE%D0%B4%D0%B0%D1%82%D0%B5%D0%BB%D0%BD%D0%B8-%D0%BC%D0%B5%D1%80%D0%BA%D0%B8/
  [2026-04-26T09:04:55.874297+00:00] Андрей Гюров: Оставяме пример как държавата може да работи прозрачно и отговорно
    https://nova.bg/news/view/2026/04/26/535156/%D0%B0%D0%BD%D0%B4%D1%80%D0%B5%D0%B9-%D0%B3%D1%8E%D1%80%D0%BE%D0%B2-%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D1%8F%D0%BC%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%BA%D0%B0%D0%BA-%D0%B4%D1%8A%D1%80%D0%B6%D0%B0%D0%B2%D0%B0%D1%82%D0%B0-%D0%BC%D0%BE%D0%B6%D0%B5-%D0%B4%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B8-%D0%BF%D1%80%D0%BE%D0%B7%D1%80%D0%B0%D1%87%D0%BD%D0%BE-%D0%B8-%D0%BE%D1%82%D0%B3%D0%BE%D0%B2%D0%BE%D1%80%D0%BD%D0%BE/

Published: 2026-04-26 09:42:16+00:00 | Title sim: 0.133 | Text sim: 0.932
  [2026-04-26T18:59:23.793158+00:00] „Продължаваме Промяната" потвърди решението за обща кандидатура за президент
    https://nova.bg/news/view/2026/04/26/535166/%D0%BF%D1%80%D0%BE%D0%B4%D1%8A%D0%BB%D0%B6%D0%B0%D0%B2%D0%B0%D0%BC%D0%B5-%D0%BF%D1%80%D0%BE%D0%BC%D1%8F%D0%BD%D0%B0%D1%82%D0%B0-%D0%BF%D0%BE%D1%82%D0%B2%D1%8A%D1%80%D0%B4%D0%B8-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%BE-%D0%B7%D0%B0-%D0%BE%D0%B1%D1%89%D0%B0-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D1%83%D1%80%D0%B0-%D0%B7%D0%B0-%D0%BF%D1%80%D0%B5%D0%B7%D0%B8%D0%B4%D0%B5%D0%BD%D1%82/
  [2026-04-26T16:49:25.492045+00:00] „Продължаваме Промяната" свика Национален съвет
    https://nova.bg/news/view/2026/04/26/535166/%D0%BF%D1%80%D0%BE%D0%B4%D1%8A%D0%BB%D0%B6%D0%B0%D0%B2%D0%B0%D0%BC%D0%B5-%D0%BF%D1%80%D0%BE%D0%BC%D1%8F%D0%BD%D0%B0%D1%82%D0%B0-%D1%81%D0%B2%D0%B8%D0%BA%D0%B0-%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D0%B5%D0%BD-%D1%81%D1%8A%D0%B2%D0%B5%D1%82/
  [2026-04-26T10:49:27.248768+00:00] „Продължаваме Промяната" свиква Национален съвет
    https://nova.bg/news/view/2026/04/26/535166/%D0%BF%D1%80%D0%BE%D0%B4%D1%8A%D0%BB%D0%B6%D0%B0%D0%B2%D0%B0%D0%BC%D0%B5-%D0%BF%D1%80%D0%BE%D0%BC%D1%8F%D0%BD%D0%B0%D1%82%D0%B0-%D1%81%D0%B2%D0%B8%D0%BA%D0%B2%D0%B0-%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D0%B5%D0%BD-%D1%81%D1%8A%D0%B2%D0%B5%D1%82/

Published: 2026-04-26 09:55:27+00:00 | Title sim: 0.559 | Text sim: 0.942
  [2026-04-26T13:12:42.871368+00:00] Световни лидери осъдиха стрелбата на събитие на Тръмп и изказаха подкрепа за него
    https://nova.bg/news/view/2026/04/26/535167/%D1%81%D0%B2%D0%B5%D1%82%D0%BE%D0%B2%D0%BD%D0%B8-%D0%BB%D0%B8%D0%B4%D0%B5%D1%80%D0%B8-%D0%BE%D1%81%D1%8A%D0%B4%D0%B8%D1%85%D0%B0-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%B1%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D1%81%D1%8A%D0%B1%D0%B8%D1%82%D0%B8%D0%B5-%D0%BD%D0%B0-%D1%82%D1%80%D1%8A%D0%BC%D0%BF-%D0%B8-%D0%B8%D0%B7%D0%BA%D0%B0%D0%B7%D0%B0%D1%85%D0%B0-%D0%BF%D0%BE%D0%B4%D0%BA%D1%80%D0%B5%D0%BF%D0%B0-%D0%B7%D0%B0-%D0%BD%D0%B5%D0%B3%D0%BE/
  [2026-04-26T10:49:27.248747+00:00] Светът осъди стрелбата на събитие на Тръмп и изказа силна подкрепа за него
    https://nova.bg/news/view/2026/04/26/535167/%D1%81%D0%B2%D0%B5%D1%82%D1%8A%D1%82-%D0%BE%D1%81%D1%8A%D0%B4%D0%B8-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%B1%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D1%81%D1%8A%D0%B1%D0%B8%D1%82%D0%B8%D0%B5-%D0%BD%D0%B0-%D1%82%D1%80%D1%8A%D0%BC%D0%BF-%D0%B8-%D0%B8%D0%B7%D0%BA%D0%B0%D0%B7%D0%B0-%D1%81%D0%B8%D0%BB%D0%BD%D0%B0-%D0%BF%D0%BE%D0%B4%D0%BA%D1%80%D0%B5%D0%BF%D0%B0-%D0%B7%D0%B0-%D0%BD%D0%B5%D0%B3%D0%BE/

Published: 2026-04-26 10:39:57+00:00 | Title sim: 0.755 | Text sim: 1.000
  [2026-04-26T13:12:42.871323+00:00] Мелания Тръмп на 56 години: Живот между модата, политиката, дискретността и опасностите
    https://nova.bg/news/view/2026/04/26/535170/%D0%BC%D0%B5%D0%BB%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D1%8A%D0%BC%D0%BF-%D0%BD%D0%B0-56-%D0%B3%D0%BE%D0%B4%D0%B8%D0%BD%D0%B8-%D0%B6%D0%B8%D0%B2%D0%BE%D1%82-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%BC%D0%BE%D0%B4%D0%B0%D1%82%D0%B0-%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0%D1%82%D0%B0-%D0%B4%D0%B8%D1%81%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%82%D0%B0-%D0%B8-%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D1%82%D0%B5/
  [2026-04-26T10:49:27.248685+00:00] Мелания Тръмп навърши 56 г.: Живот между модата, политиката, дискретността и опасностите
    https://nova.bg/news/view/2026/04/26/535170/%D0%BC%D0%B5%D0%BB%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D1%8A%D0%BC%D0%BF-%D0%BD%D0%B0%D0%B2%D1%8A%D1%80%D1%88%D0%B8-56-%D0%B3-%D0%B6%D0%B8%D0%B2%D0%BE%D1%82-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%BC%D0%BE%D0%B4%D0%B0%D1%82%D0%B0-%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0%D1%82%D0%B0-%D0%B4%D0%B8%D1%81%D0%BA%D1%80%D0%B5%D1%82%D0%BD%D0%BE%D1%81%D1%82%D1%82%D0%B0-%D0%B8-%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8%D1%82%D0%B5/

Published: 2026-04-26 16:27:43+00:00 | Title sim: 0.920 | Text sim: 1.000
  [2026-04-26T18:59:23.792920+00:00] Тръмп: Иран има възможност за директен контакт със САЩ, войната може да приключи скоро
    https://nova.bg/news/view/2026/04/26/535197/%D1%82%D1%80%D1%8A%D0%BC%D0%BF-%D0%B8%D1%80%D0%B0%D0%BD-%D0%B8%D0%BC%D0%B0-%D0%B2%D1%8A%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82-%D0%B7%D0%B0-%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B5%D0%BD-%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82-%D1%81%D1%8A%D1%81-%D1%81%D0%B0%D1%89-%D0%B2%D0%BE%D0%B9%D0%BD%D0%B0%D1%82%D0%B0-%D0%BC%D0%BE%D0%B6%D0%B5-%D0%B4%D0%B0-%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B8-%D1%81%D0%BA%D0%BE%D1%80%D0%BE/
  [2026-04-26T16:49:25.491778+00:00] Тръмп: Иран има възможност за директен контакт със САЩ за преговори, войната може да приключи скоро

In [191]:
inspect_source_duplicate_similarity(df, "actualno", threshold=0.7)

Published: 2026-04-21 11:11:00+00:00 | Title sim: 0.317 | Text sim: 0.825
  [2026-04-21T13:49:43.207655+00:00] Крум Зарков поиска вот на доверие и обяви мащабен процес на промяна в БСП
    https://www.actualno.com/politics/krum-zarkov-poiska-vot-na-doverie-i-objavi-mashtaben-proces-na-promjana-v-bsp-news_2584392.html
  [2026-04-21T11:12:12.529337+00:00] Оставката чака зад ъгъла: Крум Зарков иска вот на доверие от БСП след "много лошия" резултат
    https://www.actualno.com/politics/ostavkata-chaka-zad-ygyla-krum-zarkov-iska-vot-na-doverie-ot-bsp-sled-mnogo-loshija-rezultat-news_2584392.html

Published: 2026-04-21 21:35:00+00:00 | Title sim: 0.868 | Text sim: 0.994
  [2026-04-22T06:03:40.205382+00:00] Мбапе и Винисиус са във вихъра си: Реал Мадрид се доближи до Барселона в Ла Лига
    https://www.actualno.com/football/mbape-i-vinisius-sa-vyv-vihyra-si-real-madrid-se-dobliji-do-barselona-v-la-liga-news_2584657.html
  [2026-04-22T02:48:16.526036+00:00] Мбапе и Винисиус са във вихъра си: Реал Мадрид се добрижи до Барселона в Ла Лига
    https://www.actualno.com/football/mbape-i-vinisius-sa-vyv-vihyra-si-real-madrid-se-dobriji-do-barselona-v-la-liga-news_2584657.html

Published: 2026-04-22 14:32:00+00:00 | Title sim: 0.982 | Text sim: 0.951
  [2026-04-22T19:22:47.347631+00:00] Демерджиев за оставката на Сарафов: Изключително закъснял акт. Да не се опитват моделът да оцелява
    https://www.actualno.com/politics/demerdjiev-za-ostavkata-na-sarafov-izkluchitelno-zakysnjal-akt-da-ne-se-opitvat-modelyt-da-oceljava-news_2585056.html
  [2026-04-22T17:07:51.802930+00:00] Демерджиев за оставката на Сарафов: Изключително закъснял акт. Да не се опитват да моделът да оцелява
    https://www.actualno.com/politics/demerdjiev-za-ostavkata-na-sarafov-izkluchitelno-zakysnjal-akt-da-ne-se-opitvat-da-modelyt-da-oceljava-news_2585056.html

Published: 2026-04-23 14:55:00+00:00 | Title sim: 0.884 | Text sim: 0.995
  [2026-04-23T17:25:41.314360+00:00] The New York Times с данни колко тежко ранен е Моджтаба Хаменей. Тръмп: Очистваме Ормузкия проток от мини
    https://www.actualno.com/asia/the-new-york-times-s-danni-kolko-tejko-ranen-e-modjtaba-hamenej-trymp-ochistvame-ormuzkija-protok-ot-mini-news_2585550.html
  [2026-04-23T15:57:14.734406+00:00] The New York Times с данни колко тежко ранен е Моджтаба Хаманей. Тръмп: Очистваме Ормузкия проток от мини
    https://www.actualno.com/asia/the-new-york-times-s-danni-kolko-tejko-ranen-e-modjtaba-hamanej-trymp-ochistvame-ormuzkija-protok-ot-mini-news_2585550.html

Published: 2026-04-28 15:59:00+00:00 | Title sim: 0.896 | Text sim: 1.000
  [2026-04-28T19:45:15.867325+00:00] Тръмп: Иран ни се моли да отворим Ормузкия проток
    https://www.actualno.com/america/trymp-iran-ni-se-moli-da-otvorim-ormuzkija-protok-news_2587643.html
  [2026-04-28T17:49:56.102512+00:00] Тръмп: Иран ни се моли отворим Ормузкия проток
    https://www.actualno.com/america/trymp-iran-ni-se-moli-otvorim-ormuzkija-protok-news_2587643.html

Published: 2026-04-28 19:23:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-29T03:26:44.987770+00:00] Икономическият мозък на Русия призна: Никога не сме имали такава ситуация в страната
    https://www.actualno.com/economy/ikonomicheskijat-mozyk-na-rusija-prizna-nikoga-ne-sme-imali-takava-situacija-v-stranata-video-news_2587686.html
  [2026-04-28T19:45:15.867204+00:00] Икономическият мозък на Русия призна: Никога не сме имали такава ситуация в страната
    https://www.actualno.com/europe/ikonomicheskijat-mozyk-na-rusija-prizna-nikoga-ne-sme-imali-takava-situacija-v-stranata-video-news_2587686.html

Published: 2026-04-29 15:01:00+00:00 | Title sim: 0.802 | Text sim: 0.896
  [2026-04-29T19:42:08.606269+00:00] Стерьовски пак се активира: Хвана го антибългарска параноя в съда
    https://www.actualno.com/balkani/steriovski-pak-se-aktivira-hvana-go-antibylgarska-paranoja-v-syda-news_2588104.html
  [2026-04-29T17:42:13.472936+00:00] Щерьовски пак се активира: Хвана го антибългарска параноя в съда
    https://www.actualno.com/balkani/shteriovski-pak-se-aktivira-hvana-go-antibylgarska-paranoja-v-syda-news_2588104.html

Published: 2026-04-30 13:13:00+00:00 | Title sim: 0.818 | Text sim: 1.000
  [2026-04-30T17:25:29.615161+00:00] Ген. Залужни: Преди да умра, ще накарам сина ми да се закълне да върне окупираните от Русия земи
    https://www.actualno.com/europe/gen-zalujni-predi-da-umra-shte-nakaram-sina-mi-da-se-zakylne-da-vyrne-okupiranite-ot-rusija-zemi-video-news_2588607.html
  [2026-04-30T14:03:26.504016+00:00] Ген. Залужни: Преди да умра, ще накарам сина ми да се закълне във връщане на окупираните от Русия земи
    https://www.actualno.com/europe/gen-zalujni-predi-da-umra-shte-nakaram-sina-mi-da-se-zakylne-vyv-vryshtane-na-okupiranite-ot-rusija-zemi-video-news_2588607.html

Published: 2026-05-01 04:39:00+00:00 | Title sim: 0.802 | Text sim: 1.000
  [2026-05-01T11:09:01.023320+00:00] Синдикатите с шествие за 1 май, представят първия профсъюзен изкуствен интелект
    https://www.actualno.com/society/sindikatite-s-shestvie-za-1-maj-predstavjat-pyrvija-profsyuzen-izkustven-intelekt-news_2588799.html
  [2026-05-01T06:39:31.628006+00:00] Синдикатите с шествие за 1 май, представятн първия профсъюзен изкуствен интелект
    https://www.actualno.com/society/sindikatite-s-shestvie-za-1-maj-predstavjatn-pyrvija-profsyuzen-izkustven-intelekt-news_2588799.html

Published: 2026-05-03 09:05:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-03T13:16:58.250488+00:00] Официално: Китай отмени американските санкции срещу своите петролни гиганти
    https://www.actualno.com/economy/oficialno-kitaj-otmeni-amerikanskite-sankcii-sreshtu-svoite-petrolni-giganti-news_2589301.html
  [2026-05-03T09:24:52.710868+00:00] Официално: Китай отмени американските санкции срещу своите петролни гиганти
    https://www.actualno.com/asia/oficialno-kitaj-otmeni-amerikanskite-sankcii-sreshtu-svoite-petrolni-giganti-news_2589301.html

Published: 2026-05-04 16:54:00+00:00 | Title sim: 0.780 | Text sim: 1.000
  [2026-05-04T19:44:29.730114+00:00] Кола се вряза в тълпа в Лайпциг, има загинали и ранени
    https://www.actualno.com/europe/kola-se-vrjaza-v-tylpa-v-lajpcig-ima-zaginali-i-raneni-video-news_2589891.html
  [2026-05-04T17:44:17.595303+00:00] Кола се вряза в тълпа Лайпциг, има ;агинали и ранени
    https://www.actualno.com/europe/kola-se-vrjaza-v-tylpa-lajpcig-ima-aginali-i-raneni-video-news_2589891.html

Published: 2026-05-05 15:24:00+00:00 | Title sim: 0.669 | Text sim: 1.000
  [2026-05-05T19:25:20.453719+00:00] Гергьовден 2026: Традиции, обичаи и забрани
    https://www.actualno.com/celebrate/gergiovden-2026-tradicii-obichai-i-zabrani-news_2590278.html
  [2026-05-05T15:32:08.420743+00:00] Гергьоведен 2026: Традиции, обичаи и забрани
    https://www.actualno.com/celebrate/gergioveden-2026-tradicii-obichai-i-zabrani-news_2590278.html

Published: 2026-05-06 14:08:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T17:43:54.955315+00:00] Световна сила: България е много близо до Русия във вечната класация на световната гимнастика
    https://www.actualno.com/moresport/svetovna-sila-bylgarija-e-mnogo-blizo-do-rusija-vyv-vechnata-klasacija-na-svetovnata-gimnastika-news_2590659.html
  [2026-05-06T14:21:19.361630+00:00] Световна сила: България много близо до Русия във вечната класация на световната гимнастика
    https://www.actualno.com/moresport/svetovna-sila-bylgarija-mnogo-blizo-do-rusija-vyv-vechnata-klasacija-na-svetovnata-gimnastika-news_2590659.html

Published: 2026-05-07 14:13:00+00:00 | Title sim: 0.963 | Text sim: 1.000
  [2026-05-07T17:50:49.890276+00:00] Кой е Иван Демерджиев - предложението на Румен Радев за министър на вътрешните работи
    https://www.actualno.com/politics/koj-e-ivan-demerdjiev-predlojenieto-na-rumen-radev-za-ministyr-na-vytreshnite-raboti-news_2591099.html
  [2026-05-07T14:18:25.729275+00:00] Кой е Иван Демерджиев - предложението на Румен Радев за вицепремиер и министър на вътрешните работи
    https://www.actualno.com/politics/koj-e-ivan-demerdjiev-predlojenieto-na-rumen-radev-za-vicepremier-i-ministyr-na-vytreshnite-raboti-news_2591099.html
  [2026-05-07T14:18:25.729264+00:00] Кой е Александър Пулев - предложението на Румен Радев за вицепремиер и министър на икономиката, инвестициите и индустрията
    https://www.actualno.com/politics/koj-e-aleksandyr-pulev-predlojenieto-na-rumen-radev-za-vicepremier-i-ministyr-na-ikonomikata-investiciite-i-industrijata-news_2591139.html
  [2026-05-07T14:18:25.729254+00:00] Кой е Гълъб Донев - предложението на Румен Радев за вицепремиер и министър на финансите
    https://www.actualno.com/politics/koj-e-gylyb-donev-predlojenieto-na-rumen-radev-za-vicepremier-i-ministyr-na-finansite-news_2591106.html

Published: 2026-05-08 03:17:00+00:00 | Title sim: 0.835 | Text sim: 0.980
  [2026-05-08T06:00:12.206699+00:00] Военни кораби на САЩ са преминали през Ормузкия проток въпреки обстрела
    https://www.actualno.com/america/voenni-korabi-na-sasht-sa-preminali-prez-ormuzkija-protok-vypreki-obstrela-news_2591292.html
  [2026-05-08T03:22:55.005930+00:00] Военни кораба на САЩ са преминали през Ормузкия проток въпреки обстрела
    https://www.actualno.com/america/voenni-koraba-na-sasht-sa-preminali-prez-ormuzkija-protok-vypreki-obstrela-news_2591292.html

Published: 2026-05-08 03:18:00+00:00 | Title sim: 0.650 | Text sim: 1.000
  [2026-05-08T06:00:12.206690+00:00] Тръмп постави амбициозен срок за търговско споразумение с ЕС
    https://www.actualno.com/economy/trymp-postavi-ambiciozen-srok-za-tyrgovsko-sporazumenie-s-es-news_2591293.html
  [2026-05-08T03:22:55.005913+00:00] ЕС си постави амбициозен срок за търговско споразумение със САЩ
    https://www.actualno.com/europe/es-si-postavi-ambiciozen-srok-za-tyrgovsko-sporazumenie-sys-sasht-news_2591293.html

Published: 2026-05-08 05:00:00+00:00 | Title sim: 0.897 | Text sim: 1.000
  [2026-05-08T07:54:30.186070+00:00] Тук пак ще налучкваме! Времето ти изтече: Голямо чудене за голям мач в играта "Кой съм аз"
    https://www.actualno.com/football/tuk-pak-shte-naluchkvame-vremeto-ti-izteche-goljamo-chudene-za-goljam-mach-v-igrata-koj-sym-az-video-news_2591070.html
  [2026-05-08T06:00:12.206582+00:00] Тук пак ще налоучкваме! Времето ти изтече: Голямо чудене за голям мач в играта "Кой съм аз"
    https://www.actualno.com/football/tuk-pak-shte-nalouchkvame-vremeto-ti-izteche-goljamo-chudene-za-goljam-mach-v-igrata-koj-sym-az-video-news_2591070.html
  [2026-05-08T06:00:12.206573+00:00] Отбелязваме Световния ден на Червения кръст
    https://www.actualno.com/goodnews/otbeljazvame-svetovnija-den-na-chervenija-kryst-news_2591225.html

Published: 2026-05-08 05:41:00+00:00 | Title sim: 0.780 | Text sim: 1.000
  [2026-05-08T07:54:30.186034+00:00] Голям пробив: Милан обвърза роден талант в дългосрочен план
    https://www.actualno.com/football/goljam-probiv-milan-obvyrza-roden-talant-v-dylgosrochen-plan-news_2591316.html
  [2026-05-08T06:00:12.206534+00:00] Голям пробив: Милан обвързаха роден талант в дългосрочен план
    https://www.actualno.com/football/goljam-probiv-milan-obvyrzaha-roden-talant-v-dylgosrochen-plan-news_2591316.html

Published: 2026-05-09 05:26:00+00:00 | Title sim: 0.375 | Text sim: 0.895
  [2026-05-09T09:22:54.482867+00:00] Официалните церемонии в София за Деня на Европа
    https://www.actualno.com/society/oficialnite-ceremonii-v-sofija-za-denja-na-evropa-news_2591813.html
  [2026-05-09T06:19:27.677901+00:00] На 9 май Пеевски поздрави за Деня на Европа, който е на 8 май
    https://www.actualno.com/politics/na-9-maj-peevski-pozdravi-za-denja-na-evropa-kojto-e-na-8-maj-news_2591813.html

Published: 2026-05-09 13:31:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-09T16:58:56.320834+00:00] „Росатом“ с мащабен план за България, Унгария и Словакия: Русия не се е отказала от ядрените си амбиции
    https://www.actualno.com/economy/rosatom-s-mashtaben-plan-za-bylgarija-ungarija-i-slovakija-rusija-ne-se-e-otkazala-ot-jadrenite-si-ambicii-news_2591946.html
  [2026-05-09T14:54:04.718593+00:00] „Росатом“ с мащабен план за България, Унгария и Словакия: Русия не се е отказала от ядрените си амбиции
    https://www.actualno.com/europe/rosatom-s-mashtaben-plan-za-bylgarija-ungarija-i-slovakija-rusija-ne-se-e-otkazala-ot-jadrenite-si-ambicii-news_2591946.html

Published: 2026-05-09 14:08:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-09T16:58:56.320816+00:00] Огромен скандал в българска църква в Одрин: Гръцки попове искат богослужение на гръцки език
    https://www.actualno.com/balkani/ogromen-skandal-v-bylgarska-cyrkva-v-odrin-grycki-popove-iskat-bogoslujenie-na-grycki-ezik-news_2591959.html
  [2026-05-09T14:54:04.718573+00:00] Огромен скандал в българска църква в Одрин: Гръцки попове искат богослужение на гръцки език
    https://www.actualno.com/europe/ogromen-skandal-v-bylgarska-cyrkva-v-odrin-grycki-popove-iskat-bogoslujenie-na-grycki-ezik-news_2591959.html

Published: 2026-05-10 05:10:00+00:00 | Title sim: 0.965 | Text sim: 1.000
  [2026-05-10T09:40:44.634218+00:00] Полицията по следите на непълнолетни за нападението над автобус в Перник
    https://www.actualno.com/pernik/policijata-po-sledite-na-nepylnoletni-za-napadenieto-nad-avtobus-v-pernik-news_2592062.html
  [2026-05-10T06:35:33.641323+00:00] Полицията в Перник по следите на непълнолетни за нападението над автобус в Перник
    https://www.actualno.com/pernik/policijata-v-pernik-po-sledite-na-nepylnoletni-za-napadenieto-nad-avtobus-v-pernik-news_2592062.html

Published: 2026-05-12 18:01:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-12T21:22:32.835444+00:00] Баница за новобранеца: Новите придворни на Радев
    https://www.actualno.com/prasspress/banica-za-novobraneca-novite-pridvorni-na-radev-news_2593034.html
  [2026-05-12T18:02:27.146197+00:00] Баница за новобранеца: Новите придворни на Радев
    https://www.actualno.com/europe/banica-za-novobraneca-novite-pridvorni-na-radev-news_2593034.html

Published: 2026-05-12 22:11:00+00:00 | Title sim: 0.550 | Text sim: 1.000
  [2026-05-13T03:38:32.643632+00:00] Тръмп: Краят на войната в Украйна е близо, не съм се договарял с Путин за Донбас
    https://www.actualno.com/america/trymp-krajat-na-vojnata-v-ukrajna-e-blizo-ne-sym-se-dogovarjal-s-putin-za-donbas-video-news_2593343.html
  [2026-05-12T23:04:53.415216+00:00] Тръмп: Краят на войната в Украйна е близо
    https://www.actualno.com/america/trymp-krajat-na-vojnata-v-ukrajna-e-blizo-video-news_2593343.html

Published: 2026-05-14 03:07:00+00:00 | Title sim: 0.780 | Text sim: 0.965
  [2026-05-14T06:48:40.741946+00:00] САЩ уверяват: Рискът от заразяване с хантавирус остава нисък
    https://www.actualno.com/america/sasht-uverjavat-riskyt-ot-zarazjavane-s-hantavirus-ostava-nisyk-news_2593899.html
  [2026-05-14T03:37:56.801456+00:00] САЩ уверява: Рискът от заразяване с хантавирус остава нисък
    https://www.actualno.com/america/sasht-uverjava-riskyt-ot-zarazjavane-s-hantavirus-ostava-nisyk-news_2593899.html

Published: 2026-05-15 03:05:00+00:00 | Title sim: 1.000 | Text sim: 0.948
  [2026-05-15T06:58:13.401044+00:00] Тръмп: Китай иска да купува петрол от САЩ
    https://www.actualno.com/economy/trymp-kitaj-iska-da-kupuva-petrol-ot-sasht-news_2594431.html
  [2026-05-15T03:41:02.565121+00:00] Тръмп: Китай иска да купува петрол от САЩ
    https://www.actualno.com/america/trymp-kitaj-iska-da-kupuva-petrol-ot-sasht-news_2594431.html

Published: 2026-05-15 03:25:00+00:00 | Title sim: 0.717 | Text sim: 1.000
  [2026-05-15T06:58:13.401000+00:00] Мотористи на протест заради скъпа застраховка
    https://www.actualno.com/society/motoristi-na-protest-zaradi-skypa-zastrahovka-news_2594436.html
  [2026-05-15T03:41:02.565071+00:00] Мотористи на протест заради скъпа застрааховка
    https://www.actualno.com/society/motoristi-na-protest-zaradi-skypa-zastraahovka-news_2594436.html

Published: 2026-05-15 18:30:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-15T22:57:07.793753+00:00] Бивш заместник-министър: Очевидно охраната на Бойко Борисов и Делян Пеевски е политическо решение
    https://www.actualno.com/politics/bivsh-zamestnik-ministyr-ochevidno-ohranata-na-bojko-borisov-i-deljan-peevski-e-politichesko-reshenie-news_2594859.html
  [2026-05-15T19:42:17.978523+00:00] Бивш заместник-министър: Очевидно охраната на Бойко Борисов и Делян Пеевски е е политическо решение
    https://www.actualno.com/politics/bivsh-zamestnik-ministyr-ochevidno-ohranata-na-bojko-borisov-i-deljan-peevski-e-e-politichesko-reshenie-news_2594859.html

Published: 2026-05-15 20:03:00+00:00 | Title sim: 0.559 | Text sim: 1.000
  [2026-05-15T22:57:07.793701+00:00] Прогноза за времето - 16 май 2026 г. (събота)
    https://www.actualno.com/society/prognoza-za-vremeto-16-maj-2026-g-sybota-news_2594871.html
  [2026-05-15T21:04:29.245418+00:00] Прогноза за времето - 15 май 2026 г. (петък)
    https://www.actualno.com/society/prognoza-za-vremeto-15-maj-2026-g-petyk-news_2594871.html

Published: 2026-05-17 13:11:00+00:00 | Title sim: 0.835 | Text sim: 1.000
  [2026-05-17T14:59:25.207271+00:00] Дрон удари атомна електроцентрала в Абу Даби: Има ли опасност от радиация?
    https://www.actualno.com/asia/dron-udari-atomna-elektrocentrala-v-abu-dabi-ima-li-opasnost-ot-radiacija-news_2595271.html
  [2026-05-17T13:26:11.444034+00:00] Дрон удари атомна електроцентарала в Абу Даби: Има ли опасност от радиация?
    https://www.actualno.com/asia/dron-udari-atomna-elektrocentarala-v-abu-dabi-ima-li-opasnost-ot-radiacija-news_2595271.html

Published: 2026-05-17 13:14:00+00:00 | Title sim: 0.835 | Text sim: 1.000
  [2026-05-17T14:59:25.207262+00:00] Компани след титлата с Байерн: Радостта е огромна, но цялостната ми оценка предстои
    https://www.actualno.com/football/kompani-sled-titlata-s-bajern-radostta-e-ogromna-no-cjalostnata-mi-ocenka-predstoi-news_2595270.html
  [2026-05-17T13:26:11.444023+00:00] Компани след титлата с Байерн: Радостта е огромна, но цялостната ми оценката предстои
    https://www.actualno.com/football/kompani-sled-titlata-s-bajern-radostta-e-ogromna-no-cjalostnata-mi-ocenkata-predstoi-news_2595270.html

Published: 2026-05-17 18:21:00+00:00 | Title sim: 0.876 | Text sim: 0.999
  [2026-05-17T20:56:25.394004+00:00] "Ковачът" на 27-ата: "One-man show", учител на Лингард, изкушен за 1 нощ
    https://www.actualno.com/bgfootball/kovachyt-na-27-ata-one-man-show-uchitel-na-lingard-izkushen-za-1-nosht-news_2590364.html
  [2026-05-17T19:13:20.233048+00:00] "Ковачът" на 27-мата: "One-man show", учител на Лингард, изкушен за 1 нощ
    https://www.actualno.com/bgfootball/kovachyt-na-27-mata-one-man-show-uchitel-na-lingard-izkushen-za-1-nosht-news_2590364.html

Published: 2026-05-20 20:30:00+00:00 | Title sim: 0.802 | Text sim: 1.000
  [2026-05-20T23:20:08.078533+00:00] Говорителят на Кремъл: Дъщеря ми научи китайски преди руски
    https://www.actualno.com/europe/govoriteljat-na-kremyl-dyshterja-mi-nauchi-kitajski-predi-ruski-video-news_2596899.html
  [2026-05-20T21:58:03.744074+00:00] Говорителят на Кремъл: Дъщерят ми научи китайски преди руски
    https://www.actualno.com/europe/govoriteljat-na-kremyl-dyshterjat-mi-nauchi-kitajski-predi-ruski-video-news_2596899.html

Published: 2026-05-21 15:30:00+00:00 | Title sim: 0.835 | Text sim: 1.000
  [2026-05-21T23:05:17.244513+00:00] Как Радев създава очаквания, че ще оправи нещата? Обяснява Левон Хампарцумян
    https://www.actualno.com/interview/kak-radev-syzdava-ochakvanija-che-shte-opravi-neshtata-objasnjava-levon-hamparcumjan-video-news_2597218.html
  [2026-05-21T15:34:39.240295+00:00] Как Радев съзадава очаквания, че ще оправи нещата? Обяснява Левон Хампарцумян
    https://www.actualno.com/interview/kak-radev-syzadava-ochakvanija-che-shte-opravi-neshtata-objasnjava-levon-hamparcumjan-video-news_2597218.html

Published: 2026-05-22 14:09:00+00:00 | Title sim: 0.538 | Text sim: 0.988
  [2026-05-22T14:45:02.117113+00:00] Вижте верните отговори и изпита по математика за 12. клас на матури 2026 г.

In [192]:
inspect_source_duplicate_similarity(df, "24chasa", threshold=0.7)

Published: 2026-04-22 16:49:00+00:00 | Title sim: 1.000 | Text sim: 0.993
  [2026-04-22T20:58:34.871000+00:00] Испански прокурор поиска делото за корупция срещу съпругата на премиера да бъде прекратено
    https://www.24chasa.bg/mezhdunarodni/article/22716371
  [2026-04-22T17:05:17.998300+00:00] Испански прокурор поиска делото за корупция срещу съпругата на премиера да бъде прекратено
    https://www.24chasa.bg/zdrave/article/22716371

Published: 2026-04-23 14:33:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-23T20:56:14.066825+00:00] Правителството на Тръмп улеснява употребата на марихуана за медицински цели
    https://www.24chasa.bg/zdrave/article/22722225
  [2026-04-23T15:56:53.425387+00:00] Правителството на Тръмп улеснява употребата на марихуана за медицински цели
    https://www.24chasa.bg/mezhdunarodni/article/22722225

Published: 2026-04-23 16:43:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-23T19:15:06.157799+00:00] Арестуваха бившия шеф на северномакедонската футболна федерация
    https://www.24chasa.bg/sport/article/22723251
  [2026-04-23T17:25:30.671141+00:00] Арестуваха бившия шеф на северномакедонската футболна федерация
    https://www.24chasa.bg/mezhdunarodni/article/22723251

Published: 2026-04-25 05:45:00+00:00 | Title sim: 1.000 | Text sim: 0.997
  [2026-04-25T07:21:57.475729+00:00] Шефът на борсата в Първенец: Пресните плодове и зеленчуци продължават да поскъпват
    https://www.24chasa.bg/biznes/article/22731373
  [2026-04-25T05:50:14.172988+00:00] Шефът на борсата в Първенец: Пресните плодове и зеленчуци продължават да поскъпват
    https://www.24chasa.bg/bulgaria/article/22731373

Published: 2026-04-26 13:51:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-26T16:49:18.152131+00:00] Килим от пари край релсите: 25 г. по-късно говори кантонерът, който не посегна на милионите
    https://www.24chasa.bg/kolektsionerskiyat_broy/article/22729113
  [2026-04-26T14:47:43.391525+00:00] Килим от пари край релсите: 25 г. по-късно говори кантонерът, който не посегна на милионите
    https://www.24chasa.bg/ozhivlenie/article/22729113

Published: 2026-04-27 13:57:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-27T17:26:18.284708+00:00] Олиото от аржентински слънчоглед напуска България, изнасят го за Египет и Индия
    https://www.24chasa.bg/biznes/article/22743340
  [2026-04-27T14:00:31.468072+00:00] Олиото от аржентински слънчоглед напуска България, изнасят го за Египет и Индия
    https://www.24chasa.bg/bulgaria/article/22743340

Published: 2026-04-27 17:11:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-04-27T19:27:08.967854+00:00] Илияна Йотова: Най-важното за икономическата ни система е инвестицията в човешкия капитал
    https://www.24chasa.bg/biznes/article/22744539
  [2026-04-27T17:26:18.284367+00:00] Илияна Йотова: Най-важното за икономическата ни система е инвестицията в човешкия капитал
    https://www.24chasa.bg/bulgaria/article/22744539

Published: 2026-04-29 11:43:00+00:00 | Title sim: 0.000 | Text sim: 0.721
  [2026-04-29T14:03:37.351316+00:00] Вижте какво реши служебното правителство днес
    https://www.24chasa.bg/bulgaria/article/22755990
  [2026-04-29T14:03:37.351307+00:00] Ердоган обяви, че е преодолян критичният праг по разоръжаването на ПКК
    https://www.24chasa.bg/mezhdunarodni/article/22755998

Published: 2026-05-03 17:19:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-03T22:45:54.532558+00:00] Хуманоидният робот София: Разбирам много неща, но не и жестокостта срещу други човешки същества
    https://www.24chasa.bg/bulgaria/article/22779916
  [2026-05-03T19:03:45.494446+00:00] Хуманоидният робот София: Разбирам много неща, но не и жестокостта срещу други човешки същества
    https://www.24chasa.bg/biznes/article/22779916

Published: 2026-05-06 00:00:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T06:31:27.517028+00:00] 100 маратона за 100 дни в името на татко!
    https://www.24chasa.bg/sport/article/22794007
  [2026-05-06T03:24:38.728535+00:00] 100 маратона за 100 дни в името на татко!
    https://www.24chasa.bg/sport/article/22750612

Published: 2026-05-06 09:13:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T14:20:55.845113+00:00] Джон Малкович получи хърватско гражданство
    https://www.24chasa.bg/ozhivlenie/article/22794982
  [2026-05-06T10:22:00.289864+00:00] Джон Малкович получи хърватско гражданство
    https://www.24chasa.bg/mezhdunarodni/article/22794982

Published: 2026-05-06 09:30:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-06T14:20:55.845076+00:00] Цените на производител в Европа са скочили с 2%
    https://www.24chasa.bg/biznes/article/22795147
  [2026-05-06T10:22:00.289819+00:00] Цените на производител в Европа са скочили с 2%
    https://www.24chasa.bg/mezhdunarodni/article/22795147

Published: 2026-05-10 05:08:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-10T09:40:26.840354+00:00] Всички пътници на засегнатия от хантавирус кораб се смятат за високорискови контактни лица
    https://www.24chasa.bg/zdrave/article/22819072
  [2026-05-10T06:35:20.981638+00:00] Всички пътници на засегнатия от хантавирус кораб се смятат за високорискови контактни лица
    https://www.24chasa.bg/mezhdunarodni/article/22819072

Published: 2026-05-11 07:26:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-11T11:25:54.643101+00:00] Дуа Липа съди „Самсунг“ за $15 млн. - използвали образа ѝ в реклама без разрешение
    https://www.24chasa.bg/ozhivlenie/article/22824387
  [2026-05-11T07:44:26.972047+00:00] Дуа Липа съди „Самсунг“ за $15 млн. - използвали образа ѝ в реклама без разрешение
    https://www.24chasa.bg/mezhdunarodni/article/22824387

Published: 2026-05-12 17:41:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-12T21:22:23.916747+00:00] САЩ преговарят за 3 нови военни бази в Гренландия
    https://www.24chasa.bg/mezhdunarodni/article/22836351
  [2026-05-12T18:01:54.971075+00:00] САЩ преговарят за 3 нови военни бази в Гренландия
    https://www.24chasa.bg/ozhivlenie/article/22836351

Published: 2026-05-20 11:55:00+00:00 | Title sim: 0.000 | Text sim: 0.813
  [2026-05-20T15:27:29.025491+00:00] Прибират цялата печалба на държавните дружества от 2025 г.
    https://www.24chasa.bg/biznes/article/22885765
  [2026-05-20T15:27:29.025482+00:00] Вижте какво реши правителството днес
    https://www.24chasa.bg/bulgaria/article/22885700

Published: 2026-05-25 14:44:00+00:00 | Title sim: 0.940 | Text sim: 1.000
  [2026-05-25T17:46:16.585180+00:00] Песков: Армения ще загуби атрактивната цена, която плаща за руски газ, ако ни обърне гръб
    https://www.24chasa.bg/biznes/article/22915273
  [2026-05-25T14:58:07.539919+00:00] Песков: Армения ще загуби много атрактивната цена, която плаща за руски газ, ако ни обърне гръб
    https://www.24chasa.bg/mezhdunarodni/article/22915273

Published: 2026-05-31 11:40:00+00:00 | Title sim: 1.000 | Text sim: 1.000
  [2026-05-31T13:49:22.625700+00:00] Тих скандал между сценаристи и режисьори кой е по-заслужил за успеха на сериала "Вяра, надежда, любов"
    https://www.24chasa.bg/ozhivlenie/article/22950805
  [2026-05-31T11:41:58.701048+00:00] Тих скандал между сценаристи и режисьори кой е по-заслужил за успеха на сериала "Вяра, надежда, любов"
    https://www.24chasa.bg/bulgaria/article/22950805

Published: 2026-06-06 08:37:00+00:00 | Title sim: 0.676 | Text sim: 1.000
  [2026-06-06T13:48:43.649751+00:00] "Роснефт": Затварянето на Ормузкия проток е в интерес на САЩ
    https://www.24chasa.bg/biznes/article/22991249
  [2026-06-06T10:06:57.718870+00:00] "Роснефт": Затварянето на Ормузкия проток е опит да се промени енергийният пазар в интерес на САЩ
    https://www.24chasa.bg/mezhdunarodni/article/22991249

Source: 24chasa | Total groups: 1302 | Title sim >= 0.7: 16 | Text sim >= 0.7: 19

In [193]:
def drop_updated_duplicates(
    df: pd.DataFrame, sources: list[str], threshold: float = 0.7
) -> pd.DataFrame:
    df = df.sort_values("fetched_at", ascending=False).reset_index(drop=True)
    rows_to_drop = set()

    for source in sources:
        source_df = df[df["source"] == source]
        source_dropped = 0

        for published_at, group in source_df.groupby("published_at_dt"):
            if len(group) < 2:
                continue

            titles = group["title"].fillna("").tolist()
            texts = group["full_text"].fillna("").tolist()

            try:
                title_sim = cosine_similarity(TfidfVectorizer().fit_transform(titles))[
                    0
                ][1]
                text_sim = cosine_similarity(TfidfVectorizer().fit_transform(texts))[0][
                    1
                ]
            except ValueError:
                continue

            if title_sim < threshold and text_sim < threshold:
                continue

            indices = group.index.tolist()
            to_drop = indices[1:]
            rows_to_drop.update(to_drop)
            source_dropped += len(to_drop)

        print(f"Source: {source} | Dropping: {source_dropped}")

    before = len(df)
    df = df.drop(index=rows_to_drop).reset_index(drop=True)
    print(f"\nTotal dropped: {before - len(df)} | Remaining: {len(df)}")
    return df

In [194]:
sources_to_clean = ["segabg", "bta", "vesti", "nova", "actualno"]
df = drop_updated_duplicates(df, sources_to_clean)

Source: segabg | Dropping: 145
Source: bta | Dropping: 27
Source: vesti | Dropping: 46
Source: nova | Dropping: 320
Source: actualno | Dropping: 46

Total dropped: 584 | Remaining: 49612

Update the parquet file

In [195]:
out_path = "../data/processed/articles_clean_notebook.parquet"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
df.to_parquet(out_path, index=False)
print(f"Saved {len(df)} articles → {out_path}")

Saved 49612 articles → ../data/processed/articles_clean_notebook.parquet

# 9. Comparison with raw data

In [196]:
DATA_DIR = "../data/raw"

records = []
for date_folder in sorted(os.listdir(DATA_DIR)):
    folder_path = os.path.join(DATA_DIR, date_folder)
    if not os.path.isdir(folder_path):
        continue
    for filename in os.listdir(folder_path):
        if filename.endswith(".json"):
            filepath = os.path.join(folder_path, filename)
            with open(filepath, encoding="utf-8") as f:
                records.append(json.load(f))

df_raw = pd.DataFrame(records)
df_raw["published_at_dt"] = pd.to_datetime(
    df["published_at"], format="ISO8601", utc=True
)
print(f"Total articles loaded: {len(df_raw)}")

Total articles loaded: 63178

In [197]:
comp = (
    pd.DataFrame(
        {"raw": df_raw["source"].value_counts(), "cleaned": df["source"].value_counts()}
    )
    .fillna(0)
    .astype(int)
)
comp["dropped"] = comp["raw"] - comp["cleaned"]
comp["dropped %"] = (comp["dropped"] / comp["raw"] * 100).round(1).astype(str) + "%"

total = comp[["raw", "cleaned", "dropped"]].sum()
total["dropped %"] = str(round(total["dropped"] / total["raw"] * 100, 1)) + "%"
total.name = "TOTAL"
comp = pd.concat([comp, total.to_frame().T])
comp

                raw cleaned dropped dropped %
24chasa       13178   12908     270      2.0%
actualno       7567    7241     326      4.3%
banker          998     997       1      0.1%
blitz           531       0     531    100.0%
bta            4652    4572      80      1.7%
capital          30       0      30    100.0%
dnevnik         256       0     256    100.0%
economic        466     466       0      0.0%
fakti          7640    7565      75      1.0%
monitor       13850    3403   10447     75.4%
nova           5149    4053    1096     21.3%
segabg         1776    1385     391     22.0%
standartnews   3935    3921      14      0.4%
vesti          3150    3101      49      1.6%
TOTAL         63178   49612   13566     21.5%