# 11 — Evaluation

Compare the system's dot assignments against the manually labeled ground truth
using B-cubed Precision, Recall and F1.

- **Precision** — for each article, what fraction of its system-dot neighbours share the same GT label? Measures dot purity. Low when system under-splits.
- **Recall** — for each article, what fraction of its GT-cluster neighbours ended up in the same system dot? Measures grouping completeness. Low when system over-splits.
- **F1** — harmonic mean of precision and recall.

**Data:**
- Ground truth: `data/evaluation/ground_truth_*.json` — 24 manually labeled stories across 5 buckets
- System output: `data/processed/dots_louvain_tuned.pkl`

In [22]:
import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path("../").resolve()
EVAL_DIR = REPO_ROOT / "data" / "evaluation"

## Load Data

In [23]:
df = pd.read_parquet(REPO_ROOT / "data/processed/articles_clean.parquet")
df["published_at_dt"] = pd.to_datetime(df["published_at_dt"], utc=True)

with open(REPO_ROOT / "data/processed/stories.pkl", "rb") as f:
    stories = pickle.load(f)

with open(REPO_ROOT / "data/processed/dots_louvain_tuned.pkl", "rb") as f:
    all_dots = pickle.load(f)

print(f"Articles : {len(df):,}")
print(f"Stories  : {len(stories):,}")

Articles : 30,462
Stories  : 18,473

In [24]:
# load all ground truth buckets
BUCKETS = ["2_5", "5_10", "10_20", "20_50", "50+"]
BUCKET_LABELS = {"2_5": "2-5", "5_10": "5-10", "10_20": "10-20", "20_50": "20-50", "50+": "50+"}

ground_truth = {}
for bucket in BUCKETS:
    with open(EVAL_DIR / f"ground_truth_{bucket}.json") as f:
        data = json.load(f)
    for sid_str, v in data.items():
        ground_truth[int(sid_str)] = {**v, "bucket": BUCKET_LABELS[bucket]}

print(f"Ground truth stories: {len(ground_truth)}")

Ground truth stories: 24

## Helper Functions

In [25]:
url_to_idx = {row["url"]: i for i, row in df.iterrows()}


def system_labels_for_story(sid: int, gt_urls: list) -> list:
    """Convert system dots → per-article labels, matched by URL to ground truth order."""
    idx_to_dot = {}
    for dot_id, dot in enumerate(all_dots[sid]):
        for art_idx in dot["indices"]:
            idx_to_dot[art_idx] = dot_id
    return [idx_to_dot.get(url_to_idx.get(url), -1) for url in gt_urls]


def bcubed(gt_labels: list, sys_labels: list) -> tuple:
    """B-cubed precision, recall, F1."""
    gt = np.array(gt_labels)
    sys = np.array(sys_labels)
    n = len(gt)

    precisions, recalls = [], []
    for i in range(n):
        same_sys = sys == sys[i]
        same_gt = gt == gt[i]

        p_i = np.sum(same_sys & same_gt) / np.sum(same_sys)
        r_i = np.sum(same_sys & same_gt) / np.sum(same_gt)

        precisions.append(p_i)
        recalls.append(r_i)

    p = float(np.mean(precisions))
    r = float(np.mean(recalls))
    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0.0
    return round(p, 3), round(r, 3), round(f1, 3)

## Per-Story Evaluation

In [26]:
rows = []
for sid, gt in ground_truth.items():
    gt_labels = gt["labels"]
    sys_labels = system_labels_for_story(sid, gt["articles"])
    p, r, f1 = bcubed(gt_labels, sys_labels)

    rows.append({
        "story_id": sid,
        "bucket": gt["bucket"],
        "n_articles": len(gt_labels),
        "gt_dots": len(set(gt_labels)),
        "sys_dots": len(set(sys_labels)),
        "Precision": p,
        "Recall": r,
        "F1": f1,
    })

results = pd.DataFrame(rows).sort_values(["bucket", "story_id"])
results

    story_id bucket  n_articles  gt_dots  sys_dots  Precision  Recall     F1
13      4738  10-20          18        4         4      1.000   1.000  1.000
11      6585  10-20          12        3         4      1.000   0.750  0.857
10      7809  10-20          11        5         6      0.818   0.758  0.787
14      8716  10-20          10        1         2      1.000   0.580  0.734
12     11154  10-20          14        3         4      1.000   0.732  0.845
3        265    2-5           2        1         1      1.000   1.000  1.000
2       2810    2-5           3        3         3      1.000   1.000  1.000
1       9785    2-5           5        2         2      1.000   1.000  1.000
4      15864    2-5           2        1         1      1.000   1.000  1.000
0      17716    2-5           2        1         1      1.000   1.000  1.000
16       344  20-50          27       21        21      0.852   0.889  0.870
15      5614  20-50          20       10         5      0.595   0.950  0.732
19      6673  20-50          27       10         9      0.907   0.944  0.926
18      8049  20-50          22       18        18      0.939   0.955  0.947
17     14047  20-50          34       11         8      0.649   0.661  0.655
5       9249   5-10           5        1         1      1.000   1.000  1.000
7       9952   5-10           7        2         2      1.000   1.000  1.000
8      10796   5-10           8        1         3      1.000   0.406  0.578
6      15502   5-10           6        1         2      1.000   0.500  0.667
9      16390   5-10           8        2         2      0.812   0.571  0.671
22      7842    50+          70       16        21      0.977   0.852  0.910
21     10122    50+          65       17        19      0.792   0.787  0.790
20     11769    50+          51       11        14      0.908   0.777  0.837
23     13438    50+          65       17        18      0.779   0.822  0.800

## Summary Per Bucket

In [27]:
summary = (
    results.groupby("bucket")[["Precision", "Recall", "F1"]]
    .mean()
    .round(3)
    .reindex(["2-5", "5-10", "10-20", "20-50", "50+"])
)
summary.loc["Overall"] = results[["Precision", "Recall", "F1"]].mean().round(3)
summary

         Precision  Recall     F1
bucket
2-5          1.000   1.000  1.000
5-10         0.962   0.695  0.783
10-20        0.964   0.764  0.845
20-50        0.788   0.880  0.826
50+          0.864   0.810  0.834
Overall      0.918   0.831  0.859

In [18]:
summary = (
    results.groupby("bucket")[["Precision", "Recall", "F1"]]
    .mean()
    .round(3)
    .reindex(["2-5", "5-10", "10-20", "20-50", "50+"])
)
summary.loc["Overall"] = results[["Precision", "Recall", "F1"]].mean().round(3)
summary

         Precision  Recall     F1
bucket
2-5          1.000   1.000  1.000
5-10         1.000   0.695  0.794
10-20        0.976   0.714  0.820
20-50        0.852   0.866  0.855
50+          0.808   0.763  0.782
Overall      0.932   0.810  0.853

## Per-Story Detail

For each story: show ground truth labels vs system labels side by side.

In [20]:
def show_comparison(sid: int):
    gt = ground_truth[sid]
    gt_labels = gt["labels"]
    sys_labels = system_labels_for_story(sid, gt["articles"])
    p, r, f1 = bcubed(gt_labels, sys_labels)

    print(f"Story {sid}  [{gt['bucket']}]  P={p:.3f}  R={r:.3f}  F1={f1:.3f}  (gt_dots={len(set(gt_labels))}  sys_dots={len(set(sys_labels))})")
    print(f"{'[i]':>4}  {'GT':>3}  {'SYS':>4}  title")
    print("-" * 80)
    for i, (url, gt_l, sys_l) in enumerate(zip(gt["articles"], gt_labels, sys_labels)):
        art_idx = url_to_idx.get(url)
        row = df.iloc[art_idx]
        pub = row["published_at_dt"].strftime("%d %b %H:%M")
        match = "✓" if gt_l == sys_l else "✗"
        print(f"  [{i:2}]  {gt_l:>3}  {sys_l:>4}    {match}   {pub} [{row['source']}] {row['title'][:50]}")

In [21]:
for sid in ground_truth:
    show_comparison(sid)
    print()

Story 17716  [2-5]  P=1.000  R=1.000  F1=1.000  (gt_dots=1  sys_dots=1)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   20 May 14:09 [24chasa] Кремъл: Политиците от балтийските държави поддържа
  [ 1]    0     0    ✓   20 May 18:09 [fakti] Говори Москва: Политиците от балтийските държави п

Story 9785  [2-5]  P=1.000  R=1.000  F1=1.000  (gt_dots=2  sys_dots=2)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   06 May 09:50 [bta] Джорджа Мелони ще се срещне в Рим с новоизбрания у
  [ 1]    0     0    ✓   06 May 09:59 [fakti] Мелони приема новия унгарски премиер Петер Мадяр в
  [ 2]    1     1    ✓   07 May 15:22 [nova] Петер Мадяр се срещна с Джорджа Мелони
  [ 3]    1     1    ✓   07 May 17:00 [vesti] Нова ера в Будапеща: Мадяр начерта бъдещето на Унг
  [ 4]    1     1    ✓   07 May 17:10 [standartnews] Нова ера в Унгария. Мадяр готви решителни мерки

Story 2810  [2-5]  P=1.000  R=1.000  F1=1.000  (gt_dots=3  sys_dots=3)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   24 Apr 13:33 [24chasa] Без парад за Гергьовден тази година, само авиошоу
  [ 1]    1     1    ✓   26 Apr 06:00 [actualno] Пари или безхаберие: Парад на Гергьовден няма да и
  [ 2]    2     2    ✓   06 May 07:30 [segabg] Гергьовден е без парад заради удължителния бюджет

Story 265  [2-5]  P=1.000  R=1.000  F1=1.000  (gt_dots=1  sys_dots=1)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   24 Apr 12:39 [fakti] Мелони: Напрежението между САЩ и Испания вреди на
  [ 1]    0     0    ✓   24 Apr 12:59 [24chasa] Мелони: Напрежението между Тръмп и Испания около Н

Story 15864  [2-5]  P=1.000  R=1.000  F1=1.000  (gt_dots=1  sys_dots=1)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   15 May 09:43 [actualno] Ясни са номерата в бюлетините за частичните избори
  [ 1]    0     0    ✓   15 May 09:58 [vesti] ЦИК определи номерата в бюлетините за частичните и

Story 9249  [5-10]  P=1.000  R=1.000  F1=1.000  (gt_dots=1  sys_dots=1)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   08 May 08:29 [24chasa] Вземете новите HONOR 600 Pro и HONOR 600 от A1 – в
  [ 1]    0     0    ✓   08 May 08:32 [actualno] Вземете новите HONOR 600 Pro и HONOR 600 от A1 – в
  [ 2]    0     0    ✓   08 May 08:40 [fakti] Вземете новите HONOR 600 Pro и HONOR 600 от A1 – в
  [ 3]    0     0    ✓   08 May 08:58 [vesti] Вземете новите HONOR 600 Pro и HONOR 600 от A1 – в
  [ 4]    0     0    ✓   08 May 10:05 [standartnews] Вземете новите HONOR 600 Pro и HONOR 600 от A1 – в

Story 15502  [5-10]  P=1.000  R=0.500  F1=0.667  (gt_dots=1  sys_dots=2)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   15 May 08:55 [segabg] Средната заплата в София за пръв път мина 2000 евр
  [ 1]    0     0    ✓   15 May 09:27 [fakti] НСИ: Средната заплата за март гони 1500 евро, а в
  [ 2]    0     0    ✓   15 May 09:57 [24chasa] Средната заплата в България достига 1407 евро и на
  [ 3]    0     1    ✗   15 May 11:14 [actualno] Първи данни за заплатите в евро: Колко достигна ср
  [ 4]    0     1    ✗   15 May 12:02 [economic] Средната заплата в София надхвърли 2000 евро
  [ 5]    0     1    ✗   15 May 20:00 [24chasa] Средна заплата в София вече над 2000 евро, но депу

Story 9952  [5-10]  P=1.000  R=1.000  F1=1.000  (gt_dots=2  sys_dots=2)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   07 May 05:08 [nova] 526 евро глоба и 3 месеца без книжка: Санкционирах
  [ 1]    0     0    ✓   07 May 05:35 [vesti] Семейство, спряло в аварийната лента заради нужда
  [ 2]    0     0    ✓   07 May 06:53 [24chasa] Баща е глобен с 526 евро и ще е 3 месеца без книжк
  [ 3]    0     0    ✓   07 May 08:11 [actualno] Отбивате на магистралата, за да иде детето до тоал
  [ 4]    0     0    ✓   07 May 14:19 [monitor] АБСУРДНО: Глобиха родители заради нужда на 2-годиш
  [ 5]    1     1    ✓   21 May 04:26 [nova] 500 евро глоба и отнета книжка за майка, спряла в
  [ 6]    1     1    ✓   21 May 04:46 [24chasa] 500 евро глоба и отнета книжка за майка, спряла в

Story 10796  [5-10]  P=1.000  R=0.406  F1=0.578  (gt_dots=1  sys_dots=3)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   10 May 06:19 [standartnews] Нетаняху поздрави Радев за премиерския пост
  [ 1]    0     0    ✓   10 May 06:23 [24chasa] Нетаняху поздрави премиера Радев за новото правите
  [ 2]    0     1    ✗   10 May 06:47 [vesti] Бенямин Нетаняху поздрави Румен Радев за встъпване
  [ 3]    0     0    ✓   10 May 07:21 [banker] Бенямин Нетаняху поздрави в телефонен разговор Рум
  [ 4]    0     0    ✓   10 May 07:23 [actualno] Бенямин Нетаняху поздрави в телефонен разговор Рум
  [ 5]    0     1    ✗   10 May 09:34 [standartnews] Нетаняху и Радев разговаряха по телефона. Какво си
  [ 6]    0     1    ✗   10 May 11:28 [nova] Бенямин Нетаняху поздрави премиера Румен Радев за
  [ 7]    0     2    ✗   11 May 07:45 [monitor] Нетаняху поздрави Радев

Story 16390  [5-10]  P=1.000  R=0.571  F1=0.727  (gt_dots=2  sys_dots=3)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   18 May 11:40 [nova] Обявиха колко души ще получат по 20 евро за април
  [ 1]    0     0    ✓   18 May 11:45 [24chasa] Плащат на 232 000 души по 20 евро компенсация за в
  [ 2]    0     0    ✓   18 May 11:54 [fakti] Обявиха колко души ще получат по 20 евро за април
  [ 3]    0     0    ✓   18 May 12:09 [actualno] Стана ясно колко хора ще получат по 20 евро за гор
  [ 4]    0     1    ✗   18 May 13:35 [segabg] 232 000 души ще получат по 20 евро за горива за ап
  [ 5]    0     1    ✗   18 May 15:02 [banker] Над 230 000 души ще получат компенсации за високит
  [ 6]    0     1    ✗   18 May 16:12 [standartnews] Добра новина за над 230 хил. българи. Какво се чак
  [ 7]    1     2    ✗   19 May 04:06 [24chasa] От днес плащат по 20 евро компенсация за скъпия то

Story 7809  [10-20]  P=0.879  R=0.576  F1=0.696  (gt_dots=5  sys_dots=8)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   05 May 11:28 [24chasa] България с 20 стрелци на европейското в Осиек
  [ 1]    0     1    ✗   06 May 06:32 [monitor] България ще бъде представена от 20 състезатели на
  [ 2]    1     2    ✗   09 May 15:59 [bta] Добро представяне на българските стрелци в днешния
  [ 3]    1     3    ✗   10 May 09:41 [monitor] Как се представиха на българските стрелци в днешни
  [ 4]    2     3    ✗   10 May 12:30 [bta] Сребърен медал за България на европейското първенс
  [ 5]    2     3    ✗   10 May 12:38 [24chasa] Сребърен медал за България от европейското по стре
  [ 6]    2     4    ✗   11 May 11:27 [monitor] Сребро за България на европейското по стрелба
  [ 7]    3     5    ✗   12 May 10:27 [bta] България спечели бронз в отборната надпревара при
  [ 8]    3     5    ✗   12 May 10:44 [24chasa] И бронз за България от европейското по стрелба
  [ 9]    3     6    ✗   13 May 21:59 [actualno] Прекрасно! Пореден медал за България от Европейско
  [10]    4     7    ✗   16 May 08:45 [bta] България зае шесто място в отборното класиране на

Story 6585  [10-20]  P=1.000  R=0.778  F1=0.875  (gt_dots=3  sys_dots=4)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   24 Apr 19:32 [fakti] Каримански: Дефицитът расте, може да надхвърли и 4
  [ 1]    1     1    ✓   04 May 15:08 [economic] Дефицитът в крайна сметка нарасна с 250 млн. евро
  [ 2]    1     1    ✓   04 May 15:56 [fakti] Бюджетната лампа свети в червено: Дефицитът удари
  [ 3]    1     1    ✓   04 May 17:04 [banker] Министерството на финансите очаква бюджетният дефи
  [ 4]    1     1    ✓   04 May 19:23 [vesti] Очакват ръст на бюджетния дефицит до 1,75 млрд. ев
  [ 5]    1     2    ✗   05 May 04:24 [24chasa] Бюджетният дефицит нарасна до рекордните 1.75 млрд
  [ 6]    1     2    ✗   05 May 04:28 [segabg] Дупката в бюджета порасна с още 250 млн. евро
  [ 7]    2     3    ✗   07 May 09:42 [fakti] Дефицитът за април е с най-висока стойност от 2010
  [ 8]    2     3    ✗   07 May 10:12 [economic] „Необичайна ситуация“: Дефицитът за април е постав
  [ 9]    2     3    ✗   07 May 10:24 [nova] Фискалният съвет: Дефицитът за април е най-големия
  [10]    2     3    ✗   07 May 10:45 [24chasa] Фискалният съвет: Бюджетният дефицит към април е н
  [11]    2     3    ✗   07 May 12:08 [vesti] Фискалният съвет: Дефицитът за април най-голям от

Story 11154  [10-20]  P=1.000  R=0.732  F1=0.845  (gt_dots=3  sys_dots=4)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   08 May 09:26 [actualno] Нова измама, внимавайте: Фалшиви съобщения от КАТ
  [ 1]    0     0    ✓   08 May 11:15 [nova] Нова вълна измами: Фалшиви SMS-и от КАТ и ЦГМ крад
  [ 2]    0     0    ✓   08 May 11:46 [vesti] Пазете се от измама: Нова вълна фалшиви SMS-и от и
  [ 3]    0     0    ✓   08 May 12:28 [24chasa] МВР предупреди за нова фишинг измама с фалшиви гло
  [ 4]    0     0    ✓   08 May 17:22 [monitor] "Плати сега или ти вдигаме колата": Нова схема удр
  [ 5]    0     1    ✗   09 May 10:16 [actualno] Внимание: Фалшиви SMS-и от името на МВР източват с
  [ 6]    0     1    ✗   09 May 12:11 [fakti] ГДБОП предупреди за нова измама
  [ 7]    0     1    ✗   09 May 12:36 [banker] Нова фишинг измама: Фалшиви съобщения за неплатени
  [ 8]    1     2    ✗   09 May 14:43 [24chasa] Киберполицаи от ГДБОП задържаха изпращачи на фишин
  [ 9]    1     2    ✗   09 May 14:45 [bta] Киберполицаите от ГДБОП задържаха изпращачи на фиш
  [10]    1     2    ✗   09 May 14:52 [vesti] ГДБОП задържа двама за фишинг съобщенията от името
  [11]    1     2    ✗   09 May 16:57 [segabg] ГДБОП задържа измамници с фалшиви глоби от КАТ
  [12]    1     2    ✗   09 May 17:30 [nova] Киберполицаите на ГДБОП задържаха изпращачи на фиш
  [13]    2     3    ✗   14 May 10:41 [nova] Как да се предпазим от фишинг измамите

Story 4738  [10-20]  P=1.000  R=0.903  F1=0.949  (gt_dots=4  sys_dots=5)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   30 Apr 05:57 [actualno] Важно за пенсиите: Ето кога изплащат пенсиите за м
  [ 1]    0     0    ✓   30 Apr 08:54 [nova] Кога започва изплащането на пенсиите за май
  [ 2]    1     1    ✓   07 May 03:00 [bta] Започва изплащането на пенсиите
  [ 3]    1     1    ✓   07 May 04:42 [vesti] Започва изплащането на пенсиите за май
  [ 4]    1     1    ✓   07 May 04:52 [fakti] Започва изплащането на пенсиите
  [ 5]    1     1    ✓   07 May 05:45 [nova] Започна изплащането на пенсиите за май
  [ 6]    1     1    ✓   07 May 06:01 [vesti] НОИ обяви графика за пенсиите през май: Изплащанет
  [ 7]    1     1    ✓   07 May 14:19 [monitor] ДОБРА НОВИНА: Започва изплащането на пенсиите за м
  [ 8]    2     2    ✓   20 May 04:12 [vesti] Кабинетът гласува промени при датата за изплащане
  [ 9]    2     2    ✓   20 May 04:21 [standartnews] Ключово решение за пенсиите. Кабинетът на ход
  [10]    3     3    ✓   20 May 11:19 [segabg] Кабинетът прие промени в сроковете за плащане на п
  [11]    3     3    ✓   20 May 11:52 [24chasa] Решено! Пенсиите вече няма да се бавят заради почи
  [12]    3     3    ✓   20 May 11:57 [vesti] Одобриха промени за изплащането на пенсиите
  [13]    3     3    ✓   20 May 12:05 [nova] Изплащането на пенсиите вече няма да се бави зарад
  [14]    3     3    ✓   20 May 12:05 [standartnews] Гореща новина за пенсиите! Поправят несправедливос
  [15]    3     3    ✓   20 May 12:40 [fakti] Пенсиите вече няма да се бавят заради почивни дни
  [16]    3     3    ✓   20 May 13:47 [actualno] Изплащането на пенсиите вече няма да се бави зарад
  [17]    3     4    ✗   21 May 03:58 [monitor] РЕШЕНО: Изплащането на пенсиите няма да се бави за

Story 8716  [10-20]  P=1.000  R=0.580  F1=0.734  (gt_dots=1  sys_dots=2)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   08 May 16:40 [nova] БНБ: 92.52% от левовете са изтеглени от обращение
  [ 1]    0     0    ✓   08 May 16:49 [24chasa] БНБ: 92.52% от левовете са изтеглени от обращение
  [ 2]    0     0    ✓   08 May 17:12 [standartnews] БНБ: Само 2,3 млрд. лева са в ръцете на хората
  [ 3]    0     0    ✓   08 May 17:16 [vesti] БНБ: 92% от левовете вече са изтеглени от обращени
  [ 4]    0     0    ✓   08 May 17:16 [bta] Над 92 на сто от левовете са изтеглени от обращени
  [ 5]    0     0    ✓   08 May 18:00 [fakti] 92.52% от левовете са изтеглени от обращение
  [ 6]    0     0    ✓   08 May 21:46 [actualno] Каква част от левовете е изтеглена от обращение: Д
  [ 7]    0     1    ✗   09 May 06:13 [segabg] 93% от левовете вече са прибрани в БНБ
  [ 8]    0     1    ✗   09 May 06:23 [actualno] 2,3 милиарда лева все още са в българските джобове
  [ 9]    0     1    ✗   09 May 08:30 [banker] Извън касите на БНБ са все още 2.3 млрд. лв. в бан

Story 5614  [20-50]  P=0.650  R=0.870  F1=0.744  (gt_dots=10  sys_dots=7)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   29 Apr 21:35 [actualno] Тръмп: Обмисляме намаляване на броя на американски
  [ 1]    0     0    ✓   30 Apr 01:44 [fakti] Вашингтон обмисля намаляване на броя на американск
  [ 2]    0     0    ✓   30 Apr 03:15 [nova] След спор с Мерц: Тръмп обмисля намаляване на амер
  [ 3]    0     0    ✓   30 Apr 04:09 [24chasa] Тръмп обмисля намаляване на американските войници
  [ 4]    0     1    ✗   30 Apr 19:45 [24chasa] Тръмп плаши да изтегли 36 хиляди войници от Герман
  [ 5]    1     2    ✗   02 May 00:38 [fakti] САЩ изтеглят 5 000 войници от Германия
  [ 6]    1     2    ✗   02 May 05:07 [fakti] Нежеланието на Европа да ръководи НАТО доведе до н
  [ 7]    1     2    ✗   02 May 06:28 [24chasa] САЩ ще изтеглят 5000 американски военнослужещи от
  [ 8]    1     2    ✗   02 May 08:55 [actualno] Тръмп "наказва" Берлин заради Иран: Хиляди америка
  [ 9]    1     2    ✗   02 May 09:42 [nova] САЩ ще изтеглят 5 000 войници от Германия
  [10]    2     2    ✓   02 May 11:55 [actualno] Германия към Тръмп за изтеглянето на американските
  [11]    3     2    ✗   02 May 13:37 [fakti] Писториус: Решението за изтегляне на американските
  [12]    4     2    ✗   02 May 14:10 [24chasa] Колко са американските военни, базирани в Европа?
  [13]    5     3    ✗   03 May 08:31 [24chasa] Тръмп: САЩ ще намалят значително военното си присъ
  [14]    5     5    ✓   03 May 10:28 [segabg] САЩ съкращават военния си състав в Германия с дале
  [15]    6     4    ✗   04 May 05:48 [nova] Защо САЩ изтеглят войници от Германия
  [16]    7     5    ✗   04 May 17:55 [actualno] Военните бази на САЩ в Германия: Къде са, каква ро
  [17]    7     5    ✗   04 May 19:19 [fakti] Военните бази на САЩ в Германия: Къде са и каква р
  [18]    8     5    ✗   04 May 22:35 [actualno] САЩ започнаха изтеглянето на част от войските си о
  [19]    9     6    ✗   09 May 15:52 [banker] Европа очаква американски войски да се изтеглят не

Story 344  [20-50]  P=0.926  R=0.889  F1=0.907  (gt_dots=21  sys_dots=22)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   21 Apr 04:17 [24chasa] Тежък трафик на "Капитан Андреево" и "Лесово" за т
  [ 1]    1     1    ✓   22 Apr 04:25 [24chasa] Интензивен трафик на тирове на ГКПП „Капитан Андре
  [ 2]    1     2    ✗   23 Apr 04:21 [24chasa] Изключително интензивен трафик на изхода за тирове
  [ 3]    2     3    ✗   24 Apr 06:55 [actualno] Отново струпване на камиони на границите с Турция
  [ 4]    3     4    ✗   25 Apr 05:30 [24chasa] Трафикът на "Капитан Андреево" и "Лесово" е изключ
  [ 5]    4     4    ✓   25 Apr 08:13 [fakti] Трафикът на граничните пунктове "Капитан Андреево"
  [ 6]    4     5    ✗   26 Apr 05:31 [24chasa] Изключително интензивен е трафикът на "Капитан Анд
  [ 7]    5     5    ✓   26 Apr 09:04 [fakti] ТИР-ове затапиха пунктовете "Капитан Андреево" и "
  [ 8]    5     6    ✗   27 Apr 04:17 [24chasa] Интензивен е трафикът на тирове на ГКПП „Капитан А
  [ 9]    6     7    ✗   28 Apr 04:35 [24chasa] Трафикът на ГКПП „Капитан Андреево“ и „Лесово“ е и
  [10]    7     8    ✗   29 Apr 04:57 [24chasa] Интензивен трафик за камиони на „Капитан Андреево“
  [11]    8     9    ✗   01 May 06:24 [24chasa] Интензивен трафик на „Капитан Андреево“ и „Лесово“
  [12]    9    10    ✗   02 May 05:17 [24chasa] Интензивен трафик на границата с Турция
  [13]   10    11    ✗   03 May 05:23 [24chasa] Трафикът на граничен пункт "Капитан Андреево" е ин
  [14]   11    12    ✗   04 May 04:31 [24chasa] Интензивен трафик на изход за тирове на  "Капитан
  [15]   12    13    ✗   11 May 04:33 [24chasa] Интензивен трафик на камиони на "Капитан Андреево"
  [16]   13    14    ✗   15 May 04:44 [standartnews] Камиони задръстиха „Капитан Андреево“ още от ранни
  [17]   14    15    ✗   16 May 07:18 [24chasa] Интензивен е трафикът на тирове на "Капитан Андрее
  [18]   14    15    ✗   16 May 16:06 [bta] Интензивен е трафикът на ГКПП "Капитан Андреево" з
  [19]   15    16    ✗   17 May 07:26 [24chasa] Интензивен е трафикът на граничния пункт „Капитан
  [20]   15    16    ✗   17 May 07:33 [standartnews] Опашки от тирове на „Капитан Андреево“, трафикът к
  [21]   16    17    ✗   18 May 04:46 [24chasa] Интензивен е трафикът на граничния пункт "Капитан
  [22]   17    18    ✗   19 May 04:30 [24chasa] Интензивен е трафикът на "Капитан Андреево"
  [23]   17    18    ✗   19 May 05:13 [banker] Трафикът е интензивен на ГКПП „Капитан Андреево“ н
  [24]   18    19    ✗   20 May 10:54 [monitor] Интензивен трафик на граничните пунктове „Капитан
  [25]   19    20    ✗   21 May 04:25 [standartnews] Тежък трафик към Турция блокира камионите
  [26]   20    21    ✗   22 May 04:42 [standartnews] Натискът по границата с Турция расте при товарния

Story 14047  [20-50]  P=0.740  R=0.720  F1=0.730  (gt_dots=11  sys_dots=9)
 [i]   GT   SYS  title
--------------------------------------------------------------------------------
  [ 0]    0     0    ✓   13 May 08:36 [vesti] Свалиха охраната от НСО на Пеевски
  [ 1]    0     0    ✓   13 May 08:36 [24chasa] НСО сваля охраната на Бойко Борисов и Делян Пеевск
  [ 2]    0     0    ✓   13 May 08:38 [nova] Свалиха охраната на Бойко Борисов и Делян Пеевски
  [ 3]    0     0    ✓   13 May 08:45 [actualno] Пеевски и Борисов останаха без охрана от НСО
  [ 4]    0     0    ✓   13 May 08:57 [vesti] И Борисов остава без охрана от НСО
  [ 5]    0     0    ✓   13 May 08:57 [fakti] Делян Пеевски вече е без охрана
  [ 6]    0     0    ✓   13 May 09:00 [standartnews] Свалиха охраната от НСО на Борисов
  [ 7]    0     0    ✓   13 May 09:02 [actualno] "Емоционално, не дай Боже политическо решение": Бо
  [ 8]    0     0    ✓   13 May 09:17 [fakti] От четвъртък сутрин и Бойко Борисов остава без охр
  [ 9]    0     0    ✓   13 May 09:22 [vesti] Защо НСО охраняваше Борисов и Пеевски?
  [10]    1     1    ✓   13 May 09:27 [actualno] "Имат достатъчно ресурси - да си осигурят охрана,
  [11]    1     1    ✓   13 May 09:54 [vesti] Демерджиев за охраната на Пеевски и Борисов: Не е
  [12]    2     1    ✗   13 May 09:54 [actualno] Свалената охрана: ГЕРБ се притесни за сигурността
  [13]    1     1    ✓   13 May 10:04 [banker] Министър Демерджиев увери, че свалянето на охранат